### ISSUE TITLE
Link to docs not working

### ISSUE THREAD

**Issue by jkrems** [ageitgey/face_recognition#1]
It's a bit embarrassing for a leading ML expert to release a project where the docs link in the README leads to an ugly 404 page: https://face-recognition.readthedocs.io

**Comment by ageitgey** [comment]
Haha, Jan Krems always creeping on my uploads.

This doesn't quite work yet. I'm waiting for the pypi folks to raise my file upload size limits so I can upload `face_recognition_models`. Because of that, the tests for this don't pass yet, etc.

**Comment by ageitgey** [comment]
Fixed!

**Comment by jkrems** [comment]
Ran an extensive regression test suite and can confirm that the issue was fixed.

```
> curl -sSL https://face-recognition.readthedocs.io/ | grep Face
  <title>Welcome to Face Recognition’s documentation! &mdash; Face Recognition 0.1.0 documentation</title>
```

**Comment by ageitgey** [comment]
That's a very impressive test suite. PRs are welcome if you want to automate that and include it in the build! :trollface:
