### ISSUE TITLE
IndexError: list index out of range - Empty Array from "face_encodings"

### ISSUE THREAD

**Issue by panosvas** [ageitgey/face_recognition#100]
* face_recognition version: 0.1.14
* Python version: 3.5
* Operating System: 16.04 from VM Image

### Description

Great job! An awesome tool. My issue is that I created a simple test case for matching faces in 2 images based on your examples and there are many times I get **IndexError** when I do face_recognition.face_encodings(unknown_image)[0] on random images (either jpg or png). I debug it and obviously the face_encodings returns an empty array. There is a face in the image, which obviously is not detected. However, if I try some scale of the image or change the format, it is possible that it will recognize it. Is there any general guide on that?

### What I Did

```
import face_recognition

known_image = face_recognition.load_image_file("1-Nick_1.jpg")
unknown_image = face_recognition.load_image_file("N4_P2.png")

biden_encoding = face_recognition.face_encodings(known_image)[0]
unknown_encoding = face_recognition.face_encodings(unknown_image)[0]

results = face_recognition.compare_faces([biden_encoding], unknown_encoding, 0.5)

print(results[0])

if results[0] == True:
    print("It's a picture of me!")
else:
    print("It's not a picture of me!")
```

### Output

```
unknown_encoding = face_recognition.face_encodings(unknown_image)[0]
IndexError: list index out of range
```

**Comment by ageitgey** [comment]
First, you can check the length of the result from `face_recognition.face_encodings(unknown_image)` before trying to access index zero to prevent an exception.

But yes, this just means the dlib face detector wasn't able to find a face in the image. That happens if:
1. The face is turned sideways or upside-down
2. The face is turned too sideways away from the camera instead of looking straight into the camera
3. The face is too small in the image
4. For whatever other reason, the face detector just failed

Depending on why the face wasn't detected, you can try different things. For example if you have sideways or upside-down images, make sure to rotate them back so they are right ways up before running face recognition. This situation happens a lot with cellphone images where the image itself is captured sideways.

**Comment by panosvas** [comment]
Thanks for your quick reply. Indeed it is due to sideways face. Thanks for the hints!

Great job!

**Comment by 12345data** [comment]
unknown_encoding = face_recognition.face_encodings(unknown_image)[0]
IndexError: list index out of range
Shows the error and exits the program. How can I handle this exception and continue the program without exiting.

**Comment by 12345data** [comment]
known_image = face_recognition.load_image_file(image_path)
known_encoding.append( face_recognition.face_encodings(known_image)[0])
known_names.append(path)
I am running face encoding in a continuous loop by appending the images. Overtime a large number of images are encoded and I need to reduce the encoding time by deleting previous encoded images based on timestamp or anything. Can anybody help.

**Comment by ageitgey** [comment]
@12345data did you read my previous answer? The same thing applies for why you get "list index out of range".  I guess I need to update the example to check the array size manually because several people have run into this.

For your second question, I'm not sure how to help without having more information on what exactly you are trying to do.

**Comment by 12345data** [comment]
Thanks for the reply. Updation with checking of array size will be appreciable.
Actually I was doing to recognize known person and to label unknown person as person1, person2 and so on. After first recognition of the above unknown person if they are revisiting to the frame need to recognize them as the prevoiusly labelled name. I was saving the face of each person and encode it for recognition. overtime a large number of persons will be encoded, hence the encoding time taken is more. I need only the past 20 face encodings of known persons. If more number of persons are visiting i need to clear from the first, second  and so on by keeping the fresh 20 encoding value. 

The first problem mentioned above create unexpected exit of the program and second consumes more time.

**Comment by 12345data** [comment]
Can you please help me in this too.	
		for (top, right, bottom, left), name in zip(face_locations, face_names):
				face_alone = frame[top-70:bottom+25, left-20:right+20]
			cv2.imwrite('./return/'+name+'.bmp', face_alone)
Image written in the specific folder is some times corrupted. When I first stored the image as .jpg format the image will be stored as text document but has the name with extension .jpg. I tried with png and bmp. In bmp format some times it creates corrupted bmp files.  When I opened the image it shows that
"BMP  image has bogus header data" . What could be the problem.

**Comment by BhanuJamwal** [comment]
unknown_encoding_image=face_recognition.face_encodings(unknown_image)[0]
IndexError: list index out of range.
apple.py-
def recognize():
	cap=cv2.VideoCapture(0)
	while(True):
		ret,frame=cap.read()
		gray=cv2.cvtColor(frame,cv2.COLOR_BGR2RGB)
		cv2.imshow('frame',gray)
		if cv2.waitKey(1)&0xFF==ord('q'):
			#cv2.imwrite('image.jpg',frame)
			unknown_storage=path.join(app.config['storage'],'unknown')
			cv2.imwrite(os.path.join(unknown_storage , 'image.png'), frame)
			#file=cv2.imread('image.jpg')
			break
	cap.release()
	cv2.destroyAllWindows()
	#if 'file' not in request.files:
		#return error_handle("image is required")
	#else:
		#file=request.files['file']
	#cv2.imread('image.jpg')
	#if file.mimetype not in app.config['file_allowed']:
		#return error_handle("file extension is not allowed")
	#else:
			#filename=secure_filename(file.filename)
			#unknown_storage=path.join(app.config["storage"],'unknown')
	#filename=image.png
	filePath=path.join(unknown_storage,'image.png')
	#file.save(filePath)
	user_id=app.face.recognize("image.png")
	if user_id:
		user=get_user_by_id(user_id) 
face.py-
def recognize(self,unknown_filename):
		#unknown_image=face_recognition.load_image_file(self.load_unknown_file_by_name(unknown_filename))
		unknown_image=face_recognition.load_image_file("/home/bhanu/hello-world/face/storage/unknown/image.png")
		unknown_image = unknown_image[:, :, ::-1]
		print(type(unknown_image))
				
		unknown_encoding_image=face_recognition.face_encodings(unknown_image)[0]

		results=face_recognition.compare_faces(self.known_encoding_faces,unknown_encoding_image);
		
		print("results",results)

**Comment by pitoulambert** [comment]
I had the same issue about the IndexError found in face encoding. I made a try and except statement so that the error found is thrown and the program continue

**Comment by mohamed3051215** [comment]
> First, you can check the length of the result from `face_recognition.face_encodings(unknown_image)` before trying to access index zero to prevent an exception.
> 
> But yes, this just means the dlib face detector wasn't able to find a face in the image. That happens if:
> 
> 1. The face is turned sideways or upside-down
> 2. The face is turned too sideways away from the camera instead of looking straight into the camera
> 3. The face is too small in the image
> 4. For whatever other reason, the face detector just failed
> 
> Depending on why the face wasn't detected, you can try different things. For example if you have sideways or upside-down images, make sure to rotate them back so they are right ways up before running face recognition. This situation happens a lot with cellphone images where the image itself is captured sideways.


it couldn't detect this image 

![cbimage](https://user-images.githubusercontent.com/77445708/133599997-8821f0da-375f-4e8a-9c44-accf531e572f.png)


I noticed that it can't detect images from my phone (realme 5) , but it works with images from my brother's phone (realme 6i)

**Comment by govvind** [comment]
![WhatsApp Image 2022-03-09 at 6 56 30 PM](https://user-images.githubusercontent.com/101263111/157450818-4fc2b2c2-8e80-44e8-88d2-5de32f9bb80b.jpeg)
 I got and error and don't know how to solve it @12345data @ageitgey @panosvas @BhanuJamwal @pitoulambert  can you help me to solve it ?

**Comment by sasankaweera123** [comment]
Thank you for your help my problem was 

- The face is turned sideways or upside-down
- The face is turned too sideways away from the camera instead of looking straight into the camera

Great Job ! @ageitgey

**Comment by amr2018** [comment]
you can use this code

try: 
# your code
except:
   ConnectionRefusedError()
