### ISSUE TITLE
Saving Matched Images to Folder

### ISSUE THREAD

**Issue by Rahulsharma0810** [ageitgey/face_recognition#101]
Can I save matched image to folder or move them to folder so i can sort my photos folder.

**Comment by BalajiB3663** [comment]
Hi @ageitgey, am trying to recognize unknown person by loading multiple images. Encoding multiple faces and when comparison is made for that, the result is ambiguous even-though there is no match is found.
Can you describe how exactly the compare works in your library.
Thanks in advance,

**Comment by ageitgey** [comment]
@BalajiB3663 I don't understand what you are asking. Is it related to this issue of saving matched images? If not, can you move your question to a new issue and try to clarify what you are asking?

**Comment by ageitgey** [comment]
@Rahulsharma0810 You could use this library write a short program that sorts photos with a little more code. But this library on it's own doesn't do that.
