### ISSUE TITLE
TypeError: face_encodings() got an unexpected keyword argument 'model'

### ISSUE THREAD

**Issue by Vankeee** [ageitgey/face_recognition#1011]
* face_recognition version: 1.2.3
* Python version: 3.6
* Operating System: ubuntu 16.04

### Description
I used face_encodings function, and got this error when I  use argument 'model'.

I checked the api , here indeed is argument called 'model= small'. I want to use 'model=large'.
What is wrong here? Thanks guys.

**Comment by ageitgey** [comment]
That parameter is for face feature locations, not face encodings.

**Comment by Vankeee** [comment]
@ageitgey These two functions all have 'model' parameter, you can check the source code.

**Comment by Vankeee** [comment]
@ageitgey 
https://face-recognition.readthedocs.io/en/latest/_modules/face_recognition/api.html#face_encodings

**Comment by Vankeee** [comment]
Just do not use 'model' as the para for face_encodings function.
