### ISSUE TITLE
pil image show() not working in raspberry pi 3 

### ISSUE THREAD

**Issue by Abhiramianbu** [ageitgey/face_recognition#105]
* face_recognition version:0.1.0
* Python version:2.7
* Operating System:raspbian

### Description
When I try to run find_facial feature_in_picture.py the image is not displayed . Only the coordinates of features came as output in terminal.

**Comment by Tagge** [comment]
Well, I wouldn't call this abnormal as I don't think the terminal can display anything besides characters. If you want this function to work you would have to run the script in a Python GUI under Windows for example.

**Comment by ageitgey** [comment]
Like @Tagge said, `image.show()` won't do anything if you don't have a graphical interface running.
