### ISSUE TITLE
How to train this face recognizer?

### ISSUE THREAD

**Issue by Abhiramianbu** [ageitgey/face_recognition#106]
* face_recognition version:0.1.0
* Python version:2.7
* Operating System:raspbian jessie

How to save the face which i want to recognize instead of calculating face encodings each time like in opencv?

**Comment by ageitgey** [comment]
I'm not sure if I understand the question. The face encodings are just an array of 128 numbers. You can save and load them any way you want - as a csv file, as a pickle file, as a text file, whatever.

**Comment by Tagge** [comment]
One solution could also be to store the data in a numpy file, like I do. It works really well on the project I'm working on, and I'm dealing with 50000 sets of facial features.

**Comment by mongoose54** [comment]
@Tagge Very naive question: I am not familiar with any open sourced framework to speed up face matching? How do you deal with 50K images?

**Comment by Tagge** [comment]
@mongoose54 For this particular task, I am simply using the aforementionned library. Perhaps you could find a better classification algorithm and use it. I'll look into it. I'm using the stock features for my project, and I still get a match within 6 seconds.
