### ISSUE TITLE
AttributeError: module 'face_recognition' has no attribute 'face_encodings'

### ISSUE THREAD

**Issue by Aarijit** [ageitgey/face_recognition#107]
Hi,

I was trying to use face recognition module for my project. I created an environment in anaconda and installed all the packages, including dlib and opencv. When I'm calling these packages through import statements they are importing.

Now I was testing [this](https://github.com/ageitgey/face_recognition/blob/master/examples/facerec_from_webcam.py) code for my initial testing purpose. I changed the "VideoCapture" to a still video, changed the initial image into another image with proper path specified and tried to run the code through command prompt in the environment (python face_recognition.py). All the codes are exactly the same as written there. But I'm getting this error:

`AttributeError: module 'face_recognition' has no attribute 'face_encodings'`

In one of the issues I saw you suggested to convert "SSE4" to "SSE2" in the text file. I did that, but still getting the same error.

Interestingly when I'm running the code line-by-line I'm not getting the error. 

Will it be possible for someone to suggest where I'm making the mistake? 
(I changed image reading line to cv2.imread() as earlier I was getting error in that line)

```
(my_env) root@user:~# python /home/user/Desktop/images/face_recognition.py
Traceback (most recent call last):
  File "/home/user/Desktop/images/face_recognition.py", line 1, in <module>
    import face_recognition
  File "/home/user/Desktop/images/face_recognition.py", line 16, in <module>
    obama_face_encoding = face_recognition.face_encodings(obama_image)[0]
AttributeError: module 'face_recognition' has no attribute 'face_encodings'

```

Thank you!

**Comment by Aarijit** [comment]
Thanks Ageitgey! That was a very silly mistake :(

But now I'm getting another error:

```
(my_env) root@user:~# python /home/user/Desktop/images/face_recognition1.py
Traceback (most recent call last):
  File "/home/user/Desktop/images/face_recognition1.py", line 23, in <module>
    face_locations = face_recognition.face_locations(frame)
  File "/home/ubuntu/anaconda3/envs/my_env/lib/python3.6/site-packages/face_recognition/api.py", line 100, in face_locations
    return [_trim_css_to_bounds(_rect_to_css(face), img.shape) for face in _raw_face_locations(img, number_of_times_to_upsample)]
  File "/home/ubuntu/anaconda3/envs/my_env/lib/python3.6/site-packages/face_recognition/api.py", line 89, in _raw_face_locations
    return face_detector(img, number_of_times_to_upsample)
RuntimeError: Unsupported image type, must be 8bit gray or RGB image.

```

When I'm printing image (the one I read), it's giving me proper numpy tuple. And I'm using [this](https://www.youtube.com/watch?v=ODVxuN6m6E8) video.

Thank you!

**Comment by ageitgey** [comment]
No problem :)

For this issue, you need to make sure the image is RGB (i.e. it has three channels and image.shape returns exactly 3 dimensions) and make sure that each pixel value ranges from 0-255 (i.e. it's not using floating point numbers and wasn't captured at a higher bit depth like 16bit or 32bit).

**Comment by Aarijit** [comment]
Thanks for your reply! I'm using colored images. Please find 2 images I used and in all the cases I'm getting the same error. I'm using exactly the code you are using (not reading images in cv2 now). If I print the images , they are coming as proper numpy tuples

[[224 206 202]
  [226 208 204]
  [218 200 196]
  ..., 
  [230 179 158]
  [234 183 162]
  [235 187 167]]

![barack](https://user-images.githubusercontent.com/14370144/27453219-4d50d746-57b3-11e7-9ed5-4003409d85b0.jpg)
![obama1](https://user-images.githubusercontent.com/14370144/27453256-6c02f002-57b3-11e7-9cf4-99a2c0a6ada4.jpg)

**Comment by ageitgey** [comment]
I can load and process those images just fine, so they aren't the issue.

I'm assuming the error you get on line 23 is from this line of code:

```python
    # Grab a single frame of video
    ret, frame = video_capture.read()

    # Find all the faces and face encodings in the frame of video
    face_locations = face_recognition.face_locations(frame)
```

In other words, the error is not from loading the sample jpg files. The error is from trying to to look for faces inside the image captured from your webcam. So you need to make sure the webcam image itself is coming back in the right format (8bit, 3 channels, etc).

**Comment by Aarijit** [comment]
Thanks Ageitgey! The video I'm reading giving me "None" in frames. So need to find out why that can be.

But thanks a lot for guiding me so far.

**Comment by Aarijit** [comment]
Just for completeness, I'm putting the answer to my issue, so that other people having same problem can get the help. 

I was making mistake while installing opencv. Please follow [this](https://www.scivision.co/anaconda-python-opencv3/) or [this](http://www.codesofinterest.com/2017/01/installing-opencv-source-ubuntu.html) link while installing opencv. Once done, do the following tests:

import cv2
print cv2.__version__

cap=cv2.VideoCapture("input_video.mp4")
print cap.isOpened()
If the print result comes "True", then opencv is installed correctly.

**Comment by ageitgey** [comment]
Thanks!
