### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (1,2) (128,)

### ISSUE THREAD

**Issue by panchami88** [ageitgey/face_recognition#1077]
* face_recognition version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.
IMPORTANT: If your issue is related to a specific picture, include it so others can reproduce the issue.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by ageitgey** [comment]
You'll have to show the code that isn't working. We can't guess the problem just from the error message.
