### ISSUE TITLE
AttributeError: 'Image' object has no attribute 'read' in Google Colab

### ISSUE THREAD

**Issue by aanis** [ageitgey/face_recognition#1082]
* face_recognition version: 
* Python version:  3.0
* Operating System: Google Colab

### Description

I am trying to implement the library in Google Colab.

Here is my code so far

#pip install dependencies
!pip install face_recognition
!pip install os
!pip install cv2

import face_recognition
import os
import cv2

#Load the Drive helper and mount
from google.colab import drive

#This will prompt for authorization.
drive.mount('/content/drive')

#After executing the cell above, Drive
#files will be present in "/content/drive/My Drive".
!ls "/content/drive/My Drive"

!ls "/content/drive/My Drive/faces/unknown" 

#'sigrid.jpeg' is in unknown

from IPython.display import Image 
from IPython.display import display
Embed = Image('sigrid.jpeg') 
Embed
 
#Here the image doesn't fully show in the notebook 

import face_recognition
image = face_recognition.load_image_file(Embed)
face_locations = face_recognition.face_locations(image)

#Then I get this error

AttributeError: 'Image' object has no attribute 'read'

Can anyone please tell me how to solve this? Thanks.

**Comment by ageitgey** [comment]
You have to load the image file directly from disk. You can't pass it in from an IPython display object. Just pass the actual filename on disk to load_image_file().

I'm sure there is some other way to convert an IPython display object into a numpy array, but I'm not familiar with that API so I couldn't tell you how.

**Comment by aanis** [comment]
Thanks @ageitgey will try!
