### ISSUE TITLE
ValueError for face_recognition_svm.py example

### ISSUE THREAD

**Issue by VVinter-melon** [ageitgey/face_recognition#1083]
* face_recognition version: 1.3.0
* Python version: 3.8
* Operating System: Win 10
*scikit-learn: 0.22.2.post1

### Description

I am attempting to use the example face_recognition_svm.py to train multiple images for only one person.

### What I Did
I passed 5 image encodings into the encodings array and only one string in the names array. However, the line clf.fit(encodings, names) raised ValueError: Found input variables with inconsistent number of samples: [5, 1]
Below is the code i used:
```
encodings = []
names = ["xin"]

input_path = "C:\\Users\\Desktop\\positive_images"
train_dir = Path(input_path).glob("**/*.jpg")

for pic_path in train_dir:
    xin_face = face_recognition.load_image_file(str(pic_path))
    face_boxes = face_recognition.face_locations(xin_face)

    if len(face_boxes) == 1:
        xin_encoding = face_recognition.face_encodings(xin_face)[0]
        encodings.append(xin_encoding)
        rel_path = os.path.relpath(str(pic_path),"C:\\Users\\Desktop\\positive_images")
        print(rel_path + " added")
    else:
        print(rel_path + " was skipped, can't be used for training")

clf = svm.SVC(gamma="scale")
clf.fit(encodings,names)

```
https://stackoverflow.com/questions/44181664/sklearn-valueerror-found-input-variables-with-inconsistent-numbers-of-samples
Talks about having to reshape the array but I do not understand what is going on. Any help is appreciated :)

**Comment by caibf** [comment]
@VVinter-melon Why closed this issue? Do you solve this issue yet? I faced the same problem, but I don't know how to deal with it.

**Comment by VVinter-melon** [comment]
Yep I quickly realised it was a silly mistake. Each training image needs to have a corresponding name in the names array, even if it is of the same person. This will resolve the array shape problem during clf.fit.  For my particular code, it is wrong to pre-set the names array with just "xin".

The person you want to identify for (in my case "xin) should be labelled as in the folder name. clf.predict will output the name of the folder with images matching the given image. Read the example face_recognition_svm.py code carefully, and I hope it will resolve your issue. :)

**Comment by MattWanjia** [comment]
@VVinter-melon well? any other pointers?
