### ISSUE TITLE
dlib module not found only in api.py

### ISSUE THREAD

**Issue by MeanBluePanda** [ageitgey/face_recognition#1089]
* face_recognition version: 1.3.0
* Python version: 3.8.2
* Operating System: Windows 10

### Description

I was trying to enable GPU acceleration for CNN face locations, after compiling the dlib library version: 19.19.99 successfully with CUDA support and then installing the face-recognition library.
I tried to import the dlib library in my code and it gave no errors, however when compiling the api.py file it gives the error : 
    ImportError: DLL load failed while importing dlib: The specified module could not be found
even though like i said im able to import dlib without any problems

**Comment by imZEH** [comment]
Have you solved this kind of issue? I encountered the same problem.

**Comment by cashlo** [comment]
@imZEH if you are using Python 3.8, it's probably the same issue as I have https://github.com/davisking/dlib/issues/2039
