### ISSUE TITLE
Problem with Raspberry Pi 3

### ISSUE THREAD

**Issue by masoudr** [ageitgey/face_recognition#109]
* face_recognition version:0.1.12 latest
* Python version:3.0.0
* Operating System: Raspberry Pi3 Raspian

Hi,
I followed the specific instructions for installing this tool on Pi3 with the latest raspbian image (Full version).
I successfully compiled the program and can successfully import it with python3 with ` import face_recognition` but when I wanted to run the examples like face_recognition when I run the program with this command python3 `recognize_faces_in_pictures.py` It hangs in the terminal with no response without any errors or output when I try to terminate the program with `Ctrl+c` It through back this error:
```
Traceback (most recent call last):
  File "recognize_faces_in_pictures.py", line 1, in <module>
    import face_recognition
  File "/usr/local/lib/python3.4/dist-packages/face_recognition/__init__.py", line 7, in <module>
    from .api import load_image_file, face_locations, face_landmarks, face_encodings, compare_faces, face_distance
  File "/usr/local/lib/python3.4/dist-packages/face_recognition/api.py", line 18, in <module>
    pose_predictor = dlib.shape_predictor(predictor_model)
KeyboardInterrupt
```
Thanks.
EDIT-----------------------------------------------------------------------
I tried the same way with my Nano Pi M3 but It was Ok but takes about 1 minute to load recognize_faces_in_pictures.py. I think I'm missing some steps to compile the output. Is there something different for compiling for an embedded board?

**Comment by ageitgey** [comment]
At that point it's trying to load the prediction models into memory. My guess is that either it's just slow or maybe it's running out of memory? I'm not really sure. I haven't had this problem on the RPi 2 I have.

**Comment by masoudr** [comment]
Thanks for the answer.
I will give it another try with the new version of Raspbian and report back here.

**Comment by tengqi200** [comment]
Hi,I cannot open the link of the specific instructions,and I cannot install the face_recognition_models sucessfully on the Raspiberry Pi 3B.
So how can I do next step?

**Comment by masoudr** [comment]
@tengqi200 I think the instruction of that page must be updated because it didn't work for me either. I tried the main method with compiling `dlib `from source and then installed face_recognition as usual.

**Comment by tengqi200** [comment]
@masoudr Ok, I will have a try later, thanks.

**Comment by codeundercoverdev** [comment]
I am having the same issue.  It is happening when I run the face_encodings method.  No error - the shell just stops printing or doing anything:

    print("image loaded")
    obama_face_encoding = face_recognition.face_encodings(obama_image)[0]
    print("image encoded")

The above code just returns:

    image loaded

Any idea how to fix this?
