### ISSUE TITLE
how can i get face_encoding with base64 string image? 

### ISSUE THREAD

**Issue by farhanrbnn** [ageitgey/face_recognition#1096]
* face_recognition version: 1.3.0
* Python version:3.6.9
* Operating System: Ubuntu 18.04 

what i've done is i try to get face encoding from base64 string images. this is my code:
```
import face_recognition as fr
import base64

get_images = request.get_json()
arr_image = get_images['images']

    for image in arr_image:
        image_string = base64.b64decode(image)
        face_locations = fr.face_locations(image_string, number_of_times_to_upsample = 0, model = 'hog')
        images_encoding = fr.face_encodings(image_string, known_face_locations = face_locations)[0]
```

when i try to print images_encoding, it's not return anything. does anyone have the same problem here? how to get face encoding with base64 string image ?

thanks in advance

**Comment by VicGrygorchyk** [comment]
I believe you need to search StackOverflow how to convert base64 string to numpy array and pass a ndarray to `face_encodings`

**Comment by farhanrbnn** [comment]
i figured it out, i'm using `cv2.imdecode` instead of using numpy. thanks

**Comment by Bah1996** [comment]
> cv2.imdecode

how did you do it
