### ISSUE TITLE
face_recogition.face_locations TypeError: 'list' object is not callable

### ISSUE THREAD

**Issue by biographie** [ageitgey/face_recognition#1098]
* face_recognition version: 1.3.0
* Python version: 3.6.1
* Operating System: Manjaro 

### Description

I installed dlib and face_recognition via pip in a conda envirnment. I am trying to do facial recognition via webcam. Is it possible that the way I install face_recognition is causing a problem. Or is there an actual error in the code below?

### What I Did

```
# import libraries
import cv2
import face_recognition

# Get a reference to webcam 
video_capture = cv2.VideoCapture(0)

# Initialize variables
face_locations = []

while True:
    # Grab a single frame of video
    ret, frame = video_capture.read()

    # Convert the image from BGR color (which OpenCV uses) to RGB color (which face_recognition uses)
    rgb_frame = frame[:, :, ::-1]

    # Find all the faces in the current frame of video
   
    face_locations = face_recognition.face_locations(rgb_frame)

    # Display the results
    for top, right, bottom, left in face_locations:
        # Draw a box around the face
        cv2.rectangle(frame, (left, top), (right, bottom), (0, 0, 255), 2)

    # Display the resulting image
    cv2.imshow('Video', frame)

    # Hit 'q' on the keyboard to quit!
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# Release handle to the webcam
video_capture.release()
cv2.destroyAllWindows()
```
I am getting an error of:
face_locations = face_recognition.face_locations(rgb_frame)
TypeError: 'list' object is not callable

**Comment by ageitgey** [comment]
Did you name your own file face_recognition.py? Try renaming it to something else.

**Comment by biographie** [comment]
> Did you name your own file face_recognition.py? Try renaming it to something else.

The file was called face_recognition.py as well which is what was causing it. Just saw one of your old comments in the issues. Thanks for your work!!
