### ISSUE TITLE
Illegal Instruction. 

### ISSUE THREAD

**Issue by visionanand** [ageitgey/face_recognition#11]
* face_recognition version: 0.1.9
* Python version: 2.7
* Operating System: Linux Mint

### Description
Hey, first of all Thank you so much for this library. Its Amazing. 
When i run the script line by line, i get an error "Illegal Instruction" at the following line
"my_face_encoding = face_recognition.face_encodings(picture_of_me)[0]" 
The python terminal exits after this. Please let me know if i am doing something wrong. 

### What I Did
I am using Linux Mint and i pip installed face_recognition (got all libraries including dlib installed)

**Comment by ageitgey** [comment]
The issue is most likely that dlib was compiled with support for AVX and/or SSE4 instructions, but your cpu is too old to support them (pre-2011, I think).

The easiest solution is to download dlib and compile it yourself. But when you do that, you need to make one change.

Before compiling dlib, edit dlib's tools/python/CMakeLists.txt file from:

```
set(USE_SSE4_INSTRUCTIONS ON CACHE BOOL "Use SSE4 instructions")
```

to:

```
set(USE_SSE2_INSTRUCTIONS ON CACHE BOOL "Use SSE2 instructions")
```

And then compile and install dlib and the dlib python extensions. Hopefully that should fix it.

**Comment by visionanand** [comment]
Correct. My Laptop is from 2008. The solution you suggested has fixed my issue. The script is able to recognize faces. Thank you.

**Comment by cuimiao187561** [comment]
face_recognition version:0.1.0
Python version:2.7.6
Operating System:ubantu 14.04
I encountered the same problem，When i run the code,
I get an error "Illegal Instruction" at the following line
gnss523@gnss523:~/Desktop/face_recognition-master/examples$ python find_faces_in_picture.py
Illegal instruction (core dumped)

**Comment by ageitgey** [comment]
Did you follow the instructions above?

**Comment by cuimiao187561** [comment]
I try this method

**Comment by ncbonde** [comment]
**i have got this error ...how to solve it??**

` >>>import face_recognition

Traceback (most recent call last):
File "", line 1, in
File "/usr/local/lib/python2.7/dist-packages/face_recognition/init.py", line 7, in
from .api import load_image_file, face_locations, face_landmarks, face_encodings, compare_faces
File "/usr/local/lib/python2.7/dist-packages/face_recognition/api.py", line 21, in
face_encoder = dlib.face_recognition_model_v1(face_recognition_model)
AttributeError: 'module' object has no attribute 'face_recognition_model_v1`

**Comment by ageitgey** [comment]
`AttributeError: 'module' object has no attribute 'face_recognition_model_v1` means that the version of dlib you are using is too old. You need to use dlib 19.4 or newer.

**Comment by Forsskieken** [comment]
Hi ageitgeym
Thanks for putting this togheter. 
I've got error Process finished with exit code 132 (interrupted by signal 4: SIGILL)
when I run the examples, I also cheked if my processor was SSE4 capable (Intel® Xeon® Processor W3680) so before downloading dlib and compiling I wanted to know if there's something else I should do.

thanks for reading and your vmmachine

**Comment by ageitgey** [comment]
@Forsskieken The Intel Xeon W3680 (released 2010) doesn't support AVX instructions (released 2011). So that's why it's failing. Sorry! Your only option is to compile dlib without AVX enabled.

**Comment by Forsskieken** [comment]
Hi There the compilation suceeded but when I want to instaal it I get following error:
```
deeplearning@deep-learning-virtual-machine:~/Downloads/dlib-19.4$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 36, in <module>
    from setuptools.command.bdist_egg import bdist_egg as _bdist_egg
ImportError: No module named setuptools.command.bdist_egg
```
python3-setuptools is already the newest version (20.7.0-1). 
What am I missing
Kind Regards

**Comment by ageitgey** [comment]
@Forsskieken The problem was `python setup.py` runs Python 2, which is totally separate and doesn't have access to any libraries you installed for Python 3. So running `python3 setup.py` instead is the key.

You can choose when version of Python you are using in Pycharm by going to your project settings and changing the interpreter it's using. Just make sure you choose Python 3 for any new projects you create.

**Comment by PreethiRe** [comment]
I am getting error like this..  
import face_recognition
  File "C:\Python27\lib\site-packages\face_recognition\__init__.py", line 7, in <module>
    from .api import load_image_file, face_locations, face_landmarks, face_encodings, compare_faces, face_distance
  File "C:\Python27\lib\site-packages\face_recognition\api.py", line 22, in <module>
    face_encoder =dlib.face_recognition_model_v1(face_recognition_model)
AttributeError: 'module' object has no attribute 'face_recognition_model_v1'

**Comment by ageitgey** [comment]
@PreethiRe Please don't post on closed issues with new unrelated problems. In any case, the answer to your question is [here](https://github.com/ageitgey/face_recognition#common-issues) in the README. You need to upgrade to a newer version of dlib.

**Comment by PreethiRe** [comment]
I got it.. Thank you

**Comment by PreethiRe** [comment]
how to fix this..?
  face_distances = face_recognition.face_distance(known_encodings, image_to_test_encoding)
AttributeError: module 'face_recognition' has no attribute 'face_distance'

**Comment by ageitgey** [comment]
@PreethiRe Again, please don't post on closed issues with new unrelated problems. But I'm guessing you accidentally called your own file "face_recognition.py". You can't name your own file that or Python will find that file instead of the library you are trying to import.

**Comment by Soulzerz** [comment]
I have an acer aspire es1-512, I'm facing this error and have already tried the easy solution proposed. And don't know what else to do.
"Dlib was compiled to use AVX instructions, but these aren't available on your machine.
Illegal instruction (core dumped)"

**Comment by ageitgey** [comment]
@Soulzerz Try installing dlib by downloading the source code and running this command inside the source folder:

```
python3 setup.py install --no USE_AVX_INSTRUCTIONS --no DLIB_USE_CUDA
```

**Comment by Soulzerz** [comment]
@ageitgey  Thanks, that made it work! :smile:

**Comment by rjtmehta99** [comment]
Hi, I have been getting this error and I'm unable to understand why this keeps on happening. 
Any help would be appreciated !



import face_recognition_models

image = face_recognition_models.load_image_file("abc.jpg")
face_locations = face_recognition_models.face_locations(image)

# face_locations is now an array listing the co-ordinates of each face!
Traceback (most recent call last):

  File "<ipython-input-3-57cef0ea6b2c>", line 3, in <module>
    image = face_recognition_models.load_image_file("abc.jpg")

AttributeError: module 'face_recognition_models' has no attribute 'load_image_file'

**Comment by akhilesh-pandey** [comment]
Hi, I am new to PyCharm. I needed a library face_recognition for my project so I installed it using `pip install face_recognition`. Now i am able to import it in ipython but not in PyCharm. I get 

> ImportError: No module named 'face_recognition'

Thanks for your help.

**Comment by salonimundra** [comment]
> The issue is most likely that dlib was compiled with support for AVX and/or SSE4 instructions, but your cpu is too old to support them (pre-2011, I think).
> 
> The easiest solution is to download dlib and compile it yourself. But when you do that, you need to make one change.
> 
> Before compiling dlib, edit dlib's tools/python/CMakeLists.txt file from:
> 
> ```
> set(USE_SSE4_INSTRUCTIONS ON CACHE BOOL "Use SSE4 instructions")
> ```
> to:
> 
> ```
> set(USE_SSE2_INSTRUCTIONS ON CACHE BOOL "Use SSE2 instructions")
> ```
> And then compile and install dlib and the dlib python extensions. Hopefully that should fix it.

Hello, I didn't find this line in the specified location and also my macbook(macbook pro 2010 mid) supports SSE4 but doesn't support AVX. How do I build dlib taking into consideration this issue. I tried reinstalling dlib a lot of times but each time I get Illegal Instruction: 4.

**Comment by gujifly** [comment]
> 
> 
> > The issue is most likely that dlib was compiled with support for AVX and/or SSE4 instructions, but your cpu is too old to support them (pre-2011, I think).
> > The easiest solution is to download dlib and compile it yourself. But when you do that, you need to make one change.
> > Before compiling dlib, edit dlib's tools/python/CMakeLists.txt file from:
> > ```
> > set(USE_SSE4_INSTRUCTIONS ON CACHE BOOL "Use SSE4 instructions")
> > ```
> > to:
> > ```
> > set(USE_SSE2_INSTRUCTIONS ON CACHE BOOL "Use SSE2 instructions")
> > ```
> > And then compile and install dlib and the dlib python extensions. Hopefully that should fix it.
> 
> Hello, I didn't find this line in the specified location and also my macbook(macbook pro 2010 mid) supports SSE4 but doesn't support AVX. How do I build dlib taking into consideration this issue. I tried reinstalling dlib a lot of times but each time I get Illegal Instruction: 4.

I  find this line in  " ./dlib/dlib/cmake_utils/set_compiler_specific_options.cmake" ，so  change and recomplie , it  work!
![image](https://user-images.githubusercontent.com/32125841/54799064-78fa8480-4c96-11e9-9d1f-008532f71b7b.png)

**Comment by reliefs** [comment]
> > > The issue is most likely that dlib was compiled with support for AVX and/or SSE4 instructions, but your cpu is too old to support them (pre-2011, I think).
> > > The easiest solution is to download dlib and compile it yourself. But when you do that, you need to make one change.
> > > Before compiling dlib, edit dlib's tools/python/CMakeLists.txt file from:
> > > ```
> > > set(USE_SSE4_INSTRUCTIONS ON CACHE BOOL "Use SSE4 instructions")
> > > ```
> > > to:
> > > ```
> > > set(USE_SSE2_INSTRUCTIONS ON CACHE BOOL "Use SSE2 instructions")
> > > ```
> > > And then compile and install dlib and the dlib python extensions. Hopefully that should fix it.
> > 
> > 
> > Hello, I didn't find this line in the specified location and also my macbook(macbook pro 2010 mid) supports SSE4 but doesn't support AVX. How do I build dlib taking into consideration this issue. I tried reinstalling dlib a lot of times but each time I get Illegal Instruction: 4.
> 
> I find this line in " ./dlib/dlib/cmake_utils/set_compiler_specific_options.cmake" ，so change and recomplie , it work!
> ![image](https://user-images.githubusercontent.com/32125841/54799064-78fa8480-4c96-11e9-9d1f-008532f71b7b.png)

works

**Comment by rakode** [comment]
Buenos dias , la libreria face_recognition , confunde personas  al identifcar , lo llame falso positivo , para cuando van a resolver este problema . Estoy haciendo un sistema de reconocimiento facial y me gustaria saber para cuando tienen la solucion.

**Comment by listofbanned** [comment]
> Buenos dias , la libreria face_recognition , confunde personas al identifcar , lo llame falso positivo , para cuando van a resolver este problema . Estoy haciendo un sistema de reconocimiento facial y me gustaria saber para cuando tienen la solucion.

Hi!, could you give more details? It always happens? when it happens it's only for a moment or for a long time? is it just one face or many?
Hola!, puedes dar mas detalles? Pasa siempre? cuando pasa es solo por un momento u ocurre por largo rato?, pasa solo con una cara o con muchas?

**Comment by rakode** [comment]
El falso positivo sucede todos los dias , pasan 10 personas y confunde
3 personas ...

**Comment by rakode** [comment]
Buen dia , como se haria para calcular 83 puntos de la cara , la
libreria calcula 68 puntos , 7 objetos faciales y crea un vector de
128 puntos .

**Comment by sumeetvaidya** [comment]
I have the issue in MacOS 12.0.1 (M1 chip). Error: 
zsh: illegal hardware instruction 
installation:
using python 3.7
conda install -c conda-forge dlib
pip install face_recognition
