### ISSUE TITLE
Can I have the result in percentage instead true or false?

### ISSUE THREAD

**Issue by gustavomr** [ageitgey/face_recognition#111]
Can I have the result in percentage instead true or false? I'm looking to a feature that returns the percentage similarity of two faces.

If no, where (in code) can I adjust to have this done? 

Thanks!

**Comment by ageitgey** [comment]
Sure. I just added a code example [here](https://github.com/ageitgey/face_recognition/pull/112/files) that I'll merge into the main codebase soon.

Face distance isn't exactly the same thing as percentage match, but it serves the same purpose and is the closest thing you can do.

**Comment by gustavomr** [comment]
Thanks. You can close this thread.

**Comment by benitofe** [comment]
Hello @ageitgey,

What is the range of face distance? 
I read in another article that scores range from 0 (the same picture) to 4.0 completely different. Its true, for face recognition too?

I'm asking that because we want to calculate the percentage of face match based on this range. 

Thanks.
