### ISSUE TITLE
Error running 'find_faces_in_batches.py'

### ISSUE THREAD

**Issue by JackAllen2020** [ageitgey/face_recognition#1110]
* face_recognition version: latest
* Python version: 3.7.6
* Operating System: Ubuntu 18.04.4 LTS
### Description
Ok, so I'm pretty new to both Python and Face Recognition.
I use PyCharm to run the different example scripts. I'm trying to run the 'find_faces_in_batches' which asks for an input video, but even when using the 'short_hamilton_clip.mp4' I get the following error.

'Traceback (most recent call last):
  File "/home/user/Desktop/face_recognition-master/examples/find_faces_in_batches_old.py", line 40, in <module>
    batch_of_face_locations = face_recognition.batch_face_locations(frames, number_of_times_to_upsample=0)
  File "/home/user/Desktop/face_recognition-master/face_recognition/api.py", line 149, in batch_face_locations
    raw_detections_batched = _raw_face_locations_batched(images, number_of_times_to_upsample, batch_size)
  File "/home/user/Desktop/face_recognition-master/face_recognition/api.py", line 132, in _raw_face_locations_batched
    return cnn_face_detector(images, number_of_times_to_upsample, batch_size=batch_size)
RuntimeError: Error while calling cudaMalloc(&data, n) in file /home/user/dlib/dlib/cuda/cuda_data_ptr.cpp:58. code: 2, reason: out of memory

Process finished with exit code 1'

### What I Did
Tried running the script in PyCharm.

To the best of my knowledge I installed DLIB with CUDA enabled
```

**Comment by KiLJ4EdeN** [comment]
> * face_recognition version: latest
> * Python version: 3.7.6
> * Operating System: Ubuntu 18.04.4 LTS
> 
> ### Description
> Ok, so I'm pretty new to both Python and Face Recognition.
> I use PyCharm to run the different example scripts. I'm trying to run the 'find_faces_in_batches' which asks for an input video, but even when using the 'short_hamilton_clip.mp4' I get the following error.
> 
> 'Traceback (most recent call last):
> File "/home/user/Desktop/face_recognition-master/examples/find_faces_in_batches_old.py", line 40, in 
> batch_of_face_locations = face_recognition.batch_face_locations(frames, number_of_times_to_upsample=0)
> File "/home/user/Desktop/face_recognition-master/face_recognition/api.py", line 149, in batch_face_locations
> raw_detections_batched = _raw_face_locations_batched(images, number_of_times_to_upsample, batch_size)
> File "/home/user/Desktop/face_recognition-master/face_recognition/api.py", line 132, in _raw_face_locations_batched
> return cnn_face_detector(images, number_of_times_to_upsample, batch_size=batch_size)
> RuntimeError: Error while calling cudaMalloc(&data, n) in file /home/user/dlib/dlib/cuda/cuda_data_ptr.cpp:58. code: 2, reason: out of memory
> 
> Process finished with exit code 1'
> 
> ### What I Did
> Tried running the script in PyCharm.
> 
> To the best of my knowledge I installed DLIB with CUDA enabled

Hey, so it seems that your GPU went out of memory.

I suggest reducing the batch size, since the example processes 128 frames at once, and considering that CUDA won't use any shared memory.

**Comment by JackAllen2020** [comment]
> > * face_recognition version: latest
> > * Python version: 3.7.6
> > * Operating System: Ubuntu 18.04.4 LTS
> > 
> > ### Description
> > Ok, so I'm pretty new to both Python and Face Recognition.
> > I use PyCharm to run the different example scripts. I'm trying to run the 'find_faces_in_batches' which asks for an input video, but even when using the 'short_hamilton_clip.mp4' I get the following error.
> > 'Traceback (most recent call last):
> > File "/home/user/Desktop/face_recognition-master/examples/find_faces_in_batches_old.py", line 40, in
> > batch_of_face_locations = face_recognition.batch_face_locations(frames, number_of_times_to_upsample=0)
> > File "/home/user/Desktop/face_recognition-master/face_recognition/api.py", line 149, in batch_face_locations
> > raw_detections_batched = _raw_face_locations_batched(images, number_of_times_to_upsample, batch_size)
> > File "/home/user/Desktop/face_recognition-master/face_recognition/api.py", line 132, in _raw_face_locations_batched
> > return cnn_face_detector(images, number_of_times_to_upsample, batch_size=batch_size)
> > RuntimeError: Error while calling cudaMalloc(&data, n) in file /home/user/dlib/dlib/cuda/cuda_data_ptr.cpp:58. code: 2, reason: out of memory
> > Process finished with exit code 1'
> > ### What I Did
> > Tried running the script in PyCharm.
> > To the best of my knowledge I installed DLIB with CUDA enabled
> 
> Hey, so it seems that your GPU went out of memory.
> 
> I suggest reducing the batch size, since the example processes 128 frames at once, and also consider that CUDA won't use any shared memory.

Cool, thanks changing the number frames being processed worked, thank you
