### ISSUE TITLE
Facerec_from_video_file

### ISSUE THREAD

**Issue by JackAllen2020** [ageitgey/face_recognition#1112]
* face_recognition version: latest
* Python version: 3.7.6
* Operating System: Ubuntu 18.04

### Description
Carry out facial recognition from video file, but use all CPU cores and/or GPU. Currently the script only maxes out one CPU core.

### What I Did
Ran the script using PyCharm it starts processing the video file but only using 1 core of the CPU

**Comment by JackAllen2020** [comment]
Can't I just let all of the examples utilise the power of my machine.

I've got an Alienware Area51m with a 8-core i9, 64GB RAM and a GTX 2080

**Comment by Latestion** [comment]
@JackAllen2020 If you have such a good gpu you can use 'model' as cnn which uses your gpu. I dont know if you can use both of them at the same time though.

**Comment by JackAllen2020** [comment]
> @JackAllen2020 If you have such a good gpu you can use 'model' as cnn which uses your gpu. I dont know if you can use both of them at the same time though.

@Latestion so how do I do that exactly? Apologies I'm pretty new to this whole thing :)

**Comment by Latestion** [comment]
> 
> 
> > @JackAllen2020 If you have such a good gpu you can use 'model' as cnn which uses your gpu. I dont know if you can use both of them at the same time though.
> 
> @Latestion so how do I do that exactly? Apologies I'm pretty new to this whole thing :)

Do you have any code I can see rn?

**Comment by JackAllen2020** [comment]
> > > @JackAllen2020 If you have such a good gpu you can use 'model' as cnn which uses your gpu. I dont know if you can use both of them at the same time though.
> > 
> > 
> > @Latestion so how do I do that exactly? Apologies I'm pretty new to this whole thing :)
> 
> Do you have any code I can see rn?

@Latestion currently all I've done is taken the facerec_from_video_file example and specified a video input and added the encoding for a bunch of facial images to recognise.

**Comment by JackAllen2020** [comment]
`import face_recognition
import cv2

# This is a demo of running face recognition on a video file and saving the results to a new video file.
#
# PLEASE NOTE: This example requires OpenCV (the `cv2` library) to be installed only to read from your webcam.
# OpenCV is *not* required to use the face_recognition library. It's only required if you want to run this
# specific demo. If you have trouble installing it, try any of the other demos that don't require it instead.

# Open the input movie file
input_movie = cv2.VideoCapture("Cam06HDTraining.mp4")
length = int(input_movie.get(cv2.CAP_PROP_FRAME_COUNT))

# Create an output movie file (make sure resolution/frame rate matches input video!)
fourcc = cv2.VideoWriter_fourcc(*'XVID')
output_movie = cv2.VideoWriter('output.avi', fourcc, 25, (1920, 1080))

# Load some sample pictures and learn how to recognize them.
s107_image = face_recognition.load_image_file("107.jpg")
s107_face_encoding = face_recognition.face_encodings(s107_image)[0]

s137_image = face_recognition.load_image_file("137.jpg")
s137_face_encoding = face_recognition.face_encodings(s137_image)[0]

s158_image = face_recognition.load_image_file("158.jpg")
s158_face_encoding = face_recognition.face_encodings(s158_image)[0]

s183_image = face_recognition.load_image_file("183.jpg")
s183_face_encoding = face_recognition.face_encodings(s183_image)[0]

s266_image = face_recognition.load_image_file("266.jpg")
s266_face_encoding = face_recognition.face_encodings(s266_image)[0]

s307_image = face_recognition.load_image_file("307.jpg")
s307_face_encoding = face_recognition.face_encodings(s307_image)[0]

s395_image = face_recognition.load_image_file("395.jpg")
s395_face_encoding = face_recognition.face_encodings(s395_image)[0]

known_faces = [
    s107_face_encoding,
    s137_face_encoding,
    s158_face_encoding,
    s183_face_encoding,
    s266_face_encoding,
    s307_face_encoding,
    s395_face_encoding
]

# Initialize some variables
face_locations = []
face_encodings = []
face_names = []
frame_number = 0

while True:
    # Grab a single frame of video
    ret, frame = input_movie.read()
    frame_number += 1

    # Quit when the input video file ends
    if not ret:
        break

    # Convert the image from BGR color (which OpenCV uses) to RGB color (which face_recognition uses)
    rgb_frame = frame[:, :, ::-1]

    # Find all the faces and face encodings in the current frame of video
    face_locations = face_recognition.face_locations(rgb_frame)
    face_encodings = face_recognition.face_encodings(rgb_frame, face_locations)

    face_names = []
    for face_encoding in face_encodings:
        # See if the face is a match for the known face(s)
        match = face_recognition.compare_faces(known_faces, face_encoding, tolerance=0.50)

        # If you had more than 2 faces, you could make this logic a lot prettier
        # but I kept it simple for the demo
        name = None
        if match[0]:
            name = "107"
        elif match[1]:
            name = "137"
        elif match[2]:
            name = "158"
        elif match[3]:
            name = "183"
        elif match[4]:
            name = "266"
        elif match[5]:
            name = "307"
        elif match[6]:
            name = "395"
#        elif match[7]:
#            name = "Unknown"

        face_names.append(name)

    # Label the results
    for (top, right, bottom, left), name in zip(face_locations, face_names):
        if not name:
            continue

        # Draw a box around the face
        cv2.rectangle(frame, (left, top), (right, bottom), (0, 0, 255), 2)

        # Draw a label with a name below the face
        cv2.rectangle(frame, (left, bottom - 25), (right, bottom), (0, 0, 255), cv2.FILLED)
        font = cv2.FONT_HERSHEY_DUPLEX
        cv2.putText(frame, name, (left + 6, bottom - 6), font, 0.5, (255, 255, 255), 1)

    # Write the resulting image to the output video file
    print("Writing frame {} / {}".format(frame_number, length))
    output_movie.write(frame)

# All done!
input_movie.release()
cv2.destroyAllWindows()
`

**Comment by Latestion** [comment]
Holy. Okay is that ur code?

**Comment by JackAllen2020** [comment]
That's literally the code from the example with my edits

**Comment by Latestion** [comment]
Okay.

**Comment by Latestion** [comment]
@JackAllen2020 Whats the issue rn?
Is it very slow or?

**Comment by JackAllen2020** [comment]
@Latestion the issue I have rn is that it only uses one CPU core while processing the video, so it works it's just very time consuming

**Comment by Latestion** [comment]
@JackAllen2020 Okay give me a minute.

**Comment by Latestion** [comment]
@JackAllen2020 https://paste.ofcode.org/V2mHB98qHBS4iXUxYHkFjR That should fix everything.

**Comment by Latestion** [comment]
@JackAllen2020 I think that should have fixed your problem.

**Comment by JackAllen2020** [comment]
> @JackAllen2020 https://paste.ofcode.org/V2mHB98qHBS4iXUxYHkFjR That should fix everything.
> Edit: As you said you have a rtx 2060(which I am very jealous about xD) It will use the power of your gpu rather than the cpu.
> I changed the Initialize some variables part btw.

@Latestion cool thank you, so was it just that bit that you changed? As I ran it and it's still maxing out one CPU core :/. I spec'd the laptop myself for work and was like I need this so they paid for it.

**Comment by Latestion** [comment]
@JackAllen2020 Is it giving you the results quick or its slow like earlier?

**Comment by JackAllen2020** [comment]
@Latestion doesn't seem to be any faster

**Comment by Latestion** [comment]
@JackAllen2020 Do you want it to be real time video or do you want to take a single image of yourself?

**Comment by JackAllen2020** [comment]
@Latestion I just want to be able to chuck a video at it and be like try and find these faces in the clip, I don't need real time video, just give it some prerecorded clips if that makes sense

**Comment by Latestion** [comment]
@JackAllen2020 OHhhhh.

**Comment by JackAllen2020** [comment]
For instance I've got some CCTV footage that includes actors that we have images of, so I want to specify a video as an input and for it to use the images I have of the actors to try and recognise them in the video

**Comment by JackAllen2020** [comment]
@Latestion I think I've got it to now utilise my GPU. I had to add 'model ="cnn" in a couple of locations. Thanks for your help, it's much appreciated
