### ISSUE TITLE
Face Recognition of an Original Person

### ISSUE THREAD

**Issue by KaramveerSidhu** [ageitgey/face_recognition#1114]
How can we improve the code or add some additional functionality that the face is recognized only if there's an original person standing in front of the camera and not from a photo of that person?

Is there a way to do so?

EX- If I want Barack Obama's face to be recognized, he should be standing there in front of the camera and I must not be able to do so by showing his image on my phone.

Thanks.

**Comment by Latestion** [comment]
Well I am new to this and might not know a lot. But I dont think this is possible? As the way you compare faces is 'face_recognition.compare_faces(face1_encod, face2_encod, model)' and you cant really change anything in it.

Are you using real time footage?

**Comment by KaramveerSidhu** [comment]
Yes! I am using real time footage. But it is possible to actually train the system to recognise fake and real faces. 
I searched about it and found that it's called 'Liveness Detection'. We have to use supervised learning(classification) to train the model first to detect if the face is a live one or a fake one. It will then start face recognition only if the face is a live one. Still figuring out how to implement it though.

**Comment by Latestion** [comment]
Yes. I did some research on Liveness detectors and I think you are on great path. I found some great source for learning it and it uses openCv. Heres a link:- https://www.pyimagesearch.com/2019/03/11/liveness-detection-with-opencv/
Hope it helps you. :)

**Comment by KaramveerSidhu** [comment]
Thanks!
