### ISSUE TITLE
ordrer number of  facia landmarks 

### ISSUE THREAD

**Issue by yulongshan** [ageitgey/face_recognition#1121]
* face_recognition version:1.3.0
* Python version:3.5.2
* Operating System:ubuntu16.04

Firstly, thanks for your great job. I have one problem like this.
Order number of facial landmarks is changing between two runs. The first landmark locates bottom lip in the first run, but the first landmark locates  right eye in the second run. 

fist
![e1](https://user-images.githubusercontent.com/34642931/80068960-1481b700-8573-11ea-8ec1-f4fdac17234c.png)

second
![e2](https://user-images.githubusercontent.com/34642931/80069009-2ebb9500-8573-11ea-871e-7c15baf5758b.png)

**Comment by ariyapour** [comment]
The object (inside [ ] ) returned is a dictionary and order does not matter in a dictionary. The detections are identical as I see in both runs, but the order of different landmarks in the returned dictionary can be different but it has no effect on the final result. If you want to preserve the order then maybe we have to use an OrderedDict.

**Comment by yulongshan** [comment]
wow,I see , thank you  for your reply. It is very helpful.
