### ISSUE TITLE
Face Recognition Docker Version

### ISSUE THREAD

**Issue by Aarijit** [ageitgey/face_recognition#113]
Hi,

I'm using Windows 10, so having hard time installing this package. So I tried face recognition in the docker version. I could build face recognition container in my docker using the dockerfile. I could log into the container using the following command:

`docker run -p 9000:9000 -p 8000:8000 -t -i --name face2 face_recognition /bin/bash`

But why I'm typing python and then type `import cv2`, I'm getting module does not exist error. But if I try to `import face_recognition`, it's getting properly imported.  I need cv2 as I'm working with face detection in video.
 Am I making some where?

Thank you!

**Comment by Aarijit** [comment]
I think you didn't add opencv in the dockerfile. That's why it didn't get installed. Can you please add it?

**Comment by ageitgey** [comment]
OpenCV is not part of this library, so it's not included in the sample Docker file that demonstrates how to use this library. But you can always create your own Docker file that includes whatever you need.

**Comment by Aarijit** [comment]
@ageitgey; Thank you for the clarification!

**Comment by ageitgey** [comment]
Here's a (completely untested) example of what you could add to the Dockerfile to build OpenCV:

```
RUN apt-get update && apt-get install -y \ 
    build-essential \
    cmake \
    gfortran \
    git \
    libatlas-base-dev \
    libav-tools  \
    libgtk2.0-dev \
    libjasper-dev \
    libjpeg-dev \
    libopencv-dev \
    libpng-dev \
    libtiff-dev \
    libvtk6-dev \
    pkg-config \
    python-dev \
    python-numpy \
    python-opencv \
    python-opencv \
    python-pycurl \
    qt5-default \
    unzip \
    webp \
    wget \
    zlib1g-dev

RUN mkdir -p ~/opencv cd ~/opencv && \
    wget https://github.com/Itseez/opencv/archive/.zip && \
    unzip 3.2.0.zip && \
    rm 3.2.0.zip && \
    cd opencv-3.2.0 && \
    mkdir build && \ 
    cd build && \
    cmake -D CMAKE_BUILD_TYPE=RELEASE \
  	-D CMAKE_INSTALL_PREFIX=/usr/local \
  	-D INSTALL_C_EXAMPLES=ON \
  	-D INSTALL_PYTHON_EXAMPLES=ON \
  	-D BUILD_EXAMPLES=ON .. && \
    make -j4 && \
    make install && \ 
    ldconfig
```

One problem is I think that by default OpenCV names the Python library wrong that it puts in `/usr/local/lib/python3.4/site-packages/`, so you'll also need something like this at the end (again, untested):

```
RUN ln -s /usr/local/lib/python3.4/site-packages/cv2.cpython-34m.so /usr/local/lib/python3.4/site-packages/cv2.so
```

**Comment by Aarijit** [comment]
@ageitgey : Thanks for sharing the opencv code. I tried the code you have shared. After adding the part, I can install opencv. But still getting the same issue while trying to do `import cv2`. 

When I'm doing `find / -name "cv.py"`, I'm getting 

> /usr/lib/python2.7/dist-packages/cv.py

And for this `find / -name "cv2.so"`, the result is

> /usr/local/lib/python3.4/site-packages/cv2.so
> /usr/local/lib/python2.7/dist-packages/cv2.so
> /opencv-3.2.0/build/lib/cv2.so

It seems I'm getting the issue because cv2.so paths are different. But not sure how to rectify it. I added your opencv portion alongwith original dockerfile. 

Thank you!

**Comment by december-soul** [comment]
I have some problem to get the docker working. I used the included dockerfile.
After successful build docker image i tried to run the image.
It failed with "Illegal instruction (core dumped)"

```
#cd face_recognition
#docker build -t face_recognition .
.... wait ....
#docker run face_recognition 
Illegal instruction (core dumped)
```

docker --version
Docker version 17.05.0-ce, build 89658be

`Linux pc 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by ageitgey** [comment]
@december-soul check out the Common Issues section of the README. Most likely your CPU is too old so you'll have to edit the Dockerfile to disable AVX.

**Comment by december-soul** [comment]
Damn i found it and wanted to answer my own question:
https://github.com/ageitgey/face_recognition#common-issues

Thank you!
