### ISSUE TITLE
installing Error face_recongnition

### ISSUE THREAD

**Issue by cuimiao187561** [ageitgey/face_recognition#114]
* face_recognition version:???
* Python version:2.7.6
* Operating System:uabntu 14.04
hello  ageitgey:
when i install face_recongnition .I  got this error.
![qq 20170629170608](https://user-images.githubusercontent.com/23358104/27680320-ec7f6f96-5ced-11e7-8bdc-5fb29891fa47.jpg)
how to slove it
thank you a lot

**Comment by Aarijit** [comment]
@cuimiao187561 : Sorry to come in between you are @ageitgey.  Just want to ask if you have put the entire error report. It seems last part has been truncated.

**Comment by ageitgey** [comment]
This error just means your download failed before it completed. The `face_recognition_models` package is like 100MB of data. Either just try again or try on a different internet connection.
