### ISSUE TITLE
ImportError: Missing symbol (dlib)

### ISSUE THREAD

**Issue by srevinsaju** [ageitgey/face_recognition#1150]
* face_recognition version:
```
face-recognition              1.3.0          
face-recognition-models       0.3.0
```
* Python version: `3.8.2`
* Operating System: `Manjaro Linux 5.6.12-1-MANJARO #1 SMP PREEMPT Sun May 10 14:36:43 UTC 2020 x86_64 GNU/Linux`

### Description

Could not import `face_recognition`

### What I Did
Installation succeeded, unfortunately cannot import; looks like its a fault on `dlib's` part.
```
❯ python
Python 3.8.2 (default, Apr  8 2020, 14:31:25) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import face_recognition
Traceback (most recent call last):
  File "/home/xxx/.local/bin/face_recognition", line 5, in <module>
    from face_recognition.face_recognition_cli import main
  File "/home/xxx/.local/lib/python3.8/site-packages/face_recognition/__init__.py", line 7, in <module>
    from .api import load_image_file, face_locations, batch_face_locations, face_landmarks, face_encodings, compare_faces, face_distance
  File "/home/xxx/.local/lib/python3.8/site-packages/face_recognition/api.py", line 4, in <module>
    import dlib
ImportError: /home/xxx/.local/lib/python3.8/site-packages/dlib.cpython-38-x86_64-linux-gnu.so: undefined symbol: cblas_dtrsm

```

**Comment by karthik9319** [comment]
I've found the solution for the installation of face_recognition lib and dlib as well

Clone the code from github:

`git clone https://github.com/davisking/dlib.git`
Build the main dlib library (optional if you just want to use Python):

`cd dlib`
`mkdir build; cd build; cmake ..; cmake --build .`
Build and install the Python extensions:

`cd ..`
`python3 setup.py install`

Then, install face recognition using:
`pip3 install face_recognition`

**Comment by srevinsaju** [comment]
@karthik9319 Thanks. It now works!
