### ISSUE TITLE
bmas docker vs face_recognition has different accuracy

### ISSUE THREAD

**Issue by MyraBaba** [ageitgey/face_recognition#116]
Environment:
Python 2.7
Mac os X 2017 mac book pro

### Description

I downloaded 5700 public face data set publicly available.
I aligned them and then add the known_faces with face_recognition.face_encodings.

When I try to test with face_rec_from_camera . the results is not good. I showed the camera trained people picture from my phone and ti says other people some times find correct.

I test same data set with bmas docker image .

An I got almost %100 accuracy with
./demos/classifier.py infer models/openface/dataset.pkl ./images/examples/image.jpg

command line.

Why face_recognition is not has such level acuracy ? Or I am missing something ?

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by ageitgey** [comment]
I can't say what might be wrong without more detail. Can you create a small example program that shows faces not matching when they should and post it?

My wild guess is you said you "align" the known faces before calling `face_encondings` but that is throwing things off. What kind of alignment are you doing to the photos? You shouldn't do any pre-processing on the photos when using this library. It will do alignment itself. That could be throwing things off - especially if you are doing something like an affine transformation like OpenFace does in it's alignment script. That would warp the photos in strange ways.
