### ISSUE TITLE
How to scale facerec_from_webcam_faster?

### ISSUE THREAD

**Issue by jelimoore** [ageitgey/face_recognition#117]
Like the title says, I would like to know how to scale the webcam facerec program to see multiple faces. Since I can't see the exact code that was used for the gif of multiple faces being recognized, I am unsure of what to do to recognize faces that would be relatively fast.

**Comment by ageitgey** [comment]
If you have a relatively small number of known faces, you can just pass them all into the `compare_faces()` function as an array. The math happening is pretty simple and will take advantage of vector operations on your CPU if available.

If you have lots and lots of known faces, you can look into more complicated approaches like using clustering algorithms, indexed database tables or spatial hashing.

**Comment by jelimoore** [comment]
When you say lots, do you mean 100? 1000? I'm looking for something in the 1000 known faces range.

**Comment by ageitgey** [comment]
I don't have any fixed numbers. I'd just try it and see how fast `compare_faces()` works for you. If it's too slow, then investigate a more complicated solution. No need to introduce complexity unless the simple solution doesn't work.
