### ISSUE TITLE
Image of 1 person but when compare face of array 2 person, result is [True, True]

### ISSUE THREAD

**Issue by buihoang95** [ageitgey/face_recognition#118]
* face_recognition version: newest
* Python version: 3.6.1
* Operating System: MacOS sierra

### Description

I'm trying to use face_recognition_from_webcam
I have 2 picture of 2 person, but when I run the code, in frame have only 1 person, and then the code

> match = face_recognition.compare_faces([hoang_encoding, hai_encoding], face_encoding, tolerance=0.6)

return array of [True, True]

what should I do in this case?

**Comment by malikshubham827** [comment]
I think it's because the 2 people whose pictures you have used for encoding might have many **similar features** and the norm of their encodings come under the tolerance limit(0.6). You may _decrease the tolerance_, but it might affect the performance of the algorithm on the general dataset. 

You could also make sure that the photo is well lit, the face is clearly visible. I haven't tried it but I think that it might help. I have used this with 6 people in which it is identifying one person as another(sometimes though). So that's normal. It's not 100% accurate.

**Comment by ageitgey** [comment]
Also, what is the result if you add this line?

```
distances = face_recognition.face_distance([hoang_encoding, hai_encoding], face_encoding)
print(distances)
```

That will show you how close the faces are to each other.

**Comment by Aarijit** [comment]
Just to add to this question, suppose in my image I've 2 faces, how it will print names of both the person.
@buihoang95: I tried 0.55 as tolerance and it reduces my false positive drastically.

**Comment by jessejohnson** [comment]
@Aarijit can confirm. Tolerance of 0.5 drastically reduced the false positives.

**Comment by Aarijit** [comment]
@jessejohnson: Thanks mate!

**Comment by buihoang95** [comment]
thank you all, I added more image of the same person, it worked great

**Comment by Aarijit** [comment]
Hi,

I still have this issue. In the current setup, we are comparing and image with face_encoding (nothing but stacked matrix of all image encodings). Now, it might happen that  we have 2 faces in the dataset. How we will recognize both the names. I found something like that happening in @ageitgey video example. But could not find the code how to do it.

Thank you!

**Comment by malikshubham827** [comment]
After running the face detector we get the locations where face is in the captured photo/frame. Then we find the encodings for each face. Then for each face we find the face_distance from the known face and assign it the name(if it is in the known_people folder).That means we have to run the loop for each face detected in the current loop.I am working on something which needs it, would open-source *if* I was able to accomplish what I want.

```
for face_encoding in face_encodings:
                match = face_recognition.compare_faces(known_encodings, face_encoding)
                name = "Unknown"

                #Find if this person is in the present people array
                for i in range(len(match)):
                    if match[i]:
                        name = people[i]
                        break
```

`match gives an array of True/False, for loop finds the name if it exists, people is an array containing names in the same order as the encodings`.

**Comment by Aarijit** [comment]
@malikshubham827 : Thanks Shubham! THis was a great help!
