### ISSUE TITLE
Why some image can not find face?

### ISSUE THREAD

**Issue by thpy** [ageitgey/face_recognition#1194]
* face_recognition version: last
* Python version: 3.6
* Operating System: centos 7

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.
IMPORTANT: If your issue is related to a specific picture, include it so others can reproduce the issue.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```
[My picture location at]()

[](https://user-images.githubusercontent.com/12785867/88916417-9f6ffd00-d298-11ea-89e9-d66f9722645e.jpg)
[](https://user-images.githubusercontent.com/12785867/89135832-dc6f1480-d562-11ea-8dbf-d1b87961968a.jpg)

my code:
```
@app.route('/detect_face', methods=['POST'])
def upload_image_bas64():
    # 检测图片是否上传成功

	request.get_json(force=True)	
    
	if request.json is not None:
		try:		
			file_bytes = base64.b64decode(request.json.get('img'))
			#print(file_bytes)
			# f = open('/root/Code/face_recognition_service/test.jpg', 'wb')			
			#f.write(file_bytes)
			#f.close()
			file = io.BytesIO(file_bytes)
			return detect_faces_in_image(file)
		except:
			print(sys.exc_info())			
			return 'unkown error'# sys.exc_info()[0]
	else:
		return "none json"

def detect_faces_in_image(file_stream):
    
    # 载入用户上传的图片
    img = face_recognition.load_image_file(file_stream)
    # 为用户上传的图片中的人脸编码
    face_found = False
    name = 'unkown'    

    print(face_recognition.face_locations(img))
   


if __name__ == "__main__":
    app.run(host='0.0.0.0', port=9090, debug=False)
```

Why I get print(face_recognition.face_locations(img)) output []?

**Comment by thpy** [comment]
Any one can help?

**Comment by DavidKatz-il** [comment]
When I resize the image (50%) it works for me.

**Comment by thpy** [comment]
@DavidKatz-il 
I have try resize the image(50%), but it not work for me. Do you use my image above?
```
                        image_io= io.BytesIO(file_bytes) 
			file = Image.open(image_io)
			#print(file.size)
			width,height = file.size
			file = file.resize((width//2,height//2), Image.ANTIALIAS)
```

**Comment by thpy** [comment]
I have resolve it with rotate it. Thank you @DavidKatz-il
