### ISSUE TITLE
Cmake installation failed / Ubuntu => Solved

### ISSUE THREAD

**Issue by ihebski** [ageitgey/face_recognition#120]
dlib/CMake installation failed for Ubuntu 14.04
Here is my solution : 
**Installing Boost, Boost.Python, and X11 can be accomplished easily with**
```
$ sudo apt-get install build-essential cmake
$ sudo apt-get install libgtk-3-dev
$ sudo apt-get install libboost-all-dev
```
**Installation of Cmake:**
it tooks a while to install ~1.5 min
```
sudo wget  https://cmake.org/files/v3.9/cmake-3.9.0-rc5.tar.gz -O cmake.tar.gz
sudo tar -xvf cmake.tar.gz
cd cmake-3.9.0-rc5/
sudo chmod +x bootstrap
sudo ./bootstrap
sudo make && sudo make install
```
![screenshot 1 ](http://i.imgur.com/EVrzIwt.png)
![screenshot 2 ](http://i.imgur.com/MctEEjR.png)
**Dlib installation** 
```
$ wget https://bootstrap.pypa.io/get-pip.py
$ sudo python get-pip.p
```
Run all the examples using python3 ,it will works well now on Ubuntu 14.04
```$ python3 find_facial_features_in_picture.py```

![screenshot 3 ](http://i.imgur.com/0mhiXVv.png)

I hope this will be helpful :+1:  ,Happy H4cking .

**Comment by ageitgey** [comment]
Thanks for the tip! 

Note to anyone else reading this: This only applies to the older Ubuntu 14.04. If you have Ubuntu 16.04 or newer, you don't need to do the extra steps and can just follow the README instructions.

**Comment by ageitgey** [comment]
I'll add this 14.04 note the the README.

**Comment by Wisgon** [comment]
It works! I have been annoying about this problem for a long time, until I saw this method,thank you!

**Comment by DQ0408** [comment]
顶楼主

**Comment by elahia** [comment]
thank you for instruction, it was reaaly helpful, 
just a small edit please, 
in dlib installation command: $ sudo python get-pip.p 
 please update the file name by adding y !

**Comment by ihebski** [comment]
thank you @elahia  , I didn't notice that before , I have updated the comment . 👍 thx for ur support

**Comment by manfar** [comment]
**Dlib installation**
$ wget https://bootstrap.pypa.io/get-pip.py
$ sudo python get-pip.py

I Can't run at this step, the prompt is as follows, why? Ubuntu18

prompt

$ wget https://bootstrap.pypa.io/get-pip.py
--2019-02-22 15:57:28--  https://bootstrap.pypa.io/get-pip.py
Resolving bootstrap.pypa.io (bootstrap.pypa.io)... 151.101.72.175, 2a04:4e42:11::175
Connecting to bootstrap.pypa.io (bootstrap.pypa.io)|151.101.72.175|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1699325 (1.6M) [text/x-python]
get-pip.py: Permission denied

Cannot write to ‘get-pip.py’ (Success).

**Comment by ihebski** [comment]
`get-pip.py: Permission denied` seems you run it without permission ,try using sudo before running the command

**Comment by Alexanderm007** [comment]
I have a problem with this, I don't really know what to do, i just star learning
sudo apt-get install libgtk-3-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgtk-3-dev : Depends: libgtk-3-0 (= 3.22.30-1ubuntu1) but 3.22.30-1ubuntu4 is to be installed
                Depends: gir1.2-gtk-3.0 (= 3.22.30-1ubuntu1) but 3.22.30-1ubuntu4 is to be installed
                Depends: libatk-bridge2.0-dev but it is not going to be installed
                Depends: libxkbcommon-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
