### ISSUE TITLE
module 'face_recognition' has no attribute 'face_distance'

### ISSUE THREAD

**Issue by Pepepy** [ageitgey/face_recognition#121]
* face_recognition version: 0.1.12
* Python version: 3.5.3
* Operating System: ubuntu 16.04 LTS

### Description

I am trying to run the example face_distance.py
But it gives the following error: AttributeError: module 'face_recognition' has no attribute 'face_distance'
I Install the module using pip3: pip3 install face_recognition

I guess the repository is not updated to the latest version. How can I install the latest versions manually?

**Comment by ageitgey** [comment]
The current version (both on github and in pip) is version `0.2.0`. If you are using `0.1.12` like you said, just upgrade to the latest version.

Maybe you just need to do `pip3 install --upgrade --upgrade-strategy only-if-needed face_recognition` to fix it?

**Comment by Surbhi120201** [comment]
I'm having a similar error even tho i have the latest version . how can i fix the error
