### ISSUE TITLE
Face Matching Percentages 

### ISSUE THREAD

**Issue by mesadhan** [ageitgey/face_recognition#1211]
* face_recognition version: v1.2.2
* Python version: 3.7
* Operating System: macOS Catalonia

### Description

I would like to get a matching percentage. face_recognition library is only able to say `face_distances` and `match and unmatched`. Is that possible to show face matching value in percentage? Is that possible then how can I implement that feature?

After `comparing faces` image, I'm expecting a result like,

```
Output 1: Matched 85%
Output 2: Matched 75%
Output 3: Matched 25%
```

`Note:` Matching percentage limit (0-100%)

**Comment by KiLJ4EdeN** [comment]
Check this out

https://github.com/ageitgey/face_recognition/wiki/Calculating-Accuracy-as-a-Percentage

**Comment by mesadhan** [comment]
Thank You!

**Comment by wahyu-handayani** [comment]
@mesadhan, I am trying to follow this https://github.com/ageitgey/face_recognition/wiki/Calculating-Accuracy-as-a-Percentage to get percentage of image matching. I am using KNN algorithm by following this repo : https://github.com/ageitgey/face_recognition/blob/master/examples/face_recognition_knn.py. The thing that makes me confused is how to get face_distance value. Is face_distance value coming from closest_distances ?.. I open a question, would you like to take a look https://github.com/ageitgey/face_recognition/issues/1318 ?
