### ISSUE TITLE
Rotation?

### ISSUE THREAD

**Issue by Rainbow-Unicorn-Oo** [ageitgey/face_recognition#122]
This is not so much an issue as a question... 

I really like your project, but what I would want to use it for is to make datasets for other machine learning applications, i.e. 

- recognising certain people in frames made from youtube videos
- extracting, aligning and resizing the correct faces from the frames (so the eyes are all in a very similar region for all the faces extracted from the frames)

Question A: As I understand it, the rectangles don't follow the rotation of the faces, is there an easy way to get the rotation, so that with rotation of the whole image, I could get an aligned face? 

If Question A is possible, Question B: The rectangles seem to be growing and shrinking, is there a way to get a similar size area for the faces, so I could resize all of the resulting images in a way, I would get the eyes of all the people from all the videos in a similar region of the resulting images (that all have the same size)?

**Comment by ageitgey** [comment]
Question A:

When you get face feature landmarks for a face, you can check the location of points that should be parallel (like the outer edge of both eyes or tops of both sides of chin) and then take the angle between those points to get the angle of the face in the image.

Question B: 

The same as A - use the detected face landmarks to resize the face to a pre-determined size. Like if the two sides of the chin are 200 pixels apart but you want a face 150 pixels wide, shrink the image down to match.

OR you can do both A and B in one step: Detect all the face landmarks in your image and then apply a transformation to make the face landmarks in your image match a pre-defined template. This is usually called "face alignment". This library does that internally in dlib's C code, but you can do it manually in Python code.

For example, here's how OpenFace does it in Python code using an affine transformation to make a detected face transform to match a pre-determined face landmark map: https://github.com/cmusatyalab/openface/blob/71ee6ee7477be8fe2a2865b5b60fdfef52cf5783/openface/align_dlib.py#L182-L187 (Note that their approach DOES distort the face somewhat which you might not want)

And here's OpenFace's pre-determined landmark map they are warping each face to match: https://github.com/cmusatyalab/openface/blob/71ee6ee7477be8fe2a2865b5b60fdfef52cf5783/openface/align_dlib.py#L22-L59 - each of those points maps to one face landmark point
