### ISSUE TITLE
web service (flask) example gives "Symbol not found: _PyUnicode_AsUTF8String"

### ISSUE THREAD

**Issue by Frank1234** [ageitgey/face_recognition#124]
* face_recognition version: 0.1.12
* Python version: 3.5
* Operating System: OSX Sierra

### Description

running the web service example on Flask

### What I Did

    import face_recognition
    from flask import Flask, jsonify, request, redirect

gives

File "/Users/Frank/hack/test/dlib/python_examples/face_recognition.py", line 50, in <module>
    import dlib
ImportError: dlopen(/Users/Frank/hack/test/dlib/python_examples/dlib.so, 2): Symbol not found: _PyUnicode_AsUTF8String
  Referenced from: /usr/local/opt/boost-python/lib/libboost_python3-mt.dylib
  Expected in: flat namespace
 in /usr/local/opt/boost-python/lib/libboost_python3-mt.dylib
172.16.25.97 - - [20/Jul/2017 11:15:30] "GET / HTTP/1.1" 500 -

**Comment by ageitgey** [comment]
This is an issue with your Python environment. Probably you compiled/installed libboost against a different version of Python (compiled with different unicode options) than you are using now. I'm guessing you'll need to re-install libboost from scratch to match your current Python install.
