### ISSUE TITLE
[QUESTION] Recognize face with machine learning of *multiple* images of face?

### ISSUE THREAD

**Issue by Hat000** [ageitgey/face_recognition#1244]
* face_recognition version: Newest on Nov 11 2020
* Python version: 3
* Operating System: Ubuntu

Is it possible to load multiple images to get a better facial recognition result? 
I want to load images of my face in different lighting conditions, looking in different directions etc. to see if I can achieve a better effect.

**Comment by caredebug** [comment]
Hi, face_recognition using One-shot learning. But you can add more than one image for same person. You can do this by adding each pose with the same name. In this way, you can recognize the face more accurately.

You can check this example:
[https://github.com/ageitgey/face_recognition/blob/master/examples/face_recognition_svm.py](url)
