### ISSUE TITLE
load_image_file method argument other than image file like base64 data or frame

### ISSUE THREAD

**Issue by prakash047** [ageitgey/face_recognition#125]
* face_recognition version: 0.10
* Python version:3.4
* Operating System:ubuntu

First off, thank you for the amazing module.

I am trying to do real time face capture and recognition in a webcam/camera using this. But load_image_file takes image file (physical file) as argument. Is there any way that I could pass real time image like base64 data or frame of the video??

**Comment by ageitgey** [comment]
`load_image_file` can load from either a physical file or any python stream. So for example if you have a jpg image stored in a `BytesIO` object, you can pass that right in to `load_image_file`. You can check out the web service example to see how that works.

But if you already have a frame of data from a video, you probably don't need to load anything and can just use the data directly. This library is expecting to work with a 3d numpy array representing the image as 3 channels of 8bit color. If you load a video frame using some other library, you probably already have access to that or could easily convert your data to that format. For example, check out the webcam examples to see how you can use a frame of video from a webcam directly without needing to load anything.
