### ISSUE TITLE
Fresh Install : Undefined Symbol: _ZTINSt6thread6_StateE

### ISSUE THREAD

**Issue by abhisheksoni27** [ageitgey/face_recognition#126]
* face_recognition version: 0.2.0
* Python version: 3.5.2
* Operating System: Ubuntu 17.04

### Description

Started the REPL python console, and typed `import face_recognition`

### What I Did
```
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import face_recognition
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/abhishek/anaconda3/envs/opencv/lib/python3.5/site-packages/face_recognition/__init__.py", line 7, in <module>
    from .api import load_image_file, face_locations, face_landmarks, face_encodings, compare_faces, face_distance
  File "/home/abhishek/anaconda3/envs/opencv/lib/python3.5/site-packages/face_recognition/api.py", line 4, in <module>
    import dlib
  File "/home/abhishek/anaconda3/envs/opencv/lib/python3.5/site-packages/dlib-19.4.0-py3.5-linux-x86_64.egg/dlib/__init__.py", line 1, in <module>
    from .dlib import *
ImportError: /home/abhishek/anaconda3/envs/opencv/lib/python3.5/site-packages/dlib-19.4.0-py3.5-linux-x86_64.egg/dlib/dlib.so: undefined symbol: _ZTINSt6thread6_StateE
```

**Comment by ageitgey** [comment]
I'm guessing this is an incompatibility between the binary version of dlib you installed via Anaconda and the versions of libraries (libc++) on your system. Unfortunately I can't really help with this kinds of issues. You might try compiling and installing dlib yourself from scratch to fix it.

**Comment by htoyryla** [comment]
I am getting the same error, having 

1. built dlib manually
2. inside a conda environment, installed dlib python bindings by "python setup.py ..."
3. inside the conda environment, installed face_recognition by "pip install face_recognition"

Looking by "conda list", I am definitively not having a dlib binary installed by conda. I am looking further into this. This happens on Lubuntu 17.04 on an Intel Compute Stick.

**Comment by htoyryla** [comment]
This appears related https://github.com/davisking/dlib/issues/807
I.e. the problem is related to gcc version.

**Comment by htoyryla** [comment]
I used most of yesterday on this (building lib from sources and trying to install it and face_recognition inside a conda env with python3.6 and opencv 3.3. Also tried gcc5/g++5 for building lib. Could not get everything working so I am giving up with face_recognition and using plain dlib (version 19.4) which installs and works together with opencv 3.3.
