### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by DavidePajot** [ageitgey/face_recognition#127]
* face_recognition version: 0.2.0
* Python version: 3.6.1
* Operating System: Manjaro Linux

### Description

Started the terminal, and typed python -m setup.py install

### What I Did

```
/usr/bin/python: Error while finding module specification for 'setup.py' (AttributeError: module 'setup' has no attribute '__path__')
```

**Comment by ageitgey** [comment]
That's not how you install this. Try it without `-m`. In other words, you can just run `python setup.py install`.
