### ISSUE TITLE
Using a already loaded image with the recognition functions?

### ISSUE THREAD

**Issue by TristanBeer** [ageitgey/face_recognition#1270]
* face_recognition version: 1.3.0
* Python version: 3.8
* Operating System: Windows 10

### Description

I am trying to crop half the image out before running face recognition (The face is always in the top half) but I am unable to find a way to do this without saving the image after running the crop as there seems to be no way to pass a image to face_recognition with using face_recognition.load_image_file.  
Link to code on stackoverflow
https://stackoverflow.com/questions/65864029/passing-image-data-from-pil-to-face-recognition-library

### What I Did

```
I have tried passing a numpy array and a loaded image from PIL directly to the other functions bypassing the FR load function but with no luck.  
```

**Comment by KiLJ4EdeN** [comment]
If you take a look at the [webcam example](https://github.com/ageitgey/face_recognition/blob/master/examples/facerec_from_webcam.py)
The frame is passed directly after a color conversion and is not saved beforehand.
```python
ret, frame = video_capture.read()
rgb_frame = frame[:, :, ::-1]
face_recognition.face_locations(rgb_frame)
```

**Comment by TristanBeer** [comment]
> If you take a look at the [webcam example](https://github.com/ageitgey/face_recognition/blob/master/examples/facerec_from_webcam.py)
> The frame is passed directly after a color conversion and is not saved beforehand.
> 
> ```python
> ret, frame = video_capture.read()
> rgb_frame = frame[:, :, ::-1]
> face_recognition.face_locations(rgb_frame)
> ```

Yup, and my first assumption was to simply run my PIL image though np.array and feed it that, but it gives me a TypeError: __call__(): incompatible function arguments.
