### ISSUE TITLE
Recognizes more than one person in an image with only one person

### ISSUE THREAD

**Issue by ethirajsrinivasan** [ageitgey/face_recognition#129]
* face_recognition version: 0.2.0
* Python version: 3.5.2
* Operating System: Ubuntu 16.04

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

The  library was mentioned to return only one person but in the example given below it return two or more person. The image contains only one person. 
![image](https://user-images.githubusercontent.com/7569031/28714029-1abf1e64-73c4-11e7-9904-f595dee7a72e.png)

**Comment by ageitgey** [comment]
No model is perfect, so it's possible it made a mistake. But it's also possible there was something wrong with the pictures themselves. Without seeing the pictures, there's not really anything I can do to debug it unfortunately.

**Comment by Dineshkarthik** [comment]
Facing the same issue as above.

- face_recognition version: 0.2.0
- Python version: 3.5.2
- Operating System: Ubuntu 16.04

![image](https://user-images.githubusercontent.com/7752572/28920377-2d0c2058-786f-11e7-88b7-cbf54284a2f2.jpg)

Used images can be found [here](https://drive.google.com/file/d/0B1zkQ2AHOszfTjBDZjA0S0V3b1E/view?usp=sharing)

**Comment by ageitgey** [comment]
Hi @Dineshkarthik,

Thanks for sharing the photos. The problem is that the default tolerance value used in the CLI is too loose for your photos. I added a new way to control that in version 0.2.1.

So if you update to the latest version that I just released, you can try the new `--tolerance` parameter like this:

```bash
$ face_recognition --tolerance 0.54 known_pictures/ unknown_pictures/
WARNING: More than one face found in known_pictures/ethi.jpg. Only considering the first face.
unknown_pictures/10353313_715561941823848_7226492955083170104_o.jpg,bharad
unknown_pictures/10413426_970797789619219_7982372525457487040_n.jpg,ethi
unknown_pictures/13232962_10204711715912221_1327258177329516625_n.jpg,amer
unknown_pictures/1510994_10200347000717069_803620821_n.jpg,amer
unknown_pictures/15625978_10207271337454586_535108498906335285_o.jpg,dinesh
```
