### ISSUE TITLE
Not using GPU

### ISSUE THREAD

**Issue by gaurav7700** [ageitgey/face_recognition#1295]
* face_recognition version: latest from github
* Python version:3.8
* Operating System: windows 10

### Description
Code is not using gpu instead using cpu even after successful dlib build with avx instructions and Dlib use cuda 
its showing dlib use cuda = 1 in python
Please Help
 [
![image](https://user-images.githubusercontent.com/81248091/112277589-06ce3780-8cd6-11eb-8abe-d8bace205ef6.png)
](url)
Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.
IMPORTANT: If your issue is related to a specific picture, include it so others can reproduce the issue.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by redionxhepa** [comment]
How did you make it use the GPU ?
