### ISSUE TITLE
face_locations can be negative

### ISSUE THREAD

**Issue by fourtytwo** [ageitgey/face_recognition#13]
* face_recognition version:0.1.9
* Python version:3.5
* Operating System:Ubuntu

### Description

The resulting location/bounding boxes returned by face_recognition.face_locations(img)    
can contain negative numbers. I don't know if this is intentional(if so then please enlighten me when this might be useful)

### What I Did

Basically to solve the problem is used max(0...)
Also the image that lead to the problem was: http://scd.france24.com/en/files/imagecache/france24_ct_api_bigger_169/article/image/french-students-assembly-two.jpg

**Comment by ageitgey** [comment]
Thanks for the report. I agree that is confusing and error-prone. I'll take a look. Thanks for including a test image!
