### ISSUE TITLE
Details of face_encodings() function

### ISSUE THREAD

**Issue by AI-07** [ageitgey/face_recognition#1312]
* face_recognition version:1.3.0
* Python version:3.x
* Operating System:linux

### Description

Actually this is not an issue, rather an effort to know the details of 'face_encondings()' function.

### What I Did
so in the examples in Markdown file, you always take very first list of returned multiple lists. What does this function actually return and why do you always take the first list for comparison?

**Comment by bohdansok** [comment]
It returns a list of arrays (encodings) for every face being found at the picture according to the face boxes list you've provided to the function.
