### ISSUE TITLE
How to solve error (-255 Assertion failed)

### ISSUE THREAD

**Issue by syedali3762** [ageitgey/face_recognition#1316]
* face_recognition 
* Python version:3.9 
* Operating System: Windows

Description:

OpenCV(4.5.2) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-kuwfz3h3\opencv\modules\objdetect\src\cascadedetect.cpp:1689: error: (-215:Assertion failed) !empty() in function 'cv::CascadeClassifier::detectMultiScale'

IMPORTANT: 

![error1](https://user-images.githubusercontent.com/46029049/119278529-4dd99a00-bc3f-11eb-9cf9-627a3f297238.png)
![error2](https://user-images.githubusercontent.com/46029049/119278533-4f0ac700-bc3f-11eb-91b2-25ee9aabe16e.png)

And please do guide me for this warning message too.
Thanking you!

**Comment by abinisaac** [comment]
Were you able to solve this ?
