### ISSUE TITLE
is there any same project written in java？

### ISSUE THREAD

**Issue by ExtremeYu** [ageitgey/face_recognition#132]

**Comment by TH4NOS** [comment]
There are many written in java but majority of them are for android. You can check them out on Github by filtering the search results.


Cheers!!

**Comment by ExtremeYu** [comment]
yes,i try to search github using keyword face recognition, almost are android project ,and also less features or lower accuracy  ,i want a full function of face_recognition project like this but written in java,can you recommand some?

**Comment by ageitgey** [comment]
Sorry, I'm not really familiar with what similar tools might exist for java.

**Comment by AndrosEt** [comment]
@ExtremeYu  I'm trying to wrap up face_recognition project with Jave project, and it can work on one docker image which running two project at same time. I will try to wrap up the whole face_recognition as a RESTful API service with Java. Can check this dockerfile https://github.com/AndrosEt/face_recognition/blob/master/Dockerfile, ps. this's just demo
