### ISSUE TITLE
CUDA docker image build: dlib invalid syntax(license_files)

### ISSUE THREAD

**Issue by GHRik** [ageitgey/face_recognition#1321]
* face_recognition version:  from master
* Python version: 3.5
* Operating System: Linux 18.04.05

### Description

I am trying to build dlib with enable CUDA
and get an error:

```
Step 13/22 : RUN cd /dlib; python3 /dlib/setup.py install
 ---> Running in 2a6f8e09f8d2
Traceback (most recent call last):
  File "/dlib/setup.py", line 42, in <module>
    from setuptools import setup, Extension
  File "/usr/local/lib/python3.5/dist-packages/setuptools/__init__.py", line 18, in <module>
    from setuptools.dist import Distribution
  File "/usr/local/lib/python3.5/dist-packages/setuptools/dist.py", line 585
    license_files: Optional[List[str]] = self.metadata.license_files
                 ^
SyntaxError: invalid syntax
```

### What I Did

I am trying to build docker image using this Docerfile:
```
FROM nvidia/cuda:9.0-cudnn7-devel
# Install face recognition dependencies

RUN apt update -y; apt install -y \
git \
cmake \
libsm6 \
libxext6 \
libxrender-dev \
python3 \
python3-pip

RUN pip3 install scikit-build

# Install compilers

RUN apt install -y software-properties-common
RUN add-apt-repository ppa:ubuntu-toolchain-r/test
RUN apt update -y; apt install -y gcc-6 g++-6

RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 50
RUN update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 50

#Install dlib 

RUN git clone -b 'v19.16' --single-branch https://github.com/davisking/dlib.git
RUN mkdir -p /dlib/build

RUN cmake -H/dlib -B/dlib/build -DDLIB_USE_CUDA=1 -DUSE_AVX_INSTRUCTIONS=1
RUN cmake --build /dlib/build

RUN cd /dlib; python3 /dlib/setup.py install

# Install the face recognition package

RUN pip3 install face_recognition
RUN python3 -m pip install grpcio
RUN python3 -m pip install grpcio-tools

COPY face_pb2_grpc.py /root
COPY face_pb2.py /root
COPY identifier.py /root

VOLUME [ "/unknown_people", "/known_people" ]

EXPOSE 50051

CMD [ "python3", "/root/identifier.py" ]
```

I was trying build image via dlib v19.6 / v19.5 / v19.7 and problem still exist.

**Comment by GHRik** [comment]
It is caused by new version on
```setuptools```
https://github.com/pypa/setuptools/pull/2676

To properly deploy version setuptools should be used:
``` setuptools<57.0.0```

I will test it and notice to this issue.

**Comment by GHRik** [comment]
If anyone will be have a similary problem i create a new Dockerfile which fill all needed dependencies.
https://github.com/GHRik/Disturbed-k8s-face-recognition/blob/master/images/face_recognitionGPU/Dockerfile

**Comment by JcJinChen** [comment]
i‘ve tried multiple versions setuptools(including 54.2.0,56.0.0,57.1.0) ,the output is always “license_files: Optional[List[str]] = self.metadata.license_files
                 ^
SyntaxError: invalid syntax”, thanks 

> It is caused by new version on
> `setuptools`
> [pypa/setuptools#2676](https://github.com/pypa/setuptools/pull/2676)
> 
> To properly deploy version setuptools should be used:
> ` setuptools<57.0.0`
> 
> I will test it and notice to this issue.
