### ISSUE TITLE
why i have import dlib  but use "pip3 install face_recognition"  tips i donot import dlib  

### ISSUE THREAD

**Issue by xiaobai987292** [ageitgey/face_recognition#134]
* face_recognition version:
* Python version:3.6
* Operating System:win7 64

### Description

why i have import dlib  but use "pip3 install face_recognition"  tips i donot import dlib  

### What I Did

i use conda install -c menpo dlib  then copy dlib.pyd to  Python36\Lib\site-packages 
and import dlib without any error  but use "pip3 install face_recognition"  tips i donot import dlib

**Comment by ageitgey** [comment]
Sorry, I'm not sure I understand the question. If you got a specific error, please post the full error message.
