### ISSUE TITLE
face_recognization with python

### ISSUE THREAD

**Issue by rombysoft** [ageitgey/face_recognition#135]
* face_recognition version:
* Python version:3.5
* Operating System:windows

### Description

 I am working with some python face reorganization code in which I want to compare sampleface.jpg which contains a sample face with facegrid.jpg. The facegrid.jpg itself has some 6 faces in it. I am getting results as true for every face while I should be getting only one. The code is below. 

```python
import face_recognition
image = face_recognition.load_image_file("faceGrid.jpg")
sample_image = face_recognition.load_image_file("sampleface.jpg")

sample_face_encoding = face_recognition.face_encodings(sample_image)

face_locations = face_recognition.face_locations(image)

print (len(face_locations), " Faces")

for face_location in face_locations:
    top, right, bottom, left = face_location
    face_image = image[top:bottom, left:right]
    face_encodings = face_recognition.face_encodings(face_image)[0]
    if face_recognition.compare_faces(sample_face_encoding,face_encodings)[0]:
      print ("Found!")
```

**Comment by ageitgey** [comment]
If you want, you can simplify your `for` loop like this:

```python
for face_location in face_locations:
    face_encodings = face_recognition.face_encodings(image, known_face_locations=[face_location])[0]

    if face_recognition.compare_faces(sample_face_encoding,face_encodings)[0]:
      print("Found!")
```

But as far as why it is returning True for each face, I'm not sure without seeing the images in question. You might try adding this line to your `for` loop to print out each face distance:

```python
    print(face_recognition.face_distance(sample_face_encoding,face_encodings)[0])
```
That will show you how similar each face is to your sample face in terms of distance. By default, `compare_faces` checks for faces less the 0.6 distance apart to count as a match. Maybe your faces are very similar and need a smaller distance. You can use a smaller distance tolerance like this with the tolerance parameter:

```python
    if face_recognition.compare_faces(sample_face_encoding, face_encodings, tolerance=0.5)[0]:
```

**Comment by rombysoft** [comment]
This is faceGrid.jpg I am using and Sampleface.jpg can have any face from one of the faces in grid image.


![facegrid](https://user-images.githubusercontent.com/30628525/28834070-eab1a582-76fe-11e7-91e3-2811804bf5b7.jpg)

**Comment by ageitgey** [comment]
Oh. As noted in the README, this model is not trained on children and does not work well on children. Try using some adult photos instead.

**Comment by rombysoft** [comment]
You are right. It works only for adults. Thank you.
