### ISSUE TITLE
"Unsupported image type, must be 8bit gray or RGB image."

### ISSUE THREAD

**Issue by hkyq** [ageitgey/face_recognition#136]
* face_recognition version: Latest, just installed today from pip3
* Python version: 3.5.2
* Operating System: Fresh install of Ubuntu

### Description

I was just playing around with some of the example scripts, when I get this error:

> sudo python3 main.py obama.jpg
> obama.jpg
> Traceback (most recent call last):
>   File "main.py", line 13, in <module>
>     unkown_image_encoding = face_recognition.face_encodings(unknown_image)[0]
>   File "/usr/local/lib/python3.5/dist-packages/face_recognition/api.py", line 146, in face_encodings
>     raw_landmarks = _raw_face_landmarks(face_image, known_face_locations)
>   File "/usr/local/lib/python3.5/dist-packages/face_recognition/api.py", line 105, in _raw_face_landmarks
>     face_locations = _raw_face_locations(face_image)
>   File "/usr/local/lib/python3.5/dist-packages/face_recognition/api.py", line 89, in _raw_face_locations
>     return face_detector(img, number_of_times_to_upsample)
> RuntimeError: Unsupported image type, must be 8bit gray or RGB image.

### What I Did

```
import face_recognition
import sys

unknown_image = sys.argv[1]
print(sys.argv[1])
obama_image = face_recognition.load_image_file('obama.jpg')
obama_image_encoding = face_recognition.face_encodings(obama_image)[0]

biden_image = face_recognition.load_image_file('biden.jpg')
biden_image_encoding = face_recognition.face_encodings(biden_image)[0]


unkown_image_encoding = face_recognition.face_encodings(unknown_image)[0]

knownfaces = [
obama_image_encoding,
biden_image_encoding
]

results = face_recognition.compare_faces(knownfaces, unkown_image_encoding)
print(results)

if results[0] == True and results[1] == False:
    print("It's Obama!")
elif results[1] == True and results[0] == False: 
    print("It's Biden!")
else:
    print('Unknown person')

```

The weird thing is that I tried running it without the sys.argv and with the same files, it works.

**Comment by ageitgey** [comment]
You need to call `face_recognition.load_image_file()' on the file name you pass in via argv. argv is just a string file name, not an array of image data.

**Comment by hkyq** [comment]
Ohhh, I see. Thanks. Still a beginner, your help is greatly appreciated. :D

**Comment by ageitgey** [comment]
No problem :-)

**Comment by mberenjkoub** [comment]
I used face_recognition.load_image_file() to load the captured image but camera but still it has this error:
unknown_face_encoding = face_recognition.face_encodings(unknown_image)[0]
IndexError: list index out of range

Also, it is very slow especially on Raspberry pi.

**Comment by vrushang25** [comment]
import face_recognition
import cv2
import os
import numpy as np
from PIL import Image



path='dataset2'
imagepath = [os.path.join(path,f)for f in os.listdir(path)]
print imagepath
images=[]
for i in imagepath:
	ID = int(os.path.split(i)[-1].split('.')[1])
	print ID
	faceimg = Image.open(i).convert('L')
	print faceimg
	#obama_image = face_recognition.load_image_file(faceimg)
	obama_image = face_recognition.load_image_file("dataset2/vrushang."+str(ID)+".jpg")
#face_recognition.load_image_file(i).convert('L')
	image=np.array(obama_image)
	images.append(image)
print images
obama_face_encoding = face_recognition.face_encodings(images)[0]
# Initialize some variables
face_locations = []
face_encodings = []
face_names = []
process_this_frame = True

while True:
    # Grab a single frame of video
    ret, frame = video_capture.read()

    # Resize frame of video to 1/4 size for faster face recognition processing
    small_frame = cv2.resize(frame, (0, 0), fx=0.25, fy=0.25)

    # Only process every other frame of video to save time
    if process_this_frame:
        # Find all the faces and face encodings in the current frame of video
        face_locations = face_recognition.face_locations(small_frame)
        face_encodings = face_recognition.face_encodings(small_frame, face_locations)

        face_names = []
        for face_encoding in face_encodings:
            # See if the face is a match for the known face(s)
            match = face_recognition.compare_faces([obama_face_encoding], face_encoding)
            

            if match[0]:
                name = "vrushang"
	    else:
		name = "unknown"
		

            face_names.append(name)

    process_this_frame = not process_this_frame


    # Display the results
    for (top, right, bottom, left), name in zip(face_locations, face_names):
        # Scale back up face locations since the frame we detected in was scaled to 1/4 size
        top *= 4
        right *= 4
        bottom *= 4
        left *= 4

        # Draw a box around the face
        cv2.rectangle(frame, (left, top), (right, bottom), (0, 0, 255), 2)

        # Draw a label with a name below the face
        cv2.rectangle(frame, (left, bottom - 35), (right, bottom), (0, 0, 255), cv2.FILLED)
        font = cv2.FONT_HERSHEY_SIMPLEX
        cv2.putText(frame, name, (left + 6, bottom - 6), font, 1.0, (255, 255, 255), 1)

    # Display the resulting image
    cv2.imshow('Video', frame)

    # Hit 'q' on the keyboard to quit!
    if cv2.waitKey(1)==27:
        break

# Release handle to the webcam
video_capture.release()
cv2.destroyAllWindows()


i am getting this output with error.

['dataset2/vrushang.1.jpg', 'dataset2/vrushang.2.jpg']
1
<PIL.Image.Image image mode=L size=358x358 at 0x7F9EB10B7650>
2
<PIL.Image.Image image mode=L size=412x412 at 0x7F9EB10B7190>
[array([[[101, 101, 101],
        [101, 101, 101],
        [101, 101, 101],
        ..., 
        [ 35,  35,  35],
        [ 36,  36,  36],
        [ 36,  36,  36]],

       [[101, 101, 101],
        [101, 101, 101],
        [100, 100, 100],
        ..., 
        [ 34,  34,  34],
        [ 35,  35,  35],
        [ 35,  35,  35]],

       [[101, 101, 101],
        [101, 101, 101],
        [101, 101, 101],
        ..., 
        [ 36,  36,  36],
        [ 36,  36,  36],
        [ 36,  36,  36]],

       ..., 
       [[ 43,  43,  43],
        [ 46,  46,  46],
        [ 48,  48,  48],
        ..., 
        [ 55,  55,  55],
        [ 55,  55,  55],
        [ 55,  55,  55]],

       [[ 42,  42,  42],
        [ 44,  44,  44],
        [ 47,  47,  47],
        ..., 
        [ 54,  54,  54],
        [ 53,  53,  53],
        [ 53,  53,  53]],

       [[ 41,  41,  41],
        [ 43,  43,  43],
        [ 46,  46,  46],
        ..., 
        [ 53,  53,  53],
        [ 52,  52,  52],
        [ 51,  51,  51]]], dtype=uint8), array([[[158, 158, 158],
        [159, 159, 159],
        [159, 159, 159],
        ..., 
        [172, 172, 172],
        [172, 172, 172],
        [172, 172, 172]],

       [[159, 159, 159],
        [159, 159, 159],
        [158, 158, 158],
        ..., 
        [173, 173, 173],
        [173, 173, 173],
        [172, 172, 172]],

       [[159, 159, 159],
        [158, 158, 158],
        [156, 156, 156],
        ..., 
        [174, 174, 174],
        [173, 173, 173],
        [172, 172, 172]],

       ..., 
       [[145, 145, 145],
        [144, 144, 144],
        [144, 144, 144],
        ..., 
        [ 90,  90,  90],
        [ 90,  90,  90],
        [ 90,  90,  90]],

       [[143, 143, 143],
        [144, 144, 144],
        [144, 144, 144],
        ..., 
        [ 89,  89,  89],
        [ 89,  89,  89],
        [ 89,  89,  89]],

       [[142, 142, 142],
        [143, 143, 143],
        [145, 145, 145],
        ..., 
        [ 88,  88,  88],
        [ 88,  88,  88],
        [ 89,  89,  89]]], dtype=uint8)]
Traceback (most recent call last):
  File "fc.py", line 27, in <module>
    obama_face_encoding = face_recognition.face_encodings(images)[0]
  File "/usr/local/lib/python2.7/dist-packages/face_recognition/api.py", line 189, in face_encodings
    raw_landmarks = _raw_face_landmarks(face_image, known_face_locations)
  File "/usr/local/lib/python2.7/dist-packages/face_recognition/api.py", line 148, in _raw_face_landmarks
    face_locations = _raw_face_locations(face_image)
  File "/usr/local/lib/python2.7/dist-packages/face_recognition/api.py", line 97, in _raw_face_locations
    return face_detector(img, number_of_times_to_upsample)
RuntimeError: Unsupported image type, must be 8bit gray or RGB image.



i am trying to access whole bunch of images by converting it to array and then put it in single encoding part .how to solve this problem?

**Comment by ageitgey** [comment]
@mberenjkoub 

```python
unknown_face_encoding = face_recognition.face_encodings(unknown_image)[0]
IndexError: list index out of range
```

That just means no face encodings were found in that particular image. Just check the length of the array before assuming it has something in it:

```python
face_encodings = face_recognition.face_encodings(unknown_image)

if len(face_encodings) == 0:
    print("No faces found!")
else:
    unknown_face_encoding = face_encodings[0]
```

**Comment by ageitgey** [comment]
@vrushang25 
```python
obama_face_encoding = face_recognition.face_encodings(images)[0]
```

The `face_encodings()` function doesn't take in an array of multiple images. It takes in a single image. You can't just pass in a list of numpy arrays to it.

Instead, just call `face_encodings()` once for each images in your `images` array.

**Comment by vrushang25** [comment]
now i solve the problem but it recognise me and my brother with same name why?
i make the array of the encoding part of images to compare but gives error many times 
my code is below:-


import face_recognition
import cv2
import os
import numpy as np
from PIL import Image
import time
cap = cv2.VideoCapture(1)

count=1
path='dataset2'

img=[]
imagepath = [os.path.join(path,f)for f in os.listdir(path)]
c=len(imagepath)
#for i in imagepath: i access the each images from my folder of images
while count<=c:	
	image = face_recognition.load_image_file("dataset2/vrushang."+str(count)+".jpg")
	#now i will make list of the encoding parts to compare it runtime detected face
	img.append(face_recognition.face_encodings(image)[0])
	time.sleep(1)
	count=count+1
	
'''obama_image = face_recognition.load_image_file("dataset2/vrushang.1.jpg")
obama_encoding = face_recognition.face_encodings(obama_image)[0]
# Initialize some variables
biden_image = face_recognition.load_image_file('dataset2/vrushang.2.jpg')
biden_encoding = face_recognition.face_encodings(biden_image)[0]
knownfaces=[]
knownfaces.append(obama_encoding) 
knownfaces.append(biden_encoding) 
print knownfaces'''

face_locations = []
face_encodings = []
face_names = []
process_this_frame = True
img2 = []
img2 = img[0]
print"this is img2"
print img

while True:   
    ret, frame = cap.read()
    small_frame = cv2.resize(frame, (0, 0), fx=0.25, fy=0.25)  
    if process_this_frame:
       
        face_locations = face_recognition.face_locations(small_frame)
        face_encodings = face_recognition.face_encodings(small_frame, face_locations)
	
        face_names = []
        for face_encoding in face_encodings:
           
            match = face_recognition.compare_faces(img, face_encoding)
            print match
	   
           if match[0]==True:
               name = "vrushang"
	   elif match[1]==True:
               name = "hitu"	
	   elif match[3]==True:
               name = "sardar patel"	
	   elif match[2]==True:
               name = "yaksh"
	   else:		
	   	name = "unknown"
            face_names.append(name)
    process_this_frame = not process_this_frame   
    for (top, right, bottom, left), name in zip(face_locations, face_names):
      
        top *= 4
        right *= 4
        bottom *= 4
        left *= 4

     
        cv2.rectangle(frame, (left, top), (right, bottom), (0, 0, 255), 2)

      
        cv2.rectangle(frame, (left, bottom - 35), (right, bottom), (0, 0, 255), cv2.FILLED)
        font = cv2.FONT_HERSHEY_SIMPLEX
        cv2.putText(frame, name, (left + 6, bottom - 6), font, 1.0, (255, 255, 255), 1)

   
    cv2.imshow('Video', frame)

   
    if cv2.waitKey(1)==27:
        break

# Release handle to the webcam
cap.release()
cv2.destroyAllWindows()

**Comment by vrushang25** [comment]
many of my relatives are wrongly recognized with this code can you please help me for this proble?

**Comment by RahulData** [comment]
Can you please say whether face_recognition.load_image_file() function supports an image using a web URL.

**Comment by ageitgey** [comment]
No, it doesn't load images from URLs. You would have to code that yourself.

**Comment by zoldaten** [comment]
Convert the image from BGR color (which OpenCV uses) to RGB color (which face_recognition uses)
`rgb_small_frame = small_frame[:, :, ::-1]`

**Comment by Charlilyyyy** [comment]
import cv2
import face_recognition

# Load the first image and convert it from BGR to RGB
img = cv2.imread("./images/bon-ic.jpeg")
rgb_img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# Encode the first image
img_encoding = face_recognition.face_encodings(rgb_img)[0]

# Load the second image and convert it from BGR to RGB
img2 = cv2.imread("./images/bon-face.jpeg")
rgb_img2 = cv2.cvtColor(img2, cv2.COLOR_BGR2RGB)

# Encode the second image
img_encoding2 = face_recognition.face_encodings(rgb_img2)[0]

# Compare the faces
result = face_recognition.compare_faces([img_encoding], img_encoding2)
print("Result: ", result)

# Display the images
cv2.imshow("Img", img)
cv2.imshow("Img 2", img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

i get: RuntimeError: Unsupported image type, must be 8bit gray or RGB image.

**Comment by Mohamed-lehbib** [comment]
have a Django app in which I want to add face recognition functionality, but I'm encountering an issue that I haven't been able to fix. The error message is:

```
Frame shape: (720, 1280, 3), Frame dtype: uint8
Error processing frame: Unsupported image type, must be 8-bit gray or RGB image.
```

Here are the versions of the libraries I'm using:

```txt
asgiref==3.8.1
click==8.1.7
cmake==3.29.5.1
Django==3.1.3
dlib==19.24.4
face-recognition==1.3.0
face-recognition-models==0.3.0
numpy==2.0.0
opencv-python==4.10.0.84
Pillow==10.3.0
playsound==1.2.2
pytz==2020.4
sqlparse==0.5.0
```
I have converted the frame from OpenCV from BGR to RGB, but the error persists. Here is my code:

```python
def gen_frames():
    global known_face_encodings, known_face_names

    video_capture = cv2.VideoCapture(0)
    while True:
        success, frame = video_capture.read()
        if not success:
            break
        else:
            print(f"Frame shape: {frame.shape}, Frame dtype: {frame.dtype}")

            # Ensure the frame is valid
            if frame is None:
                print("Invalid frame")
                continue

            # Resize frame of video to 1/4 size for faster face recognition processing
            small_frame = cv2.resize(frame, (0, 0), fx=0.25, fy=0.25)

            # Convert the frame to RGB
            rgb_frame = cv2.cvtColor(small_frame, cv2.COLOR_BGR2RGB)
            
            # Find all the faces and face encodings in the current frame of video
            try:
                face_locations = face_recognition.face_locations(rgb_frame, model='hog')
                face_encodings = face_recognition.face_encodings(rgb_frame, face_locations)
                face_names = []
                for face_encoding in face_encodings:
                    # See if the face is a match for the known face(s)
                    matches = face_recognition.compare_faces(known_face_encodings, face_encoding)
                    name = "Unknown"
                    # Or instead, use the known face with the smallest distance to the new face
                    face_distances = face_recognition.face_distance(known_face_encodings, face_encoding)
                    best_match_index = np.argmin(face_distances)
                    if matches[best_match_index]:
                        name = known_face_names[best_match_index]
                    face_names.append(name)

                # Display the results
                for (top, right, bottom, left), name in zip(face_locations, face_names):
                    # Scale back up face locations since the frame we detected in was scaled to 1/4 size
                    top *= 4
                    right *= 4
                    bottom *= 4
                    left *= 4
                    # Draw a box around the face
                    cv2.rectangle(frame, (left, top), (right, bottom), (0, 0, 255), 2)
                    # Draw a label with a name below the face
                    cv2.rectangle(frame, (left, bottom - 35), (right, bottom), (0, 0, 255), cv2.FILLED)
                    font = cv2.FONT_HERSHEY_DUPLEX
                    cv2.putText(frame, name, (left + 6, bottom - 6), font, 1.0, (255, 255, 255), 1)

            except Exception as e:
                print(f"Error processing frame: {e}")

            # Encode the frame in JPEG format
            ret, buffer = cv2.imencode('.jpg', frame)
            frame = buffer.tobytes()

            yield (b'--frame\r\n'
                   b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')

    video_capture.release()

def scan(request):
    global known_face_encodings, known_face_names

    last_face = ""

    known_face_encodings = []
    known_face_names = []

    profiles = Profile.objects.all()
    for profile in profiles:
        person = profile.image
        image_path = os.path.join('media', str(person))
        if not os.path.exists(image_path):
            continue
        try:
            image_of_person = face_recognition.load_image_file(image_path)
            if image_of_person.ndim == 2:  # grayscale image
                image_of_person = cv2.cvtColor(image_of_person, cv2.COLOR_GRAY2RGB)
            elif image_of_person.ndim == 3 and image_of_person.shape[2] == 4:  # RGBA image
                image_of_person = cv2.cvtColor(image_of_person, cv2.COLOR_RGBA2RGB)
            elif image_of_person.ndim == 3 and image_of_person.shape[2] != 3:  # Unsupported image type
                print(f"Unsupported image type for {image_path}, skipping...")
                continue
            person_face_encoding = face_recognition.face_encodings(image_of_person)[0]
            known_face_encodings.append(person_face_encoding)
            known_face_names.append(str(person)[:-4])
        except IndexError:
            print(f"Could not find any faces in the image {image_path}")
        except Exception as e:
            print(f"Error loading image {image_path}: {e}")

    return StreamingHttpResponse(gen_frames(), content_type='multipart/x-mixed-replace; boundary=frame')
```

I would appreciate any help in fixing this issue.

**Comment by OlliejED** [comment]
Numpy had a major version update which doesn't seem compatable with dlib. I solved this error by downgrading my version from 2.0.0 -> 1.26.4.

@Mohamed-lehbib from the versions you have provided, I think you may be getting this error for the same reason. Try downgrading your numpy version. @Charlilyyyy this might help you too.

**Comment by Surajofficial** [comment]
import base64
import cv2
import numpy as np
from django.shortcuts import render
from django.core.files.base import ContentFile
from PIL import Image
import imagehash
import face_recognition
from .models import UserImage
from .forms import ImageUploadForm

from django.http import JsonResponse
import base64
import cv2
import numpy as np
import face_recognition


def validate_image(request):
    if request.method == 'POST':
        image_data = request.POST.get('image')
        if image_data:
            format, imgstr = image_data.split(';base64,')
            img_data = base64.b64decode(imgstr)

            # Decode image and ensure it is in RGB format
            nparr = np.frombuffer(img_data, np.uint8)
            img_np = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
            img_rgb = cv2.cvtColor(img_np, cv2.COLOR_BGR2RGB)

            face_locations = face_recognition.face_locations(img_rgb)

            if len(face_locations) == 1:
                return JsonResponse({'valid': True})
            else:
                return JsonResponse({'valid': False})
    return JsonResponse({'valid': False})


def upload_image(request):
    if request.method == 'POST':
        image_data = request.POST.get('image')
        if image_data:
            format, imgstr = image_data.split(';base64,')
            ext = format.split('/')[-1]
            img_data = base64.b64decode(imgstr)

            # Decode image and ensure it is in RGB format
            nparr = np.frombuffer(img_data, np.uint8)
            # nparr=nparr.astype('uint8')
            img_np = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
            if img_np is None:
                return render(request, 'image_comparison/result.html', {'error': 'Failed to decode image.'})

            img_rgb = cv2.cvtColor(img_np, cv2.COLOR_BGR2RGB)
            if img_rgb is None:
                return render(request, 'image_comparison/result.html', {'error': 'Failed to convert image to RGB.'})

            face_locations = face_recognition.face_locations(img_rgb)

            if len(face_locations) != 1:
                return render(request, 'image_comparison/result.html', {'error': 'Please ensure only one face is in the frame and try again.'})

            # Save the image
            img = Image.fromarray(img_rgb)
            buffered = ContentFile(
                base64.b64decode(imgstr), name='temp.' + ext)
            uploaded_image = UserImage(name="Captured Image", image=buffered)
            uploaded_image.image.save('temp.' + ext, buffered)
            uploaded_image_path = uploaded_image.image.path
            uploaded_image_hash = imagehash.average_hash(img)

            for user_image in UserImage.objects.all():
                user_image_path = user_image.image.path
                user_image_hash = imagehash.average_hash(
                    Image.open(user_image_path))

                if uploaded_image_hash == user_image_hash:
                    return render(request, 'image_comparison/result.html', {'match': user_image, 'exists': True})

            uploaded_image.save()
            return render(request, 'image_comparison/result.html', {'match': uploaded_image, 'exists': False})
    else:
        form = ImageUploadForm()
    return render(request, 'image_comparison/upload_image.html', {'form': form})
this is my django code and i am getting error 

`<h1 style="padding: 0px; margin: 0px; font-weight: normal; color: rgb(0, 0, 0); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">RuntimeError at /upload/</h1><pre class="exception_value" style="padding: 0px; margin: 10px 0px; font-size: 1.5em; white-space: pre-wrap; word-break: break-word; font-family: sans-serif; color: rgb(87, 87, 87); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Unsupported image type, must be 8bit gray or RGB image.</pre>
Request Method: | POST
-- | --
http://127.0.0.1:8000/upload/
4.2.13
RuntimeError
Unsupported image type, must be 8bit gray or RGB image.
/home/ajay/Downloads/imagecheck/imagecheck/venv/lib/python3.9/site-packages/face_recognition/api.py, line 105, in _raw_face_locations
image_comparison.views.upload_image
/home/ajay/Downloads/imagecheck/imagecheck/venv/bin/python
3.9.19
['/home/ajay/Downloads/imagecheck/imagecheck',  '/home/ajay/.pyenv/versions/3.9.19/lib/python39.zip',  '/home/ajay/.pyenv/versions/3.9.19/lib/python3.9',  '/home/ajay/.pyenv/versions/3.9.19/lib/python3.9/lib-dynload',  '/home/ajay/Downloads/imagecheck/imagecheck/venv/lib/python3.9/site-packages']
Mon, 24 Jun 2024 11:48:54 +0000

please help me i am completely biggnner

**Comment by Mohamed-lehbib-abeidna** [comment]
> Numpy had a major version update which doesn't seem compatable with dlib. I solved this error by downgrading my version from 2.0.0 -> 1.26.4.
> 
> @Mohamed-lehbib from the versions you have provided, I think you may be getting this error for the same reason. Try downgrading your numpy version. @Charlilyyyy this might help you too.

Thank you very much. I resolved the issue yesterday by downgrading the versions of NumPy and OpenCV. Here is the requirements.txt file in case it helps anyone:
```text
asgiref==3.8.1
click==8.1.7
cmake==3.29.5.1
Django==3.1.3
dlib==19.24.4
face-recognition==1.1.0
face-recognition-models==0.3.0
numpy==1.26.4
opencv-python==4.5.5.64
Pillow==10.3.0
playsound==1.2.2
pytz==2020.4
sqlparse==0.5.0
```

**Comment by Charlilyyyy** [comment]
> Numpy had a major version update which doesn't seem compatable with dlib. I solved this error by downgrading my version from 2.0.0 -> 1.26.4.
> 
> @Mohamed-lehbib from the versions you have provided, I think you may be getting this error for the same reason. Try downgrading your numpy version. @Charlilyyyy this might help you too.

yes it works thanks
