### ISSUE TITLE
Multiple Images to improve recognitio

### ISSUE THREAD

**Issue by DerLomo** [ageitgey/face_recognition#1362]
How can I add more images of the same person (from different angels, and lights) so i can have better recognition results?

**Comment by yashenkoxciv** [comment]
You can add more images of the same person to know

```
known_faces = [my_encoding_1, my_encoding_2, joe_encoding_1, joe_encoding_2]
known_faces_labels = [0, 0, 1, 1]
results = face_recognition.compare_faces(known_faces, unknown_encoding)
# take values of known_faces_labels where results == True
# then take mode of the remaining known_faces_labels
# this mode is your recognition result
```

Sorry, can not run code now...

**Comment by yashenkoxciv** [comment]
Here is an example how to recognize a face using multiple examples of known faces:
https://deepnote.com/project/facerecognition-for-multiple-examples-XM1VplWXTI6rp6Jxo21cjQ/%2Fexample.ipynb

The main idea is to compare unknown face with every examples:
`match_mask = face_recognition.compare_faces(known_face_encodings, unknown_encoding)`
which gives you True/False mask for known_face_encodings

Then we choose labels where match_mask is True and get the most frequent label which is our prediction.

It can work to some extent improving recognition accuracy.

This is an example of KNN algorithm but you can apply different algorithms to solve the problem.
