### ISSUE TITLE
Cannot install face recognition in kali linux

### ISSUE THREAD

**Issue by itsmedanka** [ageitgey/face_recognition#1368]
* Python version: python 3.9
* Operating System: kali linux

Visual studio is not recognizing face detection 
 I installed cmake, dlib , face recognition via the given method.
And i also tried in python interpreter, 
`>>>import cmake `
`>>>import dlib`
`>>>import face_recognition `
No errors were there.
But when i run a whole program using visual studio or idle python 3.9 , it is giving an error that 
No module named 'dlib'
No module named 'cmake'
No module named 'face_recognition' respectively.

**Comment by MikkelHebel** [comment]
Hi,

`pip install cmake`
`pip install dlib`
`pip install face_recognition`

This should work :)

**Comment by itsmedanka** [comment]
> Hi,
> 
> `pip install cmake`
> `pip install dlib`
> `pip install face_recognition`
> 
> This should work :)

Yeah, i tried that too! 
The same error again, but it's not giving any error in python terminal.
But, when i run a whole script, the errors are there.

**Comment by MauryaRitesh** [comment]
You should try installing with the "sudo" command. If that's not working, check the installation directory of python modules on your device and check if the installed libraries are present there. And if they aren't, manually copy and paste them.

**Comment by anant21** [comment]
> * Python version: python 3.9
> 
>     * Operating System: kali linux
> 
> 
> Visual studio is not recognizing face detection I installed cmake, dlib , face recognition via the given method. And i also tried in python interpreter, `>>>import cmake ` `>>>import dlib` `>>>import face_recognition ` No errors were there. But when i run a whole program using visual studio or idle python 3.9 , it is giving an error that No module named 'dlib' No module named 'cmake' No module named 'face_recognition' respectively.

Please share the error screenshot. I've just worked on it. Probably I could help.

**Comment by vaeXu** [comment]
您好，悉获您的邮件，我将尽快处理，感谢您的来信！

**Comment by anant21** [comment]
> 您好，悉获您的邮件，我将尽快处理，感谢您的来信！

那太棒了。
