### ISSUE TITLE
pip3 installation issue

### ISSUE THREAD

**Issue by neelkadia** [ageitgey/face_recognition#141]
* face_recognition version: latest
* Python version: 3
* Operating System:  Ubuntu 16.04 LTS

### Description
Trying to install on Ubuntu

### What I Did
Simply installing using pip3

```
CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
      Imported targets not available for Boost version
    Call Stack (most recent call first):
      /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
      /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
      /tmp/pip-build-2ug_z9pf/dlib/dlib/cmake_utils/add_python_module:61 (FIND_PACKAGE)


```

**Comment by imanoreotwe** [comment]
You probably need to install [boost](http://boost.org). There should be specific instructions for Ubuntu/Linux on their site but I found installation instructions next to error itself.
