### ISSUE TITLE
multiple result but from other photo

### ISSUE THREAD

**Issue by eloelo22** [ageitgey/face_recognition#142]
* face_recognition version:
* Python version: 3.5
* Operating System: ubuntu 16.04 lts

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.
i am trying to do face matching from a dozen of known faces to that of a single unknown photo a female friend of mine the result is as expected it got the result right but i was expecting that the result would show a single person from the known people but the result shows multiple matching person ranging from female to male please take a look at the attached photo the first command i don't know if this is an issue. you could also see from the other matching that i did from the photo i was expecting a single result. i was thinking if the face_recognition has a matching confidence percentage that could be appended to the result? 
![screenshot from 2017-08-05 09-00-20](https://user-images.githubusercontent.com/8648535/28991656-94d0575a-79bd-11e7-98eb-fb6de752c821.png)

### What I Did
face_recognition ./photos/ ./photos1/
```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by ageitgey** [comment]
Check out the answer to #129 and see if that solution works for you. 

I agree that adding the confidence to the output is a good idea too and I'll look at doing that soon.

**Comment by eloelo22** [comment]
hi it worked for me it returned fewer result i guess i have to play with the tolerance for now. i will be looking for the update with the confidence percentage

thank you

**Comment by ageitgey** [comment]
Cool, glad it worked for you. The change should be easy enough. I'll do it when I get a free moment in the next few days.

**Comment by eloelo22** [comment]
Thank you it would be great and pardon me it appears that the issue was already solved silly me i didnt read the past issue

Cheers
Thank you again

**Comment by xinshengdehuamei** [comment]
em, I wondered how accurately the model was. I tested the model, and the result was not very good.

**Comment by eloelo22** [comment]
i also tested it with the tolerance parameter and it is good
