### ISSUE TITLE
help

### ISSUE THREAD

**Issue by semen7907** [ageitgey/face_recognition#143]
How to add several faces in known_face_encoding?
https://github.com/ageitgey/face_recognition/blob/master/examples/web_service_example.py

**Comment by eloelo22** [comment]
i based the same issue you have on this project https://github.com/malikshubham827/get-me-through and it worked goodluck

**Comment by ageitgey** [comment]
@semen7907 In a real-world application, you might pull the known face encodings from a database or something instead of hard-coding them. I just put one there in an array there to keep the example simple. The solution just depends on what exactly you want to build.
