### ISSUE TITLE
Issues from using CUDA with CNN to do face recognition

### ISSUE THREAD

**Issue by HarryHur** [ageitgey/face_recognition#1432]
* face_recognition version: Most recent version
* Python version: 3.10
* Operating System: windows 10

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.
IMPORTANT: If your issue is related to a specific picture, include it so others can reproduce the issue.

### What I Did

I tried to use CNN model with CUDA + GPU to do face_recognition.
So I added `model="cnn"` to this part from `def train`  ( from face_recognition_knn.py file)
`
        for img_path in image_files_in_folder(os.path.join(train_dir, class_dir)):
            image = face_recognition.load_image_file(img_path)
            face_bounding_boxes = face_recognition.face_locations(image, model="cnn")
`

but after try to train with this change, i got this error.

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.

Training KNN classifier...
Traceback (most recent call last):
  File "c:\Users\User\Assignment\Capture\main.py", line 95, in <module>
    classifier = face_recognition_knn.train("knn_examples/train", model_save_path="trained_knn_model.clf", n_neighbors=2)
  File "c:\Users\User\Assignment\Capture\face_recognition_knn.py", line 82, in train
    face_bounding_boxes = face_recognition.face_locations(image, model="cnn")
  File "C:\Users\User\AppData\Roaming\Python\Python310\site-packages\face_recognition\api.py", line 119, in face_locations
    return [_trim_css_to_bounds(_rect_to_css(face.rect), img.shape) for face in _raw_face_locations(img, number_of_times_to_upsample, "cnn")]
  File "C:\Users\User\AppData\Roaming\Python\Python310\site-packages\face_recognition\api.py", line 103, in _raw_face_locations
    return cnn_face_detector(img, number_of_times_to_upsample)
RuntimeError: Error while calling cudnnFindConvolutionForwardAlgorithm( context(), descriptor(data), (const cudnnFilterDescriptor_t)filter_handle, (const cudnnConvolutionDescriptor_t)conv_handle, descriptor(dest_desc), num_possible_algorithms, &num_algorithms, perf_results.data()) in file C:\Users\User\Assignment\Capture\dlib\dlib\cuda\cudnn_dlibapi.cpp:827. code: 2, reason: CUDA Resources could not be allocated.
```

before I add model="cnn" (means with hog) it worked correctly, but little slow, so the reason why i tried to use cnn model,
but i got this error.
Could somebody help me?

PS. It was work with CUDA gpu when I try run with model hog 

Thanks

**Comment by HarryHur** [comment]
Can we combine KNN with CNN??
If i'm wrong, how can we use CNN to do face recognition? not face detection
cuz, this repo suggest sample face detection with CNN but not face recognition with CNN

Thanks in advance!1

**Comment by serenitist** [comment]
Training model and using it sholud be a pair. If you trained CNN use CNN.
So if you want to use CNN, model='cnn' argument should be added in pair when training and calling it .
And usually memory allocation fails could be solved by limiting the size of input data.
Like resizing the trainning image.

**Comment by HarryHur** [comment]
I solved this problem thanks to your idea! 
Thank you for your help!

For other people who on the same boat with me,
Should be use model CNN both of `train` and `predict` 
Memory allocation fail error came from the out of memory, so try to resize your image
