### ISSUE TITLE
face_encodings returning empty list for selfie

### ISSUE THREAD

**Issue by ygordanniel** [ageitgey/face_recognition#1436]
* face_recognition version: 1.3.0
* Python version: 3.10
* Operating System: Windows 10

### Description

I'm trying to use `face_encodings` to compare faces and identify a person based on a given image.
For some reason, this 2 images:
 - https://i.ibb.co/0Y5LVXR/vitor.jpg
 - https://i.ibb.co/5x9DBjH/thales.jpg

Are returning empty list when using `face_encodings`.

### What I Did

```
tmp_dir = tempfile.gettempdir()
tmp_dir = tempfile.gettempdir()
file_temp_path = os.path.join(tmp_dir, file.filename)
file.save(file_temp_path)

# file is a FileStorage that comes from request.files.get('file') on a Flask REST API
face_to_upload = face_recognition.load_image_file(file_temp_path)
face_to_upload_encoding = face_recognition.face_encodings(face_to_upload)

if len(face_to_upload_encoding) == 0:
    raise CannotEncodeException("Cannot encode image")
```

I tried https://github.com/ageitgey/face_recognition/issues/490 suggestions but it didn't work because `face_encodings` expects `128-dimension face encoding` and the suggestion is only a `4-dimension face encoding`.

**Comment by ygordanniel** [comment]
I'd also like to add that I tested with other images like these:

![obama](https://user-images.githubusercontent.com/4176921/182928634-b400838d-5bba-4a3c-9d4d-4e382e90a453.jpg)
![trump](https://user-images.githubusercontent.com/4176921/182928645-f2557448-4f00-4c14-8815-d9e82f0f7446.jpg)
![sacha-baron-cohen](https://user-images.githubusercontent.com/4176921/182928662-3c049c8f-ad62-454c-ae36-5b2d40a9806a.jpg)
![WhatsApp Image 2022-08-03 at 5 14 21 PM](https://user-images.githubusercontent.com/4176921/182928695-0e7262f4-5263-4959-bbf4-e8bdcf0cc333.jpeg)

and everything worked perfectly.

The only difference from the images that worked for the images that didn't is how it is sources. Both images that didn't worked were taken inside a mobile app and sent to the API while the images that worked were downloaded to a computer and sent via Insomnia.

**Comment by ygordanniel** [comment]
###  What was happening

Apparently when you take a picture from a mobile device camera it add a bunch of extra information on the image's binary (geolocation, labels and so on) and that was messing up face_recognition's ability to find faces on the image.

###  How we solved it

We worked around to instead of take a picture with the camera we take a screenshot of the camera view. That way the image won't have all those extra information that was messing up the encoding.

**Comment by DiasNetoJ** [comment]
Same problem here, can anybody explain what happen?
A photo taken by a Flutter app only works after I process it here: https://imagecompressor.com/

**Comment by DiasNetoJ** [comment]
The first image return empty faces on face_recognition.face_encodings call
![image-medium](https://user-images.githubusercontent.com/9969714/221424005-420d03cf-2eba-4ef2-8c83-f42b2afef382.jpg)

But this second works
![image-medium-min](https://user-images.githubusercontent.com/9969714/221424011-3b6c4ecc-8d4f-4d29-a9f0-518714fbb6e5.jpg)

**Comment by leomm20** [comment]
Try:
face_to_upload_encoding = face_recognition.face_encodings(face_to_upload)[]

Instead:
face_to_upload_encoding = face_recognition.face_encodings(face_to_upload)

> Same problem here, can anybody explain what happen? A photo taken by a Flutter app only works after I process it here: https://imagecompressor.com/

**Comment by leomm20** [comment]
> Same problem here, can anybody explain what happen? A photo taken by a Flutter app only works after I process it here: https://imagecompressor.com/

With "save link as" => I see the picture rotated to the right, so... here is the code:

```python
from PIL import Image
import face_recognition

jose1 = 'jose1.jpg'
jose1_im = Image.open(jose1)
jose1_im = jose1_im.rotate(90)
jose1_im.save('jose1_rotated.jpg')
jose1_im.close()

jose1 = 'jose1_rotated.jpg'
jose1_loaded = face_recognition.load_image_file(jose1)
try:
    jose1_encoding = face_recognition.face_encodings(jose1_loaded)[0]
    print('Jose1 OK!')
except:
    print('Error with Jose1\n')
```

**Comment by DiasNetoJ** [comment]
> > Same problem here, can anybody explain what happen? A photo taken by a Flutter app only works after I process it here: https://imagecompressor.com/
> 
> With "save link as" => I see the picture rotated to the right, so... here is the code:
> 
> `from PIL import Image import face_recognition
> 
> jose1 = 'jose1.jpg' jose1_im = Image.open(jose1) jose1_im = jose1_im.rotate(90) jose1_im.save('jose1_rotated.jpg') jose1_im.close()
> 
> jose1 = 'jose1_rotated.jpg' jose1_loaded = face_recognition.load_image_file(jose1) try: jose1_encoding = face_recognition.face_encodings(jose1_loaded)[0] print('Jose1 OK!') except: print('Error with Jose1\n')`

It works. Thanks! 
Only images from mobile have to be rotated, so to rotate only when needed I added this:
`img = ImageOps.exif_transpose(img)`

Now all is working as expected from image of any source. God bless you.

**Comment by ceyxasm** [comment]
@DiasNetoJ not related to this thread but I really want to ask how you were able to connect your flutter the library to your flutter app.
