### ISSUE TITLE
Installation issues with boost

### ISSUE THREAD

**Issue by CodingWalrus** [ageitgey/face_recognition#144]
* face_recognition version: 
* Python version: 3.6
* Operating System: Windows 8.1

### Description

I have been trying to install this on Windows for some time now. I installed scipy and numpy+mkl from wheels, I installed dlib, cmake, and boost. However, the program doesn't find the Boost Python library and cmake configuration fails as a result.
### What I Did
I entered 
     

>  pip install face_recognition 

and I got, in part:
>      --
>      --  Next, when you invoke cmake to compile dlib you may have to use cmake's
>      -G option to set the
>      --  64 vs. 32bit mode of visual studio.  Also, if you want a Python3 library
>      you will need to
>      --  add -DPYTHON3=1.  You do this with a statement like:
>      --     cmake -G "Visual Studio 12 2013 Win64" -DPYTHON3=1 ..\..\tools\python
>
>      --  Rather than:
>      --     cmake ..\..\tools\python
>      --  Which will build a 32bit Python2 module by default on most systems.
>      --
>      --  ************************************************************************
>    *****************************
>    CMake Error at C:/Users/James/AppData/Local/Temp/pip-build-ismjh6ai/dlib/dli
>    b/cmake_utils/add_python_module:116 (message):
>       Boost python library not found.
>    Call Stack (most recent call first):
>      CMakeLists.txt:6 (include)
>    -- Configuring incomplete, errors occurred!
>    See also "C:/Users/James/AppData/Local/Temp/pip-build-ismjh6ai/dlib/tools/py
>    thon/build/CMakeFiles/CMakeOutput.log".
>    error: cmake configuration failed!
>
>    ----------------------------------------
>    Command ""c:\program files\python36\python.exe" -u -c "import setuptools, tokeni
>    ze;__file__='C:\\Users\\James\\AppData\\Local\\Temp\\pip-build-ismjh6ai\\dlib\\s
>    etup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n
>    ', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Us
>    ers\James\AppData\Local\Temp\pip-nktuat8e-record\install-record.txt --single-ver
>    sion-externally-managed --compile" failed with error code 1 in C:\Users\James\Ap
>    pData\Local\Temp\pip-build-ismjh6ai\dlib\
>
Can anyone help me figure out what to do from here to ensure cmake configuration succeeds and the boost library is found? Thank you. Any general advice for a Windows installation would be appreciated as well.

**Comment by tuhinsom** [comment]
I do have a problem similar to the one above.
I have downloaded zip from http://www.boost.org/users/history/version_1_64_0.html
unpacked it -> run bootstrap.bat from the tools/build folder and run the command
b2 -a --with-python address-model=32 toolset=msvc runtime-link=static
the build was made to c:\boost_build folder
then I had to set environment variables:
set BOOST_ROOT="path to my extracted folder root"
set BOOST_LIBRARYDIR="path to my extracted folder root \stage\lib"
also the path to c:\boost_build folder\bin was set in environment variable
but according to the instruction the BOOST_LIBRARYDIR cannot be set as it is missing

can anybody please let me know where I can find the BOOST_LIBRARYDIR directory reference

**Comment by TheDogeOfTheInternet** [comment]
Do you have Visual Studio and Visual C++ Tools installed? I believe that Boost requires them to build. Also, make sure that you're running the cmd/powershell as Administrator. 

I was experiencing the same issues as you, but they cleared up after I installed Visual Studio.

**Comment by shabazbpatel** [comment]
Using Docker images helps the best in such cases since it encapsulates the environment. You can install Docker on windows using toolbox from [here](https://docs.docker.com/toolbox/overview/). 

You can use this Dockerfile to setup face_recognition library with dlib.


     FROM datmo/dlib-scikit:14.04

     # Run commands to make code work
     RUN sudo apt-get update -y

     # Numpy / Scipy reqs
     RUN sudo apt-get install python-sympy -y
     RUN pip install face_recognition
     RUN pip install pandas
     RUN pip install matplotlib

You can also use this [repository](https://github.com/shabazbpatel/datmo-face-recognition) which uses the same Dockerfile to set up the face recognition project.

     `

**Comment by ageitgey** [comment]
If you want to use Docker, there's also a more detailed [Dockerfile included in the root of this repo](https://github.com/ageitgey/face_recognition/blob/master/Dockerfile).

**Comment by shubham0704** [comment]
a detailed tutorial to install dlib - https://www.pyimagesearch.com/2017/03/27/how-to-install-dlib/

**Comment by mengDTT** [comment]
check the boost version,  1.66.0 is not well supported by cmake's FindBoost.cmake, so the cmake configration may failed and that is exactly I encounted, I tried a 1.63.0 version and then follow the instruction, everything goes well.

**Comment by ageitgey** [comment]
Boost is no longer required in the latest release of dlib.
