### ISSUE TITLE
What is the image size sweet-spot?

### ISSUE THREAD

**Issue by julianadormon** [ageitgey/face_recognition#1447]
I have been crawling the discussions here hoping to find any recommended sizes for training images.

We are building an app that will capture multiple images of each person so we can control the input.
The app will capture a full face and neck. So the face will occupy most of the image's available space.
Can anyone recommend the smallest sized file we should make to keep processing times to a minimum?

For instance is 400px x  500px suitable at 72dpi?
What would be suitable jpeg quality settings as a percentage?

Thanks in advance.

**Comment by beshman** [comment]
Did you find an answer?

**Comment by julianadormon** [comment]
> Did you find an answer?

I have not tried as yet, sorry.

**Comment by krthr** [comment]
+1

**Comment by DankMemeGuy** [comment]
Get 1 image, use python module ("PIL"/Pillow) to mass generate various sizes, then scan all those images and see what produces the best result.

**Comment by julianadormon** [comment]
So after some testing I have was getting spotty results until my images were 500px on the long side.
I see in the source code, that sizes are downsized if larger than 1600px to speed things up. 
So I guess between 500px and 1600px on the image long size.
I am going to use 600px, just to be sure.
