### ISSUE TITLE
Save face in db

### ISSUE THREAD

**Issue by Skreiphoff** [ageitgey/face_recognition#1473]
Hello everyone, tell me, can I somehow save the recognized face to the database and then get it from there to compare with the photo, I will be glad if some examples are presented

**Comment by leomm20** [comment]
here's the solution!!

```python
obama_encoded_hex = obama_encoded.dumps().hex()  # for the insert
obama_encoded = pickle.loads(bytes.fromhex(obama_encoded_db))  # after the select
```

[test_db.zip](https://github.com/ageitgey/face_recognition/files/10836412/test_db.zip)

If this is OK for you, remember to close the issue ;-)
