### ISSUE TITLE
Getting error while calling the face_recognition.face_encodings(img, face_locations) in Ubuntu & RasbianOS

### ISSUE THREAD

**Issue by sahilbm** [ageitgey/face_recognition#1488]
* face_recognition version: 1.3.0
* Python version: 3.7 & 3.8
* Operating System: Ubuntu 18.04, Raspbian, Ubuntu 20.04

### Description

Raising the TypeError Exception while face detected and having the data in face_locations variable in below code line.

`face_recognition.face_encodings(img, face_locations)`

The code line mentioned above raising the exception `TypeError: compute_face_descriptor(): incompatible function arguments.
`
As I can see from the documentation, the passed function parameters are correct and works pretty well in Windows. I observed whenever the face is getting detected and passing the face_locations as a parameter it is raising the error, Type of face_locations is a list of tuples with detected face coordinates.

```
TypeError: compute_face_descriptor(): incompatible function arguments. The following argument types are supported:
    1. (self: _dlib_pybind11.face_recognition_model_v1, img: numpy.ndarray[(rows,cols,3),numpy.uint8], face: _dlib_pybind11.full_object_detection, num_jitters: int = 0, padding: float = 0.25) -> _dlib_pybind11.vector
    2. (self: _dlib_pybind11.face_recognition_model_v1, img: numpy.ndarray[(rows,cols,3),numpy.uint8], num_jitters: int = 0) -> _dlib_pybind11.vector
    3. (self: _dlib_pybind11.face_recognition_model_v1, img: numpy.ndarray[(rows,cols,3),numpy.uint8], faces: _dlib_pybind11.full_object_detections, num_jitters: int = 0, padding: float = 0.25) -> _dlib_pybind11.vectors
    4. (self: _dlib_pybind11.face_recognition_model_v1, batch_img: List[numpy.ndarray[(rows,cols,3),numpy.uint8]], batch_faces: List[_dlib_pybind11.full_object_detections], num_jitters: int = 0, padding: float = 0.25) -> _dlib_pybind11.vectorss
    5. (self: _dlib_pybind11.face_recognition_model_v1, batch_img: List[numpy.ndarray[(rows,cols,3),numpy.uint8]], num_jitters: int = 0) -> _dlib_pybind11.vectors

Invoked with: <_dlib_pybind11.face_recognition_model_v1 object at 0x000001DAB486B7B0>, array([[[208, 223, 240],
        [204, 213, 234],
        [191, 208, 229],
        ...,
        [ 87,  76,  74],
        [ 94,  78,  77],
        [ 82,  72,  70]],

       [[214, 223, 245],
        [208, 221, 240],
        [197, 217, 235],
        ...,
        [100,  63,  68],
        [104,  74,  71],
        [ 87,  78,  75]],

       [[220, 231, 249],
        [218, 228, 245],
        [208, 224, 239],
        ...,
        [ 96,  86,  84],
        [102,  83,  82],
        [ 86,  83,  80]],

       ...,

       [[ 36,  36,  35],
        [ 41,  37,  36],
        [ 40,  35,  33],
        ...,
        [107,  65,  41],
        [109,  67,  44],
        [109,  68,  50]],

       [[ 41,  39,  38],
        [ 42,  36,  35],
        [ 44,  39,  38],
        ...,
        [107,  64,  45],
        [106,  62,  42],
        [108,  64,  42]],

       [[ 46,  42,  41],
        [ 45,  39,  38],
        [ 43,  38,  36],
        ...,
        [104,  67,  51],
        [100,  64,  46],
        [108,  64,  40]]], dtype=uint8), <_dlib_pybind11.full_object_detection object at 0x000001DAB4EF0370>, 1 
```

### What I Did
Tested above implementation with Python3.7 & Python3.8 with dlib==19.24.1, face_recognition==1.3.0, face_recognition_models==0.3.0. The same configuration works well in Windows but not in Linux.

**Comment by ghost** [comment]
I am also having this issue. I initially tried this on Windows 11 then reinstalled my system to Ubuntu 22.04.2 LTS thinking that the platform might be the cause since it is not official supported and still no luck with the same issue encountered. I am also using face_recognition v1.3.0, face_recognition_models v0.3.0 and dlib v19.24.1.

**Comment by syou83syou83** [comment]
I am having the same issue here on Mac.

**Comment by ghost** [comment]
There is already a solution submitted in [stackoverflow](https://stackoverflow.com/a/75943024/21562798).

The sample codes usually uses `rgb_small_frame = small_frame[:, :, ::-1]`. That needs to be changed with `rgb_small_frame = np.ascontiguousarray(small_frame[:, :, ::-1])`.

**Comment by sahilbm** [comment]
Figured out the solution, posted the answer on the [Stackoverflow](https://stackoverflow.com/questions/75926662/face-recognition-problem-with-face-encodings-function/75943024#75943024).
Closing the issue.
