### ISSUE TITLE
Tolerance factor not working from cli

### ISSUE THREAD

**Issue by giannigino** [ageitgey/face_recognition#149]
* face_recognition version:
* Python version: 3.5
* Operating System: Ubuntu 16

### Description

Hi! I tried to set the tolerance factor in the cli but it doesn't work....It says: "Error: no such option: --tolerance". I am using the preconfigured VM available on Medium Website. 

### What I Did

```

face_recognition --tolerance 0.5 ./knwown ./unkwnown
```
Thanks!

**Comment by ageitgey** [comment]
The tolerance parameter was just added a couple of days ago but the VM is a few months old and doesn't have that newer version.

So you probably just need to update face_recognition. Try running this command to do that:

```
sudo pip3 install --upgrade --no-deps face_recognition
```

**Comment by MuahmmadRehanQadri** [comment]
Uninstalling and re-installing face_recognition solved my issue, thanks!
sudo pip3 uninstall face_recognition
sudo pip3 install face_recognition
