### ISSUE TITLE
TypeError: No registered converter was able to produce a C++ rvalue of type dlib::rectangle from this Python object of type numpy.ndarray

### ISSUE THREAD

**Issue by smajida** [ageitgey/face_recognition#150]
* face_recognition version: 0.1.0
* Python version: 2.7
* Operating System: Linux Ubuntu 14.04

### Description
Face_recognition module uses HOG face detector. I have replaced this part by a deep learning method which is faster and more accurate. However, the output of this detector seems incompatible with Dlib's landmark prediction. 

I have tried many ways to convert the output of this detector which numpy array like 
[[ 308.53506747   65.3347368   483.16240621  299.57273737]]
<type 'list'>
to the one used in dlib like 
[(308, 65) (483, 299)]
<class 'dlib.dlib.rectangle'>

, but so far I have not been able to do so.
### What I Did
I tried to change the array to list by a.list() and another way around a.array(), but both failed. 
```
    return [pose_predictor(face_image, face_location) for face_location in face_locations]
TypeError: No registered converter was able to produce a C++ rvalue of type dlib::rectangle from this Python object of type numpy.ndarray

```

**Comment by ageitgey** [comment]
The `pose_predictor` function is just expecting a simple array of tuples with (top, right, bottom, left). 

So it's expecting [(308, 65, 483, 299)] instead of the numpy array you have. You need to covert the numpy array to a list of tuples.

Maybe this answer will help you: https://stackoverflow.com/questions/10016352/convert-numpy-array-to-tuple

**Comment by ageitgey** [comment]
`[[(308, 65) (483, 299)]]` is not the same thing as `[(308, 65, 483, 299)]` at all.

If you pass in `[(308, 65, 483, 299)]` (i.e. 4 int elements in python tuple in a python list) as the array of known face locations, the existing code will take it and convert into to a dlib object automatically. You just need to pass in the data as the correct type. You don't need to do any extra work with dlib at all.

Here's a simple working example:

```
import face_recognition

image = face_recognition.load_image_file("biden.jpg")

face_locations = [(241, 740, 562, 419)]

face_landmarks_list = face_recognition.face_landmarks(image, face_locations)

print(face_landmarks_list[0]['chin'])
```

It's that simple. Just replace `face_locations = [(241, 740, 562, 419)]` with a call to your new face detector function (i.e `face_locations = myFaceDetector()`) that returns data *in the same format as that* with no numpy objects or anything like that.

**Comment by smajida** [comment]
To reproduce the error, you can run the following piece of code:
```python
import face_recognition
import dlib
import face_recognition_models

predictor_model = face_recognition_models.pose_predictor_model_location()
pose_predictor = dlib.shape_predictor(predictor_model)

image = face_recognition.load_image_file("biden.jpg")
face_locations = [(241, 740, 562, 419)]
encoder = pose_predictor(image, face_locations)
print(encoder)
```

**Comment by ageitgey** [comment]
If you want to bypass face_recognition and use the `dlib.shape_predictor()` function directly instead of `face_recognition.face_locations()` like in your example code, then this is really just a` dlib` question and unrelated to anything in `face_recognition`.

In that case, you can just do this:

```python
import face_recognition
import dlib
import face_recognition_models

predictor_model = face_recognition_models.pose_predictor_model_location()
pose_predictor = dlib.shape_predictor(predictor_model)

image = face_recognition.load_image_file("biden.jpg")
face_location = dlib.rectangle(419, 241, 740, 562)
encoder = pose_predictor(image, face_location)
print(encoder)
```

**Comment by smajida** [comment]
that is right. I got the problem and solved it. The problem was that I was not giving dlib.rectangle object to pose_predictor.
thanks.
