### ISSUE TITLE
Set cpus in code python 

### ISSUE THREAD

**Issue by emlacuden** [ageitgey/face_recognition#151]
Hi,
I want to speed up the face_recognition so i want to use 4 cpus for this process. how can i set it in code.

**Comment by ageitgey** [comment]
Hi @emlacuden,

It's not as simple as passing in a parameter. You have to write the code to do multi-processing yourself. The details are going to depend heavily on what exactly you want to do.

You can look at the [command-line interface code](https://github.com/ageitgey/face_recognition/blob/master/face_recognition/cli.py#L68-L89) as an example of splitting up work between cpus. You can also read [my article on multi-processing](https://medium.com/@ageitgey/quick-tip-speed-up-your-python-data-processing-scripts-with-process-pools-cf275350163a) to learn more about how to code this in Python.

**Comment by emlacuden** [comment]
Thank you so much for your supported. I have a one more question: Anyway for me to run the face_recognition with cuda under GPU to run faster?

**Comment by ageitgey** [comment]
Sure. If you compile dlib with CUDA support, it will take advantage of it automatically for the face encoding step. 

The only problem is the face detection step doesn't currently take advantage of it and it's the slowest step in the process. So the speed improvement might not be that great depending on your use case. Dlib also supports a different way of doing face detection that does use CUDA, but it's not currently exposed via python so this library isn't using it yet.
