### ISSUE TITLE
plans on including the distance in the compare_face command on the API

### ISSUE THREAD

**Issue by eloelo22** [ageitgey/face_recognition#152]
* face_recognition version: current version
* Python version: 3.5.2
* Operating System: Ubuntu 16.04 LTS

### Description

hi do you have any plans to include the distance on the API?
i noticed in you're code that it is only available for the CLI

thank you

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by ageitgey** [comment]
You can access the distance with the face_distance function.

**Comment by eloelo22** [comment]
thank you sorry i am a newbie in using python

**Comment by ageitgey** [comment]
@eloelo22 No problem! I'm glad you figured it out :)

**Comment by eloelo22** [comment]
well  i tried but i cant seem to make it work for this code 

if len(unknown_face_encodings) > 0:
               
                # See if the first face in the uploaded image matches the known face of Obama
                match_results = face_recognition.compare_faces(
                    a, unknown_face_encodings[0], 0.3)
                for i in range(len(match_results)):
                    if match_results[i]:
                        name = people[i]
                        face_names.append(name[:36])

it's working but i dont have any idea how would i match the distance

**Comment by eloelo22** [comment]
i ended up with this
if file and allowed_file(file.filename):
            if known_encodings_file.is_file():
                known_encodings = np.genfromtxt(known_encodings_file, delimiter=',')
            if people_file.is_file():
                people = np.genfromtxt(people_file, dtype='U', delimiter=',')
            # The image file seems valid! Detect faces and return the result.
            img = face_recognition.load_image_file(file)
            a = np.array(list(known_encodings))
            # Get face encodings for any faces in the uploaded image
            unknown_face_encodings = face_recognition.face_encodings(img)
            face_names = []
            face_distance1 = []
            if len(unknown_face_encodings) > 0:
               
                # See if the first face in the uploaded image matches the known face of Obama
                match_results = face_recognition.compare_faces(a, unknown_face_encodings[0])
                distance = face_recognition.face_distance(a, unknown_face_encodings[0])
                for distances in distance: 
                    if(res <= 0.6):
                        face_distance1.append(distances)
                for i in range(len(match_results)):
                    if match_results[i]:
                        name = people[i]
                        face_names.append(name[:36])
            # Return the result as json
            result = {
                "result": face_names,
                "distance": face_distance1
            }
            return jsonify(result)
