### ISSUE TITLE
ImportError: dlopen(/usr/local/lib/python3.6/site-packages/dlib-19.4.99-py3.6-macosx-10.12-x86_64.egg/dlib/dlib.so, 2): Library not loaded: @rpath/libmkl_rt.dylib   Referenced from: /usr/local/lib/python3.6/site-packages/dlib-19.4.99-py3.6-macosx-10.12-x86_64.egg/dlib/dlib.so   Reason: image not found

### ISSUE THREAD

**Issue by mohitpali** [ageitgey/face_recognition#153]
* face_recognition version:
* Python version: 3.6
* Operating System: MacOS

### Description

Installed face_recognition by building from source and it installed alright. The command face_recognition is available but it is throwing error

face_recognition ./KnownPeople ./Unknown/
Traceback (most recent call last):
  File "/usr/local/bin/face_recognition", line 7, in <module>
    from face_recognition.cli import main
  File "/usr/local/lib/python3.6/site-packages/face_recognition/__init__.py", line 7, in <module>
    from .api import load_image_file, face_locations, face_landmarks, face_encodings, compare_faces, face_distance
  File "/usr/local/lib/python3.6/site-packages/face_recognition/api.py", line 4, in <module>
    import dlib
  File "/usr/local/lib/python3.6/site-packages/dlib-19.4.99-py3.6-macosx-10.12-x86_64.egg/dlib/__init__.py", line 1, in <module>
    from .dlib import *
ImportError: dlopen(/usr/local/lib/python3.6/site-packages/dlib-19.4.99-py3.6-macosx-10.12-x86_64.egg/dlib/dlib.so, 2): Library not loaded: @rpath/libmkl_rt.dylib
  Referenced from: /usr/local/lib/python3.6/site-packages/dlib-19.4.99-py3.6-macosx-10.12-x86_64.egg/dlib/dlib.so
  Reason: image not found

**Comment by ageitgey** [comment]
How did you install dlib? The error is that it's looking for `libmkl_rt.dylib` but can't find it on your system. I'm guessing you are using Anaconda or something?

**Comment by mohitpali** [comment]
Yes, I have anaconda. I installed dlib from source though because pip
install did not work.

There is another thread that is closed that talks about the same error and
installing libpng. Tried that as well but it doesn't work.

**Comment by ageitgey** [comment]
The error isn't related to `libpng`. The error is that `dlib` was compiled with support for Intel MKL, but it can't find the actual MKL library on your computer when it runs. You could either re-compile with MKL disabled (probably easiest) or make sure MKL is installed properly.

**Comment by mohitpali** [comment]
Stupid question - sorry ( a newbie to python ) - can you please share the
commands that will re-compile with MKL disabled ?

**Comment by ageitgey** [comment]
That's a totally reasonable question :)

If you are installing dlib like this: https://gist.github.com/ageitgey/629d75c1baac34dfa5ca2a1928a7aeaf

Then you can pass it to the commands like this:

```
cd dlib
mkdir build; cd build; cmake .. -DDLIB_USE_CUDA=0 -DUSE_AVX_INSTRUCTIONS=1 -DDLIB_USE_MKL_FFT=0; cmake --build .
```

and 

```python3 setup.py install --yes USE_AVX_INSTRUCTIONS --no DLIB_USE_CUDA --no DLIB_USE_MKL_FFT```

Note: I don't have MKL installed, so I haven't actually tested this. But it should work.

**Comment by MyraBaba** [comment]
Hi,

I compiled with MKL lib in ubuntu and all good. All cpu utilized. But in MAc os X still same.

I think dlib coulnd find the MKL installed lib. Is there any way to correct this ? give the path ?
