### ISSUE TITLE
How to add more images to recognize and print their perspective names

### ISSUE THREAD

**Issue by roei03jen** [ageitgey/face_recognition#154]
* face_recognition version: lastest
* Python version: 3.1
* Operating System: Raspbian jessie with desktop

### Description

Hi there sir I just want to say thank you for the face recognition tutorial and codes. I just want to ask how can I add at least 2 more person to recognize. Below is the sample code i already edited. Thanks for the reply nice project again sir... I just want to turn on the relay if it recognizes the "authorized" images..... then turn off if the face is "Unauthorized"...

### What I Did is I tried to add another image then change some code(s) but unfortunately it didn't come up as planned hehehe... :D

```
# This is a demo of running face recognition on a Raspberry Pi.
# This program will print out the names of anyone it recognizes to the console.

# To run this, you need a Raspberry Pi 2 (or greater) with face_recognition and
# the picamera[array] module installed.
# You can follow this installation instructions to get your RPi set up:
# https://gist.github.com/ageitgey/1ac8dbe8572f3f533df6269dab35df65

import face_recognition
import picamera
import numpy as np

# Get a reference to the Raspberry Pi camera.
# If this fails, make sure you have a camera connected to the RPi and that you
# enabled your camera in raspi-config and rebooted first.
camera = picamera.PiCamera()
camera.resolution = (320, 240)
output = np.empty((240, 320, 3), dtype=np.uint8)

# Load a sample picture and learn how to recognize it.
print("Loading known face image(s)")
roei_image = face_recognition.load_image_file("roei.jpg")
roei_face_encoding = face_recognition.face_encodings(roei_image)[0]
iris_image = face_recognition.load_image_file("iris.jpg")
iris_face_encoding = face_recognition.face_encodings(iris_image)[1]

# Initialize some variables
face_locations = []
face_encodings = []

while True:
    print("Capturing image.")
    # Grab a single frame of video from the RPi camera as a numpy array
    camera.capture(output, format="rgb")

    # Find all the faces and face encodings in the current frame of video
    face_locations = face_recognition.face_locations(output)
    print("Found {} faces in image.".format(len(face_locations)))
    face_encodings = face_recognition.face_encodings(output, face_locations)

    # Loop over each face found in the frame to see if it's someone we know.
    for face_encoding in face_encodings:
        # See if the face is a match for the known face(s)
        match = face_recognition.compare_faces([iris_face_encoding], face_encoding)
        match = face_recognition.compare_faces([roei_face_encoding], face_encoding)
        name = "<Unknown Person>"

        if match[0]:
            name = "Roei Boribor"
        elif match[1]:
            name = "Iris Javier"

        print("I see someone named {}!".format(name))

```

**Comment by roei03jen** [comment]
Hi I already solved my problem, But there is one tinsie little problem. How can I use all the cpu cores of the raspberry pi 3? any hint thanks

**Comment by ageitgey** [comment]
@roei03jen Basically you have to code it yourself. You can look at the [command-line interface code](https://github.com/ageitgey/face_recognition/blob/master/face_recognition/cli.py#L68-L89) as an example of splitting up work between cpus in Python and follow that pattern. You can also read [my article on multi-processing](https://medium.com/@ageitgey/quick-tip-speed-up-your-python-data-processing-scripts-with-process-pools-cf275350163a) to learn more about how to code this in Python.

**Comment by roei03jen** [comment]
thanks @ageitgey for a hint appreciate the help!!!! :D 👍 👍 👍  💯

**Comment by ageitgey** [comment]
Sure thing!
