### ISSUE TITLE
RuntimeError: Unsupported image type, must be 8bit gray or RGB image

### ISSUE THREAD

**Issue by khaltab** [ageitgey/face_recognition#1575]
**Description:**
I'm encountering a RuntimeError: Unsupported image type, must be 8bit gray or RGB image when using the face_recognition library, even though the image is in RGB format.

**Environment:**
Python version: 3.12
face_recognition version: 1.3.0
dlib version: 19.24.99
numpy version:  2.0.0
Operating System: Windows 11 Pro 64-bit

**Code to Reproduce:**

python
Copy code
import cv2
import face_recognition

# Load the image using OpenCV
image = cv2.imread('input_image.jpg')

# Check if image is loaded properly
if image is None:
    print("Error: Could not read the image.")
else:
    # Convert BGR (OpenCV default) to RGB
    rgb_image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    # Detect face locations
    face_locations = face_recognition.face_locations(rgb_image)

    # Now you can work with face_locations
    print(f"Found {len(face_locations)} face(s) in the image.")

**Error Traceback:**

Copy code
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\face_recognition\api.py", line 121, in face_locations
    return [_trim_css_to_bounds(_rect_to_css(face), img.shape) for face in _raw_face_locations(img, number_of_times_to_upsample, model)]
                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\face_recognition\api.py", line 105, in _raw_face_locations
    return face_detector(img, number_of_times_to_upsample)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Unsupported image type, must be 8bit gray or RGB image.

**Additional Information:**
I've confirmed that the image is in RGB format by printing its shape and channels. Any guidance on resolving this issue would be greatly appreciated.

**Comment by khaltab** [comment]
I resolve the problem by downgrade numpy version to 1.26.4

**Comment by khaltab** [comment]
I resolve the problem by downgrade numpy version to 1.26.4

**Comment by Ashwin-raj-kr** [comment]
`YOU` solved my problem👌

**Comment by Safaap0** [comment]
ty

**Comment by musarafhossain** [comment]
Thank you

**Comment by Xuefei-Zhang** [comment]
solved, thx

**Comment by SAPARTANS369** [comment]
thank u so much
