### ISSUE TITLE
Boost-python installation issue for windows when tried pip install face_recognition

### ISSUE THREAD

**Issue by tuhinsom** [ageitgey/face_recognition#158]
* face_recognition version:
* Python version: 3.5 32bit
* Operating System: Windows

### Description

I was trying to do pip install face_recognition
and got error boost-python is missing so tried to install boost-python rest is frustration

### What I Did

```
I have downloaded zip from http://www.boost.org/users/history/version_1_64_0.html
unpacked it -> run bootstrap.bat from the tools/build folder and run the command
b2 -a --with-python address-model=32 toolset=msvc runtime-link=static
the build was made to c:\boost_build folder
then I had to set environment variables:
set BOOST_ROOT="path to my extracted folder root"
set BOOST_LIBRARYDIR="path to my extracted folder root \stage\lib"
also the path to c:\boost_build folder\bin was set in environment variable
but according to the instruction the BOOST_LIBRARYDIR cannot be set as it is missing

can anybody please let me know where I can find the **BOOST_LIBRARYDIR** directory reference
```

**Comment by ageitgey** [comment]
Can you paste the actual command you were running and the full output?

**Comment by ageitgey** [comment]
In the meantime, check out this tip from another dlib user: https://github.com/davisking/dlib/issues/177

**Comment by TheDogeOfTheInternet** [comment]
Do you have Visual Studio/Visual C++ Tools installed? I believe that Boost needs them to build properly.

**Comment by LeiYangGH** [comment]
I have the same problem as above steps, and I have VS2015 installed.
My detailed commands(follow [stackoverflow](https://stackoverflow.com/questions/40722996/cannot-find-boost-when-installing-dlib)):

1.  cd to boost dir
2 `.\bootstrap.bat`
3. `.\b2 runtime-link=shared link=shared`
4.  cd to dlib dir
5. ```
set BOOST_ROOT=C:\Install\boost_1_58_0
    set BOOST_LIBRARYDIR=C:\Install\boost_1_58_0\stage\lib
    set PATH=%PATH%;%BOOST_ROOT%;%BOOST_LIBRARYDIR%
    python setup.py install
```
The error is like this:
![dliberror](https://user-images.githubusercontent.com/5386998/30256021-32935ac6-96da-11e7-9fd6-af13768f6192.JPG)

**Comment by LeiYangGH** [comment]
I did not succeed in `python setup.py install` until I installed VS2015 **update 3**(seems only this update contain some latest C++ standards that **dlib** requires).

**Comment by TheDogeOfTheInternet** [comment]
Visual Studio 2017 is the one that I referred to, but it's great if 2015 works too. Perhaps ageitgey should add an 'install on Windows' tutorial or at least guide.

**Comment by ageitgey** [comment]
I don't ever use Windows, so I don't claim this library will work on Windows and I can't really support Windows users. But if anyone who uses Windows wants to write up a Windows install guide, I'd be happy to link to it.

**Comment by tuhinsom** [comment]
The following solved the problem (was not mentioned anywhere in the web though, but only in the manual):
from extracted folder -> BOOST_ROOT run the following
b2 --build-dir=D:\.....\boost\boost-build-engine toolset=msvc  --build-type=complete stage

then I got the \stage\lib which was added to the Path variable BOOST_LIBRARYDIR
