### ISSUE TITLE
How to change the sensitivity/tolerance value

### ISSUE THREAD

**Issue by ricerd95** [ageitgey/face_recognition#160]
* face_recognition version:
* Python version: 3.5.4
* Operating System: Ubuntu VM

### Description

I was trying this project on PyCharm

https://github.com/ageitgey/face_recognition/blob/master/examples/facerec_from_webcam_faster.py

and the recognition was not really accurate so I was finding a way to change the sensitivity/tolerance value in order to increase the accuracy of the recognition. So may I know where can I able to change the sensitivity value?

**Comment by ageitgey** [comment]
Sure, just go to [this line](https://github.com/ageitgey/face_recognition/blob/master/examples/facerec_from_webcam_faster.py#L42) and add a `tolerance=0.55` parameter (or whatever value you want) to the [`compare_faces()`](https://face-recognition.readthedocs.io/en/latest/face_recognition.html) function call.

**Comment by ricerd95** [comment]
@ageitgey Thank you for the reply, beside that is there a way I could let the system to include a folder of sample pictures? Cause I believe the line below only read a single photo, or should I declare multiple line as below?
`obama_image = face_recognition.load_image_file("obama.jpg") `

Thank you.

**Comment by eloelo22** [comment]
@ricerd95 i had the same question on my mind similar to yours i just did something similar to this project https://github.com/malikshubham827/get-me-through and combined some of the samples from the face_recognition and now i got my own web service API
