### ISSUE TITLE
Installed Face-recognition-modeland still it prompts please install face-recognition model

### ISSUE THREAD

**Issue by Palash-Doshi-Git** [ageitgey/face_recognition#1610]
* face_recognition version:1.3.0
* Python version:3.12.3
* Operating System: Ubuntu Vm
* face_recognition_model=0.30.0

### Description

Describe what you were trying to get done.
I'm trying to use CV2 for my project and already have deployed it on Windows, now I'm trying it in Ubuntu system and it has installed all the support libs and requirements for face-recognition. Also tried installing in venv and with python3 -m and also with sudo apt.
Tell us what happened, what went wrong, and what you expected to happen.
I installed all the packages and everything while i was running '''flask run''' there is an error 

`Please install `face_recognition_models` with this command before using "face_recognition":

pip install git+https://github.com/ageitgey/face_recognition_models`

and I also tried  

`
>>pip show face-recognition
Name: face-recognition
Version: 1.3.0
Summary: Recognize faces from Python or from the command line
Home-page: https://github.com/ageitgey/face_recognition
Author: Adam Geitgey
Author-email: ageitgey@gmail.com
License: MIT license
Location: /home/azureuser/Palash/Facial-CheckIn/venv/lib/python3.12/site-packages
Requires: Click, dlib, face-recognition-models, numpy, Pillow
Required-by:
`
IMPORTANT: If your issue is related to a specific picture, include it so others can reproduce the issue.

### What I Did

```
 **>>flask run**
Connection established
Please install "face_recognition_models" with this command before using `face_recognition`:

pip install git+https://github.com/ageitgey/face_recognition_models

**>> pip show face_recognition**
Name: face-recognition
Version: 1.3.0
Summary: Recognize faces from Python or from the command line
Home-page: https://github.com/ageitgey/face_recognition
Author: Adam Geitgey
Author-email: ageitgey@gmail.com
License: MIT license
Location: /home/azureuser/Palash/Facial-CheckIn/venv/lib/python3.12/site-packages
Requires: Click, dlib, face-recognition-models, numpy, Pillow
Required-by:
>> pip show face_recognition_models
Name: face_recognition_models
Version: 0.3.0
Summary: Models used by the face_recognition package.
Home-page: https://github.com/ageitgey/face_recognition_models
Author: Adam Geitgey
Author-email: ageitgey@gmail.com
License: MIT license
Location: /home/azureuser/Palash/Facial-CheckIn/venv/lib/python3.12/site-packages
Requires:
Required-by: face-recognition

```

**Comment by ArjunAtlast** [comment]
I am facing the same issue. How can it be fixed?

**Comment by teroyks** [comment]
Installing `setuptools` into the virtual environment solved this issue for me.

```shell
pip install setuptools
```

The reason seems to be that the `face_recognition_models` package [imports a function](https://github.com/ageitgey/face_recognition_models/blob/e67de717267507d1e9246de95692eb8be736ab61/face_recognition_models/__init__.py#L7) from `pkg_resources`, but that wasn’t included automatically.

**Comment by ozskywalker** [comment]
@Palash-Doshi-Git would you consider re-opening this issue? 

Added a PR to adjust requirements file, after I came across both https://github.com/ageitgey/face_recognition_models/issues/21 & this issue.

**Comment by Palash-Doshi-Git** [comment]
Hey @ozskywalker ,

I wasn't available due to some personal reasons. I would like to know if you still need to reopen this issue.
And what's the update on your PR you added ?

Thank you
