### ISSUE TITLE
Update needed to the raspberry Pi install guide

### ISSUE THREAD

**Issue by NickPPC** [ageitgey/face_recognition#162]
Hi,
First thank you for putting this library together it is great.
I would like to report not quite an issue but a missing change to the Raspberry Pi guide. Since the last update dlib 19.5 is required and the raspberry pi guide manually compile version 19.4 which is useless in the sense that when running pip3 install face_recognition the requirements will force the download and installation of a later version (19.6 as of today)

The guide should either be changed to download, compile and install dlib version 19.5 or remove this part completely and let pip3 install face_recognition deal with dlib. 

I am currently applying the later option to my Raspberry Pi. I will let you know if I uncover any problem

Thanks

**Comment by ageitgey** [comment]
Good catch, thanks! I've updated the dlib version reference to v19.6

The reason I hard-coded a version there was to keep the directions from breaking if a later version of dlib changed something. Ironically I forgot to update that reference when I released the new version of face_recognition earlier this week and broke it myself. Thanks for pointing that out.
