### ISSUE TITLE
Attribute Error: 'Module' object has no attribute 'cnn_face_detection_model_v1'

### ISSUE THREAD

**Issue by singireddysravankumar** [ageitgey/face_recognition#164]
* face_recognition version:1.0.0
* Python version:3.6.2
* Operating System:windows 10 64 bit
* face_recognition_model version:0.2.0

Hi,
```
  I got error like 'module' object has no attribute 'cnn_face_detection_model_v1'
How to solve this can you please tell me.

 What I Did is
conda install python
conda install numpy
conda install scipy
conds install dlib
conda --no-dependecies install face_recognition
conda install face_recognition_models

when i am trying to run i got the error

Thanks in advance

**Comment by singireddysravankumar** [comment]
When i am trying to upgrade dlib using "conda install --upgrade dlib" command it is showing like unrecognized arguments: --upgrade

When i am trying using "pip install --upgrade dlib" command it is showing like 'Failed building wheel for dlib'

**Comment by ageitgey** [comment]
The error "Module' object has no attribute 'cnn_face_detection_model_v1" is because the version of dlib you are using is too old (that was added in dlib version 19.5).  Probably the version of dlib provided by conda is out of date.

I don't use Anaconda myself, so I can't really help with conda issues. One of the disadvantages of using Anaconda is you are sort of limited to whatever versions of packages their maintainers have provided.

I guess you could try using an earlier version of face_recognition that doesn't require the latest dlib release. Using face_recognition version 0.2.2 instead of version 1.0.0 might work for you.

**Comment by singireddysravankumar** [comment]
I got the output.... anyways thank u so much for your valuable reply......

**Comment by singireddysravankumar** [comment]
Hi,
 When i am trying to Get the locations and outlines of each person's eyes, nose, mouth and chin and digital make-up on a image.The image consists of 4 Persons but it is applying the locations and outlines, digital make up to one person at one time. How can we apply the outlines and digital makeup to all persons at one time please give me any idea...

**Comment by lolstatsguy** [comment]
Assuming the example. You can load the image before the the loop. Run the loop for each face. Show the picture after.

**Comment by imperator-maximus** [comment]
I installed dlib from source. and  "pip show dlib" results in 
Name: dlib
Version: 19.8.99
Summary: A toolkit for making real world machine learning and data analysis applications
Home-page: https://github.com/davisking/dlib
Author: Davis King
Author-email: davis@dlib.net
License: Boost Software License
Location: /Users/imperator/anaconda/lib/python3.5/site-packages/dlib-19.8.99-py3.5-macosx-10.6-x86_64.egg
which is newer than 19.5 I would say and no conda dlib installed. 
but I am getting the same error... so any idea what to do?

**Comment by zjmuhsin** [comment]
Hi
I followed the following steps to install dlib on Linux server:
cd dlib
mkdir build
cd build
cmake ..
cmake --build . --config Release
make install

but also got a similar error:
detector = dlib.get_frontal_face_detector()
AttributeError: module 'dlib' has no attribute 'get_frontal_face_detector'

Any help would be really appreciated - Thank you.

**Comment by Aditi1Singh** [comment]
Did you figure out the solution? I'm having the same error, and I don't know what to do.
AttributeError: module 'dlib' has no attribute 'get_frontal_face_detector'

**Comment by awaiskaleemtnr** [comment]
Anything??

**Comment by laddiexu** [comment]
I find the solution now. It is because Anaconda has installed dlib with early version. You can verify it by first pip uninstall dlib, then in python env, import dlib, dlib.__version__. You can find dlib still can be import, and version is lower than 19.5. 
The solution is: conda uninstall dlib, then pip install a newer one.

**Comment by guoqiangszzu** [comment]
> I find the solution now. It is because Anaconda has installed dlib with early version. You can verify it by first pip uninstall dlib, then in python env, import dlib, dlib._ _ version _ _. You can find dlib still can be import, and version is lower than 19.5.
> The solution is: conda uninstall dlib, then install a newer one.

I've sloved my problem by using you advise. I unistall the lower dlib and then install the latest version. It works. Thank you!

**Comment by DPEJW** [comment]
> I find the solution now. It is because Anaconda has installed dlib with early version. You can verify it by first pip uninstall dlib, then in python env, import dlib, dlib._ _ version _ _. You can find dlib still can be import, and version is lower than 19.5.
> The solution is: conda uninstall dlib, then install a newer one.

I was using the Pycharm and dlib 19.18.0, still got this error, any idea why?

**Comment by Daniyalasif129** [comment]
i have lattest version of DLIB and update show me that you are using the latest version but still has same error...any solution

**Comment by murugan-bala** [comment]
> I got the output.... anyways thank u so much for your valuable reply......

how u got ouput..same error facing me .. pls help
