### ISSUE TITLE
Making the model more sensitive

### ISSUE THREAD

**Issue by FerranAlet** [ageitgey/face_recognition#166]
Hi, I'm trying to make the model recognize faces in 'The Simpsons'. However (I guess since there are not really human faces), only very few are detected. I was wondering whether lowering a threshold in some place would help to be more sensitive, but I haven't seen any place to do it. Is there such a place?

Thanks!

**Comment by ageitgey** [comment]
These kinds of models can't generalize like humans can unfortunately. A model trained on human faces won't work well on cartoon faces. You'd need to train a new model. Here's a quick thing I wrote on how to train a new model for that: http://us13.campaign-archive1.com/?e=[UNIQID]&u=c38d3e7da60f36614035c9892&id=709bfd7aed

**Comment by FerranAlet** [comment]
Perfect; thanks!
