### ISSUE TITLE
 idea of a liveness inspection

### ISSUE THREAD

**Issue by xilu0** [ageitgey/face_recognition#167]
* face_recognition version:1.0
* Python version:3.6
* Operating System:win10

### Description

This software is very good, may I ask the author the idea of liveness inspection?

**Comment by ageitgey** [comment]
This library doesn't do any liveness detection.

You could implement something simple where you make the user blink to show they aren't a photo. See http://www.pyimagesearch.com/2017/04/24/eye-blink-detection-opencv-python-dlib/ for an example. But you could still beat that with a video file, so it wouldn't be very secure. 

For a wider list of possibilities, check out this paper: https://arxiv.org/pdf/1405.2227.pdf
