### ISSUE TITLE
Improving Accuracy

### ISSUE THREAD

**Issue by Mikebarson** [ageitgey/face_recognition#17]
Hi! This project is sooo awesome! It sure has made face recognition very easy. However, I have a few concerns. 

1) After testing this on a few of my images, there were a few results that were incorrect. Assuming the my images have different dimensions, the results were often inaccurate. Such as comparing two different persons would say that the unknown face was the known face, when in reality they were completely different persons.

2) I tried comparing a colored image of a person to a different person that was B&W. It also produced inaccurate results. The image size was also different. 

So far those 2 things are what I've noticed. My images contains different sizes. Also, my images are BGR and some B&W. 

Any suggestions on improving my results? Could it be caused by my inconsistent image dimensions, or their colors? 

Thanks!

**Comment by ageitgey** [comment]
Are you able to share some examples that failed? 

In general, just having images of different sizes shouldn't be an issue (unless the images are very low resolution or something like that).

**Comment by Mikebarson** [comment]
How should I share them?

**Comment by ageitgey** [comment]
If you are ok with them being public, you can drag and drop them in the comment box here. Otherwise I guess you could email them to me at ageitgey@gmail.com.

**Comment by Mikebarson** [comment]
I think I'd prefer emailing them. Btw, I managed to improve the accuracy results by lowering the tolerance. From 0.6 to 0.5.

**Comment by Mikebarson** [comment]
I'll send some of the pictures I used to your email.

**Comment by ageitgey** [comment]
You can also try setting jitter=100 when generating embeddings for a very slight improvement in accuracy in trade for slower runtime.
