### ISSUE TITLE
Works on RaspberryP 1?

### ISSUE THREAD

**Issue by jas1989** [ageitgey/face_recognition#170]
Hi everybody. I would like to known if I can use face_recognition on my raspberry 1.
I'm sorry if this is not an issue.

**Comment by ageitgey** [comment]
I don't know if anyone has tested this on a Raspberry PI 1, only on a 2 or 3. My guess is that it either wouldn't work (due to memory) or that it would be very slow.

**Comment by jas1989** [comment]
Thanks a lot, and thank you for this library.
