### ISSUE TITLE
face_location and face_encoding

### ISSUE THREAD

**Issue by eloelo22** [ageitgey/face_recognition#173]
* face_recognition version:
* Python version:
* Operating System:

### Description
hi this is not an issue but more of a question. i have successfully detected faces using the face_location with cnn model. i saw that it locates the faces in a left to right direction. before the face_compare, the usual thing to do is face_encoding and after invoke the face_compare. i return results as json so that i can examine it on the browser looking at the result. i saw that the face_encoding locates the faces from right to left. is there a way to tell the face_encoding to do the same as that of the face_location? i am currently making a web service. the procedure is first i upload the photo to get the locations, then display a box on the detected faces for reference, then do a face_compare in order of faces detected.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by ageitgey** [comment]
If you are already detecting the face locations first as a separate step, you can pass those face locations into `face_encoding()` so it doesn't have to re-detect them. That way the face encodings will be in the same order as the face locations you detected. That makes it easy to match them up to draw boxes around them.

You can look at [these lines](https://github.com/ageitgey/face_recognition/blob/master/examples/facerec_from_webcam.py#L23-L24) in the webcam example to see how that works.

**Comment by eloelo22** [comment]
thank you for the guidance got it working on the front end also
