### ISSUE TITLE
error with Ros camera flux

### ISSUE THREAD

**Issue by elpimous** [ageitgey/face_recognition#177]
* face_recognition version: last
* Python version: 2.7
* Operating System: ubuntu 14.04

hello, I have error in encoding camera stream : needed rgb image,
 and I only have <type 'numpy.ndarray'>

the error : 
  File "/home/nvidia/catkin_ws/src/alfred_vision/src/alfred_faceDetectionCNN.py", line 97, in process
    face_encodings = face_recognition.face_encodings(self.frame, face_locations)
  File "/usr/local/lib/python2.7/dist-packages/face_recognition-1.0.0-py2.7.egg/face_recognition/api.py", line 191, in face_encodings
    return [np.array(face_encoder.compute_face_descriptor(face_image, raw_landmark_set, num_jitters)) for raw_landmark_set in raw_landmarks]
RuntimeError: Unsupported image type, must be RGB image.

Do you have a solution ?
Thanks a lot for your work.
Vincent

**Comment by elpimous** [comment]
i think i need to change that :+1: return [np.array(face_encoder.compute_face_descriptor(face_image, raw_landmark_set, num_jitters)) for raw_landmark_set in raw_landmarks]
but don't know how to process..

**Comment by ageitgey** [comment]
That can happen when your webcam isn't returning an image so the array is empty. Are you sure your webcam is actually working with opencv?

**Comment by elpimous** [comment]
of course yes ! but i use you know, ros uses cvbridge, and automatic converts video flux to numpy array !
i think i need to modify for it

**Comment by ageitgey** [comment]
That call expects a numpy array, but the image data in the array needs to be 8bit rgb data (i.e. integers). Maybe you are passing in the data with a different format? (Like 24 bit color or floating point data or something?)

**Comment by elpimous** [comment]
@ageitgey 
what a silly boy !! I was on greyscale.
Thanks

**Comment by ageitgey** [comment]
No problem :)
