### ISSUE TITLE
face recognition only real faces not fake 

### ISSUE THREAD

**Issue by ahmadRagheb** [ageitgey/face_recognition#180]
hi ,
i use the cam example and i really want to know how to tell the difference between a real person and someone holding his image? i
could you tell me if there is a way to make the 'face_recognition ' know the difference between real person and a picture of him .. and label them as fake or pictures

**Comment by ageitgey** [comment]
One option is to use [blink detection](http://www.pyimagesearch.com/2017/04/24/eye-blink-detection-opencv-python-dlib/) and make the user blink to show they aren't a photo.

**Comment by ahmadRagheb** [comment]
thank you very much ageitgey i will read more about it .

**Comment by ahmadRagheb** [comment]
@ageitgey  i did the demo it was great thanks , 
when i use  vs= VideoStream(src=0).start()  to open the webcam windows 
and try to pass the video instead of 		video_capture = cv2.VideoCapture(0)
			ret, frame = video_capture.read()

it tell there is a lot of values to unpack ?

    ret, frame = video_capture.read()
ValueError: too many values to unpack

**Comment by cyberdrk** [comment]
Is it possible to differentiate between a human and an image without using blink detection, purely from the src image? @ageitgey

**Comment by ageitgey** [comment]
@ahmadRagheb I'm not sure. Try `result = video_capture.read()` and debugging what `result` contains on your system.

@cyberdrk Maybe, but I don't know how myself. For example the new iPhone uses depth data to prevent 2d photos from tricking their system. But that requires extra hardware and a different kind of model than used in this project.

**Comment by MLDSBigGuy** [comment]
What if a [ robot face ] (https://www.google.com/search?hl=en-DE&q=face+of+a+robot&tbm=isch&tbs=simg:CAQSnQEJ4yZJQ1VMsnkakQELEKjU2AQaCggXCD0IFAgDCAoMCxCwjKcIGmIKYAgDEijKAq0HnQfHAs4CrAfFAqUHrge4B-8kjiTuJJo69SXSLPkkmy6ULYskGjCOikmh5tA1CXy3gAPdFfCPla_1qy1RDy0tm2wYr1X-GpFS-lLfFKpV1q3qKlKOHDCwgBAwLEI6u_1ggaCgoICAESBCT_1vjoM&sa=X&ved=0ahUKEwi8j6jUxInaAhWC3SwKHZv3B0IQwg4IJSgA&biw=1428&bih=718&dpr=2) blinks ?

**Comment by hasanlatif** [comment]
may be by using emotion detectors.we can tackle this condition. have a look at [this](https://azure.microsoft.com/en-us/services/cognitive-services/emotion/)

**Comment by MLDSBigGuy** [comment]
ok. How about a humoniod robot ? No, i am just kidding :D A 3d human mask of my friend face with eyes cut out is sufficient to fake. No need to take robots help i guess.

**Comment by elyselam** [comment]
@ahmadRagheb Hey, did you figure it out? i actually was putting 2 scripts together and just kept "frame" from the detect_blink.py and commented out the rest that was related to face_recog video_capture. Couldn't get it to work :/

**Comment by Coldrog** [comment]
Hey! Is it possible to update the database with some values like updating present in attendance column by detecting the blinking face detection. If yes, how?

**Comment by parikshitparmar** [comment]
> Hey! Is it possible to update the database with some values like updating present in attendance column by detecting the blinking face detection. If yes, how?

create a connection with your database and on a specific count of blink you can fire a query to the database. That query make update to database

**Comment by parikshitparmar** [comment]
if(TOTAL == 3):
         ## ANYTHING HERE ###
        cam.release()
        cv2.destroyAllWindows()
        break

**Comment by parikshitparmar** [comment]
Yes,

if(TOTAL == 3):
#ANYTHING HERE 
cam.release()
cv2.destroyAllWindows()
break

**Comment by parikshitparmar** [comment]
> ? i actually was putting 2 scripts together and just kept "frame" from the detect_blink.py and commented out the rest that was related to face_recog video_capture. Couldn't get it to work :/

![whatsapp image 2019-01-16 at 3 42 59 pm](https://user-images.githubusercontent.com/23567163/51245389-869d4080-19ad-11e9-8615-2323b4e10937.jpeg)

**Comment by parikshitparmar** [comment]
> One option is to use [blink detection](http://www.pyimagesearch.com/2017/04/24/eye-blink-detection-opencv-python-dlib/) and make the user blink to show they aren't a photo.

![whatsapp image 2019-01-16 at 3 42 59 pm](https://user-images.githubusercontent.com/23567163/51245492-d4b24400-19ad-11e9-96b3-ad27df26034f.jpeg)

**Comment by Kamelia2000** [comment]
Hello this is Kamelia anyone know any library for face recognition possible to make cluster also possible to find difference between a picture of a person and live.I mean understand this is a picture to recognize 

Thanks,
Kamelia

**Comment by ajaymin28** [comment]
> Hello this is Kamelia anyone know any library for face recognition possible to make cluster also possible to find difference between a picture of a person and live.I mean understand this is a picture to recognize
> 
> Thanks,
> Kamelia

Use Sklearn(Machine Learning Lib) for clustering and face_reconition from github for extracting face features, feed the features to DCSCAN algorithm to generate clusters.

**Comment by ajaymin28** [comment]
> Is it possible to differentiate between a human and an image without using blink detection, purely from the src image? @ageitgey

Best idea is to use stereo vision cameras to identify 3d face and 2d face.
