### ISSUE TITLE
does load_image_file have a version which read from byte[] not just from the disk file

### ISSUE THREAD

**Issue by luchunminglu** [ageitgey/face_recognition#181]
does load_image_file have a version which read from byte array in memory not just from the disk file.

**Comment by masoudr** [comment]
You can use this method to encode an image without `load_image_file` function. Remember that `load_image_file` function only converts an image to an array and it doesn't matter which function you use to do that.

```
im_src=Image.open(file_stream);
im_src.thumbnail(size_src, Image.ANTIALIAS) # resize the image to half size
im_src_array=numpy.array(im_src)
if(len(face_recognition.face_encodings(im_src_array))):
    specific_image_encoding = face_recognition.face_encodings(im_src_array)[0]
```

**Comment by ageitgey** [comment]
The `load_image_file` should also work with a byte array as long as the array contains an actual image file. You can also pass it a BytesIO() object and it can read from that.
