### ISSUE TITLE
some photo can not be recognized

### ISSUE THREAD

**Issue by rongwwei** [ageitgey/face_recognition#182]
* face_recognition version:0.1.14
* Python version:2.7.13
* Operating System: ubuntu 17.04

### Description

some photo can not be recognized. face_recognition.face_locations and face_landmarks return [] to me.

### What I Did

```
people in the photo with black clothes
```

**Comment by masoudr** [comment]
@rongwwei As I tested this tool with a lot of databases. You need to first extract the faces in the image with `face_encodings` and then compare them, also there is a `tolerance` parameter in `compare_faces`, you can use higher values and test the results.
