### ISSUE TITLE
Providing more than one sample

### ISSUE THREAD

**Issue by AlmasM** [ageitgey/face_recognition#184]
Hi, 

I was wondering if it is possible to provide more than one sample to method : 

> 'face_recognition.load_image_file

I read API Docs, but I couldn't find anything. 

In general, I would like to input a folder of the same character rather than singular image to see if that affects accuracy.

Thanks.

**Comment by AlainPilon** [comment]
`load_image_file` only loads the image and returns its content as an array so it isnt what you are looking for. Actually, I too was wondering the same and from what I have seen looking at the code, there is no way to do that directly.

A 'solution', could be to create another entry in your list of `known_faces` for each image.
