### ISSUE TITLE
pip install face_recognition  stick

### ISSUE THREAD

**Issue by limin1130** [ageitgey/face_recognition#186]
* face_recognition version:
* Python version:
* Operating System:
when i goto the step "pip --no-cache-dir install face_recognition",it downloads several files like face_recognition,click,numpy,pillow,scipy，then stick here anybody know what's wrong? 

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by ageitgey** [comment]
No idea. Maybe you could paste the full command and output?

**Comment by limin1130** [comment]
solved already ,while i dont know why ,i just install the numpy etc separately and it work

**Comment by ageitgey** [comment]
Glad you got it working :)
