### ISSUE TITLE
error in the doc?

### ISSUE THREAD

**Issue by AlainPilon** [ageitgey/face_recognition#189]
Is this line from the doc outdated?

`face_locations = face_recognition.face_locations(image, model="cnn")`

because the current function def for `face_locations` is:

`def face_locations(img, numbers_of_time_to_upsample=1):`

Also, there is this line before the code sample:

`You can also opt-in to a somewhat more accurate deep-learning-based face detection model.`

which I guess is referring to the `cnn` model param.

**Comment by lolstatsguy** [comment]
your version is outdated. 
`def face_locations(img, number_of_times_to_upsample=1, model="hog"):`
is the current version of the function

**Comment by AlainPilon** [comment]
right... was using it inside the "official test VM". thx
