### ISSUE TITLE
How to get value of coordinates from a mmod_rectangle object

### ISSUE THREAD

**Issue by thanif** [ageitgey/face_recognition#192]
### What I Did

```
I changed the model argument to "cnn" from "hog"

It returns rectangle objects but I am unable to get four corresponding values of the rectangle



```

**Comment by ageitgey** [comment]
Can you share a code example of what you are doing? Unless there is a bug (which is possible), changing the model argument shouldn't change the format that the function returns.

**Comment by thanif** [comment]
image = face_recognition.load_image_file(known_dir+known_images_path)
encoding = face_recognition.face_encodings(image)[0]

def face_locations(img, number_of_times_to_upsample=1, model="cnn"):
def _raw_face_locations(img, number_of_times_to_upsample=1, model="cnn"):

**Comment by eloelo22** [comment]
you should use a variable i think i am not a python developer but the word def i think is somethinh like a void in c# follow this https://github.com/ageitgey/face_recognition/blob/master/examples/find_faces_in_picture_cnn.py

**Comment by eloelo22** [comment]
i used something like this declare a variable say face_rectangle then face_rectangle = face_locations(img, number_of_times_to_upsample=1, model="cnn")

**Comment by ageitgey** [comment]
I don't think that is valid python code.

In any case, you can see how to get the co-ordinates of each face in this example:

https://github.com/ageitgey/face_recognition/blob/master/examples/find_faces_in_picture_cnn.py#L19

**Comment by thanif** [comment]
Yes you are right it's not except the first two lines which show image being loaded and a function call for encodings while the  next two are just signatures with change of model "cnn" in api.py file. The error which is thrown when I try to generate encodings is as follows :
![error](https://user-images.githubusercontent.com/32266960/31025729-207cb1b6-a55d-11e7-8b82-a19e2304c782.png)

**Comment by ageitgey** [comment]
You shouldn't need to change any code in api.py or anything inside of face_recognition. 

1. Can you post the actual code for your test_experiment.py file so I can see what exactly you are doing?
2. Does the example file I linked you to work correctly?

**Comment by thanif** [comment]
[test_experiment.py.zip](https://github.com/ageitgey/face_recognition/files/1347127/test_experiment.py.zip)

**Comment by ageitgey** [comment]
If I understand the problem correctly, I think you are saying that you edited api.py like this:

```python
# You changed the default  model value here
def face_locations(img, number_of_times_to_upsample=1, model="cnn"):

# You changed the default model value here
def _raw_face_locations(img, number_of_times_to_upsample=1, model="cnn"):
```

Which would introduce the problem you are seeing.

If you want to use the cnn model to find faces and then use those faces to do face encodings, you would instead do this in your own code (NOT changing the library code):

```python
# Assuming you already loaded an image file into a variable called "img"

face_locations = face_recognition.face_locations(img, model="cnn")
face_encodings = face_recognition.face_encodings(img, face_locations)
```

That's it. No code changes required.
