### ISSUE TITLE
Low recognition performance. How to leverage more than one picture per known person to improve?

### ISSUE THREAD

**Issue by smajida** [ageitgey/face_recognition#195]
* face_recognition version: 0.1.12
* Python version:2.7
* Operating System: Linux - Ubuntu

### Description
Using one 128-d face embedding for each person does not give good results in real world in all of frames. Always there is jumping of recognition among frames even though illumination stays the same. And most of the time, recognizer gives wrong recognition. How to leverage more than one known picture per person? Perhaps in this way the performance would  be better, but I have no idea how to do that. One way of using these images is by using clustering. However how is it possible to cluster against unknown people class for which we have no idea how they look like?

Another point to improve is the similarity function. Due to high dimensional of embedding, euclidean distance suffers from curse of dimensionality. How about other similarity check criteria?

**Comment by rajesh-bhat** [comment]
@smajida were you able to get the solution?
