### ISSUE TITLE
missing face_recognition terminal command

### ISSUE THREAD

**Issue by derVedro** [ageitgey/face_recognition#2]
* face_recognition version: 0.1.0
* Python version: 3.5.2
* Operating System: ubuntu 16.04

Just install it local via pip with --user key.
CLI version (cli.py) is not avaiable as a separete face_recognition terminal command.
I actually don't know, if pip allows you to put simlinks or something like that, so you
have separete scripts you can execute on console.

**Comment by ageitgey** [comment]
If you install it with --user on Ubuntu 16.04, you'll either have to add `~/.local/bin/face_recognition` to your PATH environment variable or manually run it like this:

```bash
~/.local/bin/face_recognition
```

Let me know if that fixes it for you.

**Comment by derVedro** [comment]
yes, i forgot to look at ~/.local/bin 
thank you for remark.
