### ISSUE TITLE
AttributeError: 'module' object has no attribute 'load_image_file'

### ISSUE THREAD

**Issue by FrederikHaa** [ageitgey/face_recognition#200]
* face_recognition version: 1.0.0
* Python version: 2.7.12
* Operating System: Ubuntu 16.04

### Description
I'm trying to run the provided webcam example, but I get errors.
I am able to import the module, but not use any of the API functions.

```
Traceback (most recent call last):
  File "face_recognition.py", line 1, in <module>
    import face_recognition as fr
  File "/home/frederik/Documents/Uni/SMOOTH/face_recognition/face_recognition.py", line 20, in <module>
    image = fr.load_image_file("frederik.jpg")
AttributeError: 'module' object has no attribute 'load_image_file'
```

**Comment by ageitgey** [comment]
Don't name your own file face_recognition.py. Python is finding that instead of the library.

**Comment by FrederikHaa** [comment]
Of course, thank you.

Now I feel stupid

**Comment by Sherlock-liufr** [comment]
I cant understand you

**Comment by raybg** [comment]
> rename the file?

yes, one should never name the file name similar to the library.
