### ISSUE TITLE
 face_encoder.compute_face_descriptor have implement transform ? 

### ISSUE THREAD

**Issue by haixoay96** [ageitgey/face_recognition#201]
* face_recognition version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by ageitgey** [comment]
Sorry, I don't understand your question.

**Comment by haixoay96** [comment]
I mean,you have implement 'shear'
