### ISSUE TITLE
NameError: global name 'model' is not defined

### ISSUE THREAD

**Issue by zzw1123** [ageitgey/face_recognition#202]
### Description
I am confused when I run the following command:
face_locations = face_recognition.api.face_locations(image)

Because there is an error:
Traceback (most recent call last):
  File "face_detect.py", line 9, in <module>
    face_locations = face_recognition.api.face_locations(image) 
  File "/home/zzw/.local/lib/python2.7/site-packages/face_recognition/api.py", line 84, in face_locations
    if model == "cnn":
NameError: global name 'model' is not defined

I do check the api.py,and find there is a param "model" of the face_locations function,but I cannot get the definition of it,anyone can help me?
Thanks a lot!

**Comment by zzw1123** [comment]
I change the api.py file and the problem is solved.

**Comment by ageitgey** [comment]
Run the command as `face_locations = face_recognition.face_locations(image)` instead of `face_locations = face_recognition.api.face_locations(image)`. You shouldn't need to change any files.

**Comment by zzw1123** [comment]
@ageitgey so what is the difference between face_recognition.api.face_locations and without api?

**Comment by ageitgey** [comment]
The api.py file is just how the code is written internally inside the module. But when you use the module in a program, you can always just call `face_recognition.function_name()` directly.

**Comment by zzw1123** [comment]
@ageitgey ok,I got it.Thanks a lot!
