### ISSUE TITLE
How to make this recognize my own images?

### ISSUE THREAD

**Issue by elnasdgreat** [ageitgey/face_recognition#203]
I'm new to this, and want to learn more.
What needs to be done? Thanks in advance!

**Comment by ageitgey** [comment]
The best place to start is [reading the docs](https://github.com/ageitgey/face_recognition/blob/master/README.md#face-recognition) and running the [example programs](https://github.com/ageitgey/face_recognition/blob/master/README.md#python-code-examples).

If you aren't a programmer and want to use the command-line interface, you can check out [those docs](https://github.com/ageitgey/face_recognition/blob/master/README.md#command-line-interface) instead.
