### ISSUE TITLE
My first impressions with this software

### ISSUE THREAD

**Issue by DeadZen** [ageitgey/face_recognition#204]
It doesn't work very well, or if it does, we need more guidance on images where a face cannot be located.
Or some way to improve accuracy, this is currently a black box that even though it may utilize techniques with over 99% accuracy, it itself achieves nowhere near this. Perhaps I'm missing something, is the state of the art in visual recognition just really really bad and my expectations are too high?

**Comment by ageitgey** [comment]
Do you have specific examples (code + images) of cases you expect to work but don't? Without providing specific examples of what you are trying to do and what isn't working as expected, there's no way I can offer any good advice.

**Comment by DeadZen** [comment]
My issue was with training the facerec_..._faster example with other faces.. 
I could get it to recognize obama off a cellphone, but adding other faces, there either wouldn't locate a face in 4/5 tries (using cam photos from two different phones), or have a very low accuracy (in the one case it recognized a face), causing high settings of the tolerance (0.7) to get recognition, after which gave it a lot of false positives..  I have the repo with all the images I took, my only code change is that and s/cv2.FILLED/-1/ .. if you like I can email to you, it's probably a stupid mistake on my part, but I would like your specific images and code to create the gif with the man, woman and cell phone...
