### ISSUE TITLE
Is it possible to run on Intel Galileo?

### ISSUE THREAD

**Issue by rexlow** [ageitgey/face_recognition#207]
* Python version: 2.7.10
* Operating System: Ubuntu 16.04 LTS

### Description
My goal is to build a real-time face recognition video app. 

Is it possible to build run this on Intel Galileo Gen 1? Given that Tensorflow itself require certain amount of computing power to run efficiently.

**Comment by ageitgey** [comment]
I don't know since I've never used that particular board. But if it does, my guess is that it would be pretty slow.

**Comment by rexlow** [comment]
I thought so too. Thanks. Will try out myself on both board, make a comparison and keep you posted!
