### ISSUE TITLE
face_locations get wrong result but dlib is correct

### ISSUE THREAD

**Issue by starzxzx** [ageitgey/face_recognition#209]
* face_recognition version: 1.0.0
* Python version: 3.5
* Operating System: Ubuntu 16.04 LTS

### Description
I run the example find_faces_in_picture_cnn.py to process the image from this link.
https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1507896274082&di=824f7f59943a71e2e9904d22175ce92c&imgtype=0&src=http%3A%2F%2Fwww.moontalk.com.tw%2Fupload%2Fimages%2F20160606angelina-03.jpg
The program detect the hand as a face ,I check the code and run example in dlib from this link ,the result is correct.
http://dlib.net/cnn_face_detector.py.html
So the problem maybe occur in load_image_file ?

**Comment by ageitgey** [comment]
Hi @starzxzx,

If you change the code from:

```python
face_locations = face_recognition.face_locations(image, number_of_times_to_upsample=0, model="cnn")
```

To this:

```python
face_locations = face_recognition.face_locations(image, number_of_times_to_upsample=1, model="cnn")
```

(In other words, use `number_of_times_to_upsample=1`)

You'll get the result you expect. Upsampling is a little slower, but it allows for more accurate results.

**Comment by starzxzx** [comment]
thanks
