### ISSUE TITLE
[bug] load_image_file can't load some bytes broken image

### ISSUE THREAD

**Issue by oneTaken** [ageitgey/face_recognition#210]
I just want to know whether the image has faces. So, I use the code:
```
import face_recognition
img = face_recognition.load_image_file(imgname, mode='RGB')
faces = face_recognition.face_locations(img)
```
Suddenly, it raise error, the img must be uint8 or a PIL image.

I saw you use the function ```scipy.misc.imread()``` function to read image.
It's a combination of ```scipy.misc.fromimage(), PIL.Image.open()```.
If an image has some bytes broken, the ```scipy.misc.fromimage()```gets unexpected result.

After my endeaver, you just to add 
```
from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True
```
And everything goes perfect.
more details tomorrow.

**Comment by ageitgey** [comment]
I wouldn't call it a bug that it won't load corrupted files. But thanks for the tip to solve it for those that have this special case need.

**Comment by ageitgey** [comment]
Noted here: https://github.com/ageitgey/face_recognition/wiki/Loading-corrupted-or-partially-downloaded-image-files
