### ISSUE TITLE
why the speed with mode='CNN' on the GPU server don't get faster?

### ISSUE THREAD

**Issue by oneTaken** [ageitgey/face_recognition#211]
I want to detect faces. the speed with mode='CNN' keeps similar both on the CPU and the GPU server. 
Why? 
It should be much faster on the GPU server.

**Comment by ageitgey** [comment]
Did you compile dlib with CUDA support so that it will be able to use the GPU? Can you verify that the nvidia-smi tool shows your program actually using the GPU when running?

**Comment by oneTaken** [comment]
@ageitgey Sorry, I didn't do this. Anyway, I didn't see some guidence. I'll have a try.

**Comment by ageitgey** [comment]
No problem. Sorry it isn't really covered in the docs. I'll add some more GPU details to the docs when I have time.

**Comment by IWriteThings** [comment]
I compiled dlib with CUDA and if I get it working, I will write a PR for some documentation on what to do to get it working and how.

**Comment by FiveMaster** [comment]
@IWriteThings I want to use GPU to speed up the face recognition.but if I change model from hog to cnn, it will raise:TypeError: No registered converter was able to produce a C++ rvalue of type class dlib::rectangle from this Python object of type mmod_rectangle
this error means I did not compile dlib with CUDA? and how compile dlib with CUDA?
thank you.

**Comment by ageitgey** [comment]
@FiveMaster if you have a error like that, please give an example piece of code that generates the error so that we can see how you got it. Otherwise it's hard to know how to help without knowing what you tried.
