### ISSUE TITLE
Quickest option to recognize a person

### ISSUE THREAD

**Issue by bshao001** [ageitgey/face_recognition#214]
Firstly, I really appreciate your great work. I have tried the face detection function, and it works perfectly (29 out of 30 images were good, and the face areas were very accurate). 

As I am new to this project, I would like to ask a quick question about the recognition function:

Say I have 200 pictures/images, each of which contains only one person. I know all of them, and all the files are named with their names. Now, when a new picture/image is given, I want to know if this unknown person is one of these 200 people, what is the quickest way (speed performance) to run it? I mean what is the best format to keep the data for the 200 people:

1. Keep the original images as in .jpg or .png, even with the whole human body and probably some other area of background, such as a park.
2. Crop each image into a face only, using face_recognition face detection function.
3. Save each image/person in feature encodings only. For example, in a data file with the encoding data of all these 200 people. No image files needed at all.

I assume that option 3 runs the quickest. At the inference time, I just need to extract the encoding of the given image, and then compare with the encoding data loaded from the file.

Please confirm. Thank you so much!

**Comment by AlainPilon** [comment]
Store the encodings in a numpy Array (not a python list!). I keep my images in a folder in case I want to regenerate the encodings but I do all comparison using Arrays. It is super fast, 200 elements is a joke, I have a few thousand in memory and it works great.

If I remember correctly, each 128 points encoding takes about 2k of space.

**Comment by ageitgey** [comment]
Yep, #3 is the fastest! You understand correctly :-)

**Comment by bshao001** [comment]
@AlainPilon @ageitgey Thanks for the quick response. If I want to improve the accuracy, can I use several images for each person, extract the feature encodings from each image, average them along the axis, and then use the mean values as the encodings of that person, will that help? Thank you again!!

**Comment by AlainPilon** [comment]
Nope. The average of two faces is not the same as either originals ;-)

Instead just insert the new face encoding in your Array and have it assign to the same user. This is what I do.

**Comment by bshao001** [comment]
@AlainPilon Thank you again for the quick reply. 

Firstly, you confirmed that several images for one person does help with the accuracy. Is that correct?
Secondly, I do not get the details. Can you explain a little bit more or refer me to a sample code?

I really appreciate your time and help!

**Comment by bshao001** [comment]
@AlainPilon I am kind of getting your idea. My understanding is that your suggestion/approach might increase the recall, but may decrease the precision, because as long as the unknown image matches to any one set of the encodings of the same person, it will be classified as that person.

**Comment by ageitgey** [comment]
@bshao001 The other thing you can do if you have multiple encodings for each known person is to train a simple classifier (like an Support Vector classifier) with scikit-learn to classify each unknown encoding against all your known encodings. This is what OpenFace does. This strategy may increase overall accuracy somewhat, but whether performs better (or is worth the extra work) than just testing against all known encodings like @AlainPilons said is just something you'd have to test.

**Comment by bshao001** [comment]
@ageitgey Thank you again for the explanation. I missed a very important point before this conversation. I thought you code performs a sequential comparison along the list of encodings for each person. Now I notice that it is still a classification problem, which can be executed in parallel (especially in GPU). Therefore, it is less a speed performance concern, but the prediction result will turn to be that the unknown person will must be one of the, say, 200 people, unless we intentionally prepare encodings for OTHER as one of the many classes.

**Comment by jamescndubuis** [comment]
@ageitgey, I am working with your module using django and need to store the face-encodings in a database field, how do i do it and which field is suitable?
I used a character field and had issues comparing the face encodings retrieved from database with the one created from an image. Any advice?
