### ISSUE TITLE
Multi-people recognition from webcom 

### ISSUE THREAD

**Issue by dyshuang** [ageitgey/face_recognition#219]
* face_recognition version: the lastest version
* Python version: python 2.7
* Operating System: MacOS

### Description

As the example script of facerec_from_webcam_faster is for one person, I wonder how to do face recognition for multi-people like the README.md showed.

Any help will be appreciated!

**Comment by The-Perfect-Username** [comment]
The method **compare_faces** takes an array of facial encodings as its first paramter. In the example it only took one facial encoding, so simply add another element into the array like so:

**match = face_recognition.compare_faces([obama_face_encoding, your_face_encoding], face_encoding)**

And to see if the second face is a match, just check if **match[1]** is true.

**Comment by Osmosis311** [comment]
I'm also interested in this.  So if you had let's say 200 people's pictures in a folder of "known" people, you would loop through the files in that folder, and add them all to that array, and pass that array into compare_faces?

Thanks!

**Comment by The-Perfect-Username** [comment]
That's pretty much it.

**Comment by dyshuang** [comment]
Thank you so much for your reply~ @The-Perfect-Username 
Your code helps me a lot !
I am continuing working on it ^_^

**Comment by eldarmukhametov** [comment]
I'm also interested in this. Can you show the code to recognition two "known" face? Thanks!

**Comment by zengbing1992** [comment]
Can you solve it? @Osmosis311

**Comment by yoga1314** [comment]
@The-Perfect-Username 
I also used this method, but when I added photos of my classmates and me, the program would recognize me as my classmate and I，it returned two true

**Comment by yuen33** [comment]
The last one checked in the match array will be the final one...
This webcam project looks only can recognise Black, White, Yellow people... My picture matches mine, my friends', my dad's... Looks useless.
