### ISSUE TITLE
3D recognition

### ISSUE THREAD

**Issue by Wisgon** [ageitgey/face_recognition#220]
* face_recognition version: 1.0.0
* Python version: 3.6
* Operating System: ubuntu

### Description

Hi there!
I wonder to know that can this model recognize the real face but not the face in a picture?Because I don't want someone use a picture of mine to enter my room!

**Comment by AlainPilon** [comment]
search the closed issues, it has been asked a few weeks ago, key word: `blink detection`

**Comment by Wisgon** [comment]
Thanks ! It helps me a lot!
