### ISSUE TITLE
Get face info

### ISSUE THREAD

**Issue by Angelk90** [ageitgey/face_recognition#223]
@ageitgey:  Congratulations nice project. Would it be possible to get information like, gender, age, eye color, skin color, wearing glasses, etc ..?

**Comment by AlainPilon** [comment]
Not with this lib, but once you have the face, you can send it to another library. I know a few who can guess age (real and apparent) and gender. I dont know about your other requirements, but if you do find anything, please post them back here.

**Comment by Angelk90** [comment]
@AlainPilon: Could you post the link? of those you know.

**Comment by AlainPilon** [comment]
A bit late, but can't find the link I had in mind, but these should help: https://data.vision.ee.ethz.ch/cvl/rrothe/imdb-wiki/
