### ISSUE TITLE
can i get the api documentation?

### ISSUE THREAD

**Issue by tharssh** [ageitgey/face_recognition#224]
* face_recognition version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by ageitgey** [comment]
There is a link in the README: https://face-recognition.readthedocs.io/en/latest/face_recognition.html
