### ISSUE TITLE
pip2 install error

### ISSUE THREAD

**Issue by haoxuhao** [ageitgey/face_recognition#226]
* face_recognition version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did
My os is ubuntu16.04, when i run 'pip3 install face_recognition', it works.But when i run 'pip2 install face_recognition', it can work but output 'cleaning up' in the end.Can anybody help me?

If there was a crash, please include the traceback here.
  Downloading face_recognition-1.0.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): numpy in /usr/local/lib/python2.7/dist-packages (from face-recognition)
Requirement already satisfied (use --upgrade to upgrade): Pillow in /usr/local/lib/python2.7/dist-packages (from face-recognition)
Requirement already satisfied (use --upgrade to upgrade): Click>=6.0 in /usr/local/lib/python2.7/dist-packages (from face-recognition)
Requirement already satisfied (use --upgrade to upgrade): dlib>=19.5 in /usr/local/lib/python2.7/dist-packages (from face-recognition)
Requirement already satisfied (use --upgrade to upgrade): face-recognition-models>=0.2.0 in /usr/local/lib/python2.7/dist-packages (from face-recognition)
Requirement already satisfied (use --upgrade to upgrade): scipy>=0.17.0 in /usr/local/lib/python2.7/dist-packages (from face-recognition)
Requirement already satisfied (use --upgrade to upgrade): olefile in /usr/local/lib/python2.7/dist-packages (from Pillow->face-recognition)
Installing collected packages: face-recognition
Successfully installed face-recognition
Cleaning up...

**Comment by ageitgey** [comment]
What was the error? From your description, it seems like it worked?
