### ISSUE TITLE
multiprocessing of face_distance (question)

### ISSUE THREAD

**Issue by ZsBT** [ageitgey/face_recognition#227]
Hi, I'd like to use more CPUs when using face_distance in my python scripts. If I see well, multiprocess is implemented only in the CLI interface.
Do you have plans to have this in the libs?

**Comment by ageitgey** [comment]
Python itself supports multiprocessing. Nothing in this library needs to change by to support it. You can just copy the same approach in the cli script in your own programs.

**Comment by ZsBT** [comment]
thanks, I'll do so.
