### ISSUE TITLE
Why are we using the small model in _raw_face_landmarks?

### ISSUE THREAD

**Issue by AlainPilon** [ageitgey/face_recognition#228]
@ageitgey: Why do we use `model="small"` [here](https://github.com/ageitgey/face_recognition/blob/master/face_recognition/api.py#L197) :

    `raw_landmarks = _raw_face_landmarks(face_image, known_face_locations, model="small")`

Is it for performance reasons?

**Comment by ageitgey** [comment]
Yes. The default model finds lots of extra face landmark points but face encoding process only needs a few of those landmark points to normalize/straighten the face image. So this avoids doing extra work for no reason.
