### ISSUE TITLE
only seems to recognise obama's face

### ISSUE THREAD

**Issue by tharssh** [ageitgey/face_recognition#230]
* face_recognition version: vm 
* Python version:
* Operating System:

for some reason the codes only seem to recognise obama's face. ive tried my own datasets and it only detects a face no recognition. my datasets are all jpg. is there a certain image format or type that i am missing? thanks 

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by ageitgey** [comment]
No, nothing special. Can you share an example of two files it doesn't recognize for you? Maybe there is something wrong with the files?

**Comment by yoga1314** [comment]
@ageitgey 
I have a similar problem, the program seems to know only Obama and non-Obama, I use their own photos but can not achieve the effect of the demo

**Comment by ageitgey** [comment]
@yoga1314 I can't really help unless you post sample images that don't work.

**Comment by yoga1314** [comment]
I raised this question on GitHub, and when I use this photo, the program will recognize me as both me and my classmate. The photo is in the attachment.
