### ISSUE TITLE
Difference between face_recognition.load_image_file(path) and cv2.imread(path)

### ISSUE THREAD

**Issue by Miles-Ma** [ageitgey/face_recognition#231]
* face_recognition version: face-recognition (1.0.0), face-recognition-models (0.3.0)
* Python version: 3.5.2
* Operating System: Ubuntu-16.04-LTS x86_64

### Description
First of all, thank you for your excellent work!

I'm just confused about this:
What does the method `face_recognition.load_image_file(path)` do when loading a file? I'm asking this because I found that this method returns a slightly different result compared to `cv2.imread(path)` when loading the same `.jpg` image. This means, if I do these:
```
In [1]: import cv2, face_recognition, numpy as np

In [2]: img_fr = face_recognition.load_image_file('/home/miles/三十.jpg')[:,:,::-1]
          # use [:,:,::-1] to convert RGB -> BGR
          # "三十.jpg" is a photo containing exactly containing one face.

In [3]: img_cv = cv2.imread('/home/miles/三十.jpg')

In [4]: img_fr.shape
Out[4]: (424, 301, 3)

In [5]: img_cv.shape
Out[5]: (424, 301, 3)

In [6]: difcount = 424*301*3 - np.sum(img_fr==img_cv)

In [7]: difcount
Out[7]: 56072
```
There will be 56072 different pixels. Moreover, if I compute the distance:
```
In [1]: import cv2, face_recognition, numpy as np

In [2]: img_fr = face_recognition.load_image_file('/home/miles/三十.jpg')[:,:,::-1]

In [3]: img_cv = cv2.imread('/home/miles/三十.jpg')

In [4]: location_fr = face_recognition.face_locations(img_fr)

In [5]: location_cv = face_recognition.face_locations(img_cv)

In [6]: encodings_fr = face_recognition.face_encodings(img_fr, location_fr)

In [7]: encodings_cv = face_recognition.face_encodings(img_cv, location_cv)

In [8]: dis = face_recognition.face_distance(encodings_fr, encodings_cv[0])

In [9]: dis
Out[9]: array([ 0.03327288])
```
It won't be ZERO while it should be, because they are actually the same image. This took me 2 hours to find out as I was implementing a bit-of-complicated app. I'm curious about how the difference comes. Is it caused by floating number error when decoding the `.jpg` file?

**Comment by ageitgey** [comment]
Good question! The library is just calling `scipy.misc.imread(path)` with a mode parameter, but it's possible that function is doing some scaling on the values. I'll have to investigate. In the meantime, feel free to use `cv2.imread(path)` instead to load your images.

**Comment by luisfciencias** [comment]
`face_recognition` loads the image using the RGB ordering convention. The method `cv2.imread()` does this using the inverse ordering, BGR convention. Consider the trick `img_rgb = img_bgr[...,::-1]`.
