### ISSUE TITLE
Working with open cv and face_recognition

### ISSUE THREAD

**Issue by ayyucedemirbas** [ageitgey/face_recognition#232]
![ss](https://user-images.githubusercontent.com/8023150/32650320-2ed6d92e-c5b2-11e7-9d6f-c4421698e59a.png)

* face_recognition version:
* Python version: 3.5.2
* Operating System: Ubuntu

### Description

I am trying to compile this: https://github.com/ageitgey/face_recognition/blob/master/examples/facerec_from_webcam_faster.py

When I tried to compile the python file by typing "python face.py" I get this error message:

ImportError: No module named face_recognition

If I type "python3 face.py"  I get:

ImportError: No module named 'cv2'

### What I Did

```
I typed workon cv and "python3 face.py"  I got this message
ImportError: No module named 'face_recognition'


```

**Comment by ageitgey** [comment]
`No module named 'face_recognition'` means this library isn't installed. Did you install it already?

**Comment by ayyucedemirbas** [comment]
Yes, I can launch face_recognition command line program.

**Comment by ageitgey** [comment]
If you are typing `workon cv`, that implies you have created a new virtual environment called `cv` that would have it's own set of libraries. I'm guessing you haven't installed face_recognition in the `cv` environment (but only in your system-level environment). So maybe try it without `workon cv`?

**Comment by ayyucedemirbas** [comment]
I haven't installed face_recognition in the cv environment. Firstly I installed face_recognition, secondly open cv. How can I install face_recognition in the cv environment? If I try it without workon cv, I get ImportError: No module named 'cv2'.

**Comment by ageitgey** [comment]
When you say "workon some_name", you are telling Python to use a whole new working environment that only sees libraries installed in that environment. This makes it so that different programs that need different libraries don't conflict with each other.

So my guess is you have two environments now:

1. Main Python environment:
    - face_recognition installed
    - OpenCV *not* installed
1. "cv" Python environment:
    - face_recognition *not* installed
    - OpenCV installed

So you either need to run "workon cv" and then re-install face_recognition just like you did the first time OR you need to install OpenCV in your main Python environment instead of in the cv environment. It's up to you.

**Comment by ayyucedemirbas** [comment]
If I type "workon cv" and reinstall face_recognition by following the steps, Can I import face_recognition in the cv environment?  Sorry for my bad English.

**Comment by ageitgey** [comment]
Yep, that should work as long as you install face_recognition using the same terminal window where you typed "workon cv".

**Comment by ayyucedemirbas** [comment]
Successfully compiled. Thank you so much 🙂

**Comment by Zanbrachrissik** [comment]
Could you please tell me how to import the face_recognition module? I failed to compile all the python files. However I could launch face_recognition command line program.
![image](https://user-images.githubusercontent.com/21967806/39354062-06aeea90-4a3c-11e8-96b1-5108230852dc.png)
