### ISSUE TITLE
Cannot Read Face from rotated image 

### ISSUE THREAD

**Issue by jeremiteki** [ageitgey/face_recognition#235]
* face_recognition version: The lastest version
* Python version:Python 3.6.3 :: Anaconda custom (64-bit)
* Operating System:Linux

### Description

When passing a the folder of known people that has  images which are rotated am getting below warning.

**WARNING: No faces found in /home/jk/devOPS/facedetect/test/jeremiy_06.jpg. Ignoring file.**

### What I Did

```
face_recognition  --tolerance 0.3 /home/jk/devOPS/facedetect/test/ alvin.jpg | cut -d ',' -f2
```
Any help will be appreciated!

**Comment by yaoxx255** [comment]
yes this is how it works. there is not need to decrease tolerance such low. in face recognition api, it use HOG method to detect faces, which is more accurate than opencv's "haar cascade" method, but slower.  i would say try detect faces with haar cascade in opencv, then use opencv function rotate it. then use it as input to compareface function.

**Comment by jeremiteki** [comment]
Thanks @yaoxx255
