### ISSUE TITLE
erro: Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by cuimiao187561** [ageitgey/face_recognition#24]
* face_recognition version:0.1.0
* Python version:2.7.6
* Operating System:ubantu 14.04

### Description erro:
when I  run" recognize_faces_in_pictures.py"
gnss523@gnss523:~/Desktop/face_recognition-master/examples$ python find_faces_in_picture.py 
Illegal instruction (core dumped)

how to slove erro
thanke you very much

**Comment by visionanand** [comment]
Check out the solution suggested for Issue #11

**Comment by ageitgey** [comment]
Thanks for responding @abala003. I'm going to add a "Common Issues" section to the README to cover this.
