### ISSUE TITLE
Issues on raspberry pi zero w

### ISSUE THREAD

**Issue by zodiac1214** [ageitgey/face_recognition#240]
* face_recognition version: latest
* Python version: 3.5
* Operating System: Raspbian

### Description

I am trying to install this project on my raspberry zero. After i build those C code and pip3 install this library, i tried to run the sample code. However, I got "Ilegal Aruguments" error messages. This sounds like there is something wrong with the C lib I build. But I am not sure where it went wrong. Also, running python directly and a simple import of this library will give me the same error.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by ageitgey** [comment]
Can you paste the full error message?

In any case, I'm not sure the RPi Zero is powerful enough to run this but I've never tried.

**Comment by zodiac1214** [comment]
I figured it out. I found the problem is dlib and after so Google I managed
to install dlib and your library is working now. Like you said,  pi zero is
not powerful enough. I am only interested in face detection for now. And I
have to resize the image to 240p which still take 5s to find a face. My
plan is to push the full 1080p image to a different server and analyze
there when 240p image says there is a face. So not real time but quite close

**Comment by ageitgey** [comment]
Great, glad you figured it out!

**Comment by ToxaIvchenko** [comment]
@zodiac1214 I'm getting "Illegal instruction" on my pi zero w, how did you fix that?

**Comment by ageitgey** [comment]
I don't think you'll be able to use this on a Pi Zero. It's just not powerful enough.

**Comment by ToxaIvchenko** [comment]
@ageitgey Thank you, will try to recompile without Neon (pretty sure you're right about performance, just want to test it)
