### ISSUE TITLE
 imread() got an unexpected keyword argument 'mode'

### ISSUE THREAD

**Issue by johnwanggithub** [ageitgey/face_recognition#242]
* face_recognition version: 1.0.0
* Python version: 2.7
* Operating System: mac EI Capitan 10.11.6

### Description
after install the face_recognition, I tried to run examples/facerec_from_webcam_faster.py, but it show error as following:

Traceback (most recent call last):
  File "/Users/johnwang/workspace/PycharmProjects/Demo1/Face_Recognizer.py", line 18, in <module>
    obama_image = face_recognition.load_image_file("obama.jpg")
  File "/Library/Python/2.7/site-packages/face_recognition/api.py", line 81, in load_image_file
    return scipy.misc.imread(file, mode=mode)
TypeError: imread() got an unexpected keyword argument 'mode'

and I checked the scipy version and tried to upgrade, and scipy version which I installed is already 1.0.0
johns-MacBook-Pro:kaggle johnwang$ pip install --upgrade scipy
Requirement already up-to-date: scipy in /Library/Python/2.7/site-packages
Requirement already up-to-date: numpy>=1.8.2 in /Library/Python/2.7/site-packages (from scipy)

could you help on this problem? thanks in advance.

**Comment by johnwanggithub** [comment]
This issue has been solved by reinstall scipy to a specific target:  
sudo pip install scipy --upgrade --target="/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/"

hope it helps who meet the same issue.

**Comment by ageitgey** [comment]
Thanks!
