### ISSUE TITLE
Only PNG Images are being compared. No results are being produced if the images are in JPG format.

### ISSUE THREAD

**Issue by Sukrit-Mehta** [ageitgey/face_recognition#246]
* face_recognition version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by ageitgey** [comment]
You need to attach some sample files to reproduce this or a log of the error messages you are getting. I can't help just from a title alone.

**Comment by Sukrit-Mehta** [comment]
Ok Sure.
