### ISSUE TITLE
Random freezing of 'obama_face_encoding' on raspberry pi

### ISSUE THREAD

**Issue by abhiTronix** [ageitgey/face_recognition#253]
* face_recognition version:Latest
* Python version:2.7.13
* Operating System:Raspbian stretch
* Dlib version: 19.7.99 (with neon support)
* Scipy version: 0.17.0

### Description

 Hello everyone ,i'm testing 'obama_small image' on my raspberry pi 3 for facial recognition, my Raspberry pi CPU is randomly getting pegged at 100% when  'obama_face_encoding' is getting executed .....and moreover python get stuck with 80% CPU usage (Sometimes 100%) when i force stop the process 'obama_face_encoding' and therefore had to kill it manually!!!.

### What I Did
Here is my test code:
`import face_recognition`
`obama_image = face_recognition.load_image_file("home/pi/obama_small image")`
`print('1')`
`obama_face_encoding = face_recognition.face_encodings(obama_image)[0]`
`print('2')`

### Here is what i get : (Output)
`1`
not '2' and it happens randomly ..... sometimes i get '2' and sometimes don't ...... Moreover i have to kill process to end this by pressing 'Ctrl+Z' when this happens and therefore further results in CPU juggling at 80-100% and python freezes too, and have to reboot system in the end :(

### Trace captured during this problem : 
[output.txt](https://github.com/ageitgey/face_recognition/files/1534246/output.txt)

any help is greatly appreciated :)

**Comment by abhiTronix** [comment]
#119 I was able to create stable openCV with (TBB+NEON+VFPV3) with latest TBB and openCV for my Rpi3 ,after 15 days of debugging and compiling .
 Today,I self-compiled latest TBB(2018-Update 2) from source and compiled with latest openCV(3.3.1 -dev) and everything is just awesome with significant 30 % increase in performance :) ...also i recompiled 
my dlib with better flags , hence now `face_encodings` is just consuming only 25% of my cpu at size of image whatsoever and same for webcam too .
Anyone who want all precompiled .deb Latest `OpenCV` with (`TBB`+`NEON`+`VFPV3`) Support for Raspberry pi 3 can head over to  @my github repositories .

**Comment by xoul** [comment]
I can't find the .deb package at the suggested address, @abhiTronix. :)
Moreover, I've managed to solve the same problem just adding some swap space or resizing the image (maybe using Image.thumbnail() from Pillow) before loading it within face_recognition.

**Comment by abhiTronix** [comment]
Thank you mate for showing interest,
With due respect, As I'm an independent A.I Researcher &  I've spent a lot
of time(nearly months) and hardwork into his project,  I've recently  made
all .deb files private and only accessible to selected users only.
Anyone who want to access to those files can email me abhi.una12@gmail.com
and help me in building future projects like this, in return I'll make
those file available to you and maybe make them public hopefully in future
☺️.
Regards
AbhiTronix
