### ISSUE TITLE
Using All available CPU for camera face detection

### ISSUE THREAD

**Issue by MyraBaba** [ageitgey/face_recognition#254]
Hi,

For camera face detection look slow (faster mod is low for accuracy) .
It is using only one cpu . 

How we are going to improve speed for realtime camera detection...?

Thx

**Comment by MyraBaba** [comment]
Any idea how we can say to dlib :) to use all available CPU . ?

**Comment by ageitgey** [comment]
Please see some of the closed issues that discuss this like #151

**Comment by MyraBaba** [comment]
Is this a Dlib issue to speeding up camera face detection (look like most of the cpu spend here)?

or it has to be a single cpu for face detection ?
