### ISSUE TITLE
How Face Recognition get full benefits from the ALL CPU and CORES ? 

### ISSUE THREAD

**Issue by MyraBaba** [ageitgey/face_recognition#258]
I am working on the python face_recognition (both hog and cnn) and I couldnt find a way to use all my 8 cores cpu to fasten the face detection and recognition. It is alway using 1 cpu.

I dig a little bit on the Dlib compiling with BLAS and has no improvement. 

My Environment is : Mac book Pro i7 2017 8 cores .

Is there any one that can find a way to use all available cpu for faceRecognition ? Otherwise its really slow

Or may be it is impossible to use ALL Cores/cpus . only we can get help from GPU

Any idea, any direction or any past experience ?

Thanks

**Comment by ageitgey** [comment]
Keep in mind this is more a Python / parallel programming question than a question specifically about this library.

Have you looked at the source code to the cli.py file here? 

https://github.com/ageitgey/face_recognition/blob/master/face_recognition/cli.py#L68-L89

It shows how to run face detection on multiple cores in parallel using multiple processes.

You can also check out my article on the topic here: https://medium.com/@ageitgey/quick-tip-speed-up-your-python-data-processing-scripts-with-process-pools-cf275350163a

**Comment by MyraBaba** [comment]
I will look them again.

We are trying to utile live camera feed. And mot of the time consumed by the Face_Detection. It is coming from Dlib I think. In that case dividing the frame ie 8 pieces and using the process is a good idea ?

**Comment by ageitgey** [comment]
That could work. The risk is that you might miss faces that get cut in half at the boundaries though. So that might not be the best solution without finding creative ways to work around that problem.

Another idea would be to save each frame into a list and pass out frames from the list to different CPUs as they can handle the work. The tricky part would be to make sure you keep the frames in the right order when you display the result.

**Comment by MyraBaba** [comment]
Do you think it useful and a good starting point reading the frame directly without blocking IO Like in your fps_demo.py.


Best

**Comment by ageitgey** [comment]
What is fps_demo.py?

**Comment by MyraBaba** [comment]
https://www.pyimagesearch.com/2015/12/21/increasing-webcam-fps-with-python-and-opencv/ <https://www.pyimagesearch.com/2015/12/21/increasing-webcam-fps-with-python-and-opencv/>

**Comment by ageitgey** [comment]
Oh. That's not written by me. Adrian is a friend of mine, but that's not my website :)

**Comment by MyraBaba** [comment]
Good point :) 


All for one, one for ALL. :))

If I succeed to find a solution will post here.

Best

**Comment by MyraBaba** [comment]
I found this paper. https://arxiv.org/ftp/arxiv/papers/1508/1508.01292.pdf <https://arxiv.org/ftp/arxiv/papers/1508/1508.01292.pdf> 	at  https://github.com/cmusatyalab/openface/issues/85 <https://github.com/cmusatyalab/openface/issues/85> 

I try to work on it. I says 28fps at 4K, 54fps at 1080p…


Best
