### ISSUE TITLE
dlib configuration error on Ubuntu

### ISSUE THREAD

**Issue by lambaaada** [ageitgey/face_recognition#26]
* face_recognition version:  11ee1ea  
* Python version: 3.4
* Operating System: Ubuntu 14.04.5

After trying everything to install this on windows 7 I gave up and made on a virtual machine a Linux Ubuntu system.

I tried on the terminal the following steps in the order I write them:
pip3 install face_recognition
--ERROR--
sudo apt-get install python3-pip
pip3 install face_recognition
--ERROR--
sudo apt-get install libboost-all-dev
sudo apt-get update
sudo apt-get install git
git clone https://github.com/davisking/dlib.git
cd dlib
mkdir build
 cd build
 cmake .. -DDLIB_USE_CUDA=0 -DUSE_AVX_INSTRUCTIONS=1;
--ERROR--
sudo apt-get install cmake
sudo apt-get upgrade
--EXIT Terminal and reenter to start from main path --
cd dlib
cd build 
cmake .. -DDLIB_USE_CUDA=0 -DUSE_AVX_INSTRUCTIONS=1
cmake --build .
cd ..
python3 setup.py install --yes USE_AVX_INSTRUCTIONS --no DLIB_USE_CUDA
-- NO PERMISSION ERROR --
sudo python3 setup.py install --yes USE_AVX_INSTRUCTIONS --no DLIB_USE_CUDA
-- ERROR -- 

The final error I got was:
![ubu error 1](https://cloud.githubusercontent.com/assets/26509613/24292741/adacbeee-109f-11e7-99eb-e0452f6af574.jpg)

![ubu error 2](https://cloud.githubusercontent.com/assets/26509613/24292754/b8f204d0-109f-11e7-8031-94cd5b6c2fe3.jpg)

**Comment by lambaaada** [comment]
P.S.
Do you think I could work the Windows 7 problem by using the same commands on your linux installation tutorial but on chocolatey with Cmder?
https://superuser.com/questions/947220/how-to-install-packages-apt-get-install-in-windows

**Comment by lambaaada** [comment]
I figured out the solution to the problem I presented!!
I'll write here the lines needed to fix it so other people like me will finally be able to use this,
write these lines instead of installing cmake, I did it right after installing git:

sudo apt-get install software-properties-common
sudo add-apt-repository ppa:george-edison55/cmake-3.x
sudo apt-get update
sudo apt-get install cmake
sudo apt-get upgrade

**Comment by lambaaada** [comment]
Also I am still experiencing problems...
I can't import dlib..
nor can I import face_recognition it says theres no scipy module...

**Comment by ageitgey** [comment]
The solution for the `Illegal Instruction` issue is covered here in the README: 

https://github.com/ageitgey/face_recognition#issue-illegal-instruction-core-dumped-when-using-face_recognition-or-running-examples

So please make that change and recompile `dlib` to fix that first problem.

Second, `scipy` is a dependency of `face_recognition`, so I'm not sure how you were able to install `face_recognition` without first installing `scipy`. But you should be able to install scipy just by running `pip3 install scipy` (or if you are using python 2.x, `pip2 install scipy`).

**Comment by lambaaada** [comment]
I changed that line in the file and it still has the same result error Illegal instruction (core dumped).

The scipy issue I fixed

**Comment by ageitgey** [comment]
Did you recompile and reinstall dlib after making the change?

**Comment by Panxj** [comment]
@ageitgey I have installed dlib manually, and type import dlib successfully, but when i type pip install face_recognition ,there is still something wrong same with which before i install dlib

**Comment by lambaaada** [comment]
Yes the same error popped up when I changed the line after starting the machine from it's clean state (before any compiling and installation) and then compiling and installing.

**Comment by MauroMombelli** [comment]
arch linux as similar issue: 

```
Found PythonLibs: /usr/lib64/libpython3.6m.so (found suitable version "3.6.0", minimum required is "3.4")
```

this seems more an error on how dlib package is made, but i have no experience to where to look at.
