### ISSUE TITLE
What face_encodings() return supposed to mean?

### ISSUE THREAD

**Issue by esritines** [ageitgey/face_recognition#260]
* face_recognition version: 1.00
* Python version: 3.6
* Operating System: Windows 10 64 bit

### Description

When I print the result of face_encodings() method return an 128 float numpy array lenght, but what this supposed to mean?

How can I compare this with another 5000 results to verify if the person appears in my Data Base

**Comment by ageitgey** [comment]
1. To understand what the 128 numbers mean, read this: https://medium.com/@ageitgey/machine-learning-is-fun-part-4-modern-face-recognition-with-deep-learning-c3cffc121d78

2. To compare with 5000 results, one solution is to use a k-nearest-neighbors classifier like in #250. Another approach would be to store the encodings as rows in a database and do the euclidean distance calculation with sql like mentioned [here](https://github.com/ageitgey/face_recognition/issues/238#issuecomment-345847465).
