### ISSUE TITLE
Accurate of the API?

### ISSUE THREAD

**Issue by esritines** [ageitgey/face_recognition#261]
### Description
I am doing an assistance system, the validation of the assistance will be with a photo taken directly to the face in frontal position without the face being in an inclined direction.

The total people are 5000+, so the assistance must be accurate, without errors, without false-positive, this API will be sufficient with the methods you already have, or will have the need to implement an algorithm for the verification of assistance?

**Comment by ageitgey** [comment]
No face recognition system is 100% accurate and never has false positives. I certainly don't claim face_recognition never makes mistakes. You need to test it on your own data and draw your own conclusions for your specific use case.
