### ISSUE TITLE
Is it possible to add function like cv2.imwrite()?

### ISSUE THREAD

**Issue by lidh15** [ageitgey/face_recognition#263]
* face_recognition version:1.0.0
* Python version:3.6.3
* Operating System:ubuntu 16.04

OpenCV loads and saves image in BGR as default but face_recognition load it in RGB so it is not 
nicely compatible If there is a function which saves image in RGB than we can get rid of cv2.

**Comment by lidh15** [comment]
This is not a issue in fact.

**Comment by ageitgey** [comment]
You can use scipy.misc.imsave() or PIL to save images in RGB format without OpenCV.
