### ISSUE TITLE
Out of Memory when I recognize many images

### ISSUE THREAD

**Issue by kambeerhunter** [ageitgey/face_recognition#265]
* face_recognition version: 1.1.0 Latest
* Python version: 3.5
* Operating System: Ubuntu 16.04

### Description
I'm doing a web service based on django, which recognizes the face. I compress the photo and recognize the face using cnn. Everything works fine. But when I send several hundred files for processing one by one, such an error periodically appears

```
`Error while calling cudaMalloc(&data, n) in file /home/facer/dlib/dlib/dnn/cuda_data_ptr.cpp:28. code: 2, reason: out of memory`
```
In what there can be a reason and how it to correct?

**Comment by zhiyue** [comment]
I encountered the same problem. How did you solve that? @kambeerhunter

**Comment by X-YI** [comment]
I also encountered the same problem. How did you solve that? @kambeerhunter

**Comment by kambeerhunter** [comment]
@zhiyue @X-YI 
Hi. 
I changed the image resizing and began to send to the recognition of a photo with a width of no more than 800 pixels. I tested it on a server with a videocard of 8GB - there it worked.
That is, you can either reduce the size of the photo (the optimal size is selected manually) or add video memory, I did not find other solutions

**Comment by X-YI** [comment]
The image I used is 640*480 and have 1060Ti with about 1.5G VRam available and also face the same problem. Will the VRAM stop decreasing if I have more VRAM available? That sounds weird

**Comment by kambeerhunter** [comment]
To process a large number of images, with a maximum width of 1024 pixels, it took me 8GB VRAM
