### ISSUE TITLE
Not permited instruction

### ISSUE THREAD

**Issue by TurtleForGaming** [ageitgey/face_recognition#268]
* face_recognition version: face-recognition-1.0.0
* Python version: python2.7
* Operating System: Kali-Linux

### Description

I was tryng to start the program when I got "Instruction non permise" as an erro

### What I Did

```
root@Kali-Linux:~# face_recognition
Instruction non permise
```

**Comment by ageitgey** [comment]
Please see https://github.com/ageitgey/face_recognition/issues/11#issuecomment-287398611
