### ISSUE TITLE
Different input color space for the same network

### ISSUE THREAD

**Issue by GarrettLee** [ageitgey/face_recognition#271]
* face_recognition version: 0.1.0
* Python version: 2.7.6
* Operating System: Ubuntu 14.04

### Description

I found that in file  face_recognition/examples/facerec_from_webcam_faster.py, a picture of Obama is encoded as candidate, which is in RGB color space: https://github.com/ageitgey/face_recognition/blob/d4292a8fb2f795b9ebe265ffff2d38a5767ea349/examples/facerec_from_webcam_faster.py#L17
Then pictures are captured by OpenCV VideoCapture. Howerer, these pictures are in BGR color space:https://github.com/ageitgey/face_recognition/blob/d4292a8fb2f795b9ebe265ffff2d38a5767ea349/examples/facerec_from_webcam_faster.py#L28
Is it a mistake? Or does the color space makes no difference on the output feature?

**Comment by ageitgey** [comment]
Hi @GarrettLee, that's a great question. It's a mistake. There really should be a BGR -> RGB conversion on the frame that's passed in to face_recognition. Feel free to submit a PR or I'll do it when I have a second. Thanks!

**Comment by ageitgey** [comment]
Thanks again for the catch - adding a PR to fix it in #274
