### ISSUE TITLE
It does not recognize faces in some images

### ISSUE THREAD

**Issue by Pepepy** [ageitgey/face_recognition#272]
* face_recognition version: 1.0.0
* Python version: 3.5
* Operating System: Ubuntu 16.4

### Description

It happens that there are certain images in which it does not recognize the faces or recognizes more than one face having only one.
This usually happens with images of good quality.

Is there any way to solve this problem?

### What I Did

Reducing the size of some images manually I managed to recognize the face, but it does not work in all images.

**Comment by ageitgey** [comment]
You need to post example images that don't work in order for us to be able to try to help.  Thanks!
