### ISSUE TITLE
How to identify a small face? For example: 50 * 50 size of the human face

### ISSUE THREAD

**Issue by zengbing1992** [ageitgey/face_recognition#276]
When I enter a smaller face image, the program does not detect the key points, face_encodings function return the 128-dimension face encoding for each face in the image, and the size of the input image only 50 * 50 size

Connected to pydev debugger (build 172.3317.103)
Traceback (most recent call last):
  File "/home/zbing/Downloads/pycharm-2017.2/helpers/pydev/pydevd.py", line 1596, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/zbing/Downloads/pycharm-2017.2/helpers/pydev/pydevd.py", line 1023, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/zbing/deep-learning-12.24/face_recognition-master/examples/facerec_from_webcam_faster.py", line 20, in <module>
    obama_face_encoding = face_recognition.face_encodings(obama_image)[0]
IndexError: list index out of range

**Comment by ageitgey** [comment]
There is a `number_of_times_to_upsample=1` parameter. Setting it to a bigger number like 2 or 3 will make it find smaller faces but run more slowly. See https://face-recognition.readthedocs.io/en/latest/face_recognition.html#face_recognition.api.batch_face_locations

But even with that, 50x50 pixels is probably just too low resolution to work with at all.

**Comment by zengbing1992** [comment]
kay thank you. 50 * 50 pixel size is the size of the face, I can try the whole image is 100 * 100 pixel size
