### ISSUE TITLE
AttributeError: 'module' object has no attribute 'face_recognition_model_v1'

### ISSUE THREAD

**Issue by hemant-1332** [ageitgey/face_recognition#28]
* face_recognition version: 0.1.3
* Python version: Python 2.7.12
* Operating System: Ubuntu 16.04

### Description

when I am trying to import face_recognition module , it is displaying the below attribute error
even though model is available there
I suppose, dlib class "face_recognition_model_v1" is not taking the path of face_recognition_model or the face_recognition_model "dlib_face_recognition_resnet_model_v1.dat"
 is corrupted that is available here:  http://dlib.net/files/
 
### What I Did

```
>>> import face_recognition
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/face_recognition/__init__.py", line 7, in <module>
    from .api import load_image_file, face_locations, face_landmarks, face_encodings, compare_faces
  File "/usr/local/lib/python2.7/dist-packages/face_recognition/api.py", line 21, in <module>
    face_encoder = dlib.face_recognition_model_v1(face_recognition_model)
AttributeError: 'module' object has no attribute 'face_recognition_model_v1'
>>> import face_recognition_models
>>> face_recognition_model = face_recognition_models.face_recognition_model_location()
>>> print face_recognition_model
/usr/local/lib/python2.7/dist-packages/face_recognition_models/models/dlib_face_recognition_resnet_model_v1.dat

```

**Comment by ageitgey** [comment]
It looks like maybe you just have an old version of dlib installed. What version of dlib does pip report that you have?

**Comment by hemant-1332** [comment]
I have the latest version of dlib, ie, 19.04

**Comment by hemant-1332** [comment]
Thanks.
Problem has been resolved. 
Actually I had installed the previous version (18.xx) from source directory. Then I installed the latest version using pip. So both versions were there, and face_recognition module was accessing older version. After removing the older version, problem is resolved.

**Comment by ageitgey** [comment]
Cool, glad that solved it.
