### ISSUE TITLE
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all() in match[0] in facerec_from_webcam_faster.py

### ISSUE THREAD

**Issue by padmalcom** [ageitgey/face_recognition#281]
* face_recognition version: 1.0.0
* Python version: 2.7.13
* Operating System: CentOS 7

### Description

I tried to get the example running but whenever a match occurs I receive the error:

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

This makes sense since match[0] is an array with boolean values.

**Comment by ageitgey** [comment]
Did you edit the example at all? Can you provide any more detail? match[0] shouldn't be an array.

**Comment by padmalcom** [comment]
Sorry for the late reply, I declared a variable with the same name twice. A rename solved the issue.
