### ISSUE TITLE
Hello, Dear contributor, we want some example code for LFW accuracy test.

### ISSUE THREAD

**Issue by Heermosi** [ageitgey/face_recognition#284]
* face_recognition 0.1.12:
* Python 3.7 with Anaconda:
* Operating System: Windows 7

### Description

My college is going to verify the accuracy on LFW face sets, but she cannot find an instruction for testing.
Could you please append some code for LFW verification?

### What I Did

I knew it was a strange request, but there is no way to change her mind. I've provided her with some example codes, but it was no use. I think you should officially release something so that she can believe it.

**Comment by ageitgey** [comment]
I don't have any test code for the LFW dataset available right now. But it shouldn't be too hard to code if you download the LFW dataset and try it.

In any case, I think it's best to test the accuracy on the kind of data you actually want to use it with.
