### ISSUE TITLE
not recognizing people with glasses

### ISSUE THREAD

**Issue by yansouf** [ageitgey/face_recognition#285]
* face_recognition version: 3.5.2
* Python version: i installed it from pip so i guess the latest
* Operating System:Windows 10 

### Description
face_recognition.compare_faces() function  can't recognize people wearing glasses 
i  tested that with 2 photos of walter white  

![bryan cranston](https://user-images.githubusercontent.com/35151035/34628080-03aeab52-f25b-11e7-8094-98cc8e219a1a.jpg)
![2breaking bad](https://user-images.githubusercontent.com/35151035/34628098-0d83efac-f25b-11e7-8b1e-3aa59070c908.jpg)

### What I Did
i tried playing around with tolerance but one higher than 0.5 gives me tons of false positives

**Comment by yansouf** [comment]
guess my question so dumb it's not worth answering  ,got it

**Comment by ageitgey** [comment]
I don't really have an answer to your question. It's possible that it doesn't work well for people wearing glasses.

But keep in mind that the two pictures at the bottom are quite small and may be heavily retouched (photoshopped) since they are promotional material. That could throw things off. You might have better luck with more natural pictures - not sure.

**Comment by yansouf** [comment]
Thanks man i didn't even think of the pictures being retouched  , I
appreciate the help .

**Comment by vrushang25** [comment]
I am working in face recogniton with using the web camera and i am facing below problem. My Face is recognized same as my brother's face. I tried to reduce the tolerance to the 0.55 but no effect. what should i do?
--

**Comment by ageitgey** [comment]
@vrushang25 Please don't post unrelated questions on old issues. No one will see them there. 

To answer your question, it's possible you and your brother look very similar and maybe you two don't look that much like anything in the original training data so it isn't able to tell you two apart. I don't have a simple fix for you.
