### ISSUE TITLE
Blur Faces - Proposed Feature

### ISSUE THREAD

**Issue by EricRoche** [ageitgey/face_recognition#286]
Proposed Function - Blur Faces

This program could be useful for organizations that take many photos of public buildings, but accidently capture people's faces in them. In order to protect their privacy, these images could use the `face_recognition` code to batch detect, blur, and overwrite the image repository so that privacy is protected with little additional work.

**Comment by ageitgey** [comment]
Good idea!

You can do this easily with the existing functions and a one-line call to OpenCV. I'll upload an example script.

**Comment by ageitgey** [comment]
Here you go!

https://github.com/ageitgey/face_recognition/blob/master/examples/blur_faces_on_webcam.py
