### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by salamer** [ageitgey/face_recognition#29]
* face_recognition version:latest
* Python version:2.7
* Operating System:Mac

### Description

I just installed your great project, and run the example([foo](https://github.com/ageitgey/face_recognition/blob/master/examples/find_faces_in_picture.py))
but I got the `Segmentation fault: 11`

```
aljundeMacBook-Pro-2:face_reco aljun$ python foo.py 
Segmentation fault: 11
```
I have already installed the `boost` and the `python-boost` on my Mac

**Comment by ageitgey** [comment]
I'm not sure. I can't tell from that information what's going on. But you could try out this VM instead: https://medium.com/@ageitgey/try-deep-learning-in-python-now-with-a-fully-pre-configured-vm-1d97d4c3e9b
