### ISSUE TITLE
image encoding now recover after fetch from mongo database

### ISSUE THREAD

**Issue by ladwani** [ageitgey/face_recognition#293]
* face_recognition version:latest
* Python version:3.6
* Operating System:linux 16.04

### Description
i want to compair the single image with the other images.
for that i save the image encoding to the database,
but when i retreve the encoding form image it looks like thats
==image encoding==
('recipient_img', u'[array([ -1.92452788e-01,   1.35731220e-01,   7.20449761e-02,\n        -1.42494626e-02,  -1.10356227e-01,   4.17054668e-02,\n         3.13804485e-03,  -1.30087975e-03,   1.84923485e-01,\n        -4.71941903e-02,   1.34456679e-01,   3.08692753e-02,\n        -2.19481245e-01,   2.40990147e-02,  -2.33508423e-02,\n         1.00501731e-01,  -2.57203817e-01,  -3.14865522e-02,\n        -5.74340895e-02,  -8.26097652e-02,   1.07494751e-02,\n         7.17826039e-02,   5.37376553e-02,   4.45164479e-02,\n        -9.74944308e-02,  -3.63109857e-01,  -9.17103961e-02,\n        -1.57477796e-01,   1.40656844e-01,  -8.37804824e-02,\n         6.26444370e-02,  -2.68916041e-03,  -1.22880690e-01,\n        -9.52668302e-03,  -4.16824222e-02,   3.98224369e-02,\n        -1.21855279e-02,  -6.66880384e-02,   1.96788296e-01,\n        -1.40978042e-02,  -1.34568319e-01,   2.18121223e-02,\n         3.29566225e-02,   3.40473503e-01,   1.21492304e-01,\n         1.77914649e-02,   5.08632436e-02,  -3.58551368e-02,\n         1.55000344e-01,  -2.99984515e-01,   6.49604797e-02,\n         1.08361036e-01,   6.03830256e-02,   7.08700866e-02,\n         4.96200919e-02,  -1.67863458e-01,   8.00541639e-02,\n         1.33427262e-01,  -2.70875990e-01,   1.65902004e-01,\n         1.02901034e-01,  -1.21990144e-02,  -3.41780968e-02,\n         3.45560275e-02,   2.15608999e-01,   1.72827721e-01,\n        -1.32720560e-01,  -1.77362666e-01,   7.04866946e-02,\n        -2.05314025e-01,   3.10022030e-02,   1.45127043e-01,\n        -9.62140262e-02,  -1.85786068e-01,  -2.11299568e-01,\n         8.62439573e-02,   5.22486150e-01,   2.11898565e-01,\n        -1.28719345e-01,  -4.06402051e-02,  -1.08205482e-01,\n        -4.96541187e-02,   1.22242495e-01,   1.54299080e-01,\n        -1.34352311e-01,  -5.10181002e-02,  -1.17531702e-01,\n         8.37546960e-02,   1.45621330e-01,   5.54079823e-02,\n        -8.63621160e-02,   2.30020046e-01,   1.25539169e-01,\n         2.70106532e-02,  -2.36887746e-02,   6.52919635e-02,\n        -1.40974641e-01,  -4.37774584e-02,  -9.19075981e-02,\n        -2.69548222e-02,   3.79491746e-02,  -4.98328358e-02,\n        -2.26468369e-02,   7.44687766e-02,  -1.56430870e-01,\n         2.82724530e-01,  -4.19707038e-04,  -2.95608621e-02,\n        -4.03616298e-03,   7.27141369e-03,  -5.29306754e-02,\n         6.86958432e-02,   1.89217016e-01,  -2.56033659e-01,\n         1.67912304e-01,   1.69388860e-01,   2.73276288e-02,\n         1.93836942e-01,   1.20813269e-02,   6.91201538e-02,\n        -1.83065049e-02,  -4.58458252e-03,  -1.33325875e-01,\n        -5.24575934e-02,   2.05329768e-02,  -1.05276749e-01,\n         7.55361170e-02,  -1.52133564e-02])]')

so how can i recover the original format of image encoding while fetching that encoding from database.
how i remove the \n and convert the original form of image encoding so that i compair that and find the face distance...thanks in advance..
i want this type of encoded data after fetching from database 
[ -1.92452788e-01   1.35731220e-01   7.20449761e-02  -1.42494626e-02
  -1.10356227e-01   4.17054668e-02   3.13804485e-03  -1.30087975e-03
   1.84923485e-01  -4.71941903e-02   1.34456679e-01   3.08692753e-02
  -2.19481245e-01   2.40990147e-02  -2.33508423e-02   1.00501731e-01
  -2.57203817e-01  -3.14865522e-02  -5.74340895e-02  -8.26097652e-02
   1.07494751e-02   7.17826039e-02   5.37376553e-02   4.45164479e-02
  -9.74944308e-02  -3.63109857e-01  -9.17103961e-02  -1.57477796e-01
   1.40656844e-01  -8.37804824e-02   6.26444370e-02  -2.68916041e-03
  -1.22880690e-01  -9.52668302e-03  -4.16824222e-02   3.98224369e-02
  -1.21855279e-02  -6.66880384e-02   1.96788296e-01  -1.40978042e-02
  -1.34568319e-01   2.18121223e-02   3.29566225e-02   3.40473503e-01
   1.21492304e-01   1.77914649e-02   5.08632436e-02  -3.58551368e-02
   1.55000344e-01  -2.99984515e-01   6.49604797e-02   1.08361036e-01
   6.03830256e-02   7.08700866e-02   4.96200919e-02  -1.67863458e-01
   8.00541639e-02   1.33427262e-01  -2.70875990e-01   1.65902004e-01
   1.02901034e-01  -1.21990144e-02  -3.41780968e-02   3.45560275e-02
   2.15608999e-01   1.72827721e-01  -1.32720560e-01  -1.77362666e-01
   7.04866946e-02  -2.05314025e-01   3.10022030e-02   1.45127043e-01
  -9.62140262e-02  -1.85786068e-01  -2.11299568e-01   8.62439573e-02
   5.22486150e-01   2.11898565e-01  -1.28719345e-01  -4.06402051e-02
  -1.08205482e-01  -4.96541187e-02   1.22242495e-01   1.54299080e-01
  -1.34352311e-01  -5.10181002e-02  -1.17531702e-01   8.37546960e-02
   1.45621330e-01   5.54079823e-02  -8.63621160e-02   2.30020046e-01
   1.25539169e-01   2.70106532e-02  -2.36887746e-02   6.52919635e-02
  -1.40974641e-01  -4.37774584e-02  -9.19075981e-02  -2.69548222e-02
   3.79491746e-02  -4.98328358e-02  -2.26468369e-02   7.44687766e-02
  -1.56430870e-01   2.82724530e-01  -4.19707038e-04  -2.95608621e-02
  -4.03616298e-03   7.27141369e-03  -5.29306754e-02   6.86958432e-02
   1.89217016e-01  -2.56033659e-01   1.67912304e-01   1.69388860e-01
   2.73276288e-02   1.93836942e-01   1.20813269e-02   6.91201538e-02
  -1.83065049e-02  -4.58458252e-03  -1.33325875e-01  -5.24575934e-02
   2.05329768e-02  -1.05276749e-01   7.55361170e-02  -1.52133564e-02]

**Comment by ladwani** [comment]
plz guide me..as soon as possible

**Comment by ageitgey** [comment]
I think this is really a mongodb question, not a question about this library. You are probably storing the data in mongo incorrectly as a string instead of as an object. This library doesn't add line breaks to the output data or anything like that.

**Comment by ladwani** [comment]
while insert the image encoding into mongo database.m not making image coding into string
but while retreve image encoding its  adds /n nd all...how can i recover ?

**Comment by DishinGoyani** [comment]
Same issue i faced when i try to store image_encoding and image_name in to .csv file.

**Comment by MLDSBigGuy** [comment]
use a wrapper around numpy arrays ?
