### ISSUE TITLE
Recognition in Groups

### ISSUE THREAD

**Issue by infinityslayer52** [ageitgey/face_recognition#296]
* face_recognition version: latest(as of January 11th,2018)
* Python version: 3.6
* Operating System: Windows 10

### Description

Not much of an issue as much as a query. Is this api able to recognize a specific individual in a group of people? If not, what do you suggest can be done to make this happen?

**Comment by AlainPilon** [comment]
Yes. You can submit a picture with multiple people and it will (try to) recognize the people it already knows the encoding for. 

Look in the doc, that is what the Obama example does.
