### ISSUE TITLE
Match single image with multiple image faster

### ISSUE THREAD

**Issue by dhavalpadshala** [ageitgey/face_recognition#298]
* face_recognition version: 3
* Python version: 3.6
* Operating System: Ubuntu 14

### Description

Hello i want to match an single image from url of another domain and compare with my entire directory and want result in sorting by Priority of matches.
Can You Help Me do this?

### What I Did

i try using this type of commands
face_recognition --show-distance true ./pictures_of_people_i_know/ ./unknown_pictures/

Please reply me answer as soon as possible.

**Comment by ageitgey** [comment]
This is a tool and a programming library. It's mean to be taken and used to solve these kinds of problems, but it's not meant to solve every use case directly out of the box. So it's up to you to take it and use it in the exact way you want.

You could probably solve this by using the `curl` tool to grab the image from the url into a folder, running that command, and then using the `sort` unix command with the `cut` unix command to sort it the way you want. But it's up to you to figure that out depending on your exact use case :)

Of course if anyone else is trying to do the exact same thing, they might be willing to jump in and tell you how they did it exactly.

**Comment by dhavalpadshala** [comment]
Thanx @ageitgey  for your replay.
I try this to solve this as say it is much difficult for me.
