### ISSUE TITLE
facerec_from_webcam.py : runtime error: unsupported image type, must be 8bit gray or rgb image

### ISSUE THREAD

**Issue by dkmerona** [ageitgey/face_recognition#299]
* face_recognition version: dlib 19.8
* Python version: 3.5.3
* Operating System: raspbian 4.9.59-v7

### Description

i've followed the install procedure except the version of dlib.
I 've successfully install cv2 version 3.3.0
Then when running facerec_from_webcam.py i have the run time error 

![image](https://user-images.githubusercontent.com/30391054/34844018-643ab060-f710-11e7-8b61-4543d157ba78.png)

will be happy for any help . Thanks in advance.

**Comment by ageitgey** [comment]
Check out the answer here under "Common Issues":  https://github.com/ageitgey/face_recognition#common-issues

**Comment by dkmerona** [comment]
thanks will give a look.
 
 
 
 
> Message du 11/01/18 22:24> De : "Adam Geitgey" > A : "ageitgey/face_recognition" > Copie à : "dkmerona" , "Author" > Objet : Re: [ageitgey/face_recognition] facerec_from_webcam.py : runtime error: unsupported image type, must be 8bit gray or rgb image (#299)> >
> Check out the answer here under "Common Issues": https://github.com/ageitgey/face_recognition#common-issues
—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.



{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ageitgey/face_recognition","title":"ageitgey/face_recognition","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ageitgey/face_recognition"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ageitgey in #299: Check out the answer here under \"Common Issues\": https://github.com/ageitgey/face_recognition#common-issues"}],"action":{"name":"View Issue","url":"https://github.com/ageitgey/face_recognition/issues/299#issuecomment-357065818"}}}

**Comment by dkmerona** [comment]
OK. I followed the instruction, build the ffmpeg lib, rebuild opencv and no more run time error :-)
 
 
 
 
 
> Message du 11/01/18 22:24> De : "Adam Geitgey" > A : "ageitgey/face_recognition" > Copie à : "dkmerona" , "Author" > Objet : Re: [ageitgey/face_recognition] facerec_from_webcam.py : runtime error: unsupported image type, must be 8bit gray or rgb image (#299)> >
> Check out the answer here under "Common Issues": https://github.com/ageitgey/face_recognition#common-issues
—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.



{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ageitgey/face_recognition","title":"ageitgey/face_recognition","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ageitgey/face_recognition"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ageitgey in #299: Check out the answer here under \"Common Issues\": https://github.com/ageitgey/face_recognition#common-issues"}],"action":{"name":"View Issue","url":"https://github.com/ageitgey/face_recognition/issues/299#issuecomment-357065818"}}}

**Comment by ageitgey** [comment]
Great!
