### ISSUE TITLE
Why not openface

### ISSUE THREAD

**Issue by hhsecond** [ageitgey/face_recognition#30]
Your renowned and well written blog post is using about OpenFace in the example section (Thank you so much for that). Is there a particular reason, you are using dlib's face encoder instead of openface's? Have you got a chance to compare the performance?

**Comment by ageitgey** [comment]
OpenFace uses a mix of several programming languages and frameworks to run. That can make it difficult to deploy and use (in my opinion). The goal here was to make something much simpler to deploy and develop with. But both have their place.

I haven't extensively tested the accuracy of both libraries head to head, but both have performed well in my use cases. So it's more a matter of picking the right tool for the right job.

**Comment by hhsecond** [comment]
yes, thats absolutely true. Your package is kinda out-of-the-box compared to openface. It would be really great if you can keep a comparision/benchmarking with these two. I am writing a complete python only version of openface, so was just wondering if dlib already has comparable performance, its not worth spending time on openface python version. I'll also try to do some benchmarking as time allows. Thanks for the reply :+1:  
Cheers

**Comment by ageitgey** [comment]
In theory, the dlib model used here should be similar to or  slightly more accurate than OpenFace, but I have no real numbers to back that up. It also depends on the specific training set used for both models. I.e. you might get slightly better results if you trained your own model from scratch from a larger dataset instead of using the included models from either library.

**Comment by hhsecond** [comment]
Maybe I should spend more time on dlib before coding up openface-python. Thank you so much for the feedback. I'll keep you posted incase you are interested

**Comment by ageitgey** [comment]
Sure, I would be interested to hear how it goes. Closing this issue for now since the basic question is covered.
