### ISSUE TITLE
Question on Setting an Accuracy Threshold

### ISSUE THREAD

**Issue by Green-Wolf** [ageitgey/face_recognition#300]
I'm using face_recognition in a python tool i'm writing and I was wondering if there is a toggle or variable you can set that acts as a threshold. 

The problem i'm running into is there are images coming in sets of 10 and i compare them to an image i already have. I want to pick the one that is most likely to be correct, but its picking someone who looks similar before it gets to the correct image. Is there some sort of threshold you can like default is 50/100 and i could raise it to 70/100 or something like that?

Many thanks for the great library too!

**Comment by ageitgey** [comment]
Yep! It's called `tolerance`. It defaults to a 0.6 cut-off and lower numbers mean faces are more similar (so smaller numbers are better).

So one option is to pass in `tolerance=0.55` or whatever to `compare_faces()` to make it more sensitive:

http://face-recognition.readthedocs.io/en/stable/face_recognition.html#face_recognition.api.compare_faces

But in your case, it might be better to skip using `compare_faces()` at all and instead use the `face_distance()` function. That will just give you the measurement of how close each face is to the one you are checking:

http://face-recognition.readthedocs.io/en/stable/face_recognition.html#face_recognition.api.face_distance

Then you can pick the one with the lowest number as your match.

If you are using the CLI interface, there are similar command line options for setting and displaying the threshold.

**Comment by Green-Wolf** [comment]
Nvm solved it. For anyone else that comes across this you can add a threshold value as the 3rd parameter on the compare_faces() function. 0.6 is the default and the lower you go the stricter is becomes. Its a balancing act on if you care more about matches or mistakes. 

Standard:
results = face_recognition.compare_faces([person_encoding], potential_person_encoding,0.6)
Strict(Killed my false positives, but also removed some legit results): 
results = face_recognition.compare_faces([person_encoding], potential_person_encoding,0.5)

**Comment by Green-Wolf** [comment]
Thanks @ageitgey, if i use face distance to pick the lowest, is it still possible to then use the threshold to make sure its above/below 0.6 to make sure its a matching face?

**Comment by Green-Wolf** [comment]
Oh i guess you would just do a final compare_faces on the best match. Thanks for the help! 👍

**Comment by ageitgey** [comment]
Sure, you can just check yourself that the value is <= 0.6 (or whatever threshold you decide on). 

All the `compare_faces()` function does is call `face_distance()` and then an `if` statement to check which faces are under the threshold. You can just do that check yourself if you have the face distances already.

**Comment by Heermosi** [comment]
@ageitgey By the way, I want to ask a question.
I'm using multiprocessing in python, but the child processes failed to initialize Cuda via the face_encoding.
Is there any way to bring it up in child processes? I've tested that the call to face_encoding is successful in the main process. How can I solve it?

**Comment by ageitgey** [comment]
@Heermosi Glad you solved it! But in the future if you want to ask a question, just file a new issue instead of commenting on an unrelated one :)

**Comment by saileshprem** [comment]
Hey @Heermosi can you please explain how you solved initializing CUDA in the child process? I'm facing the same issue and not really able to work it out! Thanks.

**Comment by bitxinyu** [comment]
> @ageitgey By the way, I want to ask a question.
> I'm using multiprocessing in python, but the child processes failed to initialize Cuda via the face_encoding.
> Is there any way to bring it up in child processes? I've tested that the call to face_encoding is successful in the main process. How can I solve it?
> 
> Also, I have tried to run 10 or more processes doing the similar thing via the terminal bash. It succeeded.
> 
> Here is the following error print
> 
> ` File "faceRecognitionMain.py", line 113, in imageProcessorDaemon IdentifyImageFromDataBase(frame, workFolder, featureSet, pathSet, labelSet, stdioLock, debug) File "faceRecognitionMain.py", line 32, in IdentifyImageFromDataBase unknown_face_encoding = face_recognition.face_encodings(drawingFace, known_face_locations=faceLocations) File "/usr/local/lib/python2.7/dist-packages/face_recognition/api.py", line 191, in face_encodings return [np.array(face_encoder.compute_face_descriptor(face_image, raw_landmark_set, num_jitters)) for raw_landmark_set in raw_landmarks] RuntimeError: Error while calling cudaGetDevice(&the_device_id) in file /home/lixiayu/dlib/dlib/dnn/gpu_data.cpp:178. code: 3, reason: initialization error None`
> 
> I'm sorry, this has been solved via a in-function call to import the face_recognition package

hi,@Heermosi ,could you tell me how you solved this problem? I searched in google but still have no way to solve it. Thanks

**Comment by nouxu1** [comment]
@Heermosi I use import face_recognition in the callable function to a process but nothing solved... The error is the same: initialization error
Is there Any one solve this error?
I tried all the possibilities to use face_recognition with cuda and multiprocessing, and all of them failed..

**Comment by bitxinyu** [comment]
> @Heermosi I use import face_recognition in the callable function to a process but nothing solved... The error is the same: initialization error
> Is there Any one solve this error?
> I tried all the possibilities to use face_recognition with cuda and multiprocessing, and all of them failed..

hi, @nouxu1, I have read the source code ,and found this code in  face_recognition/face_detection_cli.py.
`# macOS will crash due to a bug in libdispatch if you don't use 'forkserver'
    context = multiprocessing
    if "forkserver" in multiprocessing.get_all_start_methods():
        context = multiprocessing.get_context("forkserver")

    pool = context.Pool(processes=processes)`
there is a comment "macOS will crash due to a bug in libdispatch if you don't use 'forkserver".  I still use forkserver in ubuntu OS. and I solved it. you can try it.

**Comment by neerajram30** [comment]
> Yep! It's called `tolerance`. It defaults to a 0.6 cut-off and lower numbers mean faces are more similar (so smaller numbers are better).
> 
> So one option is to pass in `tolerance=0.55` or whatever to `compare_faces()` to make it more sensitive:
> 
> http://face-recognition.readthedocs.io/en/stable/face_recognition.html#face_recognition.api.compare_faces
> 
> But in your case, it might be better to skip using `compare_faces()` at all and instead use the `face_distance()` function. That will just give you the measurement of how close each face is to the one you are checking:
> 
> http://face-recognition.readthedocs.io/en/stable/face_recognition.html#face_recognition.api.face_distance
> 
> Then you can pick the one with the lowest number as your match.
> 
> If you are using the CLI interface, there are similar command line options for setting and displaying the tolerance.

It worked thanks for the help
