### ISSUE TITLE
Error happened when use cnn mode to recognize face

### ISSUE THREAD

**Issue by 139419qw** [ageitgey/face_recognition#302]
* face_recognition version:The latest
* Python version:2.7
* Operating System:Ubuntu 16.04

### Description

Try to use face_recognition in cnn mode, so I changed 

> def _raw_face_locations(img, number_of_times_to_upsample=1, model="hog"):

 into

> **def _raw_face_locations(img, number_of_times_to_upsample=1, model="cnn"):**

Then I get error below:

> Traceback (most recent call last):
>   File "/home/rnd/NewDisk/Project/faceRecognition/src/recognition.py", line 10, in <module>
>     face_1 = face_recognition.face_encodings(face_image)[0]
>   File "/usr/local/lib/python2.7/dist-packages/face_recognition/api.py", line 189, in face_encodings
>     raw_landmarks = _raw_face_landmarks(face_image, known_face_locations)
>   File "/usr/local/lib/python2.7/dist-packages/face_recognition/api.py", line 152, in _raw_face_landmarks
>     return [pose_predictor(face_image, face_location) for face_location in face_locations]
> TypeError: No registered converter was able to produce a C++ rvalue of type dlib::rectangle from this Python object of type mmod_rectangle

But I can use function below correctly

> face_locations = face_recognition.face_locations(image, number_of_times_to_upsample=0, model="cnn")

So, who can tell me what happened?Please

**Comment by ageitgey** [comment]
Are you saying you changed the source code of the library? You don't need to do that. Just call it like in the example: https://github.com/ageitgey/face_recognition/blob/master/examples/find_faces_in_picture_cnn.py
