### ISSUE TITLE
face detect is not work on the pictures which human's face is behind glass

### ISSUE THREAD

**Issue by Mrliuzh** [ageitgey/face_recognition#305]
* face_recognition version:face-recognition 1.0.0 face-recognition-models 0.3.0
* Python version:python 2.7.6
* Operating System:ubuntu 14.04

### Description

face detect is not work on the pictures which human's face is behind glass,just like detect face of vehicle driver

### What I Did
face_locations = face_recognition.face_locations(....)
detect a picture but  can not find any face. a person is driving  car in this picture.case of the windshield?

**Comment by ageitgey** [comment]
Maybe you can try the cnn model by passing in model="cnn"? Otherwise without example images, I can't really suggest anything.

**Comment by Mrliuzh** [comment]
i try the cnn model by 'face_locations = face_recognition.face_locations(image,model="cnn")'.but still get the result 'Found 0 face(s) in this photograph' when i print the 'len(face_locations)'. Is this means cnn model also can not detect the face of driver in car?

**Comment by Mrliuzh** [comment]
@ageitgey hi, i have a question that what's method to detect face the face_recognition use?what's the algorithm? have it use the skin detection?
