### ISSUE TITLE
LFW accuracy.

### ISSUE THREAD

**Issue by itkinai** [ageitgey/face_recognition#309]
* face_recognition version: 0.1.0
* Python version: 2.7.6
* Operating System: Ubuntu 14.04

### Description

I was check accuracy on LFW dataset, it is only 97.56 % , how to get 99.38% ?

**Comment by ageitgey** [comment]
I don't have an answer for you. You didn't provide any information on what you tested or how exactly you measured it. 

But in any case, I'd recommend just testing it for your specific use case and using whatever measurement is most applicable to your specific application. An abstract number doesn't really matter anyway if it doesn't work that well for your specific use case.

**Comment by itkinai** [comment]
The LFW benchmark has a specific evaluation protocol, which using for get comparative result from all participants. I used this protocol and get 97.56%.

**Comment by ageitgey** [comment]
What I mean is even though you followed a specific high-level protocol, it's hard to know if there were any bugs or subtle differences in the evaluation code without seeing the actual code you used. For example, maybe there's some difference in how the images were loaded (BGR vs RGB, image normalization, etc).

**Comment by itkinai** [comment]
I don't have some preprocessing because you provide function that use file path. I load files like this
i1 = face_recognition.load_image_file(file_path) 
and get a vector
v1 = face_recognition.face_encodings(i1)[0]
Then use evaluation protocol on vectors. I think that if you provide so high-level functions, therefore all preprocessing inside.

**Comment by kclch** [comment]
@itkinai How do you test the accuracy of the model on the LFW data set? Can you provide test code? thank you very much
