### ISSUE TITLE
how can I compare facial features?

### ISSUE THREAD

**Issue by almas123** [ageitgey/face_recognition#313]
Can I compare individual facial features in two different faces?

**Comment by ageitgey** [comment]
What do you mean exactly?

**Comment by almas123** [comment]
I need to look for similar facial features in other photographs, an example is to compare two noses to their similarity

**Comment by ageitgey** [comment]
This library doesn't do that. It only compares whole faces. But it does detect the location of facial features, so maybe you could use that to build something new to solve your use case.
