### ISSUE TITLE
Can you provide the reference articles of this project?

### ISSUE THREAD

**Issue by xiao543348405** [ageitgey/face_recognition#315]
Can you provide the reference articles of this project?

**Comment by ageitgey** [comment]
This library uses dlib. You can find more info here: http://blog.dlib.net/2017/02/high-quality-face-recognition-with-deep.html

It cites:
O. M. Parkhi, A. Vedaldi, A. Zisserman Deep Face Recognition British Machine Vision Conference, 2015.

**Comment by xiao543348405** [comment]
Thank you very much.

**Comment by kaskavalci** [comment]
Can you provide a reference for your own work as well? In my opinion it is also noteworthy.

**Comment by ageitgey** [comment]
I'm not an academic, so I don't really have a good citation to provide you. But you could just cite this git repo if you wanted. Some people have also [cited my face recognition article](https://scholar.google.com/scholar?oi=bibs&hl=en&cites=11379897746519453993&as_sdt=5).

**Comment by xiao543348405** [comment]
I have studied the articles related to this project.
thank you very much.
