### ISSUE TITLE
Face_rec api issue in Raspberry Pi 3 

### ISSUE THREAD

**Issue by oguzhankarabulut** [ageitgey/face_recognition#32]
* face_recognition version: latest
* Python version: 3.4.2
* Operating System: Raspian Jessie

Firstly thanks for excellent project sharing. I successfully installed to api my raspberry pi and its dependencies.  When i was trying in python idle, i took a error. It ıs showed at picture.

![issue](https://cloud.githubusercontent.com/assets/23421095/24514777/231f3048-157e-11e7-96f4-4955055f6134.jpg)

Do you have any suggestion about this error? 
 Regars

**Comment by ageitgey** [comment]
You need to upgrade your version of `scipy` to at least version 0.17.

[See here for more info](https://github.com/ageitgey/face_recognition/issues/6#issuecomment-287122632)

**Comment by mdmedley** [comment]
@oguzhankarabulut Are you sure you have the **latest** version of ```face_recognition``` because @ageitgey updated the ```install_requirements``` to enforce ```scipy>=0.17.0``` because if you do this might be a bug.

**Comment by oguzhankarabulut** [comment]
thanks @ageitgey it is solved.

**Comment by ageitgey** [comment]
Great!

**Comment by Peppexhio** [comment]
I can't update scipy on my raspi 3.. I receive a Pip error..

**Comment by mdmedley** [comment]
What is the pip error you're seeing?

**Comment by mdmedley** [comment]
@Peppexhio You should also open a new issue for this so if it's a new issue it's tracked separately.
