### ISSUE TITLE
what's the face_recognition.load_image_file() do for my picture?

### ISSUE THREAD

**Issue by Mrliuzh** [ageitgey/face_recognition#321]
* face_recognition version:1.0.0
* Python version:2.7.6
* Operating System:ubuntu 16.04

### Description
i'm just confused with what's the 'face_recognition.load_image_file()' do for my picture.
the color of picture is different compare to original picture after 'load_image_file()'
Is the ' face_recognition.load_image_file()' changes my picture to gray picture or other types?

### What I Did
face_recognition.load_image_file() changes the color of my picture

**Comment by ageitgey** [comment]
It's supposed to just load an image file from disk into a numpy array. Any other method of loading a file into a numpy array is fine too.

If you see any problems that you can reproduce, please feel free to share them! Thanks!
