### ISSUE TITLE
Accuracy of the recognition?

### ISSUE THREAD

**Issue by Meghanaasreevatsa** [ageitgey/face_recognition#322]
* face_recognition version:
* Python version:
* Operating System:

### Description

When images were saved and code was run i had issues with accuracy my friends face and my face had were displaying same name .
Accuracy is an issue it doesn't give 99% accuracy
### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by AlainPilon** [comment]
Look in the closed tickets, may people have made the same comment. It is most likely because your faces look more like each other than they do to the training set. 

But given the fact that you did not provide any sample images, it is only a guess.

**Comment by yuen33** [comment]
I tried my photo as reference, but other people like my dad and my friend in same gender will be regarded as me...

**Comment by Meghanaasreevatsa** [comment]
i tried with my photo and one of my friends and tried with a single image given to it as it wouldn't go to the training set and compare . It just takes the image and tries to compare is what i could infer please tell me if i'm wrong also.

**Comment by Meghanaasreevatsa** [comment]
Had another question for each comparison how many frames does it require and what is the clock cycle that i should take for each comparison to happen given my processor is 1.60ghz
