### ISSUE TITLE
question about example

### ISSUE THREAD

**Issue by heyueyuan** [ageitgey/face_recognition#323]
* face_recognition version:
* Python version:
* Operating System:

### Description
your example is about two persons to recognize them, but your code is just about Obama. I try to use a list for names, but I got failed, so could you please give me an example of how to make more people be recognized, if you can, I will appreciate.

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.
IMPORTANT: If your issue is related to a specific picture, include it so others can reproduce the issue.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by heyueyuan** [comment]
import cv2
import face_recognition

names = ["catherine","william",]
images = []

for name in names:
	filename = name +".jpg"
	image = face_recognition.load_image_file(filename)
	images.append(image)

unknown_image = face_recognition.load_image_file("unknown.jpg")

face_encodings = []

for image in images:
	encoding = face_recognition.face_encodings(image)[0]
	face_encodings.append(encoding)

unknown_face_encodings = face_recognition.face_encodings(unknown_image)

face_locations = face_recognition.face_locations(unknown_image)

for i in range(len(unknown_face_encodings)):
	unknown_encoding = unknown_face_encodings[i]
	face_location = face_locations[i]
	top, right, bottom, left = face_location
	cv2.rectangle(unknown_image, (left,top), (right, bottom), (0, 255,0), 2)
	results = face_recognition.compare_faces(face_encodings, unknown_encoding)
	for j in range(len(results)):
		if results[j]:
			name = names[j]
			cv2.putText(unknown_image, name, (left - 10, top - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)

unknown_image_rgb = cv2.cvtColor(unknown_image, cv2.COLOR_BGR2RGB)
cv2.imshow("Output", unknown_image_rgb)
cv2.waitKey(0)

**Comment by heyueyuan** [comment]
above all, that's my code, but it doesn't work, I am beginning to learn about python and the package of face_recognition, if you can help me, I will appreciate. thank you.

**Comment by FiveMaster** [comment]
It is a bad code.
I think you must first understand that how to read of the frame in the camera all the time.
you can see the code: (https://github.com/ageitgey/face_recognition/blob/master/examples/facerec_from_webcam.py#L18)
