### ISSUE TITLE
Does dlib perform landmark alignment before encoding?

### ISSUE THREAD

**Issue by giffordw** [ageitgey/face_recognition#33]
Thanks for the creation of a great API! While the code runs smoothly, I'm curious if the dlib face encoding script performs an alignment with the face landmarks before encoding to the 128 length vector. There seems to be very little documentation on the dlib side how these encodings are generated, and I'm less familiar with that face recognition package. If you have any information on this it would be great to know and potentially add to your docs. Thanks.

**Comment by davisking** [comment]
Ha, not read the code.  Read the documentation :)  The example program is documentation that just happens to be executable.

**Comment by ageitgey** [comment]
haha 👍 :)
