### ISSUE TITLE
face encoding error

### ISSUE THREAD

**Issue by vijaybabu4589** [ageitgey/face_recognition#330]
*face_recognition version: install in 2018
*Python version: 3.6.2
*Operating System: Windows 10

# **some time when i  try to encode a image i get this error...please help**
##code:
        self.getimg=face_recognition.load_image_file('capture.jpg')
        self.src_encoding = face_recognition.face_encodings(self.getimg)[0]
![image](https://user-images.githubusercontent.com/35931662/35525460-8efaace0-054a-11e8-954f-2dcf9d6931e9.png)

Traceback (most recent call last):
  File "C:\Users\Vijay\Downloads\face_recognition-master\face_recognition-master\examples\knn_examples\test\test.py", line 46, in <module>
    p1.get_img()
  File "C:\Users\Vijay\Downloads\face_recognition-master\face_recognition-master\examples\knn_examples\test\test.py", line 25, in get_img
    self.src_encoding = face_recognition.face_encodings(self.getimg)[0]
IndexError: list index out of range
```
![image](https://user-images.githubusercontent.com/35931662/35525470-9aa07336-054a-11e8-80b6-db628bb03dc3.png)

**Comment by ageitgey** [comment]
That just means no face was found in the picture. Check the size of the face encodings array before trying to access index 0.

**Comment by vijaybabu4589** [comment]
![test2](https://user-images.githubusercontent.com/35931662/35582095-c1ed58e0-0613-11e8-9668-3253b7672e61.png)

At first try "capture.jpg" had no face(blank image) ,in second try "capture.jpg" had a face but both array length was same.. what logic should i apply if using len is inappropriate.

**Comment by ageitgey** [comment]
You code is wrong. Your code checking the length of the image itself, not the length of the encodings array returned by the `face_encodings()` function. You are checking the wrong thing.

You want something like this:

```python
encodings = face_recognition.face_encodings(img)
if len(encodings) > 0:
  src_encoding = encodings[0]
```
