### ISSUE TITLE
Learner: How to put boxes around recognized faces for individual images?

### ISSUE THREAD

**Issue by 54688** [ageitgey/face_recognition#341]
I'm a learner, but I love this project!

I would like to know how you can use the functions of `facerec_from_webcam.py` on individual pictures. 

I appreciate any help or suggestions! Thanks!

* face_recognition version: 1.0.0
* Python version: 3.6.4
* Operating System: macOS 10.13.3 Beta

**Comment by ageitgey** [comment]
Sure! I added a new example that does that here: https://github.com/ageitgey/face_recognition/blob/master/examples/identify_and_draw_boxes_on_faces.py

Here's an example of what it generates:

![image_with_boxes](https://user-images.githubusercontent.com/896692/35821050-91400d44-0a5c-11e8-9270-508b8843d528.jpg)
