### ISSUE TITLE
Need To Uninstall dlib and face_recognition, getting 'face_recognition' has no attribute 'load_image_file'

### ISSUE THREAD

**Issue by MotorCityCobra** [ageitgey/face_recognition#343]
* face_recognition version: The one on Github as of three days ago
* Python version: 3.6
* Operating System: Ubuntu

### Description
face_recognition was working fine but then I tried to get dlib to use my GPU.  
I uninstalled as much of the two (dlib and face_recognition) as a could, installed dlib so that it would use my GPU, re-installed face_recognition, but I clearly didn't have a clean enough uninstall.
Now when I try to use face_recognition I'm getting...  
$ python3 face.py
Traceback (most recent call last):
  File "face.py", line 58, in <module>
    image = face_recognition.load_image_file(aly)
AttributeError: module 'face_recognition' has no attribute 'load_image_file'

I know the problem is not with my code because, like I said, I worked before  and it was using the CPU. The trouble started when I tried to get it to use the GPU. I know I should have done a full uninstallation of dlib and face_recognition but I don't know how. Know face_recognition and dlib documentation or Q&A problems up on the Internet anywhere explain this in a way that I can find/ make use of.  

Could you please help me uninstall these two modules, so I can get dlib re-installed the right way? Thank you.

**Comment by ageitgey** [comment]
I don't know that uninstalling will fix your problem, but this is how you uninstall:

```
pip3 uninstall face_recognition
pip3 uninstall dlib
```

**Comment by MotorCityCobra** [comment]
I did those.
But when I installed I installed with a make install and python setup.py install for both.  
I think it's the make installs that gunked up the functioning.

**Comment by ageitgey** [comment]
To help debug the actual problem, start python3 and then type these commands into the python3 console and paste the full results:

```python
import face_recognition
face_recognition.__version__
face_recognition.__file__
dir(face_recognition)
```

**Comment by MotorCityCobra** [comment]
Weird. It imports face_recognition but threw an error for __version__, and __file__
dir(face_recognition)
returned
['__doc__', '__loader__', '__name__', '__package__', '__path__', '__spec__']

$ python3
Python 3.6.3 |Anaconda custom (64-bit)| (default, Oct 13 2017, 12:02:49) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import face_recognition
>>> face_recognition.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'face_recognition' has no attribute '__version__'

**Comment by ageitgey** [comment]
You didn't type the commands correctly. Notice the underscores in `__file__` and `__version__`.

**Comment by MotorCityCobra** [comment]
I made an edit at the top of my last comment. You might have to reload.  
Github formatting changed the double underlines to make word bold. I typed it correctly. I copied and pasted what you typed  into the termnal.


![screenshot from 2018-02-04 18-25-04](https://user-images.githubusercontent.com/14045554/35783661-eefc0dae-09d8-11e8-9499-8ade1365e577.png)

**Comment by ageitgey** [comment]
Do you happen to have a file called face_recognition.py in the working folder or something?

**Comment by MotorCityCobra** [comment]
No. I saw that as a solution to my same problem. But no.  
I get my error in this dir. Inside and outside of my env.

DIR I've been working from
![screenshot_2018-02-02_13-34-00](https://user-images.githubusercontent.com/14045554/35783692-4a3fc340-09d9-11e8-9ea6-1f19bfe6e276.png)

**Comment by MotorCityCobra** [comment]
Dir I'm working from

![screenshot from 2018-02-04 18-28-21](https://user-images.githubusercontent.com/14045554/35783696-611757e0-09d9-11e8-9778-501e5393b59f.png)

**Comment by ageitgey** [comment]
Thanks for the pics. Strange!

Try this as an alternate way to debug what is being loaded:

```python
import face_recognition
import inspect
print(inspect.getfile(face_recognition))
```

**Comment by MotorCityCobra** [comment]
Error

![inspect](https://user-images.githubusercontent.com/14045554/35783805-8304d4fc-09db-11e8-9026-10b774effd0e.png)

**Comment by MotorCityCobra** [comment]
Have you ever done a complete uninstall of dlib and face_recognition? Is that what pip3 uninstall of both of them is supposed to do? I think it's something I might have to do manually and I'm not sure I'm qualified to do it or can find instructions how to.

**Comment by ageitgey** [comment]
That's super weird that it is showing up as a built-in module. It seems like something is weird with Anaconda. Two other projects report a similar symptoms with Anaconda 3 and their libraries:
- https://github.com/scrapinghub/python-crfsuite/issues/62
- https://github.com/tensorflow/tensorflow/issues/1990

It seems the issue is something about having Anaconda installed but installing the face_recognition / dlib using the pip3 instance from a separate Python install / version.

If you do have multiple python installations, the question you are asking is hard to answer. Since I don't know exactly what's installed where on your system, I can't really tell you where to manually delete the files from. This is one reason why I really hate Anaconda because it tends to cause problems like this.

Maybe the easiest thing to do is start python again and type this:

```python
import sys
print(sys.path)
```

That should give you a list go folders and egg files like this:
```
['', '/Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip', '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6', '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload', '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages', '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/face_recognition_models-0.3.0-py3.6.egg', '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/face_recognition-1.1.0-py3.6.egg']
```

Then you can check each of those paths to see if they contain a folder or file named `face_recognition` and delete it if it does. That should help you track down the rogue copy.

**Comment by MotorCityCobra** [comment]
I get...
 >>> import sys
>>> print (sys.path)
['', '/home/eagle/anaconda3/lib/python36.zip', '/home/eagle/anaconda3/lib/python3.6', '/home/eagle/anaconda3/lib/python3.6/lib-dynload', '/home/eagle/anaconda3/lib/python3.6/site-packages', '/home/eagle/anaconda3/lib/python3.6/site-packages/Mako-1.0.7-py3.6.egg', '/home/eagle/anaconda3/lib/python3.6/site-packages/face_recognition-1.1.0-py3.6.egg', '/home/eagle/anaconda3/lib/python3.6/site-packages/face_recognition_models-0.3.0-py3.6.egg', '/home/eagle/anaconda3/lib/python3.6/site-packages/dlib-19.6.0-py3.6-linux-x86_64.egg']
>>> 

[REFORMATTED paths to make them easier to look at]
/home/eagle/anaconda3/lib/python36.zip
/home/eagle/anaconda3/lib/python3.6
/home/eagle/anaconda3/lib/python3.6/lib-dynload
/home/eagle/anaconda3/lib/python3.6/site-packages
/home/eagle/anaconda3/lib/python3.6/site-packages/Mako-1.0.7-py3.6.egg
/home/eagle/anaconda3/lib/python3.6/site-packages/face_recognition-1.1.0-py3.6.egg 
/home/eagle/anaconda3/lib/python3.6/site-packages/face_recognition_models-0.3.0-py3.6.egg
/home/eagle/anaconda3/lib/python3.6/site-packages/dlib-19.6.0-py3.6-linux-x86_64.egg

This is out of my depth already. I should look in '/home/eagle/anaconda3/lib/' for other versions of face_recognition? I should leave dlib alone? I'm not even sure how to test dlib. (I know it's a totally separate module).  
I should do this INSTEAD of doing a scorched earth uninstall or as part of trying to do said uninstall?

**Comment by MotorCityCobra** [comment]
I'm looking in /home/eagle/anaconda3/lib/python3.6/site-packages/
Two dlib eggs

![dlib](https://user-images.githubusercontent.com/14045554/35784207-ac3b53f8-09e2-11e8-8044-f2b43ea17087.png)

**Comment by MotorCityCobra** [comment]
I tried removing face_recognition from the dir shown in the photo in my previous post.  
Doesn't import now.  
When I type this, it shows this...
pip3 uninstall face_recognition
Uninstalling face-recognition-1.1.0:
  /usr/local/lib/python3.5/dist-packages/face_recognition-1.1.0-py3.5.egg
Proceed (y/n)?

**Comment by ageitgey** [comment]
If you proceed with that uninstall and then re-install it, do you get a different result when you import it?

**Comment by MotorCityCobra** [comment]
Some things going on between python3.5 and python3.6 I don't understand.
I uninstall it
It says it uninstalled
I give the command to uninstall it again just to see, and it says it's not installed
When I run the install it says it IS already installed "Requirements Satisfied".


$ sudo pip3 uninstall face_recognition
[sudo] password for me: 
The directory '/home/eagle/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Uninstalling face-recognition-1.1.0:
  /usr/local/lib/python3.5/dist-packages/face_recognition-1.1.0-py3.5.egg
Proceed (y/n)? y
  Successfully uninstalled face-recognition-1.1.0
The directory '/home/eagle/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.

$ sudo pip3 uninstall face_recognition
The directory '/home/eagle/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Cannot uninstall requirement face-recognition, not installed
The directory '/home/eagle/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.

$ sudo pip3 install face_recognition
The directory '/home/eagle/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/eagle/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting face_recognition
  Downloading face_recognition-1.2.1-py2.py3-none-any.whl
Requirement already satisfied: numpy in /home/eagle/.local/lib/python3.5/site-packages (from face_recognition)
Requirement already satisfied: Click>=6.0 in /usr/local/lib/python3.5/dist-packages (from face_recognition)
Requirement already satisfied: dlib>=19.7 in /usr/local/lib/python3.5/dist-packages/dlib-19.9.0-py3.5-linux-x86_64.egg (from face_recognition)
Requirement already satisfied: face-recognition-models>=0.3.0 in /usr/local/lib/python3.5/dist-packages (from face_recognition)
Requirement already satisfied: Pillow in /usr/lib/python3/dist-packages (from face_recognition)
Requirement already satisfied: scipy>=0.17.0 in /usr/local/lib/python3.5/dist-packages (from face_recognition)
Installing collected packages: face-recognition
Successfully installed face-recognition-1.2.1
$

**Comment by MotorCityCobra** [comment]
And now it's 'no module named face_recognition'
I removed the file we talked about earlier. The one shown from importing sys.
Hang on. I'll put it back.

**Comment by MotorCityCobra** [comment]
I put it back.
It imports again without error.
But it gives the original no such attribute to '__version__' again like before.

**Comment by MotorCityCobra** [comment]
Re installed face recognition and started python with the command 'python3.5'
Now I can import face_recognition and get the version. It said 0.1.0 

$ sudo pip3 install face_recognition
The directory '/home/eagle/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/eagle/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting face_recognition
  Downloading face_recognition-1.2.1-py2.py3-none-any.whl
Requirement already satisfied: numpy in /home/eagle/.local/lib/python3.5/site-packages (from face_recognition)
Requirement already satisfied: scipy>=0.17.0 in /usr/local/lib/python3.5/dist-packages (from face_recognition)
Requirement already satisfied: dlib>=19.7 in /usr/local/lib/python3.5/dist-packages/dlib-19.9.0-py3.5-linux-x86_64.egg (from face_recognition)
Requirement already satisfied: face-recognition-models>=0.3.0 in /usr/local/lib/python3.5/dist-packages (from face_recognition)
Requirement already satisfied: Pillow in /usr/lib/python3/dist-packages (from face_recognition)
Requirement already satisfied: Click>=6.0 in /usr/local/lib/python3.5/dist-packages (from face_recognition)
Installing collected packages: face-recognition
Successfully installed face-recognition-1.2.1
(aly) eagle@eagle-MS-7A32:~/Aly$ python3.5
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import face_recognition
>>> face_recognition.__version__
'0.1.0'

**Comment by MotorCityCobra** [comment]
The script runs with 'python3.5 script.py' now too.  
I guess it always would have.
It must be using the GPU now too because it is working on my photos at near light speed.

I have never had a problem like this before.
Thanks for taking a pass at it.

**Comment by ageitgey** [comment]
Glad you got it working!

**Comment by MotorCityCobra** [comment]
I figured out my problem was Anaconda wasn't up to date on my machine.  
That's way it installed in Python3.5 and did other weird things.

Duh.

**Comment by SaHiLR0HILLA** [comment]
i am not able to install dlib & face recognition in anconda 3.8.5 
anyone please me
