### ISSUE TITLE
Real time encoding

### ISSUE THREAD

**Issue by Jerameel** [ageitgey/face_recognition#344]
I was doing a real time recognition and I am loading the images recursively setting the folder names as the known_face_name.  I have questions with regards to the following things

1. Is it possible to know if there has been changes in the folder structure, ex. image has been added or removed? with that i can restart my encodiing function.

2. is it faster to save the encoded image array to a file, then load it again instead of reloading the whole image?

**Comment by ageitgey** [comment]
> Is it possible to know if there has been changes in the folder structure, ex. image has been added or removed? with that i can restart my encodiing function.

You could do that with a python library like watchdog: https://github.com/gorakhargosh/watchdog

> is it faster to save the encoded image array to a file, then load it again instead of reloading the whole image?

Yes, that would be faster. Or you could save the encoded image data in an array or cache. Whatever works for your application.
