### ISSUE TITLE
configure face_recognition to use gpu on windows or linux

### ISSUE THREAD

**Issue by ExtremeYu** [ageitgey/face_recognition#345]
* face_recognition version:1.2.1
* Python version:3.6
* Operating System:WIN10

how to use gpu to accelerate the speed,its too slow to generate the result

**Comment by AlainPilon** [comment]
The question has be asked a few times in the past, look at the closed issues.

**Comment by ExtremeYu** [comment]
i hope there is a turtorial about configure face_recognition to use gpu on windows or linux

**Comment by ExtremeYu** [comment]
i hope there is a turtorial about configure face_recognition to use gpu on windows or linux
