### ISSUE TITLE
python import face_recognition slow

### ISSUE THREAD

**Issue by magnoleal** [ageitgey/face_recognition#348]
* Python version: 3.5
* Operating System: Linux/Ubuntu
* RAM: 6GB
* Processor: 4 Cores

### Description

`import face_recognition`

I'm finding the python import too slow, it's taking around 5 seconds.
the recognition is fast, but the import is taking a long time, can anyone help me?

**Comment by ageitgey** [comment]
When you import it, it's loading up the machine learning models. That can be slow depending on the speed of your system and hard drive.

Depending on how you are using the library in a program, it might make sense to load it up in a separate process so it doesn't block the main program. It just depends on what you are doing.

**Comment by julio16101** [comment]
desde linux con ubuntu 15 tengo el mismo problema usando una computadora con 12GB de RAM y 4 nucleos de procesador, al realizar import face_recognition suele haber un retraso de 5 segundos, y el reconocimiento facial en tiempo real es muy lento, alguna sugerencia?

**Comment by magnoleal** [comment]
@julio16101 I work around this problem by creating an http server to respond to requests as in the example:

https://github.com/ageitgey/face_recognition/blob/master/examples/web_service_example.py
