### ISSUE TITLE
low accuracy may be due to predictor_point_model

### ISSUE THREAD

**Issue by FiveMaster** [ageitgey/face_recognition#352]
* face_recognition version:1.2.1
* Python version:3.6.1
* Operating System:Windows 10

### Description

I checked the commit history and found this commit log: 
`Will use dlib's 5-point face pose estimator when possible for speed (instead of 68-point face pose estimator)`
I have tested it, if use dlib's 5-point face pose estimator, it often give incorrect results. but if I use dlib's 68-point face pose estimator, it will give me the correct results.
so if we want to improve the accuracy rather than speed, we should use 68-point face pose estimator.

### What I Did

```
def face_encodings(face_image, known_face_locations=None, num_jitters=1):
    """
    Given an image, return the 128-dimension face encoding for each face in the image.

    :param face_image: The image that contains one or more faces
    :param known_face_locations: Optional - the bounding boxes of each face if you already know them.
    :param num_jitters: How many times to re-sample the face when calculating encoding. Higher is more accurate, but slower (i.e. 100 is 100x slower)
    :return: A list of 128-dimensional face encodings (one for each face in the image)
    """
    raw_landmarks = _raw_face_landmarks(face_image, known_face_locations, model="large")

    return [np.array(face_encoder.compute_face_descriptor(face_image, raw_landmark_set, num_jitters)) for raw_landmark_set in raw_landmarks]

```

**Comment by ageitgey** [comment]
Interesting. Do you have any sample images that show a different when using the two different models?

**Comment by FiveMaster** [comment]
for some test images, small model give better results, but the other images, large model give better results.
I do not know how to balance it.

**Comment by ageitgey** [comment]
The two models should give the same results in theory. If you can provide any images that get different results between the two models, I'd love to take a look.
