### ISSUE TITLE
KNN

### ISSUE THREAD

**Issue by Akhilelluru** [ageitgey/face_recognition#353]
* face_recognition version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.
IMPORTANT: If your issue is related to a specific picture, include it so others can reproduce the issue.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```
How to compare faces using KNN, instead of what you are doing in webcam_faster_rec.py.

**Comment by ageitgey** [comment]
There is a KNN example in the examples folder that you can try out.

**Comment by Akhilelluru** [comment]
yes we tried it, but I am missing the way,  how to reuse in webcam_faster_rec.py
