### ISSUE TITLE
face recognition speed

### ISSUE THREAD

**Issue by xbcReal** [ageitgey/face_recognition#355]
* face_recognition version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.
IMPORTANT: If your issue is related to a specific picture, include it so others can reproduce the issue.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```
Does somebody tried that using thie repo to recognize about 5k persons?And how's the speed and what's the platform?

**Comment by ageitgey** [comment]
Check out some of these previous issues:
- https://github.com/ageitgey/face_recognition/issues/279
- https://github.com/ageitgey/face_recognition/issues/273
- https://github.com/ageitgey/face_recognition/issues/238

**Comment by xbcReal** [comment]
@ageitgey thanks for your reply,another thing I want to ask you is that can it run in a tinhkerboard or a rasperry pi 3 in real time ?I mean I only use the board to detect faces and extract the 128d vector for each detected face,can this be realised in real time?Any suggestion?
Thank.

**Comment by ageitgey** [comment]
I haven't tested an RPi 3. I've only tested an RPi 2. But it was not able to run real-time on it. You'll just have to test it.

Note: If you are running on ARM, make sure you compile dlib with NEON support so it runs as fast as possible.
