### ISSUE TITLE
dlib install and uninstall problem

### ISSUE THREAD

**Issue by xbcReal** [ageitgey/face_recognition#356]
I follow the guide to install face_recognition on raspberry,I download the dlib git and compile it with "-mfpu=neon",then I try to install face_recognition ,but when installing this package,the info shows that the dlib installed on my own before are uninstalled and the pip install another dlib.I wonder whether the pip installed dlib is compiled with "-mfpu=neon" flag because the speed is important for me.

**Comment by ageitgey** [comment]
As long as the version of dlib you compiled is the newest version, pip shouldn't uninstall it when you install face_recognition. It should just find and use it. 

Maybe something else is wrong. But without you posting logs of what happened, there's no way to know.
