### ISSUE TITLE
Use opencv Mat structure 

### ISSUE THREAD

**Issue by shadow111** [ageitgey/face_recognition#36]
* face_recognition version: last version
* Python version: 2.7
* Operating System: ubuntu 16.04

### Description

i need to work with opencv images , read an images with opencv then pass it to the face_recongition 

please can that be done? if yes an example 
THank you so much
Lafi

**Comment by ageitgey** [comment]
Yep, they work great together! Check out the webcam example. It reads an image from the webcam with OpenCV and then processes it with face_recognition.

**Comment by shadow111** [comment]
ohh thank you so much that will really be great!! also i'm wondering to ask for face recongition!! if i just have one images to train then i want to recongnize the face in another image !! it will give a good result (accurate result)

**Comment by ageitgey** [comment]
It depends on how good the pictures are, but it's possible to get good results with only one known image.
