### ISSUE TITLE
Wrong landmarks returned by dlib.shape_predictor (68 points) after call to face_locations with cnn model

### ISSUE THREAD

**Issue by Clorr** [ageitgey/face_recognition#360]
* face_recognition version: latest/1.2.1
* Python version: 3.5.4/3.6.4
* Operating System: Windows/Ubuntu

(As the case came from different testers, I can't be more precise, but this seems platform independent)

### Description

Hi, we are discussing right now about an [issue about landmarks in deepfakes](https://github.com/deepfakes/faceswap/issues/187) (The link is SFW, but example faces clearly come from NSFW sources), happening on some faces detected with the `cnn` option. 

What we found is that, in the reported cases, `dlib.cnn_face_detection_model_v1` returns a very narrow sized face box and the landmarks returned by `dlib.shape_predictor` are totally wrong. It happens that if the same face is passed to the landmarks detector in a cropped image with more space around, the landmarks detection works fine.

Also we checked on `1adrianb/face-alignment` lib because it seems to have better results. It happens that [some preprocessing](https://github.com/1adrianb/face-alignment/blob/fecdd1084df5d52246d26a9eb210e3404b4f6345/face_alignment/api.py#L171) is done to add more space around the detected face before passing it to the landmarks detector (but maybe this is unrelated as it doesn't use dlib `shape_predictor`)

Also note that landmarks in `deepfakes` are returned by a [copy/paste of _raw_face_landmarks](https://github.com/deepfakes/faceswap/blob/51f1993d93e0ffb581d44416f327f0cf731c34e8/lib/faces_detect.py#L12) (as we needed a simple list of landmarks while `api.py` only offers `face_landmarks` that returns landmarks in a structured way). This shouldn't be the origin of the issue however.

Do you have any idea of the origin of the issue? Is that from a bad usage of lib? Would you recommend enlarging the face box returned by `dlib.cnn_face_detection_model_v1` to correct the problem?

Thanks and sorry if this is not relevant to your project

### What I Did

I ran the following code on images (`frame` variable) with faces from almost side view and quite rotated:
```
    face_locations = face_recognition.face_locations(frame, model=model)
    landmarks = _raw_face_landmarks(frame, face_locations)
```

**Comment by ageitgey** [comment]
The dlib shape predictor is trained on the non-CNN face detection model. It's not really intended to be used with the CNN face detector model so the results will be unpredictable and not that reliable.

As a side note, I'm not a supporter of the project that you linked to and would prefer if you didn't discuss it on issues related to this project.
