### ISSUE TITLE
Scipy.misc.imread not found

### ISSUE THREAD

**Issue by jdineen123** [ageitgey/face_recognition#363]
Got everything running on Windows, but was met with a module not found error after ending my Jupyter session. Anyone else having this issue? Updated load_image_file function to use cv2.imread rather than scipy.misc.imread.

**Comment by ageitgey** [comment]
cv2 loads images in BGR format by default. Make sure you convert them to RGB before you pass them to face_recognition or the results will be a little off.

**Comment by jdineen123** [comment]
Thank you! Believe this works:: 

def load_image_file(file):
    """
    Loads an image file (.jpg, .png, etc) into a numpy array

    :param file: image file name or file object to load
    :return: image contents as numpy array
    """
    file = cv2.imread(file)
    return cv2.cvtColor(file, cv2.COLOR_BGR2RGB)
