### ISSUE TITLE
Distance from webcam to a person (using face recognition with webcam)

### ISSUE THREAD

**Issue by julayelei** [ageitgey/face_recognition#368]
* face_recognition version: the last one until this day
* Python version: 3.5.2
* Operating System: Ubuntu 16.04

### Description

Everything works perfect! The only thing is that if I want to be recognized I have to put my face at least at 50 cm to the webcam. I was wondering if there was a way to be recognized at least at one meter of distance from the person and the webcam.

Thanks anyway!

**Comment by ageitgey** [comment]
Check out #333

**Comment by julayelei** [comment]
Thanks!!
