### ISSUE TITLE
Two people in one face

### ISSUE THREAD

**Issue by UberFluff** [ageitgey/face_recognition#37]
* face_recognition version: latest
* Python version: 3.5
* Operating System: Windows

### Description

Hello, I tried your library and I must say it's pretty cool and does work ! But sometimes when I enter an image and want it to recognize who it belongs to, I get two people instead of one. Is there some sort of precentage of accuracy where we could take the higher one ?

**Comment by gamblenull1996** [comment]
In https://face-recognition.readthedocs.io/en/latest/face_recognition.html
face_recognition.compare_faces(known_face_encodings, face_encoding_to_check, tolerance=0.6)
The author already explained that there is a parameter to control.
tolerance – How much distance between faces to consider it a match. Lower is more strict. 0.6 is typical best performance.
You may set tolerance lower to distinguish two people.

**Comment by UberFluff** [comment]
Oh thanks ! I didn't even think of going to see the docs ...

**Comment by ageitgey** [comment]
It still would be useful to expose the face distance in case you get two matches. Maybe I can add that in a future version.

**Comment by UberFluff** [comment]
Well it would be great

**Comment by lambaaada** [comment]
UberFluff is there any way to contact you so I could ask you how did you get this module (face_recognition)
to work on Windows? I have been trying for a while now with no success

**Comment by UberFluff** [comment]
Lambaaada, well I only followed the tutorial on how to install dlib on windows I think and I'm on python 3.5 btw
