### ISSUE TITLE
code compiled but i am not getting any output

### ISSUE THREAD

**Issue by kandy1417** [ageitgey/face_recognition#373]
* face_recognition version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.
IMPORTANT: If your issue is related to a specific picture, include it so others can reproduce the issue.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by ageitgey** [comment]
We can't help if you don't provide any of the required information. There's no way to know what you tried.
