### ISSUE TITLE
module 'dlib' has no attribute 'cnn_face_detection_model_v1'

### ISSUE THREAD

**Issue by ankitjha97** [ageitgey/face_recognition#379]
* face_recognition version:
* Python version:
* Operating System:

### Description

I was installing dlib and face_recognition.I have installed dlib and face_recognition using pip but i was not able to import face_recognition in anaconda.Then, I installed dlib through conda and this error came on importing face_recognition
import face_recognition
**Error** : _module 'dlib' has no attribute 'cnn_face_detection_model_v1'_

**Comment by xbcReal** [comment]
what's the version of the dlib you installed?

**Comment by ankitjha97** [comment]
I uninstalled the conda versions and it is working good.

**Comment by chaitanyajalluri** [comment]
@ankitjha97  can u please explain clearly  how u resolved

**Comment by ankitjha97** [comment]
@chaitanyajalluri , I don't remember exactly. Dlib was incompatible with the version of anaconda so I downgraded it.

**Comment by hnustpengmi** [comment]
I didn't use the cnn, so I commented out the line in the corresponding file. Fortunately, it seems to work as well.
