### ISSUE TITLE
ValueError thrown known_face_encodings is an empty list

### ISSUE THREAD

**Issue by robnils** [ageitgey/face_recognition#38]
* face_recognition version:
* Python version:
* Operating System:

### Description

In:
    compare_faces(known_face_encodings, face_encoding_to_check, tolerance=0.6)

if known_face_encodings is an empty list, a non-intuitive ValueError is thrown. Created this issue so I can attach the pull request to it. 

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by robnils** [comment]
I suggest modifying compare_faces to

    if not known_face_encodings:
        return []
    return list(_face_distance(known_face_encodings, face_encoding_to_check) <= tolerance)

to allow the user to input an empty list for known_face_encodings which then returns an empty list of "matches". Otherwise, an expected ValueError occurs which isn't particularly intuitive.

I tried creating a pull request but I didn't have permissions to push my branch (or I'm just missing something).

**Comment by ageitgey** [comment]
Thanks. You should fork this repo, push the code change to your forked repo, and then create the pull request between your fork and this repo.
