### ISSUE TITLE
I just want to ask what is the theory or method behind the HOG based model,is it combined with some machine learning method?

### ISSUE THREAD

**Issue by Racheal1064** [ageitgey/face_recognition#384]
* face_recognition version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.
IMPORTANT: If your issue is related to a specific picture, include it so others can reproduce the issue.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by ageitgey** [comment]
Yes, you can find the paper here: https://arxiv.org/abs/1502.00046
