### ISSUE TITLE
Issue in face_encodings

### ISSUE THREAD

**Issue by vikramjagan** [ageitgey/face_recognition#385]
* face_recognition version:
* Python version:
* Operating System:

### Description

When i tried use the function face_encodings() it shows some error of

IndexError: list index out of range
### What I Did

I tried with some other photos.Some photos its working fine for some other its showing same error

kindly help regrading this issue

**Comment by Hrishi1999** [comment]
Similar issue, but I use a code like this : 
`subfolders = [f.path for f in os.scandir(os.getcwd()) if f.is_dir() ] 
subfolders.remove(os.getcwd() + r'\face_recognition')
for item in subfolders:
    obj_names.append(item)
    cnt = cnt +1
    for file_name in os.listdir(item):
        obj_images.append(face_recognition.load_image_file(item + '\\' +file_name))
        obj_encs.append(face_recognition.face_encodings(obj_images[cnt]))`

I am dynamically trying to add faces with names of persons as folder names and images inside it for create face encodings. Need help

**Comment by Hrishi1999** [comment]
I solved my issue btw

**Comment by ageitgey** [comment]
Great!

**Comment by dheeru999** [comment]
i'am facing the same issue 
(list index out of range)

Can any one help me to resolve this issue!

**Comment by Hrishi1999** [comment]
It does mean that the face wasn't detected.
