### ISSUE TITLE
CUDA error

### ISSUE THREAD

**Issue by waslleysouza** [ageitgey/face_recognition#396]
* face_recognition version: latest
* Python version: 3.6.2
* Operating System: Ubuntu 16.04.3 LTS

### Description

The application fails to run and reports an unknown error.

### What I Did

I'm using an AWS Deep Learning instance and I followed this tutorial: https://gist.github.com/ageitgey/629d75c1baac34dfa5ca2a1928a7aeaf

I changed these two commands to use CUDA:

mkdir build; cd build; cmake .. -DDLIB_USE_CUDA=1 -DUSE_AVX_INSTRUCTIONS=1; cmake --build .

python3 setup.py install --yes USE_AVX_INSTRUCTIONS --yes DLIB_USE_CUDA

```
> python /home/ubuntu/projects/face_recognition/facerec_from_webcam_faster.py

Traceback (most recent call last):
  File "/home/ubuntu/projects/face_recognition/facerec_from_webcam_faster.py", line 1, in <module>
    import face_recognition
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/face_recognition/__init__.py", line 7, in <module>
    from .api import load_image_file, face_locations, batch_face_locations, face_landmarks, face_encodings, compare_faces, face_distance
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/face_recognition/api.py", line 24, in <module>
    cnn_face_detector = dlib.cnn_face_detection_model_v1(cnn_face_detection_model)
RuntimeError: Error while calling cudaGetDevice(&the_device_id) in file /home/ubuntu/dlib/dlib/dnn/gpu_data.cpp:178. code: 30, reason: unknown error
```

**Comment by ageitgey** [comment]
Check out #358 which is the same issue - It seems like running the app with sudo worked for some users.

**Comment by futureisatyourhand** [comment]
There is the same problem. How do you solve it? Thanks!
