### ISSUE TITLE
whether using "predictor_68_point_model" or "predictor_5_point_model"

### ISSUE THREAD

**Issue by z384647062** [ageitgey/face_recognition#399]
* face_recognition version:
* Python version: 3.6
* Operating System: windows10

### Description
Whether using "predictor_68_point_model" or "predictor_5_point_model" in "_raw_face_landmarks" will have an affect on the result(accuracy)?
Sometimes when I execute "facerec_from_webcam_faster.py", several entirely different faces will be recognized as the same face, so I've been trying to improve the accuracy (modify the value of "tolerance", any other ways?)

### What I Did

In face_encodings() , I changed
```
raw_landmarks = _raw_face_landmarks(face_image, known_face_locations, model="small")
```
to
```
raw_landmarks = _raw_face_landmarks(face_image, known_face_locations, model="large")
```

**Comment by ageitgey** [comment]
Changing that face alignment model should have no affect. If it does change the results, it's probably a bug.
