### ISSUE TITLE
AttributeError: 'module' object has no attribute 'imread'

### ISSUE THREAD

**Issue by vin67** [ageitgey/face_recognition#4]
* face_recognition version: 
* Python version: 3.x
* Operating System: MacOS

### Description

face_recognition ./known_people/ ./unknown_people/

was returning error message:  AttributeError: 'module' object has no attribute 'imread'

### What I Did

```
pip3 install Pillow
```

then it worked. was just a module I hadn't installed

**Comment by ageitgey** [comment]
Thanks for the report! Fixing in #5.
