### ISSUE TITLE
Could this lib run on Android?

### ISSUE THREAD

**Issue by neovaldivia** [ageitgey/face_recognition#408]
* face_recognition version:
* Python version: None
* Operating System: Android

### Description

I would like to get this lib to run on android and was wondering if you have any ideas that will help compile this lib to run on Android 

### What I Did
I was reading through Stackoverflow and found https://kivy.org/#home but I have not tried it yet.
What would be your recommendation if we wanted to run in on mobile 
```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by ageitgey** [comment]
No, this library won't work on Android. It's just not designed for that.

Note: It's possible *in theory* with a lot of custom hacking, but it's pretty much impractical. And even if it did work, it would be slow and consume a lot of power.

**Comment by FaceAI** [comment]
Android ?  here  

https://github.com/AnyLifeZLB/FaceVerificationSDK
