### ISSUE TITLE
Problem in encoding error landmark style

### ISSUE THREAD

**Issue by AbhiJoshi32** [ageitgey/face_recognition#410]
* face_recognition version: 1.2.1 
* Python version: 3.5
Tried on raspberry 2

### Description

i was trying the to encode the image and got this error.

### What I Did

```
>>> im_encoding = face_recognition.face_encodings(known_image)[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/face_recognition/api.py", line 199, in face_encodings
    return [np.array(face_encoder.compute_face_descriptor(face_image, raw_landmark_set, num_jitters)) for raw_landmark_set in raw_landmarks]
  File "/usr/local/lib/python3.5/dist-packages/face_recognition/api.py", line 199, in <listcomp>
    return [np.array(face_encoder.compute_face_descriptor(face_image, raw_landmark_set, num_jitters)) for raw_landmark_set in raw_landmarks]
RuntimeError: The full_object_detection must use the iBUG 300W 68 point face landmark style.
```

**Comment by ageitgey** [comment]
Is it possible you are running a new-ish version of face_recognition but still have an old version of dlib installed?

A fairly recent version of dlib added support for a smaller face landmark model, so face_recognition switched to using it. Check the version of dlib you have installed. It probably just needs to be updated. Alternatively, I guess you could install an older version of face_recognition via pip.

**Comment by Guo-king** [comment]
hi, I also got this error and I solved this problem by changing a parameter in api.py.
209 line: raw_landmarks = _raw_face_landmarks(face_image, known_face_locations, model="small")
Change the model="small" to model="large".

**Comment by AbhiJoshi32** [comment]
Thanks for the reply.
