### ISSUE TITLE
How to get the more accurate face'recognititon 

### ISSUE THREAD

**Issue by mansonami** [ageitgey/face_recognition#412]
* face_recognition version:
face-recognition          1.2.1                     <pip>
face-recognition-models   0.3.0                     <pip>
* Python version:Python 3.6.2
* Operating System:win10

### Description

I download the pic from www.baidu.com,  the movie star "林青霞" English name is Brigitte Lin， then recognize it with following code : 

    picture_of_lin = face_recognition.load_image_file(".\lin.png")
    lin_face_encoding = face_recognition.face_encodings(picture_of_lin)[0]

    for file in os.listdir(args.fin):
        tmpfile = os.path.join(args.fin, file)

        try:
            unknown_picture = face_recognition.load_image_file(tmpfile)
            unknown_face_encoding = face_recognition.face_encodings(unknown_picture)[0]            

            results = face_recognition.compare_faces([lin_face_encoding], unknown_face_encoding)

The results includes 10% pics not Brigitte Lin

So how to recognize the more accurate?

**Comment by ageitgey** [comment]
You could try passing in a lower `tolerance=` parameter to the `compare_faces()` function. The default is 0.6. You might try 0.5, for example, to make the comparison more strict.

**Comment by mansonami** [comment]
thanks very much

**Comment by kksu49** [comment]
can you show an example ?
