### ISSUE TITLE
Issue executing setup.py on dlib with docker

### ISSUE THREAD

**Issue by smajohusic** [ageitgey/face_recognition#413]
* face_recognition version: latest
* Python version: 3.4-slim
* Operating System:

Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.3 (stretch)
Release:	9.3
Codename:	stretch

Running on Raspberry Pi 3B

### Description
Issue with executing setup.py for dlib when building docker image

Step 3/6 : RUN cd ~ &&     mkdir -p dlib &&     git clone -b 'v19.7' --single-branch https://github.com/davisking/dlib.git dlib/ &&     cd  dlib/ &&     python3 setup.py install --yes USE_AVX_INSTRUCTIONS

### What I Did

Dockerfile that i use building the image

https://github.com/ageitgey/face_recognition/blob/master/Dockerfile

sudo docker build -t face-recognition .

```
Cloning into 'dlib'...
Note: checking out 'ba9c71d66adefa61980a44a598035cc45dfc106f'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

Traceback (most recent call last):
  File "setup.py", line 39, in <module>
    from setuptools.command.bdist_egg import bdist_egg as _bdist_egg
  File "/usr/local/lib/python3.4/site-packages/setuptools/__init__.py", line 14, in <module>
    from setuptools.dist import Distribution, Feature
  File "/usr/local/lib/python3.4/site-packages/setuptools/dist.py", line 25, in <module>
    from setuptools import windows_support
  File "/usr/local/lib/python3.4/site-packages/setuptools/windows_support.py", line 2, in <module>
    import ctypes
  File "/usr/local/lib/python3.4/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: /usr/local/lib/python3.4/lib-dynload/_ctypes.cpython-34m.so: undefined symbol: _PyTraceback_Add
The command '/bin/sh -c cd ~ &&     mkdir -p dlib &&     git clone -b 'v19.7' --single-branch https://github.com/davisking/dlib.git dlib/ &&     cd  dlib/ &&     python3 setup.py install --yes USE_AVX_INSTRUCTIONS' returned a non-zero code: 1
```

**Comment by smajohusic** [comment]
@ageitgey Tested this last night, and the Docker image was build along with all the requirements. Thank you and appreciate the help.

**Comment by ageitgey** [comment]
Nice, glad it worked :)

**Comment by smajohusic** [comment]
If someone comes across this, there is a issue with python3.6 release that will create trouble importing some packages.

See links:
https://github.com/waveform80/picamera/issues/386
https://raspberrypi.stackexchange.com/questions/60419/cant-import-picamera
