### ISSUE TITLE
To increase response time loading imags can be done separatly ??

### ISSUE THREAD

**Issue by Nurulhasan113** [ageitgey/face_recognition#414]
using open cv face recognition we can use 2 different scripts train and detect which reduces response time it is possible in this python scripts to use different script for this part 
```python
obama_image = face_recognition.load_image_file("obama.jpg")
obama_face_encoding = face_recognition.face_encodings(obama_image)[0]
biden_image = face_recognition.load_image_file("biden.jpg")
biden_face_encoding = face_recognition.face_encodings(biden_image)[0]
known_face_encodings = [
    obama_face_encoding,
    biden_face_encoding
]
known_face_names = [
    "Barack Obama",
    "Joe Biden"
]
```

**Comment by ageitgey** [comment]
Sure, you could save the face encodings to a file in a training script and then just load them when you want to do detection in a separate script.

Each face encoding is a numpy array, so you can easily save and load them: https://docs.scipy.org/doc/numpy/reference/generated/numpy.save.html
