### ISSUE TITLE
Create git tags for PyPI releases

### ISSUE THREAD

**Issue by Ma27** [ageitgey/face_recognition#417]
* face_recognition version: 1.2.1
* Python version: 2.7 / 3.6
* Operating System: NixOS 18.03

### Description

This is rather a feature request than a bug report. I'd like to ask if it's possible to create a git tag for each PyPI release (the latest git tag available on GitHub is v0.1.12, but I can install v1.2.1 from PyPI).
This can be helpful when you want to package such a library for bigger environments such as a Linux distribution where it's always preferred to run the tests inside the env created by the distro during the actual package build process (see https://github.com/NixOS/nixpkgs/pull/37566 and https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/python.md#buildpythonpackage-function for further reference regarding python libraries in Nix)

**Comment by ageitgey** [comment]
Sure, I'll do this going forward.

**Comment by Ma27** [comment]
great! Is there anything else to discuss, unless I'd close this issue %)

**Comment by ageitgey** [comment]
Nope! 

New release here: https://github.com/ageitgey/face_recognition/releases/tag/v1.2.2

**Comment by Ma27** [comment]
awesome!
