### ISSUE TITLE
How to detect side profiles? - Side face

### ISSUE THREAD

**Issue by PandaWhoCodes** [ageitgey/face_recognition#421]
* face_recognition version: v0.1.12
* Python version: 3.6
* Operating System: Windows

### Description

I would like to recognize a person from the side profile of the person.

### What I Did

Tried working it the normal way, but the face is not detected when I turn my head.

**Comment by ageitgey** [comment]
The model used in this library is not trained to detect side profiles, so it probably won't work for this purpose.

**Comment by nyck33** [comment]
@ageitgey which model is used for detection?  Is it possible to use another model?  I found DFSD by Tencent to be very robust, more so than MTCNN for face detection.

[DFSD](https://github.com/TencentYoutuResearch/FaceDetection-DSFD)

**Comment by SaddamBInSyed** [comment]
@nyck33 
set the model as "cnn" while you enumerating faces using the below method,

face_recognition.face_locations(rgb_small_frame, number_of_times_to_upsample=1,model="cnn")

 I have tried the same and it was working fine.

note:
but this model only fast with GPU.

ref info.
https://www.arunponnusamy.com/cnn-face-detector-dlib.html
