### ISSUE TITLE
AttributeError: 

### ISSUE THREAD

**Issue by rjtmehta99** [ageitgey/face_recognition#423]
* face_recognition version: 
* Python version: 3.6.3
* Operating System: Windows 8.1

### Description

I have install Pillow, numpy+mkl, pip, scipy, face_recognition_models
Encountering error while running the following code
import face_recognition_models

image = face_recognition_models.load_image_file("abc.jpg")
face_locations = face_recognition_models.face_locations(image)

Traceback (most recent call last):

  File "<ipython-input-5-824c31992c93>", line 3, in <module>
    image = face_recognition_models.load_image_file("abc.jpg")

AttributeError: module 'face_recognition_models' has no attribute 'load_image_file'

**Comment by ageitgey** [comment]
You are using the wrong package name. You wrote `face_recognition_models.load_image_file` but it's supposed to be `face_recognition.load_image_file`.

**Comment by rjtmehta99** [comment]
But according to the Anconda documentation, face_recognition_models is used. https://anaconda.org/akode/face_recognition_models

**Comment by nkimran94** [comment]
@rjtmehta99 
did you get any solution?
I'm also getting simillar error
