### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by Jegath** [ageitgey/face_recognition#426]
* face_recognition version:
* Python version:
* Operating System:

### Description

When trying to uploading a face which I don't have the encoding,its throwing an exception list index out of range.

### What I Did

```
    unknown_face_encoding = face_recognition.face_encodings(unknown_image)[0]
IndexError: list index out of range
```

**Comment by PandaWhoCodes** [comment]
It means it could not find any faces.

**Comment by Jegath** [comment]
Ok thankyou.

**Comment by ageitgey** [comment]
Please see https://github.com/ageitgey/face_recognition/wiki/Common-Errors#list-index-out-of-range-errors for a more detailed answer
