### ISSUE TITLE
how to save encoding of each face to file

### ISSUE THREAD

**Issue by oknoproblem3** [ageitgey/face_recognition#427]
hi, i want to know how to save encoding of each face to a file. i made a face recognition tool based on your api. but i can't make database because encodings of faces are only made when i run my tool, how to save them? other question, before extracting features from face image using Convolution Neural Network (face encoding function), i want to know the size of input face image. 
I'm vietnamese, sorry for my bad english. Thank you very much.

**Comment by afibrahi** [comment]
To save the encoding you can use numpy library
`import numpy as np
np.save('biden_face_encoding.npy', biden_face_encoding)
biden_face_encoding_loaded = np.load('biden_face_encoding.npy')`

**Comment by khaerulumam42** [comment]
To save model you can check on [here](https://github.com/ageitgey/face_recognition/issues/243) .
Just type `image.shape` to check dimension or size of the image

Hope can help you @oknoproblem3

**Comment by Heermosi** [comment]
You may use numpy.savez to save both label set and image feature set
It was an advanced format for numpy.save
Remember that there is something different when using loaded data compared with using the data before saving.

You may run this following code to experience the difference directly:

import numpy
a = ['a', 'b']
numpy.save("fuck", a)
b = numpy.load("fuck.npy")
b
a[0] = None
b[0] = None
a[0] is None
b[0] is None
a
b

**Comment by ageitgey** [comment]
I added this question to the new wiki here: https://github.com/ageitgey/face_recognition/wiki/How-do-I-save-face-encodings-to-a-file%3F
