### ISSUE TITLE
RPi 3B sudo pip3 install face_recognition no progress

### ISSUE THREAD

**Issue by JulianKling** [ageitgey/face_recognition#428]
* face_recognition version: current (1.2.1?)
* Python version: 3.6
* Operating System: Rasbian Stretch Lite

### Description

Trying to install on Raspberry Pi 3B, following the provided tutorial. After executing sudo pip3 install face_recognition there is no progress even after some hours. It stops at:

sudo pip3 install face_recognition
Collecting face_recognition
  Using cached face_recognition-1.2.1-py2.py3-none-any.whl
Requirement already satisfied: numpy in /usr/local/lib/python3.5/dist-packages (from face_recognition)
Requirement already satisfied: face-recognition-models>=0.3.0 in /usr/local/lib/python3.5/dist-packages (from face_recognition)
Requirement already satisfied: Pillow in /usr/lib/python3/dist-packages (from face_recognition)
Requirement already satisfied: dlib>=19.7 in /usr/local/lib/python3.5/dist-packages (from face_recognition)
Requirement already satisfied: Click>=6.0 in /usr/lib/python3/dist-packages (from face_recognition)
Collecting scipy>=0.17.0 (from face_recognition)
  Using cached scipy-1.0.1.tar.gz
Building wheels for collected packages: scipy
  Running setup.py bdist_wheel for scipy ... |

Any suggestions how to proceed or somebody has a working image he could share?
Thanks

**Comment by victoryWang** [comment]
hello, I have the same problem，how did you solved, 
Thanks
