### ISSUE TITLE
Best way to store the face features in a database

### ISSUE THREAD

**Issue by GuilhermeCaeiro** [ageitgey/face_recognition#43]
Hello, 

A few months ago, I saw the tutorial that, indirectly, originated this library, and, today, I finally had the need to implement a solution that uses facial recognition. However, I got stuck with a big problem when I started planning the data model: what's the best way to store the face features in a database (in order to optimize the search)?
Given the fact that the matches are not based on "perfect matches" (it deals with "similarity"), I'm having a real hard time to build the model. With what I have right now, I would have to load to the memory all the features' sets I have and then execute the comparisons. Given the current application that my project has, that approach wouldn't be a huge problem but... it could become one in the future.

If possible, could you guys, please, give some hints or point some articles/papers on that matter?

**Comment by ageitgey** [comment]
You could store the face encodings for each user as one database row per user with 128 columns in each row.

Then you could do the face_distance (euclidian distance) calculation yourself as a sql query calculation and sort the database results in order of smallest face distance.

There are a lot of other ways you could do it, too. But that's one idea.
