### ISSUE TITLE
Right factor to scale for identifying faces in image 

### ISSUE THREAD

**Issue by MLDSBigGuy** [ageitgey/face_recognition#430]
I am scaling images before finding the face_locations to 300x300 for faster processing times. 

My image files sometimes have small faces in big image file and sometime big faces in big image files. Processing big image files like 2000x2000 or 3000x3000 is taking time. Sometimes faces go too small and unidentified with this 300x300 scaling factor. 

If i identify faces without scaling, it is taking lot of time. I want to minimize the time taking to process the image file for dentifying the faces. 

How to comeup with right scale factor without faces going unrecognized ?  Any ideas ? 

Thank you

**Comment by ageitgey** [comment]
Just test it:

1. Take a picture with the smallest you need to capture (i.e. a person standing as far away from the camera as you need to capture)
2. Scale the image down to different sizes and find the smallest that still works for that far away face

**Comment by MLDSBigGuy** [comment]
OK thank you :) And one more problem is losing quality when i scale down the image. You know if i can maintain the quality near to the actual image and still scale down ?

**Comment by ageitgey** [comment]
Of course you will lose resolution when you downscale. There's no avoiding that.

But when downscaling images, make sure you are using a suitable downscaling algorithm like Lanczos. Using Lanczos is an option you can specify in most image downscaling functions. Just doing a downscale by dropping pixels or merging nearest neighbors (the default downscaling option in most image libraries) will result in worse image quality.

**Comment by MLDSBigGuy** [comment]
Thank you :) I think i have older version of PIL installed. It has Antialias. I think its same as lanczos from [here] (http://pillow.readthedocs.io/en/3.0.x/releasenotes/2.7.0.html#antialias-renamed-to-lanczos). isnt it ?

**Comment by ageitgey** [comment]
Sure, I guess that would work.

**Comment by MLDSBigGuy** [comment]
Thank you 👍
