### ISSUE TITLE
Face identification incase of Black and white faces

### ISSUE THREAD

**Issue by MLDSBigGuy** [ageitgey/face_recognition#436]
Hi,

Is there any requirement that i should pass only color images to get the faces identified / for face encodings ? 

Why all examples in project readme are shown only with color images ? 

Color images comes with more file size than black&white. Means more time to load in real time scenarios. why no conversion applied ? 

Thank you,

**Comment by ageitgey** [comment]
The three separate channels of information in a color photo gives you 3x more data to pass into the model than one channel of data from a B/W photo. So if you pass a B/W image instead of color, you are throwing away valuable data (two thirds of your data) that could be used to increase accuracy.

**Comment by MLDSBigGuy** [comment]
Thank you
