### ISSUE TITLE
How to read image from url not local file?

### ISSUE THREAD

**Issue by Jayhello** [ageitgey/face_recognition#442]
* face_recognition version:  0.1.0
* Python version: 2.7
* Operating System: ubuntu16

### Description

How to read image from url .
instead of 
    # Load the jpg file（local directory） into a numpy array
    image = face_recognition.load_image_file("biden.jpg")

I want to use (load image from url in mysql)

image = face_recognition.load_image_file("www.example.com/test1.jpg")

but I don't know the format.

### What I Did

first way
```python
    url = 'https://gss1.bdstatic.com/-vo3dSag_xI4khGkpoWK1HF6hhy/baike/c0%3Dbaike80%2C5%2C5%2C80%2C26/sign=468864cdf0039245b5b8e95de6fdcfa7/54fbb2fb43166d22ca0c87944a2309f79052d2b3.jpg'
    resp = urllib.urlopen(url)
    image = np.asarray(bytearray(resp.read()), dtype="uint8")
    image = cv2.imdecode(image, cv2.IMREAD_COLOR)
```

secondly  (it seems this works)

```
from skimage import io
image = io.imread(url)

```

How do think of the above two?

**Comment by ageitgey** [comment]
That should work fine. There are a million ways to open a url as a file object in Python. It doesn't really matter which you use. 

But in general, I wouldn't use the cv2 approach unless you know how to covert your loaded image from BGR color to RGB color. cv2 stores image data differently than most other Python libraries (i.e with the Blue and Red channels reversed).
