### ISSUE TITLE
ImportError face_recognition

### ISSUE THREAD

**Issue by vrivera2017** [ageitgey/face_recognition#45]
* face_recognition version: most recent
* Python version: 2.7.12
* Operating System: ubuntu 16.04

### Description

I was trying to run the image compare algorithm and got the following error-- ImportError: No module named face_recognition. I downloaded the most recent version of face_recognition, so I'm not sure what could be going wrong. 

### What I Did

```
Traceback (most recent call last):
  File "ImageCompare.py", line 1, in <module>
    import face_recognition
ImportError: No module named face_recognition
```

**Comment by ageitgey** [comment]
That means it's just not installed for your current version of python. Do you have multiple installations of python? Maybe you installed it for Python 3 but are trying to use it from Python 2 (or the reverse)?

**Comment by nashents** [comment]
hello ageitgey i was getting the same error as vrivera2017 but when i run my code in py2.7 shell it was successful,  i had installed the package twice using pip install and pip3 install on my raspberry ,so guess the python 2 one override the python 3 ...but i want it to run on python 3 what should i do
