### ISSUE TITLE
children's face model?

### ISSUE THREAD

**Issue by tangmeng09** [ageitgey/face_recognition#451]
* face_recognition version: master
* Python version: 2.7
* Operating System: centos 7.4

### Description
Hello,
Is there any resource about the model for children's face recognition? 
What can I help to train a model? 

Thanks.

**Comment by ageitgey** [comment]
Face recognition for children is not something I really want to support with this library. You need millions of pictures of people to train a model and collecting millions of pictures of children is a bad idea in my opinion.

**Comment by tangmeng09** [comment]
I do need a children's model because I have many kindergarten clients.

Is it possible to give some limited images to train the model? Model working on my clients is enough.

I have some svm and neaural network experience to analyis data sequence years ago.

Thanks a lot!

________________________________
