### ISSUE TITLE
Raspberry pi camera images not read for my facial recognition module

### ISSUE THREAD

**Issue by nashents** [ageitgey/face_recognition#454]
* face_recognition version:
* Python version:3
* Operating System:raspian stretch

Goodday was trying to run my facial recognition module using my raspberry pi , that is feeding known images and comparing them to other images 

what went wrong is it seems like everytime i try to use the images taken by my pi camera its returning an error message below  

Traceback (most recent call last):
  File "/home/pi/Desktop/iss/livefacereco.py", line 23, in <module>
    known_face_encoding = face_recognition.face_encodings(known_image)[0]
IndexError: list index out of range

after running this file below 
[livefacereco.zip](https://github.com/ageitgey/face_recognition/files/1929118/livefacereco.zip)

if i replace a picture taken by the raspberry pi camera with the one i downloaded online the code runs and execute smoothly  
```

```

**Comment by ageitgey** [comment]
https://github.com/ageitgey/face_recognition/wiki/Common-Errors#list-index-out-of-range-errors
