### ISSUE TITLE
face_locations slow

### ISSUE THREAD

**Issue by morningpaddington** [ageitgey/face_recognition#464]
* face_recognition version:1.2.2
* Python version: 3.5.3
* Operating System: Raspbian stretch

### Description
face_locations(image size(1000+ * 1000+)) method is taking around 45s to complete, while using faceCascade.detectMultiScale() provided by cv2 is only taking 2s.  Is it normal or is there any way to improve the speed? What's the advantage of using face_locations over detectMultiScale? The later one is still much faster when I use a smaller size image.

**Comment by ageitgey** [comment]
`faceCascade.detectMultiScale()` uses Haar Cascades which are much less accurate than the face detection models used in this library. You'll get many more false positives with that approach.

It sounds like you are running this an a Raspberry Pi (not sure which model). Those things aren't very fast in any case. But make sure you compiled dlib with NEON extensions to at least make sure things are running as fast as possible on the ARM cpu.

**Comment by Latestion** [comment]
I have the same problem and cant figure out a way to fix it now. Im on windows.

**Comment by progmars** [comment]
The same issue for me, inside https://github.com/deepfakes/faceswap  project on Windows 10.
The worst thing is that Python doesn't seem to even use any CPU / GPU while running `face_locations`.
