### ISSUE TITLE
Is there any library for AMD graphic card to speed up Face Recognition

### ISSUE THREAD

**Issue by kedar2594** [ageitgey/face_recognition#465]
* face_recognition version:1.2.2
* Python version:3.5.2
* Operating System:Ubuntu

### Description
I have successfully installed face recognition API and Dlib and I getting output also, but its slow.
I can't use CUDA for my system, because I have AMD graphic card, Please suggest me, is there any library to speed up the process for AMD Graphic card and how to use it in python.

**Comment by ageitgey** [comment]
Nope, sorry.

In general, very few machine learning libraries have useful AMD support at this point. Almost everyone uses Nvidia cards right now. They pretty much have a monopoly on the market right now.
