### ISSUE TITLE
--tolerance parameter,--show-distance true:

### ISSUE THREAD

**Issue by kksu49** [ageitgey/face_recognition#466]
* face_recognition version: 1.2.2
* Python version: 2.7
* Operating System:Ubuntu 17

### Description

--tolerance parameter

so I want to change the tolerance in my python code, but I can't find any examples 

### What I Did

```
I have tried put the tolerance value, before the compare method, but it did not work, so I want see an format example in python code. Thank you all ~ 
```

**Comment by ageitgey** [comment]
Check out the docs: http://face-recognition.readthedocs.io/en/latest/face_recognition.html#face_recognition.api.compare_faces

```python
results = face_recognition.compare_faces(known_face_encodings, face_encoding_to_check, tolerance=0.55)
```

**Comment by iamarunchauhan** [comment]
@ageitgey @kksu49 actually I want to pass show-distance true in "face_recognition.compare_faces" function not by setting this argument by command line. I'm unable to find how to set this show-distance value in my python file. Can you please guide ?
