### ISSUE TITLE
Which openface model does face_recognition module use for generating the 128 embeddings

### ISSUE THREAD

**Issue by yolob21** [ageitgey/face_recognition#468]
Trying to do transfer learning with the openface model using keras, need the name of the model which face_recognition module used so that I can correctly choose the model for exporting the weights

Thanks

**Comment by MLDSBigGuy** [comment]
resnet from dlib

**Comment by ageitgey** [comment]
This library uses a model from dlib. This library is totally unrelated to openface which has it's own models. The model used by this library is not compatible with Keras.
