### ISSUE TITLE
Face_landmarks missing two points.

### ISSUE THREAD

**Issue by sbourigault** [ageitgey/face_recognition#48]
* face_recognition version: last
* Python version: 2.7
* Operating System: Ubuntu 

### Description

The face_landmarks wrapper is missing two points from the _raw_face_landmarks output

### What I Did

I noticed the faces I draw using face_landmark were missing a bit of chin.
Turned out the chin only contains points 0 to 14 rather than 0 to 16. Two points are completely missing from the output.

Line where it happens : https://github.com/ageitgey/face_recognition/blob/master/face_recognition/api.py#L125

I'll see I have to time to contribute to try and correct this.

**Comment by oliroy** [comment]
Fyi there is a PR open with your suggested fix: https://github.com/ageitgey/face_recognition/pull/49

**Comment by sbourigault** [comment]
Indeed. I also opened a PR (my first one, I used the occasion to learn how to do a pull request) with nothing but this fix. #50 

Unfortunately, the Travis build failed precisely because the extra 3 output points are interpreted as a mistake.

Hopefully this can be adressed by @ageitgey.

**Comment by ageitgey** [comment]
Thanks, I'll take a look as soon as I have a free moment!
