### ISSUE TITLE
Installation Issue 

### ISSUE THREAD

**Issue by IarveJ** [ageitgey/face_recognition#487]
* face_recognition version: 
* Python version: 3 
* Operating System: Linux, PYNQ board

### Description
after I try to run python setup.py install 

running install
running bdist_egg
running egg_info
writing requirements to face_recognition.egg-info/requires.txt
writing face_recognition.egg-info/PKG-INFO
writing top-level names to face_recognition.egg-info/top_level.txt
writing dependency_links to face_recognition.egg-info/dependency_links.txt
writing entry points to face_recognition.egg-info/entry_points.txt
reading manifest file 'face_recognition.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no previously-included files matching '*.py[co]' found under directory '*'
warning: no files found matching '*.jpg' under directory 'docs'
warning: no files found matching '*.png' under directory 'docs'
warning: no files found matching '*.gif' under directory 'docs'
writing manifest file 'face_recognition.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-armv7l/egg
running install_lib
running build_py
creating build/bdist.linux-armv7l/egg
creating build/bdist.linux-armv7l/egg/face_recognition
copying build/lib.linux-armv7l-2.7/face_recognition/face_detection_cli.py -> build/bdist.linux-armv7l/egg/face_recognition
copying build/lib.linux-armv7l-2.7/face_recognition/__init__.py -> build/bdist.linux-armv7l/egg/face_recognition
copying build/lib.linux-armv7l-2.7/face_recognition/face_recognition_cli.py -> build/bdist.linux-armv7l/egg/face_recognition
copying build/lib.linux-armv7l-2.7/face_recognition/api.py -> build/bdist.linux-armv7l/egg/face_recognition
byte-compiling build/bdist.linux-armv7l/egg/face_recognition/face_detection_cli.py to face_detection_cli.pyc
byte-compiling build/bdist.linux-armv7l/egg/face_recognition/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-armv7l/egg/face_recognition/face_recognition_cli.py to face_recognition_cli.pyc
byte-compiling build/bdist.linux-armv7l/egg/face_recognition/api.py to api.pyc
creating build/bdist.linux-armv7l/egg/EGG-INFO
copying face_recognition.egg-info/PKG-INFO -> build/bdist.linux-armv7l/egg/EGG-INFO
copying face_recognition.egg-info/SOURCES.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying face_recognition.egg-info/dependency_links.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying face_recognition.egg-info/entry_points.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying face_recognition.egg-info/not-zip-safe -> build/bdist.linux-armv7l/egg/EGG-INFO
copying face_recognition.egg-info/requires.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying face_recognition.egg-info/top_level.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
creating 'dist/face_recognition-1.2.2-py2.7.egg' and adding 'build/bdist.linux-armv7l/egg' to it
removing 'build/bdist.linux-armv7l/egg' (and everything under it)
Processing face_recognition-1.2.2-py2.7.egg
removing '/usr/local/lib/python2.7/dist-packages/face_recognition-1.2.2-py2.7.egg' (and everything under it)
creating /usr/local/lib/python2.7/dist-packages/face_recognition-1.2.2-py2.7.egg
Extracting face_recognition-1.2.2-py2.7.egg to /usr/local/lib/python2.7/dist-packages
face-recognition 1.2.2 is already the active version in easy-install.pth
Installing face_detection script to /usr/local/bin
Installing face_recognition script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/face_recognition-1.2.2-py2.7.egg
Processing dependencies for face-recognition==1.2.2
Searching for Pillow
Reading https://pypi.python.org/simple/Pillow/
Download error on https://pypi.python.org/simple/Pillow/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) -- Some packages may not be found!
Couldn't find index page for 'Pillow' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) -- Some packages may not be found!
No local packages or download links found for Pillow
error: Could not find suitable distribution for Requirement.parse('Pillow')

**Comment by ageitgey** [comment]
This has nothing to do with this library. Basically your python installation is lacking SSL certificates and can't verify remote connections when trying to install the required library dependencies.

Try this to install ssl certificates to hopefully fix the issue: 

```
pip install --trusted-host pypi.python.org certifi
```
