### ISSUE TITLE
face_encodings return empty list

### ISSUE THREAD

**Issue by hoangdzung** [ageitgey/face_recognition#490]
* face_recognition version:1.2.2
* Python version:2.7.12
* Operating System:Ubuntu  16.04.4 LTS

### Description

I have an image dataset and half of them couldn't be encoded using face_encodings() function.
This is one of them:
![tr ng_hoa_binh_0018](https://user-images.githubusercontent.com/26489703/39851268-1ed5b136-5440-11e8-825c-d98893dbf208.png)
Firstly, I used load_image_file() and I got a numpy array with shape (182,182,3). There was no problem, but when I use the numpy array I've got with face_encodings(), it return [ ].

**Comment by ageitgey** [comment]
That means it didn't find any faces in the image to encode. By default, it tries to locate a face in the image before it encodes it. Since your image is already cropped to the face area, you can pass in `known_face_locations=[(0, width, height, 0]]` to tell it where the face is.

**Comment by rizasif** [comment]
That seems to work, thank you @ageitgey
