### ISSUE TITLE
how to let my webcam (not video mp4)run in cuda version

### ISSUE THREAD

**Issue by blairnan** [ageitgey/face_recognition#498]
* face_recognition version:1.22
* Python version:3.6
* Operating System:windows8

I read your cuda code but it make a example by video not webcam I run the opencv faster version but it looks slowly ,too. I am a new student in college,know not much about this.Hope you can help me ,thanks a lot !!!

**Comment by ageitgey** [comment]
There are several webcam examples listed that you can try out. All the examples will take advantage of cuda if you compile dlib with cuda support and have an Nvidia gpu.
