### ISSUE TITLE
face_encodings returns different values when given exact same image and using jitters=10

### ISSUE THREAD

**Issue by norvikgustav** [ageitgey/face_recognition#502]
* face_recognition version: 1.2.2
* Python version: 3.6.4
* Operating System: Windows 10

### Description
Hi! 
First of all; thank you for your awesome work. Fantastic!

I find some _distance_ differences when running the _face_recognition_ modules.
I traced it back to _face_encodings_ which gives different values on the 128 measurements when given the exact same image AND using '10' as jitter -value. 
   Shouldn't I get the exact same output when doing this?   (see code and output further down)
   Am I using the wrong syntax?
   (when using default jitter-value, I get the exact same output on all three. -> face_encodings("Selfie.jpg")[0]

Grateful for answers 

Cheers // g

### What I Did
Added "None" and "10" --->

import face_recognition
import cv2

training_image1_face_encoding = face_recognition.face_encodings(cv2.imread("SELFIE.jpg"), None, 10)[0]
training_image2_face_encoding = face_recognition.face_encodings(cv2.imread("SELFIE.jpg"), None, 10)[0]
training_image3_face_encoding = face_recognition.face_encodings(cv2.imread("SELFIE.jpg"), None, 10)[0]

known_face_encodings = [
    training_image1_face_encoding,
    training_image2_face_encoding,
    training_image3_face_encoding
]
print (str(known_face_encodings))

Output:  (the three first measurements of 128)

[array([-0.10088058,  0.08250218,  0.04085633,
array([-0.10413098,  0.07289482,  0.04550746,
array([-0.10535627,  0.08541356,  0.04277503,

**Comment by ageitgey** [comment]
Jitter is random, so the results will be slightly different each time.
