### ISSUE TITLE
Face Recognition in C++

### ISSUE THREAD

**Issue by Rencita** [ageitgey/face_recognition#506]
Hi,
I tried your Face Recognition library and recognized a few people in my company. It works amazing with a slight tweek of tolerance factor.
Is it possible to recognize using C++? Is it already available OR can you help me in figuring this?

Thanks in Advance

**Comment by ageitgey** [comment]
This library is really a wrapper around [dlib](http://dlib.net/), which is a C++ library. So you can just use dlib if you want to use C++ instead. Check out this example: http://dlib.net/dnn_face_recognition_ex.cpp.html

**Comment by uday60** [comment]
@ageitgey 

The link uses a clustering algorithm. However your using euclidean distance to calculate the index of the known entity. Can you share the same in c++ ?

Comparing vector<vector<double>> containing all the known encodings with the vector<vector<double>> of face_encodings.

**Comment by ageitgey** [comment]
You can just remove the part of the code that does clustering and just check the distance between one face and a list of known faces:

```c++ 
// test_face: descriptors for one unknown face to check
// face_descriptors[]: array of descriptors for all known faces

    for (size_t i = 0; i < face_descriptors.size(); ++i)
    {
            if (length(face_descriptors[i] - test_face) < 0.6)
                // Match!
                doSomethingWithMatch();
    }
```

**Comment by VijayaLakshmiArthanari** [comment]
> You can just remove the part of the code that does clustering and just check the distance between one face and a list of known faces:
> 
> ```c++
> // test_face: descriptors for one unknown face to check
> // face_descriptors[]: array of descriptors for all known faces
> 
>     for (size_t i = 0; i < face_descriptors.size(); ++i)
>     {
>             if (length(face_descriptors[i] - test_face) < 0.6)
>                 // Match!
>                 doSomethingWithMatch();
>     }
> ```

@ageitgey, Can you please share the full code to match the image with other image with single face?
