### ISSUE TITLE
Different encoding with same image file

### ISSUE THREAD

**Issue by lordcenzin** [ageitgey/face_recognition#508]
* face_recognition version: 1.2.2
* Python version: 2.7.15
* Operating System: Linux

### Description
I noticed that the same image gets different encodings if the face_encoding is called more than once. is it normal?
![file1](https://user-images.githubusercontent.com/30053696/40552378-c1414e34-603f-11e8-97d3-600080d7ae40.png)

### What I Did
```
import face_recognition as fr

a = fr.load_image_file(file1)
aa = fr.face_encodings(a, num_jitters=10)
b = fr.load_image_file(file1)
bb = fr.face_encodings(a, num_jitters=10)
print aa[0] == bb[0]
print aa[0]
print bb[0]

```

**Comment by ageitgey** [comment]
You are asking it to do 10 random jitters each time. Because the jittering is random, you'll get slightly different results each time. If you pass in 0, you'll get the same result each time.

**Comment by Essence9999** [comment]
> You are asking it to do 10 random jitters each time. Because the jittering is random, you'll get slightly different results each time. If you pass in 0, you'll get the same result each time.

encoding = face_recognition.face_encodings(known_image)
Same image and same code has different encoding, windows vs ubuntu
please help me
