### ISSUE TITLE
how to recognize person from far distance>2 meter?

### ISSUE THREAD

**Issue by vrushang25** [ageitgey/face_recognition#510]
* face_recognition version:0.1.6
* Python version:2.7
* Operating System:Ubuntu 16.04

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.
IMPORTANT: If your issue is related to a specific picture, include it so others can reproduce the issue.

### What I Did

here i tried to combine the dlib face detector and face recognition. i tried to get Location of face from dlib detector function and use that Location for face encoding and compare to database so that i can make far distance face recognition but i am getting error while encoding with "dats " part from API.Py file it is given as

File "v.py", line 72, in <module>
    face_encodings = face_recognition.face_encodings(small_frame, v)
  File "/usr/local/lib/python2.7/dist-packages/face_recognition/api.py", line 189, in face_encodings
    raw_landmarks = _raw_face_landmarks(face_image, known_face_locations)
  File "/usr/local/lib/python2.7/dist-packages/face_recognition/api.py", line 150, in _raw_face_landmarks
    face_locations = [_css_to_rect(face_location) for face_location in face_locations]
  File "/usr/local/lib/python2.7/dist-packages/face_recognition/api.py", line 44, in _css_to_rect
    return dlib.rectangle(css[3], css[0], css[1], css[2])
TypeError: 'int' object has no attribute '__getitem__'

My code is Here

import face_recognition
import cv2
import os
import numpy as np
from PIL import Image
import time
import urllib
import dlib
import sys

accuracy=0.45
cap = cv2.VideoCapture(1)

count=1
path='data'
detector = dlib.get_frontal_face_detector()
color_green = (0,255,0)
line_width = 3
img=[]
imagepath = [os.path.join(path,f)for f in os.listdir(path)]
imagepath.sort(key = lambda x: int(x[5:-4]))
c=len(imagepath)
for i in imagepath:
#while count<=c:	
	image = face_recognition.load_image_file(i)
	#i2=face_recognition.face_encodings(image)
	#print "this is image number"
	#print i
	img.append(face_recognition.face_encodings(image)[0])
	#time.sleep(1)
	count=count+1
	#print face_encoding
	#img.append(face_recognition.face_encodings(image))

face_locations = []
face_encodings = []
face_names = []
process_this_frame = True
img2 = []
img2 = img[0]
print"this is img2"
print img

while True:   
    #imgResp=urllib.urlopen(url)
    #imgNp=np.array(bytearray(imgResp.read()),dtype=np.uint8)
    #frame=cv2.imdecode(imgNp,-1)
    ret_val, frame = cap.read()
    rgb_image = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    dets = detector(rgb_image)
    small_frame = cv2.resize(frame, (0, 0), fx=0.25, fy=0.25) 
    #print small_frame 
    if process_this_frame:
       
        face_locations = face_recognition.face_locations(small_frame)
	print"this is face location"
	print face_locations
	for det in dets:
		print"this is dets value"
        	cv2.rectangle(frame,(det.left(), det.top()), (det.right(), det.bottom()), color_green, line_width)
		#print det.left()
		#print det.top()
		#print det.right()
		#print det.bottom()
		v = [det.top(),det.right(),det.bottom(),det.left()]
		print v
        face_encodings = face_recognition.face_encodings(small_frame, v)
	
        face_names = []
        for face_encoding in face_encodings:
           #print(face_recognition.face_distance(face_encoding, img))
           match = face_recognition.compare_faces(img, face_encoding,tolerance=accuracy)
           print match
           if match[0]==True:
               name = "vrushang"
	  # elif match[1]==True:
           #    name = "hitu"	
	  # elif match[6]==True:
	   #    name = "anil sir"
	   #elif match[5]==True:
            #   name = "Het"	
	   elif match[2]==True:
               name = "yaksh"
	   else:		
	   	name = "unknown"
           face_names.append(name)
    process_this_frame = not process_this_frame   
    for (top, right, bottom, left), name in zip(face_locations, face_names):
      
        top *= 4
        right *= 4
        bottom *= 4
        left *= 4

     
        cv2.rectangle(frame, (left, top), (right, bottom), (67, 23, 255), 2)

      
        cv2.rectangle(frame, (left, bottom - 35), (right, bottom), (67, 23, 255), cv2.FILLED)
        font = cv2.FONT_HERSHEY_SIMPLEX
        cv2.putText(frame, name, (left + 6, bottom - 6), font, 1.0, (255, 255, 255), 1)

   
    cv2.imshow('Face Recognizer by vrushang', frame)

   
    if cv2.waitKey(1)==27:
        break

# Release handle to the webcam
cap.release()
cv2.destroyAllWindows()

please help me for this problem

In dlib is it possible to do this task???

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by ageitgey** [comment]
This library just uses dlib behind the scenes. There's no reason to separately pull in dlib.

If the root issue is that you aren't able to detect faces far away from the camera, please read this: https://github.com/ageitgey/face_recognition/issues/333#issuecomment-362018429

**Comment by vrushang25** [comment]
Thank you:)
