### ISSUE TITLE
I downloaded the dat.bz2 file. What should I do?

### ISSUE THREAD

**Issue by acemi1** [ageitgey/face_recognition#511]
* face_recognition version: 
* Python version: 3.6.5
* Operating System: Windows

### Description

I get the following error message when I try to run face_recognition.py.
I downloaded the files "shape_predictor_5_face_landmarks.dat.bz2" and "dlib_face_recognition_resnet_model_v1.dat.bz2".
Now I do not know what to do.

### What I Did
I downloaded the files, I get the following error message

Call this program like this:
   ./face_recognition.py shape_predictor_5_face_landmarks.dat dlib_face_recognition_resnet_model_v1.dat ../examples/faces
You can download a trained facial shape predictor and recognition model from:
    http://dlib.net/files/shape_predictor_5_face_landmarks.dat.bz2
    http://dlib.net/files/dlib_face_recognition_resnet_model_v1.dat.bz2

Process finished with exit code 0

**Comment by ageitgey** [comment]
What is face_recognition.py? Are you sure you are actually using this library?

**Comment by acemi1** [comment]
I do not know,
http://dlib.net/face_recognition.py.html
