### ISSUE TITLE
does face_recognition integrate face alignment by default?

### ISSUE THREAD

**Issue by rocket1024** [ageitgey/face_recognition#512]
* face_recognition version:latest
* Python version:3.5
* Operating System:ubuntu16.04

### Description
does face_recognition integrate face alignment by default?
### What I Did
I found default find the face does not return with a face alignment

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by ageitgey** [comment]
Yes, when you call encode_faces(), it does face alignment before encoding the faces. But the aligned versions of the faces are not exposed anywhere in the API.

**Comment by rocket1024** [comment]
thanks for the quick reply, so my intention is to save up alignment face, so now there is no way to do it?

**Comment by ageitgey** [comment]
Why do you want the aligned images? What are you trying to do?

**Comment by rocket1024** [comment]
after we crop image and get face alignment, try to use these data to do the training, we not going to recognize but to give each face a symmetric score,

**Comment by ageitgey** [comment]
Ok, got it. Unfortunately this library won't be able to do that. 

Just a guess, but a basic face alignment affine transform probably won't work for symmetry since it distorts the face. You might have to try something more complicated that does a 3d projection.
