### ISSUE TITLE
Circleci integration

### ISSUE THREAD

**Issue by Meemaw** [ageitgey/face_recognition#513]
* face_recognition version: face-recognition==1.2.2
* Python version: Dockerfile
* Operating System: Dockerfile

### Description
Hey, I'm trying to get my app working on circleCI. I am building it inside docker. I'm using the Dockerfile from this repository.

I am able to build/run app locally, but pip install fails on circle CI when building dlib?

Stack trace can be seen here: https://circleci.com/api/v1.1/project/github/Meemaw/Idify/21/output/103/0?file=true

Everything else can be found at:
https://github.com/Meemaw/Idify

**Comment by tomul** [comment]
Hi @Meemaw did you manage to get through the circleCI build, i'm having the same issue.
Thanks

**Comment by Meemaw** [comment]
No, I switched to travis.

**Comment by chrismo** [comment]
Leaving this behind as none of the hits when I Googled for this problem had this as an answer: You probably need more memory. Even the xlarge size currently isn't enough in our case.

https://github.com/davisking/dlib/issues/2261#issuecomment-744115606
