### ISSUE TITLE
Intel Movidius

### ISSUE THREAD

**Issue by turowicz** [ageitgey/face_recognition#522]
### Description

Is it possible to accelerate the execution of face recognition by exposing an Intel Movidius stick to it?

It's a very cheap way of getting certain AI problems off the CPU and it gives pretty good results.

Link: https://developer.movidius.com/

**Comment by sadimoodi** [comment]
thats a good question, wish we could use this stick to expedite processing....

**Comment by ageitgey** [comment]
Intel Movidius acceleration would have to be added to dlib. It's not currently supported. Maybe someone adventurous could contribute this to dlib and see if @davisking was interested in accepting it. But without doing any actual research, I'm guessing it wouldn't be a small amount of work and would add a decent amount of complexity to the dlib codebase which might not be desirable.

See:
- https://github.com/davisking/dlib/issues/401#issuecomment-351320916
- https://github.com/davisking/dlib/issues/1121

**Comment by davisking** [comment]
I'm fine with it if someone wants to do the work.

**Comment by vrushang25** [comment]
I want to work with this movidius stick but will it be supportive in Raspberry pi?
