### ISSUE TITLE
Provide (signed) release tarballs

### ISSUE THREAD

**Issue by hlef** [ageitgey/face_recognition#53]
Hi,

I'd like to package face_recognition for Debian. It would be very convenient if you could provide release tarballs.

Additionally, you might consider signing your releases. You can find more informations about it [here](https://wiki.debian.org/Creating%20signed%20GitHub%20releases).

Cheers,
Hugo (hle)

**Comment by ageitgey** [comment]
Thanks, that's great! I'll tag and sign the next release (which should be today).

**Comment by ageitgey** [comment]
Let me know if this works for you: https://github.com/ageitgey/face_recognition/releases
