### ISSUE TITLE
I am stuck with python3 setup.py install --yes USE_AVX_INSTRUCTIONS

### ISSUE THREAD

**Issue by EsraaQandel** [ageitgey/face_recognition#531]
* Python version: 3
* Operating System: Ubuntu 16.06 -lightsail instance 

### Description

I am trying to get dlib so I can run my face_recognition based app.
I followed the instructions in the docker file, installed all the required and then when running 
`python3 setup.py install --yes USE_AVX_INSTRUCTIONS`

I get stuck with Invoking Cmake build as it starts loading but never gets to 100% 

### What I Did

```
ubuntu@ip-172-26-0-63:~/dlib$ sudo python3 setup.py install --yes USE_AVX_INSTRUCTIONS
running install
running bdist_egg
running egg_info
writing top-level names to dlib.egg-info/top_level.txt
writing dependency_links to dlib.egg-info/dependency_links.txt
writing dlib.egg-info/PKG-INFO
package init file 'dlib/__init__.py' not found (or not a regular file)
reading manifest file 'dlib.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'dlib.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
Invoking CMake setup: 'cmake /home/ubuntu/dlib/tools/python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/ubuntu/dlib/build/lib.
linux-x86_64-3.5 -DPYTHON_EXECUTABLE=/usr/bin/python3 -DUSE_AVX_INSTRUCTIONS=yes -DCMAKE_BUILD_TYPE=Release'
-- pybind11 v2.3.dev0
-- Enabling AVX instructions
-- Searching for BLAS and LAPACK
-- Searching for BLAS and LAPACK
-- Checking for module 'cblas'
--   No package 'cblas' found
-- Found LAPACK library
-- Found BLAS library
-- C++11 activated.
-- Found Python with installed numpy package
-- Numpy include path '/usr/lib/python3/dist-packages/numpy/core/include'
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/dlib/build/temp.linux-x86_64-3.5
Invoking CMake build: 'cmake --build . --config Release -- -j1'
[  1%] Building CXX object dlib_build/CMakeFiles/dlib.dir/global_optimization/global_function_search.cpp.o
```

**Comment by ageitgey** [comment]
How long did you wait? Did it stop at 1% or ever get further?

My initial guess would just be that your instance doesn't have enough ram to run the compilier. Try a bigger instance. But typically in that case it would freeze up later on some of the bigger files.

**Comment by EsraaQandel** [comment]
I waited for almost 30 min but then the instance keeps disconnecting... 
It once reached 38% but never goes further!

Aha I see! My instance is 512 MB, so probably your initial guess is in the right place, but 512MB is the size provided during the free trial so I will either pay for external storage and attache it to the instance or try Google cloud free trial plan.

Hopefully, that will fix it inshaAllah! 

Thanks!

**Comment by ageitgey** [comment]
If you know how, you might also want to check the virtual memory/swap file settings on that linux instance. You may be able to work around the problem by just enabling or increasing the size of the swap file during the compilation process.

Check out this for a guide: https://blog.metova.com/how-to-enable-swapfile-on-ubuntu-aws-instances/

**Comment by EsraaQandel** [comment]
The swap file thing is not really straightforward for a newbie like myself and even attaching external storage didn't fix it for me!
I tried a bigger instance and dlib was successfully installed. It sounds like deleting the instance before a month will not charge me anything and that is enough time for me to try it before paying for it!

Following the docker file made my life easier! Thanks

**Comment by ageitgey** [comment]
Glad it worked! :-)

**Comment by EsraaQandel** [comment]
Now that I have everything successfully installed, I am stuck with
`'NameError: global name 'face_recognition' is not defined` 
(Please let me know If I should open a new issue for it)

### Description
I made a simple web service based on the Face Recognition API using Flask, it is simply a form that takes in a person's image, name and id to store it to a db (for the image we store it's encoding). 

I executed it with python3 on my local machine and it worked perfectly but after deploying it to AWS when I upload the photo to the server it responds with:

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

Here is what the error log gives:
```
ubuntu@ip-172-26-9-5:~$ sudo tail -f /var/log/apache2/error.log
[Sat Jun 16 16:36:39.980677 2018] [wsgi:error] [pid 3558:tid 140391063971584]     reraise(exc_type, exc_value, tb)
[Sat Jun 16 16:36:39.980679 2018] [wsgi:error] [pid 3558:tid 140391063971584]   File "/usr/lib/python2.7/dist-packages/fl
ask/app.py", line 1475, in full_dispatch_request
[Sat Jun 16 16:36:39.980682 2018] [wsgi:error] [pid 3558:tid 140391063971584]     rv = self.dispatch_request()
[Sat Jun 16 16:36:39.980684 2018] [wsgi:error] [pid 3558:tid 140391063971584]   File "/usr/lib/python2.7/dist-packages/fl
ask/app.py", line 1461, in dispatch_request
[Sat Jun 16 16:36:39.980687 2018] [wsgi:error] [pid 3558:tid 140391063971584]     return self.view_functions[rule.endpoin
t](**req.view_args)
[Sat Jun 16 16:36:39.980689 2018] [wsgi:error] [pid 3558:tid 140391063971584]   File "/var/www/CaptureIt/Face_recognition
_API/service.py", line 73, in upload_image
[Sat Jun 16 16:36:39.980692 2018] [wsgi:error] [pid 3558:tid 140391063971584]     return detect_faces_in_image(file,name,
ID)
[Sat Jun 16 16:36:39.980694 2018] [wsgi:error] [pid 3558:tid 140391063971584]   File "/var/www/CaptureIt/Face_recognition
_API/service.py", line 119, in detect_faces_in_image
[Sat Jun 16 16:36:39.980696 2018] [wsgi:error] [pid 3558:tid 140391063971584]     img = face_recognition.load_image_file(
file_stream)
[Sat Jun 16 16:36:39.980699 2018] [wsgi:error] [pid 3558:tid 140391063971584] NameError: global name 'face_recognition' i
s not defined
```

Thanks in advance!

**Comment by ageitgey** [comment]
Without seeing the full code and knowing how you installed things on AWS, I can't be sure. But it looks like you are running your code with python 2 on AWS instead of python 3. Is it possible you only installed face recognition for python 3 but then ran your code using python 2?

**Comment by EsraaQandel** [comment]
## Here is the case
- I have face_recognition only installed for python 3 
- AWS by default uses Python 2 and thus when running my site the error log complains that there is no Module named Face_recogintion
- My site is just for testing and is really nothing more than the code you have in [web_service_example.py](https://github.com/ageitgey/face_recognition/blob/master/examples/web_service_example.py)


## Things I tried
1- I installed face_recognition for python2 because, as you mentioned in the documentation, the API is fine with python2.7 as well as python3 but then I had the error 
`'NameError: global name 'face_recognition' is not defined`

2- I gave up on python2 and decided to go back and force the server to execute using python3 I did that by changing the first line of my wsgi file from
`#!/usr/bin/python` to `#!/usr/bin/python3`
and then uninstalled the face_recognition for python2 just to make sure the server is using python3 but still got the same error `'NameError: global name 'face_recognition' is not defined`

## What I have noticed
Whether the server is executing using python2 or python3, The error log gives the same errors, the server only looks at the dist-packages in python2.7 as you can tell from the first 2 lines in the error log:

```
ubuntu@ip-172-26-9-5:~$ sudo tail -f /var/log/apache2/error.log
[Sat Jun 16 16:36:39.980677 2018] [wsgi:error] [pid 3558:tid 140391063971584]     reraise(exc_type, exc_value, tb)
[Sat Jun 16 16:36:39.980679 2018] [wsgi:error] [pid 3558:tid 140391063971584]   File "/usr/lib/python2.7/dist-packages/fl
ask/app.py", line 1475, in full_dispatch_request
[Sat Jun 16 16:36:39.980682 2018] [wsgi:error] [pid 3558:tid 140391063971584]     rv = self.dispatch_request()
[Sat Jun 16 16:36:39.980684 2018] [wsgi:error] [pid 3558:tid 140391063971584]   File "/usr/lib/python2.7/dist-packages/fl
ask/app.py", line 1461, in dispatch_request
[Sat Jun 16 16:36:39.980687 2018] [wsgi:error] [pid 3558:tid 140391063971584]     return self.view_functions[rule.endpoin
t](**req.view_args)
[Sat Jun 16 16:36:39.980689 2018] [wsgi:error] [pid 3558:tid 140391063971584]   File "/var/www/CaptureIt/Face_recognition
_API/service.py", line 73, in upload_image
[Sat Jun 16 16:36:39.980692 2018] [wsgi:error] [pid 3558:tid 140391063971584]     return detect_faces_in_image(file,name,
ID)
[Sat Jun 16 16:36:39.980694 2018] [wsgi:error] [pid 3558:tid 140391063971584]   File "/var/www/CaptureIt/Face_recognition
_API/service.py", line 119, in detect_faces_in_image
[Sat Jun 16 16:36:39.980696 2018] [wsgi:error] [pid 3558:tid 140391063971584]     img = face_recognition.load_image_file(
file_stream)
[Sat Jun 16 16:36:39.980699 2018] [wsgi:error] [pid 3558:tid 140391063971584] NameError: global name 'face_recognition' i
s not defined
```

## I have 2 options now

1- To continue with python3 and try to some how force the server to check the dist-packages for python3 and see how it goes 

2- Or to try python2 and rebuild dlib with it's all required packages, reinstall face_recognition with pip2 instead of pip3 and see how it goes 

Which option do you recommend or maybe you have another idea?

Thanks
