### ISSUE TITLE
face_recognition does not quit on pressing 'q' on a Mac.

### ISSUE THREAD

**Issue by chanakyashah** [ageitgey/face_recognition#532]
* face_recognition version: 1.2.2
* Python version: 3.6.5
* Operating System: MacOS High Sierra 10.13.5

### Description

The python script fails to quit on pressing 'q' as per the code on a Mac. However, it works perfectly fine on my Windows Laptop. Is this a known bug or I have done something wrong?

### What I Did

```
    # Hit 'q' on the keyboard to quit!
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# Release handle to the webcam
video_capture.release()
cv2.destroyAllWindows()

# Prints out the time of recognition and name of the person recognised
print(c)
print(present)
```

**Comment by ageitgey** [comment]
It works for me (I'm on a mac). But it could take a second to respond and it might be that you have the wrong window active when you are pressing 'q'? Just a guess.

**Comment by chanakyashah** [comment]
So it's working on my friends Mac which has 16gb RAM and is the latest one. However, everything return to normal if I shutdown the kernel or interrupt it. I am not sure why its happening on my laptop.
