### ISSUE TITLE
face_recognition missing module

### ISSUE THREAD

**Issue by sheepy928** [ageitgey/face_recognition#537]
* face_recognition version: 1.2.2
* Python version: 3.6.5, Anaconda 5.1.0
* Operating System: Windows10 x64 1803

It seems that the installation of face_recognition is not complete. The screenshot of the installation folder is shown below.

When I opened that demo of face_recognition in VS Code, there were lots of errors (from pylint):
    Module 'face_recognition' has no 'compare_faces' member
    Module 'face_recognition' has no 'load_image_file' member

When running .py:

Traceback (most recent call last):
  File "f:\OneDrive\Programming\Python\Project\Face Recognition\face_recognition.py", line 1, in <module>
    import face_recognition
  File "f:\OneDrive\Programming\Python\Project\Face Recognition\face_recognition.py", line 17, in <module>
    obama_image = face_recognition.load_image_file("obama.jpg")
AttributeError: module 'face_recognition' has no attribute 'load_image_file'

![8](https://user-images.githubusercontent.com/35769263/41497886-aef5294a-7191-11e8-905d-9eea970b6ba1.png)
![9](https://user-images.githubusercontent.com/35769263/41497887-af35d6ca-7191-11e8-9533-291af9f98932.png)

**Comment by ageitgey** [comment]
```
File "f:\OneDrive\Programming\Python\Project\Face Recognition\face_recognition.py", line 1, in 
import face_recognition
```

The problem is that you called your own file `face_recognition.py`. So `import face_recognition` just re-imports your own file, not the library. You need to rename your file a different name.

**Comment by sheepy928** [comment]
It works after I changed the file name, thx!

**Comment by hemanthnielit** [comment]
import face recognition as fr

face_detect =fr.facedetection(image)



using above code  i'm getting face recognition has no attribute nam fcae detection
