### ISSUE TITLE
Don't want read photo from the phone (REAL-TIME FACE RECOGNITION)

### ISSUE THREAD

**Issue by furkankaradas** [ageitgey/face_recognition#538]
Hi,
I develop platform using real-time face recognition. But I am confronted with a security problem. I don't want read photo from the phone (FIGURE - 1). Actually, I tried a few methods. For instance, when each frame is taken, I checked coordinates and determined some tolerance values. If frame had below tolerance values, I did take out. I couldn't be successful but reduced error margin. How can I overcome this problem?
Thank you.
![FIGURE - 1](https://user-images.githubusercontent.com/22975926/41502952-4c18cca8-71cf-11e8-9678-eb1b29fbaad9.PNG)
(FIGURE - 1)

**Comment by sandeep17628** [comment]
Exactly - I also need only to recognize people in video Not images. Pls let me know how to do it.

**Comment by xugaoxiang** [comment]
@sandeep17628 , read video frame by frame and do recognization.

**Comment by navalchand** [comment]
Hope i can relate to your question. 

**Requirement**
```
How can we distinguish between a real face and face which is printed or displayed.
```

If this is what you need to identify please find below solution.

> 1. face_recognition and identify.
> 2. Add an object detection.
> 3. Check for intersecting areas of objects in image and face locations.

This can solve the above problem and you can also use the above for **Visual Relationship Detection Track**.  Reference : https://storage.googleapis.com/openimages/web/challenge.html

Combination of face_recognition and Visual Relationship Detection Track can lead to many use cases.
