### ISSUE TITLE
QUESTION: Transformation when generating encodings

### ISSUE THREAD

**Issue by lordcenzin** [ageitgey/face_recognition#544]
* face_recognition version: 1.2.2
* Python version: 2.7
* Operating System: Linux

### Description
in your [post on Medium](https://medium.com/@ageitgey/machine-learning-is-fun-part-4-modern-face-recognition-with-deep-learning-c3cffc121d78), section "Running yourself" you say: 

> 2. Figure out the pose of the face by finding the main landmarks in the face. Once we find those landmarks, use them to warp the image so that the eyes and mouth are centered.
> 3. Pass the centered face image through a neural network that knows how to measure features of the face. Save those 128 measurements.

Then you suggest to use the face_recognition library, as i am doing :+1: 
However, does it mean the face_encodings automatically performs such "warp"...so that eyes and mouth are centered"?

Thanks

**Comment by ageitgey** [comment]
Yep, it does it automatically!
