### ISSUE TITLE
Question about n_neighbors in face_recognition_knn.py?

### ISSUE THREAD

**Issue by xugaoxiang** [ageitgey/face_recognition#555]
* face_recognition version: git latest 
* Python version: 3.6.4
* Operating System: ubuntu 18.04 64bit

### Description

In file face_recognition_knn.py, training the model, n_neighbors = 2, but when predict , n_neighbors = 1.
 
Two questions, 
1 The meaning of n_neighbors?
2 Can I change the value of n_neighbors to reach high accuracy?(I now use the module to recognize people from ip camera by rtsp protocol, the project was not doing well when the first few frames come, so it needs many seconds.)

Thanks.

**Comment by mrazimi** [comment]
How Can I get accuracy results from KNN example code?

**Comment by ageitgey** [comment]
`n_neighbors` is the number of neighbors it looks for using the KNN algorithm to find the nearest neighbor. If you read up on the KNN algorithm itself, it will make more sense.

If you want to try a different approach for your IP camera, maybe check out this method instead: https://www.pyimagesearch.com/2018/06/18/face-recognition-with-opencv-python-and-deep-learning/

It adds a simple voting algorithm that might improve accuracy in your use case.

**Comment by xugaoxiang** [comment]
@ageitgey ,thanks a lot.
