### ISSUE TITLE
 Enhance FPS with IP cameras

### ISSUE THREAD

**Issue by AndreWicked** [ageitgey/face_recognition#562]
* face_recognition version: 1.2.2
* Python version: 3.5
* Operating System: Windows 10 x64

Hello. The situation is this, I use the opencv and face_recognition library to recognize faces from ip cameras, I get the image in a separate thread and I transfer it to the main one where the faces are searched, the problem is that fps does not exceed 4. In this case, the CPU is loaded only by 30% and the GPU on 50%, to search for individuals I use the model CNN, resolution 720p, have ideas how to increase fps?

**Comment by ageitgey** [comment]
Check out this demo: https://github.com/ageitgey/face_recognition/blob/master/examples/find_faces_in_batches.py

If you are able to send batches of faces to the GPU, it will have higher throughput and use more of the GPU.

**Comment by AndreWicked** [comment]
Thanks a lot for the answer, but I tried this example, he gives me an out of memory error, tried to change the batch size, and still this error, gtx1050ti card with 4GB on board.

**Comment by AndreWicked** [comment]
Maybe there is an opportunity to realize the search for faces not in every frame, but let's say 1 time for 3 frames, I think it should increase fps.
