### ISSUE TITLE
Unable to locate face

### ISSUE THREAD

**Issue by zijing-wu** [ageitgey/face_recognition#566]
* Python version: 3.5
* Operating System: Ubuntu 16.04

### Description
I am trying to follow the [https://github.com/ageitgey/face_recognition/blob/master/examples/recognize_faces_in_pictures.py](url) to recognize faces. However, it always fails to locate faces with `face_recognition.face_encodings` function.

### What I Did
Because I need to detect small faces (face area about 30*30), I followed #276 and set number_of_times_to_upsample to larger values (I tried 2 to 5). Also, I tried to change the hog model to cnn model. But it still doesn't work.

Then I tried to separate the steps. I followed [https://github.com/ageitgey/face_recognition/blob/master/examples/find_faces_in_picture_cnn.py](url) to find the face location first and supplied the locations to `face_recognition.face_encodings` function.
Using 
`face_location = face_recognition.face_locations(img, number_of_times_to_upsample=2, model="cnn")[0]`
I can get face locations without problem.
However, 
`face_recognition.face_encodings(img, known_face_locations=face_location)[0]`
still cannot get the encoding.

@ageitgey Do you know how to solve this problem? Thank you!

**Comment by ageitgey** [comment]
known_face_locations expects an array, not a single face. Try passing in an array instead of just one face:

face_recognition.face_encodings(img, known_face_locations=[face_location])[0]

**Comment by zijing-wu** [comment]
It works after I just pass the array `face_recognition.face_locations` returns to `face_encodings`
Thank you!

**Comment by ageitgey** [comment]
Glad to help :)
