### ISSUE TITLE
C port of this lib?

### ISSUE THREAD

**Issue by boehm-e** [ageitgey/face_recognition#58]
Is there a c port of this library (in order to improve the poor framerate i got ?)
Thx :)

**Comment by ageitgey** [comment]
Not of this library. But if you are using C++, you can just use `dlib` directly without needing this library. Here's an example: http://dlib.net/dnn_face_recognition_ex.cpp.html

**Comment by mbnoimi** [comment]
@ageitgey I've tested this lib and I got fantastic results so I wonder in case I used dlib directly depending in [this example](http://dlib.net/dnn_face_recognition_ex.cpp.html) do you expect to get same results?

**Comment by ageitgey** [comment]
Yep, you should get the same results!
