### ISSUE TITLE
Can face_recognition  perform facial expression recognition? Such as happiness, anxiety, etc.

### ISSUE THREAD

**Issue by movehaolv** [ageitgey/face_recognition#593]
Face recognition program is mainly used to identify Poeple. Does face_recognition  has perform facial expression recognition? Such as happiness, anxiety, etc. 

Thank you in advance.

**Comment by ageitgey** [comment]
Nope, emotion detection is not a feature of this library.

**Comment by sandipJava** [comment]
@ageitgey , how I can achieve emotion feature using this library

**Comment by ageitgey** [comment]
That is not a feature if this library.
