### ISSUE TITLE
Unexpected keyword argument 'mode' with imread()

### ISSUE THREAD

**Issue by raphadasilva** [ageitgey/face_recognition#6]
* face_recognition version: 0.1.0
* Python version: 3.4
* Operating System: GNU/Linux Debian (Jessie)

### Description

I'm trying to make just a few tests inspirer by the repo's examples.

### What I Did

```
import face_recognition as fr

image = fr.load_image_file('my_pic.jpg')
```
### The error

```
----> 3 image = fr.load_image_file('my_pic.jpg')

/usr/local/lib/python3.4/dist-packages/face_recognition/api.py in load_image_file(filename, mode)
     60     :return: image contents as numpy array
     61     """
---> 62     return scipy.misc.imread(filename, mode=mode)
     63 
     64 

TypeError: imread() got an unexpected keyword argument 'mode'
```
Thanks in advance !

**Comment by ageitgey** [comment]
It seems like the `mode` parameter was added to `scipy` in [version 0.17](https://github.com/scipy/scipy/commit/d00861911e012bfc70cace4f0d88f6bea01a307b).

Can you try updating scipy? Maybe this would work:

```
pip install --upgrade scipy
```

If that solves the issue, I'll update this library to make sure it requires scipy 0.17+ to prevent this issue in the future.

**Comment by ageitgey** [comment]
The update is in #7

**Comment by ageitgey** [comment]
Ok, I merged the fix. Let me know if that doesn't fix it.
