### ISSUE TITLE
face_recognition.face_encodings(...) doesn't work on multiprocessing

### ISSUE THREAD

**Issue by DQ0408** [ageitgey/face_recognition#602]
* face_recognition version:lastest
* Python version:3.6
* Operating System:Ubuntu16.04

### Description

I was trying to put face_recognition.face_encodings on multiprocessing cause it's time consuming.
But it seems like face_recognition didn't do anything on sub process.

### What I Did
    import cv2
    import face_recognition as fr
    import os
    import numpy as np
    from multiprocessing import Process,Pool
    img_list = []
    def multi_process(img):
        cnt=img_list.index( img)+1
        print(cnt)
        locations=fr.face_locations(img,number_of_times_to_upsample=2,model="cnn")
        print(cnt,locations)
        out_path = "./test/faces"
    
        encs = fr.face_encodings(img, locations, 500)
    
        for index, location in enumerate(locations):
            print(out_path + "/%d_%d_%d_%d_%d_%d.jpg" % (cnt, index, location[1], location[0]
                                                         , location[3], location[2]))
            img = cv2.rectangle(img, (location[1], location[0]), (location[3], location[2]), (0, 255, 0), 1)
    
            if not os.path.exists(out_path):
                os.makedirs(out_path)
            cv2.imwrite(out_path + "/%d_%d_%d_%d_%d_%d.jpg" % (cnt, index, location[1], location[0]
                                                               , location[3], location[2]), img)
            np.save(out_path + "/%d_%d" % (cnt, index), encs[index])
    def preprocess(video_path):
        cap=cv2.VideoCapture(video_path)
        cnt=0
        out_path="./test/faces"
        while True:
            _,img=cap.read()
            cnt+=1
            if img is None:
                break
            img_list.append(img)
        pro_cnt=32
        print(len(img_list))
        locations = fr.face_locations(img_list[0], number_of_times_to_upsample=2, model="cnn")
        print(locations)
        for i in range(len(img_list)//pro_cnt):
            p = Pool(pro_cnt)
            for img_i in img_list[i*pro_cnt:i*pro_cnt+pro_cnt]:
                p.apply_async(multi_process,(img_i,))
            p.close()
            p.join()
    if __name__=="__main__":
        video_path ="/path/to/test.avi" 
        data_base = "./test"
        start=time.time()
        preprocess(video_path)
        end=time.time()
        print(end-start)

###Thanks
Pretty thank you all for watching my stupid issue.

**Comment by DQ0408** [comment]
import cv2
import face_recognition as fr
import os
import numpy as np
from raw_cluster import raw_cluster
from multiprocessing import Process,Pool
img_list = []
def multi_process(img):
    cnt=img_list.index( img)+1
    print(cnt)
    locations=fr.face_locations(img,number_of_times_to_upsample=2,model="cnn")
    print(cnt,locations)
    out_path = "./test/faces"

    encs = fr.face_encodings(img, locations, 500)

    for index, location in enumerate(locations):
        print(out_path + "/%d_%d_%d_%d_%d_%d.jpg" % (cnt, index, location[1], location[0]
                                                     , location[3], location[2]))
        img = cv2.rectangle(img, (location[1], location[0]), (location[3], location[2]), (0, 255, 0), 1)

        if not os.path.exists(out_path):
            os.makedirs(out_path)
        cv2.imwrite(out_path + "/%d_%d_%d_%d_%d_%d.jpg" % (cnt, index, location[1], location[0]
                                                           , location[3], location[2]), img)
        np.save(out_path + "/%d_%d" % (cnt, index), encs[index])
def preprocess(video_path):
    cap=cv2.VideoCapture(video_path)
    cnt=0
    out_path="./test/faces"
    while True:
        _,img=cap.read()
        cnt+=1
        if img is None:
            break
        img_list.append(img)
    pro_cnt=32
    print(len(img_list))
    locations = fr.face_locations(img_list[0], number_of_times_to_upsample=2, model="cnn")
    print(locations)
    for i in range(len(img_list)//pro_cnt):
        p = Pool(pro_cnt)
        for img_i in img_list[i*pro_cnt:i*pro_cnt+pro_cnt]:
            p.apply_async(multi_process,(img_i,))
        p.close()
        p.join()
if __name__=="__main__":
    video_path ="/path/to/***.avi" 
    data_base = "./test"
    start=time.time()
    preprocess(video_path)
    end=time.time()
    print(end-start)

**Comment by DQ0408** [comment]
`import cv2
import face_recognition as fr
import os
import numpy as np
from raw_cluster import raw_cluster
from multiprocessing import Process,Pool
img_list = []
def multi_process(img):
    cnt=img_list.index( img)+1
    print(cnt)
    locations=fr.face_locations(img,number_of_times_to_upsample=2,model="cnn")
    print(cnt,locations)
    out_path = "./test/faces"

    encs = fr.face_encodings(img, locations, 500)

    for index, location in enumerate(locations):
        print(out_path + "/%d_%d_%d_%d_%d_%d.jpg" % (cnt, index, location[1], location[0]
                                                     , location[3], location[2]))
        img = cv2.rectangle(img, (location[1], location[0]), (location[3], location[2]), (0, 255, 0), 1)

        if not os.path.exists(out_path):
            os.makedirs(out_path)
        cv2.imwrite(out_path + "/%d_%d_%d_%d_%d_%d.jpg" % (cnt, index, location[1], location[0]
                                                           , location[3], location[2]), img)
        np.save(out_path + "/%d_%d" % (cnt, index), encs[index])
def preprocess(video_path):
    cap=cv2.VideoCapture(video_path)
    cnt=0
    out_path="./test/faces"
    while True:
        _,img=cap.read()
        cnt+=1
        if img is None:
            break
        img_list.append(img)
    pro_cnt=32
    print(len(img_list))
    locations = fr.face_locations(img_list[0], number_of_times_to_upsample=2, model="cnn")
    print(locations)
    for i in range(len(img_list)//pro_cnt):
        p = Pool(pro_cnt)
        for img_i in img_list[i*pro_cnt:i*pro_cnt+pro_cnt]:
            p.apply_async(multi_process,(img_i,))
        p.close()
        p.join()
if __name__=="__main__":
    video_path ="/path/to/***.avi" 
    data_base = "./test"
    start=time.time()
    preprocess(video_path)
    end=time.time()
    print(end-start)`

**Comment by DQ0408** [comment]
[https://github.com/ageitgey/face_recognition/issues/478](url)

**Comment by DQ0408** [comment]
老哥

**Comment by DQ0408** [comment]
@windforce7 老哥，我的服务器有四块显卡，所以要想并行处理图片只能开四个进程把任务部署到四个显卡上吗？

**Comment by windforce7** [comment]
Go to api.py and adapt
```python
face_detector = dlib.get_frontal_face_detector()
```
to
```
import dlib.cuda as cuda

cuda.set_device(0)
face_detector_0 = dlib.get_frontal_face_detector()
cuda.set_device(1)
face_detector_1 = dlib.get_frontal_face_detector()
```
and do this to all other "dlib." resources (and relevant functions too). Then you can execute tasks on each cards. Threads are always more convenient than processes.
