### ISSUE TITLE
I don't want to use GPU, what should I do(┬＿┬)

### ISSUE THREAD

**Issue by DQ0408** [ageitgey/face_recognition#604]
* face_recognition version:1.2.2
* Python version:3.6.5
* Operating System:Ubuntu16.04

### Description
Dear ageigey,
  If I don't want to use GPU to speed up the codes, what should I do? I just want to use cpu to run the codes. When I ran my code by  CUDA_VISIBLE_DEVICES="" python xxx.py, I got a error said that "RuntimeError: Error while calling cudaGetDevice(&the_device_id) in file /tmp/pip-install-qhoqkpna/dlib/dlib/cuda/gpu_data.cpp:178. code: 38, reason: no CUDA-capable device is". But if i run my code on Windows, there is no problem though my Windows machine doesn't have a GPU.

**Comment by ageitgey** [comment]
Did you compile dlib with CUDA support? Just recompile dlib without CUDA support and it won't ever try to use a GPU.

**Comment by DQ0408** [comment]
THX... It worked~
