### ISSUE TITLE
Intel MKL FATAL ERROR: Cannot load libmkl_core.dylib.

### ISSUE THREAD

**Issue by jsniff** [ageitgey/face_recognition#61]
When I run program, I also get following error:

Intel MKL FATAL ERROR: Cannot load libmkl_core.dylib.

Anybody have any work around?

**Comment by jsniff** [comment]
think i got it :  export DYLD_LIBRARY_PATH=/path/to/libmkl/lib:$DYLD_LIBRARY_PATH

**Comment by ageitgey** [comment]
Nice! That should do it.
