### ISSUE TITLE
Image encoding

### ISSUE THREAD

**Issue by rakibulislam01** [ageitgey/face_recognition#618]
* face_recognition version: 1.2.2
* Python version: 3.6
* Operating System: Ubuntu

### Description

How can I encode many images at a time? [https://github.com/ageitgey/face_recognition/blob/master/examples/facerec_from_webcam_faster.py#L17-L32]
Hare, one encoding for one image. I want to encode many images at a time.

**Comment by khaerulumam42** [comment]
This is part of my code using more than one image for every class 

`import os
import cv2
import face_recognition as fr
import pickle
import os
import json

dirname, filename = os.path.split(os.path.abspath(__file__))
path = os.path.join(dirname,'dataset')

all_face = {}
encodings = []
names = []
for name in os.listdir(path):
    folder_kelas = os.path.join(path,name)
    for image in os.listdir(folder_kelas):
        img = fr.load_image_file(os.path.join(folder_kelas, image))
        encoding = fr.face_encodings(img)[0]
        encodings.append(encoding)
        names.append(name)
all_face = {"encodings":encodings, "names":names}
with open('encodings.dat', 'wb') as f:
    pickle.dump(all_face, f)
`
