### ISSUE TITLE
AttributeError:' No attribute 'load_image_file'

### ISSUE THREAD

**Issue by Ayiruss** [ageitgey/face_recognition#62]
* face_recognition version: 0.1.11
* Python version: 3.4.4
* Operating System: Ubuntu 16.04 LTS

### Description

AttributeError: 'module' object has no attribute 'load_image_file'

### What I Did
I have installed face_recognition using pip install face_recognition.
When I try to use the function load_image_file, I am getting the error

AttributeError: 'module' object has no attribute 'load_image_file'

I just gave what is given in the description.. is it changed in the new version?
![screenshot from 2017-04-18 10-08-38](https://cloud.githubusercontent.com/assets/14228815/25143386/0deddd32-241f-11e7-83f4-27ec7d6a07f8.png)

**Comment by ageitgey** [comment]
Don't call your file `face_recognition.py` :)

You are importing your own file, not the face_recognition library. So that's why you are getting an error.

**Comment by Ayiruss** [comment]
Thanks a lot. It worked! silly mistake

**Comment by ageitgey** [comment]
No problem! :)
