### ISSUE TITLE
This software ，Whether can join the age, sex identification

### ISSUE THREAD

**Issue by wangzhouwang** [ageitgey/face_recognition#63]
* face_recognition version:
* Python version:python3.5
* Operating System:Linux

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by ageitgey** [comment]
No, just face recognition.
