### ISSUE TITLE
has anybody tried it on  windows ?

### ISSUE THREAD

**Issue by safaad** [ageitgey/face_recognition#641]
* face_recognition version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.
IMPORTANT: If your issue is related to a specific picture, include it so others can reproduce the issue.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by thisisppn** [comment]
I have tried it on Windows. 

Face-recognition==1.2.3
Python=3.6.6
Windows 10 pro

Looks like everything's working fine, although the face recognition seems to take up some time in CPU, around 2 seconds. I haven't tried it on Linux, so, not sure about the relative speed, and whether this is good or bad.

**Comment by MdAshrafulAlam** [comment]
did you face problems while using python 3.6?

**Comment by cepxuo** [comment]
I tried on Windows 10 with Python 2.7.15 and face_recognition 1.2.3. It works fine with little lag while detecting the face. Face detection is very good, I've recently tried it on twins - the result is positive!
