### ISSUE TITLE
More then one GPU

### ISSUE THREAD

**Issue by Brew8it** [ageitgey/face_recognition#642]
* face_recognition version: Latest
* Python version: 3.6.6
* Operating System: Ubuntu server 18.04

### Description
I im running the CNN model at the moment with a 1060 3GB GTX GPU and it is working fine!
But i have a curios question regarding multiple GPU's would this work or is there any limitations to this?

**Comment by Brew8it** [comment]
Ah thank you for the reply! :)
On a side note, using batch_face_location is there an easy way to calculate how much GPU ram is needed for doing X amount of images and also calculate in upsampling=1? 
Becouse i cannot even run the 128 frame batch example with upsampling=0 without getting cuda malloc error. 

I know the 3GB i have is low but would be Nice to know how to calculate it so i dont have to just try different batch sizes and could help in future upgrades to GPU purches

**Comment by ageitgey** [comment]
I don't have the exact math handy. But it breaks down to this - at minimum you want an old GT 980 Ti with 6GB of RAM. Above that, you could get a 1080 Ti or 2080 Ti (newest). I wouldn't waste money on anything else since RAM is so important and those cards give you the best RAM options.

**Comment by Brew8it** [comment]
Thanks for the awnser @ageitgey🥇 ! Loving the API so far and experimenting with some applications for it

**Comment by ageitgey** [comment]
Nice! Let us know if you build anything cool :)
