### ISSUE TITLE
Could i perform face-recognition with depth

### ISSUE THREAD

**Issue by nbabetas** [ageitgey/face_recognition#666]
Hi all,

I know that it is supposed to post an issue but I didn't find a mail to make this question. I am curious, could i reproduced the same behaviour of iphone's faceid with this lib ? 

Thanks in advance.

**Comment by ageitgey** [comment]
No, this library doesn't have any concept of depth. If you collected a big enough training data set, you could implement something similar to this library but this library wouldn't give you much of a head start.
