### ISSUE TITLE
module object has no attribute 'FILLED'

### ISSUE THREAD

**Issue by N00D13** [ageitgey/face_recognition#67]
* face_recognition version: face-recognition-0.1.14 face-recognition-models-0.1.3
* Python version: Python 2.7.13
* Operating System: macOSX 10.12.4 (16E195)

### Description

I want to execute facerec_from_webcam_faster.py example

### What I Did

```
sudo python facerec_from_webcam_faster.py 
```

### What I got
```
Traceback (most recent call last):
  File "startCam.py", line 65, in <module>
    cv2.rectangle(frame, (left, bottom - 35), (right, bottom), (0, 0, 255), cv2.FILLED)
AttributeError: 'module' object has no attribute 'FILLED'
```

**Comment by ageitgey** [comment]
Are you using a really old version of OpenCV?

cv2.FILLED just equals -1, so you could try replacing it in the script with the value -1 and see if that works for you.

**Comment by N00D13** [comment]
No just for a little moment 😢
