### ISSUE TITLE
cv2.error: /home/pi/opencv-3.1.0/modules/imgproc/src/imgwarp.cpp:3229: error: (-215) ssize.area() > 0 in function resize

### ISSUE THREAD

**Issue by parinfuture** [ageitgey/face_recognition#68]
* face_recognition version:
* Python version: 3.4
* Operating System: Jesse Raspbian

### Description

Whenever I try to run facerec_from_webcam_faster.py, I get the error below. Note that I have checked my local files, the image to be recognized is place appropriately. 

### 

```
OpenCV Error: Assertion failed (ssize.area() > 0) in resize, file /home/pi/opencv-3.1.0/modules/imgproc/src/imgwarp.cpp, line 3229
Traceback (most recent call last):
  File "pj_webcam.py", line 31, in <module>
    small_frame = cv2.resize(frame, (1, 1), fx=0.01, fy=0.01)
cv2.error: /home/pi/opencv-3.1.0/modules/imgproc/src/imgwarp.cpp:3229: error: (-215) ssize.area() > 0 in function resize
```

**Comment by ageitgey** [comment]
This probably means OpenCV wasn't able to grab an image from your webcam. Can you try rebooting your computer and running it again?

**Comment by parinfuture** [comment]
Hi, 
Rebooted my Raspberry Pi. I am still get the same error.

**Comment by ageitgey** [comment]
Oh, this is a raspberry pi. You put macOS in the issue description..

The RPi camera doesn't work with OpenCV like that. There's a [separate code example for raspberry pis](https://github.com/ageitgey/face_recognition/blob/master/examples/facerec_on_raspberry_pi.py) that uses the picamera module.

**Comment by parinfuture** [comment]
Is there any separate code module that can do live video processing on Raspberry Pi similar to this? https://github.com/ageitgey/face_recognition/blob/master/examples/facerec_from_webcam_faster.py

**Comment by ageitgey** [comment]
The examples do almost the same thing. The only difference is the opencv example shows the video in a window while it processes it.

If you want to use the OpenCV example on an RPi, you could modify the OpenCV example to replace the part that captures the image:

```python
# Get a reference to webcam #0 (the default one)
video_capture = cv2.VideoCapture(0)

# .. etc ..

while True:
    # Grab a single frame of video
    ret, frame = video_capture.read()

    # Resize frame of video to 1/4 size for faster face recognition processing
    small_frame = cv2.resize(frame, (0, 0), fx=0.25, fy=0.25)
```

with the equivalent code using picamera:

```python
camera = picamera.PiCamera()
camera.resolution = (320, 240)
small_frame = np.empty((240, 320, 3), dtype=np.uint8)

# ... etc ...

while True:
    print("Capturing image.")
    # Grab a single frame of video from the RPi camera as a numpy array
    camera.capture(small_frame, format="bgr")
```

And something like that should work.

**Comment by parinfuture** [comment]
@ageitgey Thanks for your help. Will definitely try this out.

**Comment by ageitgey** [comment]
Cool! 👍
