### ISSUE TITLE
Hi, how should i cite you in .bib when i use you face_recognition library?? 

### ISSUE THREAD

**Issue by Lane565** [ageitgey/face_recognition#684]
As the title suggests

**Comment by ageitgey** [comment]
You can just cite "face_recognition" and url of this repo I guess. The author is me, Adam Geitgey.

But if you are using face_recognition in your paper, it's worth also citing @davisking's dlib, the underlying ML library that this uses to do the heavy lifting. See http://dlib.net/faq.html#HowcanIcitedlib for that cite.

**Comment by Lane565** [comment]
Yeah, that's exactly what I've done.
And I found the detection function(face_recognition.face_locations()) in your face_recognition using CNNs is more robust than MTCNN.
