### ISSUE TITLE
Face Estimation Landmark (model='small') does not show 5 points only 3 points

### ISSUE THREAD

**Issue by sekti92** [ageitgey/face_recognition#686]
![tes](https://user-images.githubusercontent.com/14885417/48985192-01a85000-f0fd-11e8-9ab9-2d7140c0ed5f.png)

**Comment by ageitgey** [comment]
I think your imwrite and yield lines are indented one level too deep.

**Comment by sekti92** [comment]
@ageitgey thank you sir it is working now
