### ISSUE TITLE
How get a similar faces?

### ISSUE THREAD

**Issue by psyapathy** [ageitgey/face_recognition#689]
* face_recognition version: last
* Python version: Python 3
* Operating System: Win10

Hello!
I like example web_service_example.py
I have 100 photos with faces. And I have 1 photo with the original face.
How can I do a search of the source persons for 100 persons with the greatest speed?

Do I need to encoding all 100 images first and store them in a dataset? Then go through each and compare? Or is there method search encoding the original entity dataset?

Thank you advance

**Comment by ageitgey** [comment]
> Do I need to encoding all 100 images first and store them in a dataset?

Yes.

> Then go through each and compare?

Well, you need to calculate the face distance between the new face and the 100 other faces. You can do that either by comparing every single one or you can use an Approximate Nearest Neighbors (ANN) algorithm to get an answer faster with less accuracy.

There are several ANN packages for Python that you can try out, like Spotify's Annoy. I personally like `pynndescent` but it doesn't have very good docs yet.

**Comment by psyapathy** [comment]
@ageitgey  Thank you!
Is there an example of how to make a dataset from a variety of face photos?



> Well, you need to calculate the face distance between the new face and the 100 other faces. You can do that either by comparing every single one or you can use an Approximate Nearest Neighbors (ANN) algorithm to get an answer faster with less accuracy.There are several ANN packages for Python that you can try out, like Spotify's Annoy. I personally like pynndescent but it doesn't have very good docs yet.

Forces face_recognition not to make it? Your example face_recognition_knn does not do this task?

**Comment by ageitgey** [comment]
There's no example yet of using an ANN algorithm, only the KNN example. The KNN example should work fine for 100 faces. An ANN approach would scale to much larger sizes.

When I have time, I'll add an ANN example using pynndescent.

**Comment by psyapathy** [comment]
@ageitgey 
Thank you!
How to create a dataset? Is there an example of creating a dataset from encodings?

**Comment by brunosps** [comment]
Please try 

https://github.com/ageitgey/face_recognition/issues/243#issuecomment-347639467

it worked for me.

**Comment by psyapathy** [comment]
@brunosps  Thank you Bruno! Have a nice day!
