### ISSUE TITLE
run on OSX 

### ISSUE THREAD

**Issue by hanbim520** [ageitgey/face_recognition#69]
abcdeMacBook-Pro:examples abc$ python facerec_from_webcam.py 
OpenCV Error: Unspecified error (The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script) in cvShowImage, file /Users/travis/build/skvark/opencv-python/opencv/modules/highgui/src/window.cpp, line 583
Traceback (most recent call last):
  File "facerec_from_webcam.py", line 44, in <module>
    cv2.imshow('Video', frame)
cv2.error: /Users/travis/build/skvark/opencv-python/opencv/modules/highgui/src/window.cpp:583: error: (-2) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function cvShowImage

**Comment by shiliufu369** [comment]
Excuse me, could you tell me how to solve the problem is?

**Comment by hanbim520** [comment]
I wrote myself a set of face recognition, face detection, with caffe. TensorFlow also got it. How to solve this I really forgot, the time a little longer
