### ISSUE TITLE
cannot detect the 4th face in the picture

### ISSUE THREAD

**Issue by sekti92** [ageitgey/face_recognition#690]
Hi i was trying to detect a face from an image. I was taken the script from dlib site. However, the script cannot recognise the 3th person in the image. 
I already up the sample into 2, but still does not works, any idea how to detect the 3rd person in this image?

**The result**
![ask](https://user-images.githubusercontent.com/14885417/49200123-45b48280-f393-11e8-8f46-c4922fa051ee.PNG)

**The code**
```
import sys
import dlib

detector = dlib.get_frontal_face_detector()
win = dlib.image_window()

for f in sys.argv[1:]:
    print("Processing file: {}".format(f))
    img = dlib.load_rgb_image(f)

    dets = detector(img, 2)
    print("Number of faces detected: {}".format(len(dets)))
    for i, d in enumerate(dets):
        print("Detection {}: Left: {} Top: {} Right: {} Bottom: {}".format(
            i, d.left(), d.top(), d.right(), d.bottom()))

    win.clear_overlay()
    win.set_image(img)
    win.add_overlay(dets)
    dlib.hit_enter_to_continue()
```

The original image
![test_3](https://user-images.githubusercontent.com/14885417/49200154-65e44180-f393-11e8-8cfc-79450330489f.jpg)

**Comment by ageitgey** [comment]
This is a dlib question, not a face_recognition question.

In any case, you'll probably get better results with the CNN face detector modal instead of the HOG face detector you are using.
