### ISSUE TITLE
Web service (flask) gives "error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'"

### ISSUE THREAD

**Issue by aaichsancr** [ageitgey/face_recognition#693]
* face_recognition version: latest
* Python version: 3.6
* Operating System: Ubuntu

### Description

I tried to make a simple project from your code where people upload an image and it compares to the encodings.pickle where it could recognize people faces.
I'm using flask for the framework, xampp and postman to test the web service.

I already went all over the google, common issues example, your web_service_example.py and found related, but not similar, issues #599 

### What went wrong:
When I tried to run the code and tested it by uploading an image from postman, it returns an error 

```
  File "...", line 56, in recog
    rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.0.0-beta) /.../opencv/modules/imgproc/src/color.cpp:181: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
```
Here's the code
```
def recog(self, photo):
        data = pickle.loads(open("encodings.pickle", "rb").read())
        photo = str(photo)
        image = cv2.imread(photo)
        rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

        boxes = face_recognition.face_locations(rgb, model="cnn")
        encodings = face_recognition.face_encodings(rgb, boxes)

        names = []

        for encoding in encodings:
            matches = face_recognition.compare_faces(data("encodings.pickle", "wb"), encoding)
            name = "Unknown"

            if True in matches:
                matchedIdxs = [i for (i, b) in enumerate(matches) if b]
                counts = {}
                for i in matchedIdxs:
                    name = data["names"][i]
                    counts[name] = counts.get(name, 0) + 1
                name = max(counts, key=counts.get)
            names.append(name)
        return name
```

Any help will be appreciated. I am completely clueless just like #599

Thank you for the support

**Comment by ageitgey** [comment]
That error message is basically a really complicated way of it complaining that the image you passed to `cv2.cvtColor()` was empty. So the problem is that earlier in your program `cv2.imread()` failed to load a valid image from the data that you passed in to it.

So either you didn't read the data from the request correctly, you didn't post the image data correctly with postman, or something with the image data is getting mangled along the way.

**Comment by aaichsancr** [comment]
Thanks for the quick response @ageitgey I'll look deeper into it and look for the possible solutions, hope it works!

**Comment by aaichsancr** [comment]
Looks like it is indeed an error with the image data, when I add print(image.shape) to verify the problem
```
data = pickle.loads(open("encodings.pickle", "rb").read())
        photo = str(photo)
        image = cv2.imread(photo)
        print(image.shape)
        rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
```
it returns a nonetype attribute error
```
AttributeError: 'NoneType' object has no attribute 'shape'
```
While surfing for solutions, I found similar errors and possible from here
https://www.pyimagesearch.com/2016/12/26/opencv-resolving-nonetype-errors/

From what I read. there's two possible root causes from the nonetype error and assertion failed error:
1. An invalid file path supplied to cv2.imread2 (most common cause)
2. The image does exist on disk, but I didn’t compile OpenCV with the given image I/O libraries installed. (rarer cause)

I'll stick in digging solutions to root cause number 1 first, if I haven't got the solution, I'll consider creating a new environment with re-compile OpenCV

Or if anyone got any clues on how to help from @ageitgey clues above than I do, your help are certainly be appreciated
```
So either you didn't read the data from the request correctly, you didn't post the image data correctly with postman, or something with the image data is getting mangled along the way.
```

Because I just learn programming, python, and face recognition for about 2-3 months, so this kind of learning curves is still kinda steep for me lol

**Comment by aaichsancr** [comment]
Solved it yesterday by tweaking around the image path,
```
def recog(self, photopath):
        data = pickle.loads(open("encodings-nip.pickle", "rb").read())
        filepath = 'static/img/img_180201.jpg'

        #photo = str(photo)
        image = cv2.imread(photopath)
        print(image.shape)
        rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

        boxes = face_recognition.face_locations(rgb, model="cnn")
        encodings = face_recognition.face_encodings(rgb, boxes)

        names = []

        for encoding in encodings:
            matches = face_recognition.compare_faces(data["encodings"], encoding)
            name = "Unknown"

            if True in matches:
                matchedIdxs = [i for (i, b) in enumerate(matches) if b]
                counts = {}
                for i in matchedIdxs:
                    name = data["names"][i]
                    counts[name] = counts.get(name, 0) + 1
                name = max(counts, key=counts.get)
            names.append(name)
        return name
```
Thank you for the clues and awesome library! Cheers.

**Comment by Divya-14** [comment]
> That error message is basically a really complicated way of it complaining that the image you passed to `cv2.cvtColor()` was empty. So the problem is that earlier in your program `cv2.imread()` failed to load a valid image from the data that you passed in to it.
> 
> So either you didn't read the data from the request correctly, you didn't post the image data correctly with postman, or something with the image data is getting mangled along the way.

Thank you so much! I was struggling with that problem since 4 hours. Means a lot!
