### ISSUE TITLE
Can't find faces using face_locations with cnn mode

### ISSUE THREAD

**Issue by jianfei1020** [ageitgey/face_recognition#702]
* face_recognition version: 
* Python version: 3.5
* Operating System: windows8

### Description

It works well when I'm trying face_recognition/examples/find_faces_in_picture.py, but can't find any face when using face_recognition/examples/find_faces_in_picture_cnn.py with same picture.

Then I tried change the code from face_locations = face_recognition.face_locations(image, number_of_times_to_upsample=0, model="cnn") to face_locations = face_recognition.face_locations(image, model="cnn"), it works! Seems "number_of_times_to_upsample=0" make it fail? Can't understand what's number_of_times_to_upsample for？ Why it works with cnn model without  number_of_times_to_upsample setting?

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by ageitgey** [comment]
The default setting of `number_of_times_to_upsample` is `1`. So by removing it, you are really setting it to `1`.

The setting controls how many times the input picture gets scaled up in size before you check for faces. Scaling up the picture is slower and uses more memory but allows it to find smaller faces in the image.

**Comment by jianfei1020** [comment]
set upsample to 1, it works. seems it's picture quality issue, need high resolution photos.

**Comment by jianfei1020** [comment]
Thanks ageitgey!
