### ISSUE TITLE
what if i installed face_recognition on remote linux server, how can i use my pc webcam to identify people

### ISSUE THREAD

**Issue by AlexPeng19** [ageitgey/face_recognition#704]
* face_recognition version: 
* Python version: python 3.4.9
* Operating System: centos 7.5

### Description

i want to provide a face recognition service, what if i installed the face_recognition on the remote linux server,how can it invoke my pc webcam to identify the face.

thanks in advance.

**Comment by ageitgey** [comment]
You would have to write a web app that runs on the remote linux server that uses something like webrtc to stream video to the server from the user's browser. It's not something that's built in to this library.

**Comment by AlexPeng19** [comment]
@ageitgey appreciated for your guide, nice day!
