### ISSUE TITLE
recognition time

### ISSUE THREAD

**Issue by bkoffler** [ageitgey/face_recognition#71]
* face_recognition version: newest
* Python version: 2.7
* Operating System: Ubuntu

### Description

I ran the script and it ran well - correct faces were detected. The problem is that it took 25 seconds - is that typical? Ultimately i will be sending pictures from remote camera to compare against a central database and send back info based on who is detected. I only have a second or two for this to happen. Thoughts?
### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by ageitgey** [comment]
No. Was the picture super large? What kind of CPU (and GPU, if you have one) are you using?

Times should be well under a second unless your images are large or your computer is very slow.

**Comment by bkoffler** [comment]
i am running this on a virtualbox ubuntu machine - no GPU but i have 2 cores of the of core i3 and 4gb of ram allocated to this machine.

I have another box with 4 sapphire 290 GPUs attached for hash testing - i'm not sure if this will be able to take advantage of the multiple GPUs, but I'm sure it will be able to grab at least one if that should speed it up.

I have 5 unknown pictures of around 100kb each and 5 known pictures of around 300kb each.

**Comment by ageitgey** [comment]
First, virtualbox is really slow in general. So it's probably worth using VMware or running it some other way if possible. I wouldn't use virtualbox for anything intensive. That's probably the first adjustment to make.

Second, if you compiled dlib yourself, make sure it has SSE4 and AVX enabled. Those are features on newer CPUs (2011+) that speed up the processing a lot. Unfortunately I don't think the Sapphire 290 GPUs will be helpful. Most machine learning libraries are built on CUDA and cuDNN which is an nvidia product and only runs on nvidia GPUs. AMD GPUs aren't commonly used for machine learning right now, so they are not supported by any of the popular libraries.

Finally, the most important thing about image size is the actual resolution of the image, not the file size. You'll get way faster performance if you scale down your images before running face recognition on them. For example, scaling an image down to 640x480 would result in way faster performance than trying to process a 5MP picture right out of a cell phone camera. So try scaling down your images first. The trade-off is that the smaller you scale down the images, the less likely it is to find and recognize smaller faces in the image.

The built-in face_recognition command-line script tries to scale down your images to 1600 pixels wide here:

https://github.com/ageitgey/face_recognition/blob/master/face_recognition/cli.py#L36-L37

If you are using that script, you could try changing 1600 to 640 there and seeing how much faster it got.

**Comment by bkoffler** [comment]
great thanks i will try running this outside of the virtual environment and see how that goes. Going that route, is there anything special i need to do to have it utilize the gpu if i throw in a NVIDIA card at a later time to see how that impacts performance?

**Comment by ageitgey** [comment]
Yes, to use an nvidia GPU you'd need to install both [CUDA](https://developer.nvidia.com/cuda-downloads) and [cuDNN](https://developer.nvidia.com/cudnn) and compile dlib with CUDA support enabled.  It's simpler to install dlib without CUDA support, but then it won't take advantage of a GPU even if it's there.

**Comment by bkoffler** [comment]
got it - ok i will order some gear and test it out when i have a chance. I will report back. thanks.

**Comment by bkoffler** [comment]
Actually one last question - would this program be able to take advantage of multiple GPUs if the need arose for the additional power?

**Comment by ageitgey** [comment]
No, it's not currently coded in a way to take advantage of multiple GPUs. With some work and custom coding, you could probably set up your program to run as multiple processes and tweak the code so that each process uses a different GPU and distribute the work that way, but I've never tested it.

But unless you are processing millions of images or something, I doubt you would really need to mess with that. And if you get to that point, then maybe this isn't the right tool anyway.

**Comment by bkoffler** [comment]
Yes all true – ok thanks again for taking the time to answer my questions.
