### ISSUE TITLE
How to deal with 1000 face images, 

### ISSUE THREAD

**Issue by verma171** [ageitgey/face_recognition#715]
* face_recognition version: 1.2.3.
* Python version: 2.7
* Operating System: Mac

### Description
I want to recognize the face of guest onboard on hotel and want to update checkin status in data base, I have guest image of 1000 guest, will this library work with 1K image is there any performance impact or any other better way to do the same.

**Comment by avinsit123** [comment]
It all depends on whether your system has a GPU,you can increase performance with this.Otherwise a normal CPU performance would be slow for 1k face images.Do you have individual facial photos of 1k people or do you want to recognise them from a scenery?

**Comment by verma171** [comment]
I have individual image of person.

**Comment by sandip-narwade** [comment]
@avinsit123  I want to recognize them from a scenery. I created .cfl model (700KB file). While recognize it is slow.
