### ISSUE TITLE
Error in importing on Google Colab

### ISSUE THREAD

**Issue by avinsit123** [ageitgey/face_recognition#717]
* face_recognition version:1.2.3
* Python version:3.4.0
* Operating System:Google Colab

### Description
I am trying to import face_recognition on Google Colab after installing it using pip.However the following error appears : **RuntimeError: Error while calling cudaGetDevice(&the_device_id) in file /tmp/pip-install-m826kloy/dlib/dlib/cuda/gpu_data.cpp:178. code: 30, reason: unknown error**

### What I Did

``` python
!pip install face_recogntion
import face_recogntion
```
The error was 
![screenshot 2019-01-10 at 1 27 31 pm](https://user-images.githubusercontent.com/33565881/50954128-8ac3ec80-14db-11e9-97b2-58c62863dd8f.png)

**Comment by RoadToML** [comment]
Hey mate @avinsit123. That fixed for me when i changed my runtime type to 'GPU'

you can do this by clicking 'Runtime' (in the tool bar) --> then 'Change Runtime Type' --> 'Hardware Accelerator' to 'GPU'

**Comment by Ishikaaa** [comment]
> Hey mate @avinsit123. That fixed for me when i changed my runtime type to 'GPU'
> 
> you can do this by clicking 'Runtime' (in the tool bar) --> then 'Change Runtime Type' --> 'Hardware Accelerator' to 'GPU'

Thank you sooo much. This thing was disturbing me from so much time.
