### ISSUE TITLE
Would using GPU make the process much faster?

### ISSUE THREAD

**Issue by jazz3020** [ageitgey/face_recognition#724]
* face_recognition version: 
* Python version: 3
* Operating System: MacOS

### Description

I realized the process is quite slow on my laptop without GPU and wanted to see if setting up a VM with GPU(s) will be worth it?

Are there any other ways to run it? I am using this for videos.

**Comment by jazz3020** [comment]
I am running the cnn model on a GPU, and it works much faster.

**Comment by xSNYPSx** [comment]
How you make it to run with gpu ?

**Comment by xSNYPSx** [comment]
> I am running the cnn model on a GPU, and it works much faster.

How you make it to run with gpu ?
