### ISSUE TITLE
Detect human face exclude paint image

### ISSUE THREAD

**Issue by khs123** [ageitgey/face_recognition#728]
* face_recognition version:1.2.3
* Python version: 3.5
* Operating System: 16.04

### Description

Hi !
I using face_recognition to find face on picture and recognition who they are ! Everything is good but i have a issue.
When i load paint image what i drew person to my script. Face_recognition detect the face i drew
How can i remove those faces ? 
Thank a lots

**Comment by rompic** [comment]
hi, not really sure if I understood what you try to do, but you may be interested in this discussion: https://github.com/ageitgey/face_recognition/issues/371

**Comment by khs123** [comment]
Thank you bro
