### ISSUE TITLE
Hi Adam, great work you have here. I would like to know if and how I can use this api from an android device,  I am building an android app for face recognition and AR, that I intend to run online by uploading an image online for processing

### ISSUE THREAD

**Issue by Nuelsian** [ageitgey/face_recognition#73]
* face_recognition version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by ageitgey** [comment]
There's an simple example of running this as a web service here: https://github.com/ageitgey/face_recognition/blob/master/examples/web_service_example.py
