### ISSUE TITLE
Issues with Program?

### ISSUE THREAD

**Issue by jsniff** [ageitgey/face_recognition#74]
@ageitgey Also, when you run the program, normally from command line, it does return matches with distance greater than .6. I know this, b/c when I take the matches and compare them separately with the distance program, to try to help rank them and understand, it shows the distance and for some matches they’re greater than point6, even though threshold was that. How is this possible

@ageitgey Does this work well on any ethnicity? I'm trying to do some benchmarking on asian and chinese faces. I'm wondering how it will perform. Any idea if it will break down? My preliminary results on South American faces show several matches---I'm trying to reduce with confidence and understand, etc.

**Comment by ageitgey** [comment]
Can you narrow it down to a test case with specific images that shows it returning results greater than .6? That would help to find the bug.

I don't have any information on how accurate it is on different ethnicities. The recognition model included was trained by Davis King on 3 million faces, but I don't know what the distribution of faces was. If you come up with any detailed results, let me know!

**Comment by jsniff** [comment]
I can't share the specific database that gave me problems, but I hope to try more that I can soon and I'll let you know.

I did some research and found following notes on data-sets trained on:

i.) face scrub dataset[2]

http://vintage.winklerbros.net/facescrub.html


“FaceScrub - A Dataset With Over 100,000 Face Images of 530 People

Large face datasets are important for advancing face recognition research, but they are tedious to build, because a lot of work has to go into cleaning the huge amount of raw data. To facilitate this task, we developed an approach to building face datasets that detects faces in images returned from searches for public figures on the Internet, followed by automatically discarding those not belonging to each queried person. The FaceScrub dataset was created using this approach, followed by manually checking and cleaning the results. It comprises a total of 107,818 face images of 530 celebrities, with about 200 images per person. As such, it is one of the largest public face databases.”


ii.)  the VGG dataset[1]

http://www.robots.ox.ac.uk/~vgg/data/vgg_face/

This page contains the download links for building the VGG-Face dataset, described in [1]. 

The dataset consists of 2,622 identities. Each identity has an associated text file containing URLs for images and corresponding face detections. Please read the licence file carefully before downloading the data. Models pretrained using this data can be found at VGG Face Descriptor webpage. Please check the MatConvNet package release on that page for more details on Face detection and cropping.

**Comment by jsniff** [comment]
Program does work pretty well! I'm continuing to benchmark!
