### ISSUE TITLE
Python 2 version is much worse than python 3 in face detection

### ISSUE THREAD

**Issue by YubinXie** [ageitgey/face_recognition#756]
* face_recognition version: V1.2.3
* Python version:2.7
* Operating System: Mac OS

### Description

I tested on the same human face dataset (very obvious face in every image); the python 2 version is not able to detect many faces while the python 3 works perfectly.

**Comment by ageitgey** [comment]
Is it possible there is a bug in your code or in what extra libraries you are loading? There should be no accuracy difference using Python 2 vs Python 3.

**Comment by YubinXie** [comment]
It does not look like a bug since python 2 works 95% of the time.

**Comment by ageitgey** [comment]
You'll need to create a test case of an image and code that fails in Python 2 but works in Python 3. Otherwise I can't really guess what might be wrong.

**Comment by YubinXie** [comment]
I think you were right about the other libraries. I updated some other libraries like opencv et al..., now the python2 works same as python3. I can't identify which library it is yet, but will keep an eye on it in the future. 

Thanks for your quick response!
