### ISSUE TITLE
recognise known peoples face in live cc camera(with ip)

### ISSUE THREAD

**Issue by VellalaVineethKumar** [ageitgey/face_recognition#757]
* face_recognition version:latest git clone
* Python version:3.7.1(anaconda distrubution)
* Operating System:ubuntu 16.04

### Description
1) i have the IP of cc camera eg.10.2.0.10
2) I have the pictures of my friend's face (known peoples folder)
3) I want to recognize his face from the stream I get from cc camera(just like a webcam)
what changes can i make to this to happen?
please help!

**Comment by rodrigofay** [comment]
you can use a RTSP protocol url in you VideoCapture,
something like cv2.VideoCapture("rtsp://USER:PWD@10.2.0.10:port")
I also recommend using two different process: 1)read the input stream 2) recognize the person

**Comment by VellalaVineethKumar** [comment]
Yea that worked! Thank you

**Comment by guruvishnuvardan** [comment]
Hi,

I am also planning to use IP CCTV camera to recognize faces, Can you please let me know, how the face accuracy is maintained @ 99% for real time Face Recognition.

Thanks
Guru
