### ISSUE TITLE
landmarks clarification 

### ISSUE THREAD

**Issue by DecentMakeover** [ageitgey/face_recognition#765]
Hi 

When running 

    import face_recognition
    image = face_recognition.load_image_file("your_file.jpg")
    face_locations = face_recognition.face_locations(image)

i just wanted to understand when face locations returns the co-ordinates of the face, do you run mtcnn on it? i mean do you align the face and then return the face?

Thanks in advance.

**Comment by ageitgey** [comment]
No, asking for face locations only runs the face locator. The default is to use a HOG-based face locator, but you can pass model="cnn" to use a CNN-based face locator instead. Neither do any alignment or facial feature detection in that step.

**Comment by DecentMakeover** [comment]
Thanks for the reply.

Is there any function in face_recognition that does alignment?

**Comment by ageitgey** [comment]
The face_encodings function aligns the images internally before it generates face encodings, but it doesn't exposed the aligned images. If you just want the facial feature locations, then you can use the face_landmarks function:

```
import face_recognition
image = face_recognition.load_image_file("your_file.jpg")
face_landmarks_list = face_recognition.face_landmarks(image)
```

Check out the demos in the examples folder, like this one: https://github.com/ageitgey/face_recognition/blob/master/examples/find_facial_features_in_picture.py

**Comment by DecentMakeover** [comment]
Thanks for the reply,
I’ll look into it-

On 05-Mar-2019, at 1:40 AM, Adam Geitgey <notifications@github.com<mailto:notifications@github.com>> wrote:


The face_encodings function aligns the images internally before it generates face encodings, but it doesn't exposed the aligned images. If you just want the facial feature locations, then you can use the face_landmarks function:

import face_recognition
image = face_recognition.load_image_file("your_file.jpg")
face_landmarks_list = face_recognition.face_landmarks(image)


Check out the demos in the examples folder, like this one: https://github.com/ageitgey/face_recognition/blob/master/examples/find_facial_features_in_picture.py
