### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by vinycoolguy2015** [ageitgey/face_recognition#77]
* face_recognition version:
* Python version: 2.7
* Operating System: Ubuntu 16

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by ageitgey** [comment]
Please fill in the details of the issue if you have a problem. We can't help you just from the title. It's not enough information.
