### ISSUE TITLE
Recognizing 2 persons in 1 person image 

### ISSUE THREAD

**Issue by mzkhan141** [ageitgey/face_recognition#82]
* face_recognition version:  v0.1.14
* Python version: 2.7.12
* Operating System: Ubuntu 16.04.2 LTS Xenial

### Description

At first I tried pretty much everything to install this on Windows 10 but it wont so installed Ubuntu in a VM and installed face_recognition with pip successfully but when I try to recognize this image with only one face in it, it give me 2 persons name for the same image.
![bla](https://cloud.githubusercontent.com/assets/22846717/26124000/993e3658-3a85-11e7-8d00-7c69c9abf455.jpg)
I currently have only two images in the 'known' folder 
 

### What I Did

```
zk@ubuntu:~/Pictures$ face_recognition known/ unknown/
unknown/bla.jpg,Person 1
unknown/bla.jpg,Person 2
```

**Comment by usingnamespaceSystem** [comment]
Hello, @mzkhan141 ! If person 1 and person 2 are photos of one and the same person, then app gives you right result.

**Comment by mzkhan141** [comment]
No person 1 and person 2 are not same but two different persons. The image posted above is `bla.jpg` and consist of only `Person 1` but not `Person 2`. As you can see in the above posted output it recognizes 2 persons in the image. You can judge yourself that in the above posted image there is only 1 person.

**Comment by ageitgey** [comment]
@mzkhan141 That just means the face recognition system made a mistake. This picture has a lot of glare, so maybe that's why it did a bad job on this picture.

**Comment by mzkhan141** [comment]
Yes, I thought the same but then wanted to be sure if that is the problem.
Thanks!
