### ISSUE TITLE
What is the order of the returned list of face encodings? Left to Right?

### ISSUE THREAD

**Issue by mjpoltorak** [ageitgey/face_recognition#820]
### Description

I am trying to figure out the order of the list given by face_recognition.face_encodings(image). Does it return a list of face encodings of faces starting from left to right in the image? Right to left?

### What I Did

face_recognition.face_encodings(image)

**Comment by ageitgey** [comment]
Don't depend on the return order. Instead, call `locs = face_recognition.face_locations(image)` first to get the list of face locations and then pass that in to `encodings = face_recognition.face_encodings(image, known_face_locations=locs)`. Then the face encodings you get back from the second call will be in the same order with the list of locations you got from the first call, so you know which face is which.

Hope that helps!

**Comment by mpoltora** [comment]
@ageitgey Thank you very much that is a perfect solution!

**Comment by mjpoltorak** [comment]
@ageitgey Thank you very much this is the perfect solution to my problem! 
Closing the issue now.

**Comment by rommeldias** [comment]
> Don't depend on the return order. Instead, call `locs = face_recognition.face_locations(image)` first to get the list of face locations and then pass that in to `encodings = face_recognition.face_encodings(image, known_face_locations=locs)`. Then the face encodings you get back from the second call will be in the same order with the list of locations you got from the first call, so you know which face is which.
> 
> Hope that helps!

Hi,
I have a particular question concerning it.
What is the order of faces returned by face_locations()?
In some preliminary experiments, the method grabs frontal faces and index them first, while side faces come later.

**Comment by zzy-life** [comment]
> > 不要依赖退货单。相反，`locs = face_recognition.face_locations(image)`首先调用以获取面部位置列表，然后将其传递给`encodings = face_recognition.face_encodings(image, known_face_locations=locs)`. 然后，您从第二次通话中获得的人脸编码将与您从第一次通话中获得的位置列表的顺序相同，因此您知道哪个人脸是哪个人脸。
> > 希望有帮助！
> 
> 嗨， 我有一个特别的问题。 face_locations() 返回的面的顺序是什么？ 在一些初步实验中，该方法首先抓取正面并对其进行索引，而侧面则稍后出现。

Did you solve it? It appears that the face codes returned by this method are out of order.
Or not just left-to-right

**Comment by rommeldias** [comment]
> > > 不要依赖退货单。相反，`locs = face_recognition.face_locations(image)`首先调用以获取面部位置列表，然后将其传递给`encodings = face_recognition.face_encodings(image, known_face_locations=locs)`. 然后，您从第二次通话中获得的人脸编码将与您从第一次通话中获得的位置列表的顺序相同，因此您知道哪个人脸是哪个人脸。
> > > 希望有帮助！
> > 
> > 
> > 嗨， 我有一个特别的问题。 face_locations() 返回的面的顺序是什么？ 在一些初步实验中，该方法首先抓取正面并对其进行索引，而侧面则稍后出现。
> 
> Did you solve it? It appears that the face codes returned by this method are out of order. Or not just left-to-right

Hi. As you said, the faces do not have a specific order.
If I have an image that has both front and side faces, I am not able to get only the front ones.
