### ISSUE TITLE
Small landmark model for face recognition

### ISSUE THREAD

**Issue by hoenickf** [ageitgey/face_recognition#830]
Hi, is there any reason why the method to generate face encodings (def face_encoding) in face_recognition/api.py uses the small landmark model?
Would it generate more accurate encodings when using the large model?

**Comment by ageitgey** [comment]
The small model is faster.

The face landmarks are used as control points to do a simple affine transform on the face image to align it to a normalized position, so using the larger model with more face points shouldn't change the result since those extra points aren't used in the transform anyway.
