### ISSUE TITLE
about recognition rate of light direction

### ISSUE THREAD

**Issue by sgc0907** [ageitgey/face_recognition#839]
* face_recognition version:
* Python version:
* Operating System:
-> VirtualBox VM image

### Description
I've been using your program lately, and I find that the recognition rate changes when I change the direction of the light on the same person's face.
Is it possible to progress this problem without controlling the tollerance? 

Thank you.

**Comment by ageitgey** [comment]
Not without retraining the underlying face recognition model with more many thousands of samples of the same people lit from different directions. The problem is that most of the training data used in the initial model was scraped from the web and is lit in normal room lighting conditions.

**Comment by sgc0907** [comment]
Oh, okay. i get it.
Thanks.
