### ISSUE TITLE
install face_reconition on python3.5

### ISSUE THREAD

**Issue by rongwwei** [ageitgey/face_recognition#84]
* face_recognition version:face_recognition-0.1.14
* Python version:py3.5
* Operating System:ubuntu17.04

### Description

I install it for python2.7.And it works.

But I still want to install this lib on python3.5,but it failed.

### What I Did

```
error info:
ImportError: /usr/local/lib/libboost_python.so.1.64.0: undefined symbol: PyClass_Type


```
I get the reason from internet:
PyClass_Type is is part of the Python 2 C API and not part of the Python 3 C API. Hence, the Boost.Python library was likely built against Python 2. However, it is being loaded by a Python 3 interpreter, where the PyClass_Type is not available.

How can i install it for py3.5?

please help me... Thank you.

**Comment by usingnamespaceSystem** [comment]
I have the same issue on CentOS 6.0. I solved PyClass_Type error by recompiling boost with `python3.5, but then I got undefined symbol: _ZN5boost6python6detail11init_moduleER11PyModuleDefPFvvE and still loking for solution.

Do smth like this:
 1. Check Python3 root
$ which python3
/usr/local/bin/python3

2. Modify /boost_1_57_0/tools/build/example/user-config.jam

using python : 3.5 : /usr/local/bin/python3.5 : /usr/local/include/python3.5m : /usr/local/lib ;

4. ./bootstrap.sh --with-python=/usr/local/bin/python3 --with-python-version=3.5 --with-python-root=/usr/local/lib/python3.5

5. sudo ./b2 --enable-unicode=ucs4 install

**Comment by rongwwei** [comment]
@usingnamespaceSystem I have compiled boost by py3.5,but it still use libboost_python.so,so the error info still is 
"error info:
ImportError: /usr/local/lib/libboost_python.so.1.64.0: undefined symbol: PyClass_Type"
and there is "libboost_python3.5.so.1.64.0" in the same path,but it did not use.I have reinstall dlib,but it didn't work.

**Comment by sluongng** [comment]
Im not sure about ubuntu but on window I used Anaconda to install this library with great success.

Here are the commands I used
```
conda create -n py35 python=3.5
activate py35
conda config --add channels conda-forge
conda install numpy
conda install scipy
conda install dlib
pip install face_recognition
```

Strongly recommend running `conda clean --all` before installation in case of library crashing.
Conda-forge is optional but advised because it often has the latest version of packages (OpenCV etc...)
