### ISSUE TITLE
THIS IS RUBBISH

### ISSUE THREAD

**Issue by intgogo** [ageitgey/face_recognition#842]
RUBBISH!
RUBBISH!
RUBBISH!
So many stars,but this is rubbish!

**Comment by ageitgey** [comment]
If you are having a specific problem, you can post an issue asking for help.

**Comment by intgogo** [comment]
@ageitgey 我对比了很多开源的人脸识别项目(face-alignment,facenet,face.evoLVe.PyTorch)，无论是在人脸检测、对齐、识别各个算法的准确度上，这个都是最差的，没有之一。而且，如果有多张显卡，连最基本的部署到指定显卡这种功能都做不到，简直愤怒~难道你们作者开发了这么多年没发现这种最基本的问题吗？连我一个刚接触人脸识别一个月不到的新手都看不下去了。

**Comment by intgogo** [comment]
@ageitgey 不过还是要感谢这个项目，集成确实简单。而且我现在还是用了你们dlib里面对齐函数(get_face_chip)

**Comment by primejava** [comment]
you know nothing
