### ISSUE TITLE
Not able to detect face

### ISSUE THREAD

**Issue by akshay-shah** [ageitgey/face_recognition#851]
* face_recognition version: Latest
* Python version: 3.7
* Operating System: Mac

### Description
I am not able to detect a face in the below picture can someone tell me why..and it's not only about this picture it's with many of them clicked with my ONE PLUS 6 
![Amit](https://user-images.githubusercontent.com/6313300/59174501-46627880-8b6f-11e9-849f-b4086702135c.jpg) Can someone try and let me know why

**Comment by somuchtyler** [comment]
try rotating your phone, face_detect won't detect faces when they aren't correctly rotated

**Comment by akshay-shah** [comment]
Tried but still not able to...

**Comment by akshay-shah** [comment]
Okay found something crucial @ageitgey please look into this...I kept my phone in portrait mode (height > width) and took some face pics I did not recognize the face, tried keeping my phone in landscape mode(width>height) and it detected the faces in the photos.

**Comment by ageitgey** [comment]
Please see the common issues list here: https://github.com/ageitgey/face_recognition/wiki/Common-Errors#issue-its-not-detecting-faces-in-my-very-simple-image-i-took-with-my-iphone--android-phone

**Comment by akshay-shah** [comment]
Thank you so much @ageitgey !! Closing this.
