### ISSUE TITLE
 __call__(): incompatible function arguments

### ISSUE THREAD

**Issue by niltonmalves** [ageitgey/face_recognition#853]
* face_recognition version: face-recognition == 1.2.3 / face-recognition-models == 0.3.0

* Python version: Python 3.7.3 
* Operating System: windows 10

### Description

I'm trying to catalog all the faces that go to a store. then try to find out if a particular person frequents that place. first I removed all of the faces and saved separately. Now I'm trying to compare these saved files, but the second error happens.

### What I Did

```python

import os
import cv2
import face_recognition
from PIL import Image, ImageDraw
import numpy as np
import shutil


#pick up the faces and compare if there is any equal from this list
#having repeated face, create and put in separate folder.
#path = r'C:\Users\Matriz\Documents\rostos_vouga\ss\210520193'
path = r'C:\Users\Matriz\Documents\teste_verif_rosto_em_pasta\posicao_inicial'
files = []
#r=root, d=directories, f = files
for r, d, f in os.walk(path):
    for file in f:
        if '.jpg' in file:
            files.append(os.path.join(r, file))
        print(file)

for indice ,f   in enumerate(files):
    print(f)

    encodings = face_recognition.face_encodings(f)
    if len(encodings) > 0:
        biden_encoding = encodings[0]
        print("x1")
else:
   print("No faces found in the image!")
   
   pasta = "/Users/Matriz/Documents/teste_verif_rosto_em_pasta/posicao_final/xx%d" % indice
   try:
       os.makedirs(pasta)
   except OSError:
       print ("Creation of the directory %s failed" % pasta)
   else:
       print ("Successfully created the directory %s" % pasta)

   print("sdsd")
   obama_image = face_recognition.load_image_file(f)
   obama_face_encoding = face_recognition.face_encodings(obama_image)[0]
   known_face_encodings = [obama_face_encoding]
   known_face_names = ["cliente%d" % indice]
   print(indice)
   for un in reversed(files):
       print('loop procurando rosto', un)
                # Load an image with an unknown face
       unknown_image = face_recognition.load_image_file(un)
                # Find all the faces and face encodings in the unknown image
       face_locations = face_recognition.face_locations(unknown_image)
       face_encodings = face_recognition.face_encodings(unknown_image, face_locations)
       for (top, right, bottom, left), face_encoding in zip(face_locations, face_encodings):
            # See if the face is a match for the known face(s)
           matches = face_recognition.compare_faces(known_face_encodings, face_encoding)
           name = "Unknown"
                    # If a match was found in known_face_encodings, just use the first one.
                    # if True in matches:
                    #     first_match_index = matches.index(True)
                    #     name = known_face_names[first_match_index]

                    # Or instead, use the known face with the smallest distance to the new face
           face_distances = face_recognition.face_distance(known_face_encodings, face_encoding)
           best_match_index = np.argmin(face_distances)
           if matches[best_match_index]:
               name = known_face_names[best_match_index]
               #cut the file from the unknown folder and paste it into the folder of known
                        
               shutil.move(un,pasta)

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
 RESTART: C:\Users\Matriz\Documents\frames_vouga\verify_faces_in_path_asked_in_github.py 
frame13.jpg
frame131.jpg
frame136.jpg
frame145.jpg
frame146.jpg
frame147.jpg
frame152.jpg
frame155.jpg
frame166.jpg
frame167.jpg
frame170.jpg
frame171.jpg
frame181.jpg
frame185.jpg
frame199.jpg
frame2.jpg
frame210.jpg
frame217.jpg
frame219.jpg
frame221.jpg
frame222.jpg
frame23.jpg
frame256.jpg
frame264.jpg
frame266.jpg
frame273.jpg
frame276.jpg
frame36.jpg
frame42.jpg
frame49.jpg
frame50.jpg
frame52.jpg
frame65.jpg
frame93.jpg
C:\Users\Matriz\Documents\teste_verif_rosto_em_pasta\posicao_inicial\frame13.jpg
Traceback (most recent call last):
  File "C:\Users\Matriz\Documents\frames_vouga\verify_faces_in_path_asked_in_github.py", line 24, in <module>
    encodings = face_recognition.face_encodings(f)
  File "C:\Python37\lib\site-packages\face_recognition\api.py", line 209, in face_encodings
    raw_landmarks = _raw_face_landmarks(face_image, known_face_locations, model="small")
  File "C:\Python37\lib\site-packages\face_recognition\api.py", line 153, in _raw_face_landmarks
    face_locations = _raw_face_locations(face_image)
  File "C:\Python37\lib\site-packages\face_recognition\api.py", line 102, in _raw_face_locations
    return face_detector(img, number_of_times_to_upsample)
TypeError: __call__(): incompatible function arguments. The following argument types are supported:
    1. (self: dlib.fhog_object_detector, image: array, upsample_num_times: int=0) -> dlib.rectangles

Invoked with: <dlib.fhog_object_detector object at 0x0000017FCFB1B570>, 'C:\\Users\\Matriz\\Documents\\teste_verif_rosto_em_pasta\\posicao_inicial\\frame13.jpg', 1
>>> 
```
![frame2](https://user-images.githubusercontent.com/46911747/59291636-c19c5b00-8c51-11e9-9971-1394c5d50a63.jpg)
![frame13](https://user-images.githubusercontent.com/46911747/59291637-c19c5b00-8c51-11e9-8fd0-15d27732efd1.jpg)
![frame23](https://user-images.githubusercontent.com/46911747/59291638-c19c5b00-8c51-11e9-9b80-407386f3b911.jpg)
![frame36](https://user-images.githubusercontent.com/46911747/59291639-c19c5b00-8c51-11e9-833a-00bfafd66d1e.jpg)
![frame42](https://user-images.githubusercontent.com/46911747/59291641-c234f180-8c51-11e9-9c7e-349fe886f863.jpg)
![frame49](https://user-images.githubusercontent.com/46911747/59291643-c234f180-8c51-11e9-9b54-2473d35561aa.jpg)
![frame50](https://user-images.githubusercontent.com/46911747/59291644-c234f180-8c51-11e9-80ee-a68cfb10b18f.jpg)
![frame52](https://user-images.githubusercontent.com/46911747/59291645-c234f180-8c51-11e9-883b-fcf40c168194.jpg)
![frame65](https://user-images.githubusercontent.com/46911747/59291646-c2cd8800-8c51-11e9-8515-687b1a497556.jpg)
![frame93](https://user-images.githubusercontent.com/46911747/59291648-c2cd8800-8c51-11e9-9fe0-c193076fbd33.jpg)
![frame131](https://user-images.githubusercontent.com/46911747/59291650-c2cd8800-8c51-11e9-9fac-89561ffe3aed.jpg)
![frame136](https://user-images.githubusercontent.com/46911747/59291651-c2cd8800-8c51-11e9-88be-27d2ddccec9b.jpg)
![frame145](https://user-images.githubusercontent.com/46911747/59291652-c2cd8800-8c51-11e9-8b21-ce94196b590b.jpg)
![frame146](https://user-images.githubusercontent.com/46911747/59291653-c3661e80-8c51-11e9-9d9e-ab7f287bec8c.jpg)
![frame147](https://user-images.githubusercontent.com/46911747/59291654-c3661e80-8c51-11e9-8bb3-b63b27634e12.jpg)
![frame152](https://user-images.githubusercontent.com/46911747/59291655-c3661e80-8c51-11e9-9cb8-3cbe1ca582f2.jpg)
![frame155](https://user-images.githubusercontent.com/46911747/59291656-c3661e80-8c51-11e9-93a7-ed689ec6e3e5.jpg)
![frame166](https://user-images.githubusercontent.com/46911747/59291658-c3feb500-8c51-11e9-91ce-293eae10440c.jpg)
![frame167](https://user-images.githubusercontent.com/46911747/59291659-c3feb500-8c51-11e9-8ffc-3665cca1f7a8.jpg)
![frame170](https://user-images.githubusercontent.com/46911747/59291660-c3feb500-8c51-11e9-808c-c9b2f7b00dfc.jpg)
![frame171](https://user-images.githubusercontent.com/46911747/59291661-c3feb500-8c51-11e9-9a89-fe87f49a00cc.jpg)
![frame181](https://user-images.githubusercontent.com/46911747/59291662-c4974b80-8c51-11e9-9e6e-ff356701871d.jpg)
![frame185](https://user-images.githubusercontent.com/46911747/59291663-c4974b80-8c51-11e9-9ed4-67caaa9d2926.jpg)
![frame199](https://user-images.githubusercontent.com/46911747/59291664-c4974b80-8c51-11e9-994b-c2364c4defbf.jpg)
![frame210](https://user-images.githubusercontent.com/46911747/59291665-c4974b80-8c51-11e9-9e87-f0543bb3bde3.jpg)
![frame217](https://user-images.githubusercontent.com/46911747/59291666-c4974b80-8c51-11e9-8df1-8ad79a8dea56.jpg)
![frame219](https://user-images.githubusercontent.com/46911747/59291667-c52fe200-8c51-11e9-9a79-305659c84b2d.jpg)
![frame221](https://user-images.githubusercontent.com/46911747/59291668-c52fe200-8c51-11e9-857c-0af80a64a5bf.jpg)
![frame222](https://user-images.githubusercontent.com/46911747/59291669-c52fe200-8c51-11e9-82c8-dbe7eb4c0365.jpg)
![frame256](https://user-images.githubusercontent.com/46911747/59291670-c52fe200-8c51-11e9-95b1-c89d12dfe0a1.jpg)
![frame264](https://user-images.githubusercontent.com/46911747/59291671-c52fe200-8c51-11e9-82d3-8453d7b643e1.jpg)
![frame266](https://user-images.githubusercontent.com/46911747/59291672-c5c87880-8c51-11e9-9e1c-b153a98a4a21.jpg)
![frame273](https://user-images.githubusercontent.com/46911747/59291675-c5c87880-8c51-11e9-9a67-e7a2d1e29774.jpg)
![frame276](https://user-images.githubusercontent.com/46911747/59291676-c5c87880-8c51-11e9-84ba-49fe5f73b238.jpg)

**Comment by ageitgey** [comment]
You have to call face_recognition.load_image_file() on each file to load the image contents before you look for faces in it. You can't pass a raw filename to `face_encodings()` function like you are doing here.

**Comment by niltonmalves** [comment]
thanks!

**Comment by akshayks98** [comment]
i am getting the same error. can you please tell me what you changed in this code to solve this issue.

**Comment by ageitgey** [comment]
@akshayks98 Read my comment right above.
