### ISSUE TITLE
Unable To install face_recognition

### ISSUE THREAD

**Issue by harshmittal2210** [ageitgey/face_recognition#863]
* face_recognition version: Latest
* Python version: 3 
* Operating System: Raspberry Pi 3

### Description

When I entered the command:
```
sudo pip install face_recognition
``` 

I got:
```
pi@raspberrypi:~ $ pip install face_recognition
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting face_recognition
  Using cached https://files.pythonhosted.org/packages/3f/ed/ad9a28042f373d4633fc8b49109b623597d6f193d3bbbef7780a5ee8eef2/face_recognition-1.2.3-py2.py3-none-any.whl
Requirement already satisfied: numpy in /usr/local/lib/python3.5/dist-packages (from face_recognition) (1.16.4)
Requirement already satisfied: Pillow in /usr/lib/python3/dist-packages (from face_recognition) (4.0.0)
Requirement already satisfied: dlib>=19.7 in /usr/local/lib/python3.5/dist-packages (from face_recognition) (19.17.0)
Requirement already satisfied: Click>=6.0 in /usr/lib/python3/dist-packages (from face_recognition) (6.6)
Collecting face-recognition-models>=0.3.0 (from face_recognition)
  Downloading https://www.piwheels.org/simple/face-recognition-models/face_recognition_models-0.3.0-py2.py3-none-any.whl (100.6MB)
     |██████████████████████████████▊ | 96.6MB 1.2MB/s eta 0:00:04
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    face-recognition-models>=0.3.0 from https://www.piwheels.org/simple/face-recognition-models/face_recognition_models-0.3.0-py2.py3-none-any.whl#sha256=8d6b0af2e37a17120c3f13107974bc252142a4ffcb4e58eabdfcf26608e52c24 (from face_recognition):
        Expected sha256 8d6b0af2e37a17120c3f13107974bc252142a4ffcb4e58eabdfcf26608e52c24
             Got        8d74fb7d6b99b175e6073af059126d07da87ee7b2f395ad1c05fbce76d60b765


```

For python 3 I tried using pip3 but same error is comming.

**Comment by harshmittal2210** [comment]
I don't know why but when I ran this command 14th time. The library was installed.

**Comment by akeilox** [comment]
have you changed the swap size in between the attempts? I could only install dlib with instructions at https://gist.github.com/ageitgey/1ac8dbe8572f3f533df6269dab35df65

**Comment by harshmittal2210** [comment]
Yes! I followed the instructions in here
https://www.pyimagesearch.com/2017/05/01/install-dlib-raspberry-pi/

Except I did not create a virtual environment.

**Comment by harshmittal2210** [comment]
Earlier I was using 
```
sudo pip install --no-cache-dir  face_recognition
```
But in this, it was not using previously downloaded cache files. What I think is every time I ran the command :
```
sudo pip3 install face_recognition
```
some part of it was downloaded and then finally whole file was downloaded and library was installed.

**Comment by akeilox** [comment]
Thats exactly what I have been thorough. Ended up compiling dlib manually as per guide in above link and change swap and only then I could proceed on rpi3 stretch (16gb sd, file system expanded, with x installed)

**Comment by harshmittal2210** [comment]
For dlib This was my 7th or 8th attempt. It took almost 1hr to install.

Did you do memory split from Advanced Options => Memory Split in raspi-config.

**Comment by akeilox** [comment]
I didnt do the memory split, as I changed to console only boot even though x was installed.

I assume most changed memory split at some point. I am yet to try samples on tinker xwindow having enabled x gui boot after install of face_recog
