### ISSUE TITLE
face_encodings  return [] to me

### ISSUE THREAD

**Issue by rongwwei** [ageitgey/face_recognition#87]
* face_recognition version:(0.1.14)
* Python version:py2.7
* Operating System:ubuntu17.04

### Description

when I use function face_encodings(),it return [].

### What I want to know

I just want to know what it means.
It can't recognize the picture ?

**Comment by sluongng** [comment]
Review this:

```python
# Load a sample picture and learn how to recognize it.
obama_image = face_recognition.load_image_file("obama.jpg")
obama_face_encoding = face_recognition.face_encodings(obama_image)[0]
```

What happened here is that `face_encodings` loaded an image and find faces(note that its plural, not `face` but `faces`) in that image. Once thats done, it translated those faces into numpy array of 128 features.

So what you have in the end is a 2D array with first dimension being the faces and the 2nd dimension being the facial encoding features (size 128)

**Comment by ageitgey** [comment]
So like @sluongng said, if `face_encodings()` returns `[]`, that means it didn't find any faces in the picture so the array is empty.
