### ISSUE TITLE
face_recognition does not recognize dlib on python 3.6

### ISSUE THREAD

**Issue by sluongng** [ageitgey/face_recognition#89]
* face_recognition version: Latest
* Python version: 2.6
* Operating System: Ubuntu on docker

### Description

Installation of Face_Recognition on python 3.6 does not recognize that dlib has already been installed in the system.

![image](https://cloud.githubusercontent.com/assets/26684313/26502856/a02d42c0-4268-11e7-85cb-aea279d81615.png)

### What I Did

- I ran anaconda docker image on window.
- Created a virtual environment with python=3.6
- Ran `conda install dlib scipy numpy` successfully
- Ran `pip install face_recognition` and the installation tried to reinstall dlib again.
- ~~Have tried and I dont think this happen on python=3.5 environment~~ I had same problem with 3.5 environment on docker (anaconda image) but not when use conda 3.5 environment on window directly

**Comment by sluongng** [comment]
further investigation revealed that `pip install face_recognition` checked for info in `/opt/conda/envs/py36/lib/python3.6/site-packages` which seems to only contain `dlib.so` and without related `*.egg-info` or `*.dist-info` file.

![image](https://cloud.githubusercontent.com/assets/26684313/26503283/47ea20c2-426a-11e7-83f2-05b9e5c6f548.png)

I installed dlib from channel `conda-forge` , anybody know why is this missing?

**Comment by ageitgey** [comment]
Sounds like a potential problem with the conda package. You should probably file an issue on https://github.com/conda-forge/dlib-feedstock and ask @patricksnape. I unfortunately don't know anything about how conda-forge works.

**Comment by ageitgey** [comment]
I guess in the meantime you could hack around it with `pip install --no-dependencies face_recognition face_recognition_models`

**Comment by patricksnape** [comment]
That's just how dlib builds. The new(ish) pip installs of dlib are not currently compatible with conda-forge since we need patches to even get dlib to build. Pip isn't so great at detecting conda packages so you'd be better off making  all the deps conda packages if you really want full compatibility.

**Comment by sluongng** [comment]
using `--no-dependencies` solved the problem for me. Installing `dlib` manually is a great hassle and conda with `conda-forge` channel solved that problem. I strongly recommend you include this option in setup guide because it is a lot more accessible compare to downloading boost and compile dlib by hand.

**Comment by ageitgey** [comment]
Please don't ask new questions on old closed issues. No one is going to see them.

**Comment by SardorbekJavaDev** [comment]
I have a problem installing face_recognartion in my fast-API Python project, I am very glad for any help.  
![Screenshot from 2024-04-12 10-07-46](https://github.com/ageitgey/face_recognition/assets/105339939/7d51837a-d046-4f77-b7d2-4889f1622e73)
