### ISSUE TITLE
RuntimeError: Python version >= 3.5 required.

### ISSUE THREAD

**Issue by lanzhou2012** [ageitgey/face_recognition#896]
* face_recognition version: 1.2.3
* Python version: 2.7.12
* Operating System: Ubuntu 16.04

### Description

Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-GoCe89/numpy/setup.py", line 31, in <module>
        raise RuntimeError("Python version >= 3.5 required.")
    RuntimeError: Python version >= 3.5 required.

### What I Did

```
pip install face_recognition
```

**Comment by lanzhou2012** [comment]
python2 counld not work with numpy==1.17.0

**Comment by JonnoFTW** [comment]
Have you tried updating to a newer version of python?

**Comment by lanzhou2012** [comment]
No, I have another idea to solved it: 
`pip install face_recognition numpy==1.16`
