### ISSUE TITLE
CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by Legorooj** [ageitgey/face_recognition#897]
* face_recognition version: 1.2.3
* Python version: 3.6.8
* Operating System: Windows 10
* CUDA version 10.1.168_425.25

### Description

I have been attempting to install face_recognition with CUDA support for my nvidia GPU, but I get the error:
```python
RuntimeError: Error while calling cudaGetDevice(&dev) in file C:/Users/user/AppData/Local/Temp/pycharm-packaging/dlib/dlib/cuda/cuda_dlib.cu:27. code: 35, reason: CUDA driver version is insufficient for CUDA runtime version
```
### What I Did
I upgraded CUDA, cuDNN, PhysX, and everything I could to the latest version, but I still get the error.

**Comment by 2006pmach** [comment]
Same here but I am using Linux, python 2.7 and CUDA 10

**Comment by Goyicho** [comment]
just update your cuda driver to the one fits your cuda version
