### ISSUE TITLE
Question: Liviness and Running on iOS

### ISSUE THREAD

**Issue by SilentCicero** [ageitgey/face_recognition#898]
Hi there,

I love the approach for this tech. open-source is the way to go. 

1) Is there any way to have liviness detection with the facial recognition?

2) As well, is there any approach to create a unique identifier out of a specific face?

3) I'd like to be able to determine if a scan is a "photo" or "spoof" or an actual face. Any thoughts? 

4) Has anyone successfully built this library into an iOS application before? How large would the build be if I did such a thing?

I'd like to keep everything open-source, so third-party api's are out of the question for my project.

**Comment by ageitgey** [comment]
1. There's lots of threads here where people talk about different ideas for liveness detection, but liveness detection is not a built-in feature of this library.
1. Yes, see the face_encodings() function.
1. Same answer as #1 
1. There's no iOS support for this library. You'd have to find a different library for iOS.
