### ISSUE TITLE
'module' object has no attribute

### ISSUE THREAD

**Issue by AlmasM** [ageitgey/face_recognition#90]
* face_recognition version: 
face-recognition==0.1.14
face-recognition-models==0.1.3
* Python version: 2.7
* Operating System: linux

### Description

Hi,

At first, I thought the problem was with dlib package. I tried installing using pip, after which I got problem. Then, however, I resolved the problem by installing from the guide you provided. Now, I can successfully import dlib. However, I still can't import face_recognition. 

I couldn't find the exact issue online, but from what I could find, it could be a typo, as indicated in this [issue](https://github.com/tensorflow/tensorflow/issues/5514)

Thank you,

Almas M.

(faceR) amyrzat@ainos03:~$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import dlib
>>> import face_recognition
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/amyrzat/.virtualenvs/cv/lib/python2.7/site-packages/face_recognition/__init__.py", line 7, in <module>
    from .api import load_image_file, face_locations, face_landmarks, face_encodings, compare_faces, face_distance
  File "/home/amyrzat/.virtualenvs/cv/lib/python2.7/site-packages/face_recognition/api.py", line 21, in <module>
    face_encoder = dlib.face_recognition_model_v1(face_recognition_model)
AttributeError: 'module' object has no attribute 'face_recognition_model_v1'
>>>

**Comment by ageitgey** [comment]
This means you installed a version of dlib that is too old and doesn't support face recognition. You need dlib 19.4 or newer.

**Comment by AlmasM** [comment]
Hi,

I believe I have installed dlib version 19.4. I tried to install it using both pip and manually from the source. Still same error. Below is my output from terminal.

Any help appreciated.

```

Finished processing dependencies for dlib==19.4.99
(faceR) amyrzat@ainos03:~/dlib$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import dlib
>>> import face_recognition
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named face_recognition
>>> 
[22]+  Stopped                 python
(faceR) amyrzat@ainos03:~/dlib$ cd
(faceR) amyrzat@ainos03:~$ pip install face_recognition
Collecting face_recognition
  Using cached face_recognition-0.1.14-py2.py3-none-any.whl
Requirement already satisfied: numpy in ./.virtualenvs/cv/lib/python2.7/site-packages (from face_recognition)
Requirement already satisfied: dlib>=19.3.0 in ./.virtualenvs/faceR/lib/python2.7/site-packages/dlib-19.4.99-py2.7-linux-x86_64.egg (from face_recognition)
Requirement already satisfied: Pillow in ./.virtualenvs/cv/lib/python2.7/site-packages (from face_recognition)
Requirement already satisfied: scipy>=0.17.0 in ./.virtualenvs/cv/lib/python2.7/site-packages (from face_recognition)
Requirement already satisfied: Click>=6.0 in ./.virtualenvs/cv/lib/python2.7/site-packages (from face_recognition)
Collecting face-recognition-models (from face_recognition)
  Using cached face_recognition_models-0.1.3-py2.py3-none-any.whl
Requirement already satisfied: olefile in ./.virtualenvs/cv/lib/python2.7/site-packages (from Pillow->face_recognition)
Installing collected packages: face-recognition-models, face-recognition
Successfully installed face-recognition-0.1.14 face-recognition-models-0.1.3
(faceR) amyrzat@ainos03:~$ python 
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import dlib
>>> import face_recognition
/home/amyrzat/.virtualenvs/faceR/local/lib/python2.7/site-packages/face_recognition_models/__init__.py:7: UserWarning: Module dlib was already imported from /home/amyrzat/.virtualenvs/cv/lib/python2.7/site-packages/dlib.so, but /home/amyrzat/.virtualenvs/faceR/lib/python2.7/site-packages/dlib-19.4.99-py2.7-linux-x86_64.egg is being added to sys.path
  from pkg_resources import resource_filename
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/amyrzat/.virtualenvs/faceR/local/lib/python2.7/site-packages/face_recognition/__init__.py", line 7, in <module>
    from .api import load_image_file, face_locations, face_landmarks, face_encodings, compare_faces, face_distance
  File "/home/amyrzat/.virtualenvs/faceR/local/lib/python2.7/site-packages/face_recognition/api.py", line 21, in <module>
    face_encoder = dlib.face_recognition_model_v1(face_recognition_model)
AttributeError: 'module' object has no attribute 'face_recognition_model_v1'
```

**Comment by ageitgey** [comment]
Look at the warning you are getting:

UserWarning: Module dlib was already imported from /home/amyrzat/.virtualenvs/cv/lib/python2.7/site-packages/dlib.so, but /home/amyrzat/.virtualenvs/faceR/lib/python2.7/site-packages/dlib-19.4.99-py2.7-linux-x86_64.egg is being added to sys.path

My guess is you have two copies of dlib installed - an old one and a new one - and it's still finding the old one.

You could try temporarily renaming the file `/home/amyrzat/.virtualenvs/cv/lib/python2.7/site-packages/dlib.so` to `dlib.ignore` or something to see if that helps.

**Comment by badory** [comment]
Hello Adam,

Thank you for sharing this wonderful module. 

I'd appreciate if you please help me with this error that happened when I try to run the example:
Traceback (most recent call last):
  File "facerec_on_raspberry_pi.py", line 9, in <module>
    import face_recognition
  File "/home/pi/.virtualenvs/cv/local/lib/python3.4/site-packages/face_recognition/__init__.py", line 7, in <module>
    from .api import load_image_file, face_locations, batch_face_locations, face_landmarks, face_encodings, compare_faces, face_distance
  File "/home/pi/.virtualenvs/cv/local/lib/python3.4/site-packages/face_recognition/api.py", line 15, in <module>
    face_detector = dlib.get_frontal_face_detector()
AttributeError: 'module' object has no attribute 'get_frontal_face_detector'

Many thanks in advance.,
