### ISSUE TITLE
Error: Missing argument "KNOWN_PEOPLE_FOLDER". and  Error: Missing argument "IMAGE_TO_CHECK".

### ISSUE THREAD

**Issue by sandipJava** [ageitgey/face_recognition#900]
* face_recognition version: 1.2.3
* Python version: 3.7
* Operating System: windows 7

### Description

When I run **face_detection_cli.py** or **face_recognition_cli.py** file its throwing below error

Usage: face_detection_cli.py [OPTIONS] IMAGE_TO_CHECK
Try "face_detection_cli.py --help" for help.

Error: Missing argument "IMAGE_TO_CHECK".

Process finished with exit code 2

and

Usage: face_recognition_cli.py [OPTIONS] KNOWN_PEOPLE_FOLDER IMAGE_TO_CHECK
Try "face_recognition_cli.py --help" for help.

Error: Missing argument "KNOWN_PEOPLE_FOLDER".

Process finished with exit code 2

**Comment by ageitgey** [comment]
You have to pass in the right command line arguments to the CLI.

Please see here: https://github.com/ageitgey/face_recognition#command-line-interface

**Comment by alishabbir53** [comment]
You have to pass in the right command line arguments to the CLI.

Please see here: https://github.com/ageitgey/face_recognition#command-line-interface

sorry i cant understand can you explain properly

**Comment by alishabbir53** [comment]
because i am facing the same problem

**Comment by sandip-narwade** [comment]
@alishabbir53 , what error. I think that time I missed the folder

**Comment by joshuaeduards** [comment]
@alishabbir53 @sandip-narwade you need to create a reference folder e.g. "ref_people", this folder will work as a basis to identify the image that you are trying to identify by placing images with filename as their name. and also create another folder e.g. "unknown_people", you will place all the pictures that you're trying to identify. regardless of the filename, it will be identified as long as there's a basis from "ref_people" folder. 

Syntax: face_recognition ./ref_people/ ./unknown_people/
