### ISSUE TITLE
Create manylinux wheel

### ISSUE THREAD

**Issue by abagshaw** [ageitgey/face_recognition#91]
Might it be possible to create a manylinux `.whl` to put on PyPI? Installing on Windows is nice and fast thanks to the prebuilt wheel - but on linux it takes upwards of 7 minutes for me.

**Comment by ageitgey** [comment]
Are you sure you are talking about the `face_recognition` library itself and not a dependency library? For this library, I upload a `-py2.py3-none-any.whl` file.

**Comment by abagshaw** [comment]
@ageitgey Sorry, my mistake - the problem is with the `dlib` library which only has a precompiled wheel for windows (not linux) resulting in the super long installation times. Oh well! Not sure if much can be done about that. Thanks for your help.
