### ISSUE TITLE
Cant install face_recognition (stuck at bdist_wheel for dlib...)

### ISSUE THREAD

**Issue by sunnyg1210** [ageitgey/face_recognition#916]
* face_recognition version: latest
* Python version: 3.5.2
* Operating System: Ubuntu Server 16.04

### Description
Trying to install the face_recognition package on the server running ubuntu 16.04. But it gets to the following line of the install `Running setup.py bdist_wheel for dlib ... ` and then stays there indefinetely. 
I have installed dlib etc seperately too. Had to install dilb without cuda support due to the server not having any gpus. See below for terminal output and where it gets stuck.

### What I Did
```
xxxxx@xxxxx:/$ pip3 install face_recognition
Collecting face_recognition
  Using cached https://files.pythonhosted.org/packages/3f/ed/ad9a28042f373d4633fc8b49109b623597d6f193d3bbbef7780a5ee8eef2/face_recognition-1.2.3-py2.py3-none-any.whl
Collecting numpy (from face_recognition)
  Using cached https://files.pythonhosted.org/packages/d4/64/7619774f0bd8ef364d46a5df8eb1bc78784cd787324b9624f6793e72f787/numpy-1.17.1-cp35-cp35m-manylinux1_x86_64.whl
Collecting Pillow (from face_recognition)
  Using cached https://files.pythonhosted.org/packages/d6/98/0d360dbc087933679398d73187a503533ec0547ba4ffd2115365605559cc/Pillow-6.1.0-cp35-cp35m-manylinux1_x86_64.whl
Collecting face-recognition-models>=0.3.0 (from face_recognition)
Collecting Click>=6.0 (from face_recognition)
  Using cached https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl
Collecting dlib>=19.7 (from face_recognition)
  Using cached https://files.pythonhosted.org/packages/05/57/e8a8caa3c89a27f80bc78da39c423e2553f482a3705adc619176a3a24b36/dlib-19.17.0.tar.gz
Building wheels for collected packages: dlib
  Running setup.py bdist_wheel for dlib ... /

```

Please help.

**Comment by freedom9393** [comment]
You should wait until it finishes. It normally takes some time to install :)

**Comment by sunnyg1210** [comment]
So turns out the problem was the server was just running out of memory. Stopped other applications and reran the install and it went through no problem. 

FYI this server has 2 core cpu and 4GB ram.
