### ISSUE TITLE
How do we improve accuracy on live recognition?

### ISSUE THREAD

**Issue by CyberSinister** [ageitgey/face_recognition#918]
Hi!
I'm using the script and it's working just fine.
It's really amazing how it recognizes faces. But I just had one concern. 

Is there a way to improve the accuracy of the script (withOUT implementing a neural network or deep learning)?

**Comment by krunal704** [comment]
Follow Wiki page of this repo, I think this will help to improve accuracy
[Wiki page](https://github.com/ageitgey/face_recognition/wiki/Face-Recognition-Accuracy-Problems)

**Comment by CyberSinister** [comment]
Yea I found it right as I posted this issue. I just forgot to close it. Thank tho'!
