### ISSUE TITLE
Error in the 'facerec_from_webcam_faster' example and possible fix

### ISSUE THREAD

**Issue by piraka9011** [ageitgey/face_recognition#92]
* face_recognition version: 0.1.14
* Python version: 2.7
* Operating System: Ubuntu 14.04 LTS

### Description

While running the `facerec_from_webcam_faster.py` example, I came across the following error:

`...in processImg
    if match[0]:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`

### What I Did

Simply running the script caused the error. I followed what the error suggested and replaced line 45 in the script with: 
`if np.any(match[0]): name = "Pineapple"`

And added to the import list:
`import numpy as np`

I'm not sure if anyone came across the same error or if this is something expected and we should adjust the condition appropriately?

**Comment by ageitgey** [comment]
That's strange. The value of `match` should be either `[True]` or `[False]`. So `match[0]` should be just the value `True` or `False`, not multiple values.

Can you add a `print(match)` line above the `if match[0]:` line in the original script and show me what it outputs when you run the script?

**Comment by piraka9011** [comment]
I did that while debugging and `match[0]` prints: 
`[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True]`
While `match` prints:
`[array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True], dtype=bool)]`

Sorry I didn't concatenate, thought the whole thing might be necessary...

**Comment by shehzi-khan** [comment]
Same here... I'm passing a list of encodings calculated for all training images and I was expecting 
...
match = [False False False True False False False False]
... 
For the case I have 8 training images and image 4 is the most appropriate match. Instead I'm getting a list 128 boolean values, set to True.
