### ISSUE TITLE
Multiprocess only face_recognition.face_encodings() 

### ISSUE THREAD

**Issue by CyberSinister** [ageitgey/face_recognition#920]
Hi!

So, I don't know jack about multiprocessing and when I went to look up some examples, I was already pulling my hair. I want to know if I can multiprocess three face_encodings at a time. 

I tried the live_rec multiprocess script but my webcam slows down like hell and I can't really make anything of what I'm doing. I tried commenting the time.sleep(Global.frame_delay) and my webcam lights just turn on for 2 minutes and then turn off without giving me any errors. Same happens when I lower the frame delay under the fps if statements, if I lower it too much, it shows the light and then it turns off.
I get around 1 - 2 fps. Never over 2 per frame. The fps it shows with the Width and Height is 27fps.

I can use the default script but just want to speed the nums_jitter=100 in face_encodings. and I have three face encodings.

Sorry, I'm stupid, and really high.
Any help is appreciated.

**Comment by CyberSinister** [comment]
Anyone?

**Comment by tomasdembelli** [comment]
Have you tried:
```python
from multiprocessing import Pool

with Pool() as pool:
    pool.map(func_enc, list_of_images)
```
You need to define a custom function `func_enc` which accepts image files or frames. Then put the images/frames in a list `list_of_images`.
If you want to limit the number of processors used:
`with Pool(2) as pool:` Only `2` processors will be used here.

You can check how I used it in [my project](https://github.com/tomasdembelli/find_my_pictures/blob/master/find_my_pictures.py#L231) where batch image files are being encoded.
