### ISSUE TITLE
Question: will this work with Google Coral USB accelerator?

### ISSUE THREAD

**Issue by juanjux** [ageitgey/face_recognition#923]
I see references to the Jetson Nano, but I would like to know if this would use the TPU processor on a normal PC (Intel NUC) with a Google Coral USB accelerator. If that's the case, it would be nice to add a reference to this in the README. Thanks!

**Comment by Computer-Man497** [comment]
Yeah, that should work, feel free to make a pull request from an edit to the read me @juanjux

**Comment by juanjux** [comment]
I'll get one soon and do a PR update the README with the required instructions / configuration. Thanks!

**Comment by KostyaCholak** [comment]
Hello, any updates on using Google Coral USB accelerator with face_recognition? Your project is awesome and I was wondering how to setup up it to use with usb accelerator.

**Comment by ned-kelly** [comment]
+1

**Comment by ned-kelly** [comment]
> Hello, any updates on using Google Coral USB accelerator with face_recognition? Your project is awesome and I was wondering how to setup up it to use with usb accelerator.

+1

**Comment by ned-kelly** [comment]
Hi @eth0sec and @juanjux - Just wondering if you could elaborate what you did to get this working with Coral?

Thanks,
