### ISSUE TITLE
How can I detect the small faces or far away human face?

### ISSUE THREAD

**Issue by dasmehdix** [ageitgey/face_recognition#928]
* face_recognition version:Latest one, I just cloned
* Python version: 3.6
* Operating System:Windows 10

I can use the api without problem.My question is simple.Is there another way to detect small faces or people who in a long distance from camera?

I know that using upsample increase the detection on the single image.

```
face_locations = face_recognition.face_locations(face_image, number_of_times_to_upsample=2)
```

**Comment by raydioshead** [comment]
I have the same issue, the API is not able to recognize faces over 0.5 meters away from the camera.
How do we achieve this?

**Comment by ageitgey** [comment]
Can you just use a higher res camera and/or better camera optics?

**Comment by raydioshead** [comment]
I found this in the documentation:
https://face-recognition.readthedocs.io/en/latest/face_recognition.html
I changed my code to use the second parameter, values of 2 and 3 work a lot better to detect smaller faces but it is also slower, I am going to use a Pi 4 and try, I am sure in windows with a decent PC will work just fine.
face_locations = face_recognition.face_locations(rgb_small_frame, 2)

**Comment by dasmehdix** [comment]
> I found this in the documentation:
> https://face-recognition.readthedocs.io/en/latest/face_recognition.html
> I changed my code to use the second parameter, values of 2 and 3 work a lot better to detect smaller faces but it is also slower, I am going to use a Pi 4 and try, I am sure in windows with a decent PC will work just fine.
> face_locations = face_recognition.face_locations(rgb_small_frame, 2)

You just changed the parameter of upsample which me and @ageitgey already mentioned.
I solved this issue with using Resnet based face detection.I suggest you too use caffe resnet model.

> Can you just use a higher res camera and/or better camera optics?

You know, it's a hardware solution and we looking for a software solution :))

**Comment by tongvantruong** [comment]
> I solved this issue with using Resnet based face detection.I suggest you too use caffe resnet model.

Can you tell me how to do it? I have the same issue that if increase the parameter to 2 or 3 then it very slow...

**Comment by thusinh1969** [comment]
ResNet50 and 800x1333 will do well.
