### ISSUE TITLE
how to do live face recognition with RPi

### ISSUE THREAD

**Issue by N00D13** [ageitgey/face_recognition#93]
* Operating System: Debian

### Description

i want to use the example ```facerec_from_webcam_faster.py``` 
but i don't know how to change the video_output source to the PiCam

### What I Did

```
camera = picamera.PiCamera()
camera.resolution = (320, 240)
output = np.empty((240, 320, 3), dtype=np.uint8)


while True:
    # Grab a single frame of video
    ret, frame = camera.capture(output, format="rgb")
```
but i got erros, so how can i use the picam as source?

**Comment by ageitgey** [comment]
`camera.capture(output, format="rgb")` writes the output into the `output` variable. It doesn't return anything from the function call. So the frame data will be in `output`.

**Comment by N00D13** [comment]
i changed the ```ret, frame= camera.capture...``` to ```ret, frame= output```
but i only got these error: 
```ValueError: too many values to unpack (expected 2)```

**Comment by ageitgey** [comment]
```
camera = picamera.PiCamera()
camera.resolution = (320, 240)
frame = np.empty((240, 320, 3), dtype=np.uint8)


while True:
    # Grab a single frame of video
    camera.capture(frame, format="rgb")
```
