### ISSUE TITLE
Return the best 10 matches, not only one ? ( KNN )

### ISSUE THREAD

**Issue by alihannka** [ageitgey/face_recognition#938]
* face_recognition version: Lastest
* Python version: 3.6
* Operating System: Ubuntu 16.04

### Description

I trained my knn model with 500k images and works well but I want to see the best 5 matches in the result, how can i get that ? 

### What I Did

knn trained with encodes and predict methods works with encodes as well. I can get the best 10 score with: 

closest_distances = knn_clf.kneighbors(faces_encodings, n_neighbors=10)
    for j in range(10):
        print(closest_distances[0][0][j])

It returns the best 10 scores but I can't convert these to names. Because as you see predict uses encodes and use closest distances for only check for threshold.

return [(pred, loc) if rec else ("unknown", loc) for pred, loc, rec in zip(knn_clf.predict(faces_encodings), X_face_locations, are_matches)]

In sum, There is any way can get the best 10 matches and names ?

**Comment by fadi212** [comment]
Your n_neighbors argument has nothing to do with the distances. I think K_Nearest_Neighbors algorithms just returns score based on voting or distances. It does not return a distance. 
To find the closest 10 distance what you can do compare your encoding with all the encodings and compute distance and append them to a list or what and then apply an ascending function and it will give you the 10 closest distances.

**Comment by fadi212** [comment]
And what you are trying with j is not the distance its the array number or index may be.

**Comment by alihannka** [comment]
> Your n_neighbors argument has nothing to do with the distances. I think K_Nearest_Neighbors algorithms just returns score based on voting or distances. It does not return a distance.
> To find the closest 10 distance what you can do is compare your encoding with all the encodings, compute distance and append them to a list and then apply an ascending function and it will give you the 10 closest distances.

Yeah This is what I'm trying to do now, thank you for your response

**Comment by ferasawadi** [comment]
Hi there, any way to write the code to get 10 persons out of the predect method, am new to python and am not sure how to write it 👍 
thanks in advance
