### ISSUE TITLE
mode error

### ISSUE THREAD

**Issue by profbit** [ageitgey/face_recognition#95]
<img width="643" alt="123" src="https://cloud.githubusercontent.com/assets/29194923/26776870/a985b602-4a0d-11e7-982c-e1321d9b0cdb.PNG">
After running, im getting strange errors. any help?

**Comment by profbit** [comment]
btw, im using rpi and want picam to operate

**Comment by sluongng** [comment]
it seems like the problem is with `scipy.misc.imread`

Quick google search give you this https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.misc.imread.html where it stated that there is no such `mode` with value `mode`.

```
mode can be one of the following strings:

- ‘L’ (8-bit pixels, black and white)
- ‘P’ (8-bit pixels, mapped to any other mode using a color palette)
- ‘RGB’ (3x8-bit pixels, true color)
- ‘RGBA’ (4x8-bit pixels, true color with transparency mask)
- ‘CMYK’ (4x8-bit pixels, color separation)
- ‘YCbCr’ (3x8-bit pixels, color video format)
- ‘I’ (32-bit signed integer pixels)
- ‘F’ (32-bit floating point pixels)
```

**Comment by sluongng** [comment]
do make sure to check your version of scipy though. It seems like you are using Python 3.4 which isnt the latest. This might cause scipy version to be old as well. Find your version and find the correct documentation for that version.

**Comment by sluongng** [comment]
https://github.com/ageitgey/face_recognition/blob/master/face_recognition/api.py#L78

this is the specific line of code you are having trouble with. I think this is because your scipy is out-of-date thus the `imread()` method does not accept `mode`.

Try updating scipy?

**Comment by ageitgey** [comment]
This is the same problem reported in #6 and other issues. This issue happens if you have too old a version of `scipy`. Can you try the solution [listed here](https://github.com/ageitgey/face_recognition/issues/6#issuecomment-287122632)?

```
pip install --upgrade scipy
```

**Comment by ageitgey** [comment]
I added this to the [Common Issues](https://github.com/ageitgey/face_recognition/blob/master/README.md#common-issues) in the README to hopefully make it easier to find for the next person.
