### ISSUE TITLE
Error Buffer dtype mismatch, expected 'ITYPE_t' but got 'long'.

### ISSUE THREAD

**Issue by SaddamBInSyed** [ageitgey/face_recognition#953]
* face_recognition version: latest
* Python version:3.6.8
* Operating System:windows10

### Description

1. (Websocket) The client is sending base64 image to the server.
2. (WebSocket) The server receives the same and identifying the face. 
3. I am using the provided "knn example code" to train images and predict the received images from client.

But I am getting an error in below code,

 #### Load a trained KNN model (if one was passed in)
    if knn_clf is None:
        with open(model_path, 'rb') as f:
            knn_clf = pickle.load(f)===> throwing below exception

**Buffer dtype mismatch, expected 'ITYPE_t' but got 'long'.**

So What is wrong here. Please advise,

@ageitgey

**Comment by SaddamBInSyed** [comment]
solved.

**Comment by UngarMax** [comment]
@SaddamBInSyed how did you fix it?

**Comment by Anubha-Singh** [comment]
> Issue related to scikit-learn/Knn model persistence.
> 
> solved.
how did you fix?
