### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by FUjr** [ageitgey/face_recognition#957]
i'm a student from the contry which not use English,sorry for my poor English.
I am a player instead of a professioner . I can't even understand the notes,but I have to use this program to finish my homework,could you please help me?
Thank you whether you help me! (it means whether you help me or not, I will thank you for your reading my poor explaintion.)

**Comment by KNobHack** [comment]
https://youtu.be/QSTnwsZj2yc

just follow the instruction.
you can use auto translate

**Comment by FUjr** [comment]
> https://youtu.be/QSTnwsZj2yc
> 
> just follow the instruction.
> you can use auto translate
> i hope that can help

thanks a lot ！

**Comment by KNobHack** [comment]
> > https://youtu.be/QSTnwsZj2yc
> > just follow the instruction.
> > you can use auto translate
> > i hope that can help
> 
> thanks a lot ！

please close this issue
