### ISSUE TITLE
Installation on Windows [works!]

### ISSUE THREAD

**Issue by Dingo64** [ageitgey/face_recognition#96]
1.    Download these files:
https://github.com/Dingo64/face_rec/blob/master/dlib-19.4.0-cp35-cp35m-win_amd64.whl
https://github.com/Dingo64/face_rec/blob/master/python-3.5.0-amd64-webinstall.exe
https://github.com/Dingo64/face_rec/blob/master/scipy-0.19.0-cp35-cp35m-win_amd64.whl

2.    Download numpy‑1.11.3+mkl‑cp35‑cp35m‑win_amd64.whl from http://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy

3.    Install python-3.5.0-amd64-webinstall.exe (Python 3.5 Amd64 for Windows)

4.    Update pip. In command line type:

python -m pip install --upgrade pip

5.    In command line type:

pip3 install dlib-19.4.0-cp35-cp35m-win_amd64.whl
pip3 install scipy-0.19.0-cp35-cp35m-win_amd64.whl
pip3 install numpy-1.11.3+mkl-cp35-cp35m-win_amd64.whl

6.    In command line type:

pip3 install face_recognition

**Comment by sluongng** [comment]
You could always follow my steps using `conda` over at #81

**Comment by Dingo64** [comment]
Conda is huge. This way is very fast and it doesn't take up a lot of space on disk.

**Comment by ageitgey** [comment]
Cool, thanks!

**Comment by kinder01** [comment]
installed it on python 3.6  on windows 7 using your guide. Thanks!
requirements-
1. dlib-19.8.1-cp36-cp36m-win_amd64.whl
2. scipy-1.0.0-cp36-cp36m-win_amd64.whl
3.  numpy-1.14.0+mkl-cp36-cp36m-win_amd64.whl

**Comment by varun30300** [comment]
I couldn't find numpy‑1.11.3+mkl‑cp35‑cp35m‑win_amd64.whl in the link
