### ISSUE TITLE
can't recognize known faces on jetson nano

### ISSUE THREAD

**Issue by farhanrbnn** [ageitgey/face_recognition#962]
* face_recognition version: 1.2.3
* Python version: 3.6.8
* Operating System: debian 

description:
i want to minimize my face recognition from PC to jetson nano.
i use this example [https://github.com/ageitgey/face_recognition/blob/master/examples/facerec_from_webcam_faster.py](url) and it works fine on PC. but when i move to jetson nano, it can't recognize known faces.

what i did:
i combined face recognition code with doorbell cam code. i just add `def running_on_jetson()` `def get_jetson_gstreamer_source()` to the face recognition code so it can run on jetson. 

and then i also follow this guidline [https://medium.com/@ageitgey/build-a-hardware-based-face-recognition-system-for-150-with-the-nvidia-jetson-nano-and-python-a25cb8c891fd](url) to fix the dlib bug on jetson nano and recompiled the dlib. 

and then i re run the face recognition code and still can't recognize known faces. what should i do?

any answer would be appreciated, thanks in advance and pardon my englsih.

**Comment by ageitgey** [comment]
Have you tried to debug it? Just saying it doesn't work doesn't give us much information. Are the face encodings returned on the jetson nano similar to the encodings on the desktop version? Are the images coming through ok on the jetson nano? Are you using the same known images in both places?

**Comment by farhanrbnn** [comment]
i'm sorry for the lack of information, i already debug it. the face encodings on desktop and jetson are different with the same known images. on jetson, some face encoding returned 'nan' value but on the desktop there's no 'nan' value.

**Comment by farhanrbnn** [comment]
and when i print the value of this code https://github.com/ageitgey/face_recognition/blob/master/examples/facerec_from_webcam_faster.py#L55 it retruned 128-dimension value and sometimes a 'nan' value. i'm using pi camera
