### ISSUE TITLE
Crop image to preferred region to speed up detection

### ISSUE THREAD

**Issue by congphase** [ageitgey/face_recognition#968]
Hi everyone. 

My problem is that I cannot resize the input image to smaller resolution (because faces then are to small to be detected) to apply cnn detection. My application scenario is that faces only appear in some specific region of a frame. Is it okay to keep the image the original size, but crop only the region that faces most likely appear, then apply face detection to that cropped region and then just use it for recognition without resizing anything? Is this okay? Have anyone tried this please give me some advice. Thank you a lot!!!

**Comment by ageitgey** [comment]
Sure, that is fine.

**Comment by congphase** [comment]
Thank you for your quick reply. I'm trying it.
