### ISSUE TITLE
Accuracy less when cropped the face from Image

### ISSUE THREAD

**Issue by sandip-narwade** [ageitgey/face_recognition#977]
* face_recognition version: 1.2.3
* Python version: 3.6
* Operating System: Windows 7

### Description
Accuracy giving less when cropped the face from an image.

### What I Did
When I trained a model with **sandip.jpg** and recognize with **sandip.jpg** it is giving 100% accuracy in percentage. It is working fine.

Image size is big, It will slow after adding more image, So I decided to crop the face from an image so it will fast. I cropped face from image then trained a model. But when I am doing recognized it is giving 90%. How I can achieve 100% on the cropped image.

Please check the below image to get a better understanding.

Left Side **Trained** Images Right Side used for **Recognize**
Between this, I gave **percentages** that I got

@Reddyforcode

![Untitled](https://user-images.githubusercontent.com/32532237/68830221-16487400-06d1-11ea-8ffa-d489214fc370.jpg)

**Comment by aliang-Dev** [comment]
Well Done！！

**Comment by sandip-narwade** [comment]
@aliang-Dev , How to get 100% on the cropped face. Any Suggestions.

**Comment by Reddyforcode** [comment]
Are you using Hog or CNN for detection?
The faces detected for each image are not the same, I'm sure they have a little difference for ex:
with this format (x, y, w, h) imagine
    face_detected_img1 -> [100, 110, 23, 24]
    face_detected_img2 -> [0, 0, 22, 25]
    face_detected_img3 -> [10, 12, 23, 27]
so the encodings are not exactly the same.

You can try printing your bounding boxes for each image.

**Comment by sandip-narwade** [comment]
@Reddyforcode 
Its solved. I tried with

                   `images = face_recognition.load_image_file(image)
                    faces = face_recognition.face_locations(images)
                    h = images.shape[0]
                    w = images.shape[1]
                    for i in range(len(faces)):
                        top, right, bottom, left = faces[i]
                        leftD = left / 4
                        leftM = left - leftD

                        topD = top / 4
                        topM = top - topD

                        rightD = (w - right) / 4
                        rightM = right + rightD

                        bottomD = (h - bottom) / 4
                        bottomM = bottom + bottomD

                        faceImage = images[int(topM):int(bottomM), int(leftM):int(rightM)]
                        final = Image.fromarray(faceImage)
                    final.save(os.path.join(path, secure_filename(image.filename)))`

**Comment by congphase** [comment]
@sandip-narwade 

Can you explain a little bit more detail what you have done? I don't understand what you mean in your code. What is leftD, leftM? What does D, M stand for?

**Comment by congphase** [comment]
@sandip-narwade 
I'm dealing the problem the same as yours.

Why do you have the formulas as `leftD = left / 4
                    leftM = left - leftD

                    topD = top / 4
                    topM = top - topD

                    rightD = (w - right) / 4
                    rightM = right + rightD

                    bottomD = (h - bottom) / 4
                    bottomM = bottom + bottomD`

I don't understand. Please explain me.

**Comment by sandip-narwade** [comment]
@congphase 
Sorry I did not use naming standards. See the 
image size is **h 371 w 660**

leftD means left devide

For **left** and **top**, I subtracted value
For **right** and **bottom**, I added value.


![akshay - Copy](https://user-images.githubusercontent.com/32532237/68988319-491e7380-085b-11ea-9ace-a3b04ac87e4f.jpg)


Hope u understood.

**Comment by wahyu-handayani** [comment]
@sandip-narwade, I would like to get percentage image matching like your, would you like to give an example how to get that percentage, I am trying to follow this way https://github.com/ageitgey/face_recognition/wiki/Calculating-Accuracy-as-a-Percentage, but the thing that makes me confused is how to get face_distance value. I open a question in https://github.com/ageitgey/face_recognition/issues/1318, would you like to take a look ?
