### ISSUE TITLE
Please specify the cv2 version

### ISSUE THREAD

**Issue by BalajiB3663** [ageitgey/face_recognition#99]
* face_recognition version:--
* Python version:3.5
* Operating System:Windows

### Description

I have installed successfully all the prerequisites for my windows 64-bit, with python 3.5 64-bit version. Now when i import the face_recognition module, its throwing an error no module named cv2.  

### What I Did

``I think your opencv version is different to mine. So please help me in this regard.
```

**Comment by ageitgey** [comment]
`face_recognition` doesn't depend on `cv2`. I'm assuming you ran one of the webcam examples that uses `cv2`. I used OpenCV 3.2 with the Python extensions installed.
