### ISSUE TITLE
How can I add Percentage rate?

### ISSUE THREAD

**Issue by HAKANMAZI** [ageitgey/face_recognition#993]
* face_recognition version: 1.2.3
* Python version: 3.6.8
* Operating System: windows 10

### Description

Hi Adam, Firstly thanks for great library, I already 21k faces(one of mine) encoded and insert to sql , I am testing three different photos of mine. Results are below.

First photo : 40 different person (one of them is mine) 
Second photo : 20 different person (one of them is mine) 
Third photo : 77 different person (one of them is mine) 

So I wanna say mine photo %100 matched, other photos %94, %54, %69.... İs there any way to do?

**Comment by alessiosavi** [comment]
You have to use a neural network in order to do that. You can't rely on `euclidean distance` or `cosine distance` or `manhattan norm`.

Have a look at my little repo that wrap `face_recognition` for extract the points of the faces, and then feed a neural network with the encoded faces. https://github.com/alessiosavi/PyRecognizer/

**Comment by sandip-narwade** [comment]
add this code at line number 104

    `per = [closest_distances[0][i][0] for i in range(len(X_face_locations))]

    for _, ii in enumerate(per):
        # print((1.0 - ii) * 100)
        global xx
        xx.append((1.0 - ii) * 100)`

**Comment by HAKANMAZI** [comment]
> add this code at line number 104
> 
> ```
> `per = [closest_distances[0][i][0] for i in range(len(X_face_locations))]
> 
> for _, ii in enumerate(per):
>     # print((1.0 - ii) * 100)
>     global xx
>     xx.append((1.0 - ii) * 100)`
> ```

Thanks sandip-narwade 
there was an allready answer from wiki https://github.com/ageitgey/face_recognition/wiki/Calculating-Accuracy-as-a-Percentage

**Comment by wahyu-handayani** [comment]
@HAKANMAZI, I have the same case like yours but I don't know where ```face_distance``` comes from, would you like to take a look to my open question here https://github.com/ageitgey/face_recognition/issues/1318?
