### ISSUE TITLE
Suggestion: Add "model" in the function parameter of "face_encodings"

### ISSUE THREAD

**Issue by adjr2** [ageitgey/face_recognition#999]
### Description

Hello,

What am I doing?
I am using your package to extract face encoding which I am later planning to use to compare against a collection of images (by creating a ckd-tree). 

PROBLEM:
While extracting features I faced a problem: I am unable to use "large" model in the function "face_encodings" as by default "small" is set in the internal function "_raw_face_landmarks" which I can't change.

Probable SOLUTION:
Change the definition of the function "face_encodings" to 
`def face_encodings(face_image, known_face_locations=None, num_jitters=1, model="small"):`

P.S: I am new to all this so please be kind if what I am suggesting is silly. Thank you

**Comment by ageitgey** [comment]
Why do you want to use the large face landmarks model here?

**Comment by adjr2** [comment]
I have tried both small and large face landmarks model and I saw improvement in my results when I used large model to compare faces.
Like I have said, it is just a suggestion. I believe changing the function definition to the one I have suggested will give user (like me) more flexibility.
